# Generated by test-lab — blind adversarial evaluation
"""test_package_phase_review - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

import json
import hashlib
import tempfile
import unittest
import zipfile
from pathlib import Path

import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from package_phase_review import main
from phase_status import compute_phase_subject_sha256, compute_progress_context_sha256, compute_skill_context_sha256, load_status, save_status, status_path, validate_status


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def receipt_for(
    review: str,
    request: str,
    bundle: str,
    reviewer: str = "scillm-gpt55-high",
    adjudicator: str = "scillm",
    phase_subject_sha256: str = "phase-subject",
    progress_context_sha256: str | None = None,
    skill_context_sha256: str | None = None,
) -> str:
    receipt = {
        "status": "completed",
        "raw_contains_sentinel": True,
        "clean_contains_sentinel": False,
        "sentinel": "<<<WEBGPT_DONE:fixture>>>",
        "controlled_tab_id": "123",
        "controlled_tab_id_mismatch": False,
        "no_activate": True,
        "focus_changed": False,
        "reviewer_id": reviewer,
        "adjudicator_kind": adjudicator,
        "response_sha256": sha256_text(review),
        "request_sha256": sha256_text(request),
        "review_bundle_sha256": sha256_text(bundle),
        "phase_subject_sha256": phase_subject_sha256,
    }
    if progress_context_sha256 is not None:
        receipt["progress_context_sha256"] = progress_context_sha256
    if skill_context_sha256 is not None:
        receipt["skill_context_sha256"] = skill_context_sha256
    return json.dumps(receipt, sort_keys=True)


def add_skill_context(phase_dir: Path, status: dict[str, object]) -> str:
    text = "Headless skill context: plan-iterate/review-code/scillm/memory contracts.\n"
    path = phase_dir / "skill-context.md"
    path.write_text(text, encoding="utf-8")
    status["skill_context_artifacts"] = [{"path": "skill-context.md", "sha256": sha256_text(text)}]
    return text


class PackagePhaseReviewTest(unittest.TestCase):
    def test_init_creates_phase_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            exit_code = main(["--root", tmp, "init", "--phase", "phase-01"])

            self.assertEqual(0, exit_code)
            self.assertTrue((Path(tmp) / "phase-01" / "PHASE_STATUS.json").exists())
            self.assertTrue((Path(tmp) / "phase-01" / "PHASE_REVIEW_REQUEST.md").exists())

    def test_package_fails_when_evidence_missing(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self.assertEqual(0, main(["--root", str(root), "init", "--phase", "phase-01"]))
            status_file = status_path(root, "phase-01")
            status = load_status(status_file)
            status.update(
                {
                    "status": "ready_for_review",
                    "acceptance_contract": ["contract"],
                    "changed_files": ["file.py"],
                    "validation_commands": [{"command": "true", "exit_code": 0}],
                    "evidence_artifacts": ["missing.txt"],
                    "claims": [{"claim": "validated", "evidence_artifacts": ["missing.txt"]}],
                }
            )
            add_skill_context(root / "phase-01", status)
            save_status(status_file, status)

            exit_code = main(
                [
                    "--root",
                    str(root),
                    "package",
                    "--phase",
                    "phase-01",
                    "--output",
                    str(root / "bundle.zip"),
                ]
            )

            self.assertEqual(1, exit_code)
            self.assertFalse((root / "bundle.zip").exists())

    def test_package_writes_manifest_with_hashes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self.assertEqual(0, main(["--root", str(root), "init", "--phase", "phase-01"]))
            phase_dir = root / "phase-01"
            (root / "file.py").write_text("source", encoding="utf-8")
            (root / "file.py").write_text("print('changed')\n", encoding="utf-8")
            (phase_dir / "evidence.txt").write_text("proof", encoding="utf-8")
            status_file = status_path(root, "phase-01")
            status = load_status(status_file)
            status.update(
                {
                    "status": "ready_for_review",
                    "acceptance_contract": ["contract"],
                    "changed_files": [{"path": "file.py", "sha256": sha256_text("source")}],
                    "validation_commands": [{"command": "true", "exit_code": 0}],
                    "evidence_artifacts": ["evidence.txt"],
                    "claims": [{"claim": "validated", "evidence_artifacts": ["evidence.txt"]}],
                }
            )
            add_skill_context(phase_dir, status)
            save_status(status_file, status)
            output = root / "bundle.zip"

            exit_code = main(
                [
                    "--root",
                    str(root),
                    "package",
                    "--phase",
                    "phase-01",
                        "--output",
                        str(output),
                        "--repo-root",
                        str(root),
                    ]
                )

            self.assertEqual(0, exit_code)
            with zipfile.ZipFile(output) as bundle:
                manifest = json.loads(bundle.read("manifest.json"))
                self.assertEqual("plan_iterate.review_bundle_manifest.v1", manifest["schema"])
                self.assertTrue(any(entry["path"] == "evidence.txt" for entry in manifest["entries"]))
                self.assertTrue(all(entry["sha256"] for entry in manifest["entries"]))
                extract_dir = root / "extracted"
                bundle.extractall(extract_dir)
            extracted_status = load_status(extract_dir / "PHASE_STATUS.json")
            self.assertEqual([], validate_status(extracted_status, extract_dir))

    def test_package_preserves_evidence_relative_paths_to_avoid_collisions(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self.assertEqual(0, main(["--root", str(root), "init", "--phase", "phase-01"]))
            phase_dir = root / "phase-01"
            (root / "file.py").write_text("source", encoding="utf-8")
            (root / "file.py").write_text("print('changed')\n", encoding="utf-8")
            (phase_dir / "reports").mkdir()
            (phase_dir / "logs").mkdir()
            (phase_dir / "reports" / "audit.json").write_text('{"kind":"report"}\n', encoding="utf-8")
            (phase_dir / "logs" / "audit.json").write_text('{"kind":"log"}\n', encoding="utf-8")
            status_file = status_path(root, "phase-01")
            status = load_status(status_file)
            status.update(
                {
                    "status": "ready_for_review",
                    "acceptance_contract": ["contract"],
                    "changed_files": [{"path": "file.py", "sha256": sha256_text("source")}],
                    "validation_commands": [{"command": "true", "exit_code": 0}],
                    "evidence_artifacts": ["reports/audit.json", "logs/audit.json"],
                    "claims": [
                        {
                            "claim": "validated",
                            "evidence_artifacts": ["reports/audit.json", "logs/audit.json"],
                        }
                    ],
                }
            )
            add_skill_context(phase_dir, status)
            save_status(status_file, status)
            output = root / "bundle.zip"

            exit_code = main(
                [
                    "--root",
                    str(root),
                    "package",
                    "--phase",
                    "phase-01",
                    "--output",
                    str(output),
                    "--repo-root",
                    str(root),
                ]
            )

            self.assertEqual(0, exit_code)
            with zipfile.ZipFile(output) as bundle:
                names = bundle.namelist()
                self.assertIn("reports/audit.json", names)
                self.assertIn("logs/audit.json", names)

    def test_record_review_transitions_status(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self.assertEqual(0, main(["--root", str(root), "init", "--phase", "phase-01"]))
            phase_dir = root / "phase-01"
            (root / "file.py").write_text("source", encoding="utf-8")
            review = root / "review.md"
            review_text = "PASS"
            request_text = "review this"
            bundle_text = "bundle bytes"
            review.write_text(review_text, encoding="utf-8")
            review_request = root / "request.md"
            review_request.write_text(request_text, encoding="utf-8")
            review_bundle = root / "bundle.zip"
            review_bundle.write_text(bundle_text, encoding="utf-8")
            invocation_receipt = root / "receipt.json"
            (phase_dir / "evidence.txt").write_text("proof", encoding="utf-8")
            status_file = status_path(root, "phase-01")
            status = load_status(status_file)
            status.update(
                {
                    "acceptance_contract": ["contract"],
                    "changed_files": [{"path": "file.py", "sha256": sha256_text("source")}],
                    "validation_commands": [{"command": "true", "exit_code": 0}],
                    "evidence_artifacts": ["evidence.txt"],
                }
            )
            add_skill_context(phase_dir, status)
            save_status(status_file, status)
            skill_context_sha256 = compute_skill_context_sha256(status, phase_dir)
            invocation_receipt.write_text(
                receipt_for(
                    review_text,
                    request_text,
                    bundle_text,
                    phase_subject_sha256=compute_phase_subject_sha256(status),
                    skill_context_sha256=skill_context_sha256,
                ),
                encoding="utf-8",
            )

            exit_code = main(
                [
                    "--root",
                    str(root),
                    "record-review",
                    "--phase",
                    "phase-01",
                    "--verdict",
                    "passed",
                    "--review",
                    str(review),
                    "--review-request",
                    str(review_request),
                    "--review-bundle",
                    str(review_bundle),
                    "--invocation-command",
                    "curl /v1/chat/completions model=gpt-5.5 reasoning_effort=high",
                    "--invocation-receipt",
                    str(invocation_receipt),
                    "--repo-root",
                    str(root),
                ]
            )

            self.assertEqual(0, exit_code)
            updated = load_status(status_file)
            self.assertEqual("external_review_passed", updated["status"])
            self.assertEqual("passed", updated["review_status"])
            self.assertEqual("scillm", updated["review_results"][0]["adjudicator_kind"])
            self.assertIn("artifact_sha256", updated["review_results"][0])
            self.assertIn("review_request_sha256", updated["review_results"][0])
            self.assertIn("review_bundle_sha256", updated["review_results"][0])
            self.assertIn("receipt_sha256", updated["review_results"][0]["invocation"])
            self.assertTrue((phase_dir / updated["review_results"][0]["review_request_artifact"]).exists())
            self.assertTrue((phase_dir / updated["review_results"][0]["review_bundle_artifact"]).exists())
            self.assertTrue((phase_dir / updated["review_results"][0]["invocation"]["receipt_artifact"]).exists())
            self.assertTrue(updated["review_comparison"]["closure_allowed"])
            self.assertTrue(any((phase_dir / artifact).exists() for artifact in updated["review_artifacts"]))

    def test_conditional_pass_records_blocked_state(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self.assertEqual(0, main(["--root", str(root), "init", "--phase", "phase-01"]))
            phase_dir = root / "phase-01"
            review = root / "review.md"
            review_text = "CONDITIONAL"
            request_text = "review this"
            bundle_text = "bundle bytes"
            review.write_text(review_text, encoding="utf-8")
            review_request = root / "request.md"
            review_request.write_text(request_text, encoding="utf-8")
            review_bundle = root / "bundle.zip"
            review_bundle.write_text(bundle_text, encoding="utf-8")
            invocation_receipt = root / "receipt.json"
            (phase_dir / "evidence.txt").write_text("proof", encoding="utf-8")
            status_file = status_path(root, "phase-01")
            status = load_status(status_file)
            status.update(
                {
                    "acceptance_contract": ["contract"],
                    "changed_files": ["file.py"],
                    "validation_commands": [{"command": "true", "exit_code": 0}],
                    "evidence_artifacts": ["evidence.txt"],
                }
            )
            add_skill_context(phase_dir, status)
            save_status(status_file, status)
            skill_context_sha256 = compute_skill_context_sha256(status, phase_dir)
            invocation_receipt.write_text(
                receipt_for(
                    review_text,
                    request_text,
                    bundle_text,
                    phase_subject_sha256=compute_phase_subject_sha256(status),
                    skill_context_sha256=skill_context_sha256,
                ),
                encoding="utf-8",
            )

            exit_code = main(
                [
                    "--root",
                    str(root),
                    "record-review",
                    "--phase",
                    "phase-01",
                    "--verdict",
                    "conditional_pass",
                    "--review",
                    str(review),
                    "--review-request",
                    str(review_request),
                    "--review-bundle",
                    str(review_bundle),
                    "--invocation-command",
                    "curl /v1/chat/completions model=gpt-5.5 reasoning_effort=high",
                    "--invocation-receipt",
                    str(invocation_receipt),
                    "--repo-root",
                    str(root),
                ]
            )

            self.assertEqual(0, exit_code)
            updated = load_status(status_file)
            self.assertEqual("external_review_blocked", updated["status"])
            self.assertFalse(updated["review_comparison"]["closure_allowed"])

    def test_record_context_adds_progress_artifact_and_memory_key(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self.assertEqual(0, main(["--root", str(root), "init", "--phase", "phase-01"]))
            context = root / "context.md"
            context.write_text("Prior findings: H1 fixed.\nCurrent delta: added tests.\n", encoding="utf-8")

            exit_code = main(
                [
                    "--root",
                    str(root),
                    "record-context",
                    "--phase",
                    "phase-01",
                    "--context",
                    str(context),
                    "--memory-key",
                    "phase-01-review-002",
                    "--skip-memory-upsert",
                    "--repo-root",
                    str(root),
                ]
            )

            self.assertEqual(0, exit_code)
            updated = load_status(status_path(root, "phase-01"))
            self.assertEqual(["phase-01-review-002"], updated["memory_context"]["keys"])
            self.assertEqual(1, len(updated["progress_context_artifacts"]))
            artifact = updated["progress_context_artifacts"][0]
            self.assertTrue((root / "phase-01" / artifact["path"]).exists())

    def test_comparison_required_records_reviews_then_comparison(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self.assertEqual(0, main(["--root", str(root), "init", "--phase", "phase-01"]))
            phase_dir = root / "phase-01"
            (root / "file.py").write_text("source", encoding="utf-8")
            (phase_dir / "evidence.txt").write_text("proof", encoding="utf-8")
            progress_context_text = "Prior findings: none yet.\nCurrent delta: initial comparison review.\n"
            (phase_dir / "progress-context.md").write_text(
                progress_context_text,
                encoding="utf-8",
            )
            status_file = status_path(root, "phase-01")
            status = load_status(status_file)
            status.update(
                {
                    "status": "ready_for_review",
                    "acceptance_contract": ["contract"],
                    "changed_files": [{"path": "file.py", "sha256": sha256_text("source")}],
                    "validation_commands": [{"command": "true", "exit_code": 0}],
                    "evidence_artifacts": ["evidence.txt"],
                    "progress_context_artifacts": [
                        {"path": "progress-context.md", "sha256": sha256_text(progress_context_text)}
                    ],
                    "memory_context": {
                        "collection": "plan_iterate_phase_context",
                        "keys": ["phase-01-initial-comparison"],
                    },
                    "reviewer_policy": {
                        "required": True,
                        "comparison_required": True,
                        "closure_rule": "deterministic_validation_and_external_review",
                    },
                }
            )
            add_skill_context(phase_dir, status)
            save_status(status_file, status)
            phase_subject_sha256 = compute_phase_subject_sha256(status)
            progress_context_sha256 = compute_progress_context_sha256(status, phase_dir)
            skill_context_sha256 = compute_skill_context_sha256(status, phase_dir)
            shared_bundle_text = "same bundle bytes"

            for reviewer, adjudicator in [("webgpt", "webgpt"), ("scillm-gpt55", "scillm")]:
                review_text = f"PASS {reviewer}"
                request_text = f"review this {reviewer}"
                bundle_text = shared_bundle_text
                review = root / f"{reviewer}-review.md"
                request = root / f"{reviewer}-request.md"
                bundle = root / f"{reviewer}-bundle.zip"
                receipt = root / f"{reviewer}-receipt.json"
                review.write_text(review_text, encoding="utf-8")
                request.write_text(request_text, encoding="utf-8")
                bundle.write_text(bundle_text, encoding="utf-8")
                receipt.write_text(
                    receipt_for(
                        review_text,
                        request_text,
                        bundle_text,
                        reviewer,
                        adjudicator,
                        phase_subject_sha256,
                        progress_context_sha256,
                        skill_context_sha256,
                    ),
                    encoding="utf-8",
                )
                self.assertEqual(
                    0,
                    main(
                        [
                            "--root",
                            str(root),
                            "record-review",
                            "--phase",
                            "phase-01",
                            "--verdict",
                            "passed",
                            "--review",
                            str(review),
                            "--review-request",
                            str(request),
                            "--review-bundle",
                            str(bundle),
                            "--invocation-command",
                            f"{adjudicator} review",
                            "--invocation-receipt",
                            str(receipt),
                            "--reviewer",
                            reviewer,
                            "--adjudicator-kind",
                            adjudicator,
                            "--repo-root",
                            str(root),
                        ]
                    ),
                )

            mid_status = load_status(status_file)
            self.assertEqual("ready_for_review", mid_status["status"])
            self.assertEqual(
                0,
                main(
                    [
                        "--root",
                        str(root),
                        "record-comparison",
                        "--phase",
                        "phase-01",
                        "--agreement",
                        "agree",
                        "--closure-allowed",
                        "--reason",
                        "two reviewers passed",
                        "--repo-root",
                        str(root),
                    ]
                ),
            )
            updated = load_status(status_file)
            self.assertEqual("external_review_passed", updated["status"])


if __name__ == "__main__":
    unittest.main()
