#!/usr/bin/env python3
"""Cross-project quality checks for monitor-codebase.

Composes /treesitter violations command for AST-based checks (banned imports,
inline prompts, regex classifiers, hardcoded paths, AQL, file length, etc.)
and adds test-quality checks (handwritten tests, mock-only tests) that are
file-content based, not AST.

Replaces the previous bespoke ast.walk() implementation.
"""
from __future__ import annotations
import os

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from loguru import logger

SKILL_DIR = Path(__file__).resolve().parent
SKILLS_DIR = SKILL_DIR.parent
TREESITTER_RUN = SKILLS_DIR / "treesitter" / "run.sh"
SCHEMA_VERSION = 1

# Directories always excluded from scanning
_EXCLUDE_DIRS = {
    ".venv", "venv", "node_modules", "__pycache__", ".git", "dist", "build",
    ".eggs", ".mypy_cache", ".pytest_cache", ".uv", ".tox", ".ruff_cache",
    "site-packages", ".worktrees", ".cache", "archive-v0",
}

# Test-lab markers that distinguish generated blind tests from handwritten tests
_TEST_LAB_MARKERS = [
    "test-lab", "test_lab", "blind evaluation", "adversarial", "Generated by",
]
_TYPESCRIPT_SUFFIXES = {".ts", ".tsx", ".js", ".jsx"}
_RUST_SUFFIXES = {".rs"}
_PROMPT_SUFFIXES = {".md", ".txt"}
_PROMPT_DIR_NAMES = {"prompt", "prompts", "prompt_templates", "prompt-templates"}
_PROMPT_WEASEL_WORDS = (
    "relevant",
    "appropriate",
    "comprehensive",
    "thorough",
    "ensure",
    "consider",
    "properly",
    "meaningful",
    "high-quality",
    "as needed",
    "various",
    "leverage",
    "utilize",
)

_RULE_CONFIDENCE = {
    "use-loguru": 0.95,
    "use-httpx": 0.95,
    "use-typer": 0.95,
    "max-800-lines": 0.90,
    "inline-prompt": 0.75,
    "regex-classifier": 0.80,
    "hardcoded-skill-path": 0.90,
    "shell-aql": 0.90,
    "python-bespoke-aql": 0.90,
    "bespoke-aql": 0.90,
    "bespoke-aql-api": 0.90,
    "handwritten-tests": 0.70,
    "mock-only-tests": 0.85,
    "typescript-any-type": 0.90,
    "typescript-inline-import": 0.90,
    "typescript-barrel-import": 0.80,
    "rust-unwrap": 0.85,
    "rust-debug-output": 0.95,
    "prompt-missing-rationale": 0.85,
    "prompt-weasel-word": 0.75,
    "prompt-missing-output-format": 0.70,
    "prompt-missing-review-payload": 0.80,
}

_RULE_ROUTE = {
    "use-loguru": "code-runner",
    "use-httpx": "code-runner",
    "use-typer": "code-runner",
    "max-800-lines": "subagent-runner",
    "inline-prompt": "subagent-runner",
    "regex-classifier": "subagent-runner",
    "hardcoded-skill-path": "code-runner",
    "shell-aql": "code-runner",
    "python-bespoke-aql": "code-runner",
    "bespoke-aql": "code-runner",
    "bespoke-aql-api": "code-runner",
    "handwritten-tests": "human-review",
    "mock-only-tests": "code-runner",
    "typescript-any-type": "code-runner",
    "typescript-inline-import": "code-runner",
    "typescript-barrel-import": "code-runner",
    "rust-unwrap": "code-runner",
    "rust-debug-output": "code-runner",
    "prompt-missing-rationale": "review-prompt",
    "prompt-weasel-word": "review-prompt",
    "prompt-missing-output-format": "review-prompt",
    "prompt-missing-review-payload": "code-runner",
}

_RULE_ACTIONS = {
    "use-loguru": (
        "replace-logging",
        "Replace stdlib logging with `from loguru import logger`.",
        True,
    ),
    "use-httpx": (
        "replace-requests",
        "Replace requests calls with httpx and preserve timeout/error handling.",
        True,
    ),
    "use-typer": (
        "replace-argparse",
        "Replace argparse CLI wiring with a thin Typer command surface.",
        False,
    ),
    "max-800-lines": (
        "split-large-file",
        "Split the file into named modules with stable imports and focused tests.",
        False,
    ),
    "inline-prompt": (
        "externalize-prompt",
        "Move long prompt text into a prompt template or documented resource.",
        False,
    ),
    "regex-classifier": (
        "replace-regex-classifier",
        "Replace brittle regex classification with a structured classifier path.",
        False,
    ),
    "hardcoded-skill-path": (
        "use-skills-dir",
        "Resolve skill paths from SKILLS_DIR or the skill root instead of hardcoding.",
        True,
    ),
    "shell-aql": (
        "use-memory-api",
        "Move raw AQL out of shell and call the memory API boundary instead.",
        False,
    ),
    "python-bespoke-aql": (
        "use-memory-api",
        "Replace bespoke AQL with the memory API or shared Arango helper.",
        False,
    ),
    "bespoke-aql": (
        "use-memory-api",
        "Replace bespoke AQL with the memory API or shared Arango helper.",
        False,
    ),
    "bespoke-aql-api": (
        "use-memory-api",
        "Replace bespoke AQL API access with the memory API boundary.",
        False,
    ),
    "handwritten-tests": (
        "review-test-source",
        "Review whether this handwritten test should come from /test-lab or be documented.",
        False,
    ),
    "mock-only-tests": (
        "add-real-smoke-test",
        "Add a non-mocked sanity or smoke test that exercises the composed path.",
        False,
    ),
    "typescript-any-type": (
        "replace-any",
        "Replace `any` with a concrete type, unknown plus narrowing, or a local interface.",
        False,
    ),
    "typescript-inline-import": (
        "replace-inline-import",
        "Replace dynamic/type-position inline imports with top-level imports.",
        False,
    ),
    "typescript-barrel-import": (
        "replace-barrel-import",
        "Import from the concrete module to keep dependency and bundle boundaries visible.",
        False,
    ),
    "rust-unwrap": (
        "replace-unwrap",
        "Replace `.unwrap()` with `?`, `let else`, or an invariant `expect` with context.",
        False,
    ),
    "rust-debug-output": (
        "replace-debug-output",
        "Replace debug output with tracing or structured user-facing output.",
        True,
    ),
    "prompt-missing-rationale": (
        "add-prompt-rationale",
        "Add a best-practices-prompt rationale header: purpose, consumer, risk, input, output, and last reviewed.",
        False,
    ),
    "prompt-weasel-word": (
        "replace-vague-prompt-language",
        "Replace vague prompt language with concrete nouns, closed criteria, and measurable quantities.",
        False,
    ),
    "prompt-missing-output-format": (
        "add-output-contract",
        "Add an exact output schema or format contract near the end of the prompt.",
        False,
    ),
    "prompt-missing-review-payload": (
        "add-review-payload",
        "Add or regenerate a review/*_payload.txt file for review-prompt and external LLM audit.",
        False,
    ),
}


def _should_skip(path: Path) -> bool:
    parts = path.parts
    if set(parts) & _EXCLUDE_DIRS:
        return True
    # Catch .venv-batch, .venv_old, .venv.bak and any other venv variant
    return any(part.startswith(".venv") for part in parts)


def _iter_py_files(root: Path) -> list[Path]:
    return [f for f in root.rglob("*.py") if not _should_skip(f)]


def _iter_files(root: Path, suffixes: set[str]) -> list[Path]:
    """Return source files with suffix filtering and shared directory excludes."""
    return [
        f for f in root.rglob("*")
        if f.is_file() and f.suffix in suffixes and not _should_skip(f)
    ]


def _read_text(path: Path) -> str:
    """Read text for heuristic scanners."""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _line_number(content: str, offset: int) -> int:
    """Return a 1-based line number for a character offset."""
    return content.count("\n", 0, offset) + 1


def _relative_path(path_value: object, root: Path) -> str:
    """Return a stable project-relative path for JSON output."""
    if not path_value:
        return ""

    path_text = str(path_value)
    path = Path(path_text)
    if not path.is_absolute():
        return path_text

    try:
        return str(path.relative_to(root))
    except ValueError:
        return path_text


def _route_allowlist(rule: str, file_path: str) -> list[str]:
    """Return a conservative write allowlist for a routed finding."""
    if rule == "mock-only-tests":
        return ["tests/", "sanity.sh"]
    if rule == "handwritten-tests":
        return []
    if rule == "prompt-missing-review-payload":
        return [file_path, str(Path(file_path).parent / "review")]
    if file_path and file_path != ".":
        return [file_path]
    return []


def _route_dod(rule: str, file_path: str) -> dict[str, str] | None:
    """Suggest a minimal deterministic verification command for a finding."""
    if rule == "mock-only-tests":
        return {
            "command": "python -m compileall -q tests",
            "assertion": "exit_code == 0",
        }
    if file_path.endswith(".rs"):
        return {
            "command": "cargo check --workspace --all-targets",
            "assertion": "exit_code == 0",
        }
    if file_path.endswith((".ts", ".tsx", ".js", ".jsx")):
        return {
            "command": "npm run check",
            "assertion": "exit_code == 0",
        }
    if file_path.endswith(".py"):
        return {
            "command": f"python -m py_compile {file_path}",
            "assertion": "exit_code == 0",
        }
    if file_path.endswith(".sh"):
        return {
            "command": f"bash -n {file_path}",
            "assertion": "exit_code == 0",
        }
    if rule.startswith("prompt-"):
        return {
            "command": "review-prompt --dry-run with the prompt template and source context",
            "assertion": "review payload can be assembled without missing files",
        }
    return None


def _default_action(rule: str) -> dict[str, object]:
    """Build the primary action for a rule."""
    action_type, description, auto_fixable = _RULE_ACTIONS.get(
        rule,
        (
            "review-finding",
            "Review this finding and choose a project-specific remediation.",
            False,
        ),
    )
    return {
        "type": action_type,
        "auto_fixable": auto_fixable,
        "runner": _RULE_ROUTE.get(rule, "human-review"),
        "description": description,
    }


def _suppression_action(rule: str) -> dict[str, object]:
    """Build the standard suppression/documentation action."""
    return {
        "type": "suppress",
        "auto_fixable": False,
        "description": (
            f"Document why `{rule}` is acceptable for this file and add a "
            "narrow suppression only if the project owner accepts the tradeoff."
        ),
    }


def _remediation_route(rule: str, file_path: str) -> dict[str, object]:
    """Suggest the safest downstream runner for a finding."""
    runner = _RULE_ROUTE.get(rule, "human-review")
    route: dict[str, object] = {
        "runner": runner,
        "confidence": 0.72
        if runner == "code-runner"
        else 0.68
        if runner == "review-prompt"
        else 0.55,
        "reason": "Bounded finding with an executable verification path"
        if runner == "code-runner"
        else "Prompt finding should be reviewed by the prompt review loop"
        if runner == "review-prompt"
        else "Finding needs architectural judgment or human review",
    }
    allowlist = _route_allowlist(rule, file_path)
    if allowlist:
        route["allowlist"] = allowlist
    dod = _route_dod(rule, file_path)
    if dod:
        route["definition_of_done"] = dod
    return route


def _normalize_violation(
    violation: dict[str, Any],
    root: Path,
    detector: str,
) -> dict[str, Any]:
    """Add stable automation metadata to a raw violation."""
    normalized = dict(violation)
    rule = str(normalized.get("rule", "unknown"))
    file_path = _relative_path(normalized.get("file") or normalized.get("path"), root)
    if not file_path:
        file_path = "."

    line_value = normalized.get("line", 0)
    try:
        line = int(line_value or 0)
    except (TypeError, ValueError):
        line = 0

    normalized["rule"] = rule
    normalized["file"] = file_path
    normalized["line"] = line
    normalized.setdefault("severity", "warn")
    normalized.setdefault("confidence", _RULE_CONFIDENCE.get(rule, 0.60))
    normalized.setdefault(
        "finding_id",
        f"{rule}:{file_path}:{line}",
    )
    normalized.setdefault(
        "evidence",
        {
            "source": "monitor-codebase",
            "detector": detector,
        },
    )
    normalized.setdefault(
        "actions",
        [
            _default_action(rule),
            _suppression_action(rule),
        ],
    )
    normalized.setdefault("remediation_route", _remediation_route(rule, file_path))
    return normalized


# ---------------------------------------------------------------------------
# Treesitter-based checks (compose /treesitter violations)
# ---------------------------------------------------------------------------

def _run_treesitter_violations(
    root: Path,
    exclude_rules: list[str] | None = None,
) -> list[dict[str, Any]]:
    """Call /treesitter violations and return parsed results."""
    cmd = [str(TREESITTER_RUN), "violations", str(root), "--json"]
    if exclude_rules:
        cmd.extend(["--exclude-rules", ",".join(exclude_rules)])

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=120,
            env={k: v for k, v in os.environ.items() if k != 'VIRTUAL_ENV'},
        )
        # Exit code 1 means violations found (not an error)
        if result.stdout.strip():
            return json.loads(result.stdout)
        return []
    except (subprocess.TimeoutExpired, json.JSONDecodeError, OSError) as e:
        logger.warning("treesitter violations failed: {}", e)
        return []


# ---------------------------------------------------------------------------
# File-content checks (not AST — test quality detection)
# ---------------------------------------------------------------------------

def _check_handwritten_tests(root: Path) -> list[dict[str, Any]]:
    """Detect test files without test-lab markers."""
    violations = []
    for py_file in _iter_py_files(root):
        if not py_file.name.startswith("test_"):
            continue
        try:
            content = py_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if not any(marker in content for marker in _TEST_LAB_MARKERS):
            violations.append({
                "rule": "handwritten-tests",
                "file": str(py_file.relative_to(root)),
                "line": 0,
                "message": "Test file has no test-lab markers — use /test-lab generate",
                "severity": "warn",
            })
    return violations


def _check_mock_only_tests(root: Path) -> list[dict[str, Any]]:
    """Detect projects where ALL tests use mocks with no integration tests."""
    test_files = [f for f in _iter_py_files(root) if f.name.startswith("test_")]
    if not test_files:
        return []

    has_sanity = (root / "sanity.sh").exists()
    all_mocked = True
    for tf in test_files:
        try:
            content = tf.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if not any(p in content for p in [
            "unittest.mock", "MagicMock", "AsyncMock", "@patch", "mock.patch",
        ]):
            all_mocked = False
            break

    if all_mocked and not has_sanity:
        return [{
            "rule": "mock-only-tests",
            "file": str(root),
            "line": 0,
            "message": "All tests use mocks but no sanity.sh — mock tests pass while real service may be broken",
            "severity": "warn",
        }]
    return []


def _check_typescript_practices(root: Path) -> list[dict[str, Any]]:
    """Detect conservative TypeScript/React best-practice violations."""
    violations = []
    any_pattern = re.compile(r"(:\s*any\b|as\s+any\b|<any>)")
    inline_import_pattern = re.compile(r"\bimport\s*\(")
    barrel_import_pattern = re.compile(r"from\s+['\"](?:\.\.?/)?(?:index)?['\"]")

    for source_file in _iter_files(root, _TYPESCRIPT_SUFFIXES):
        if source_file.name.endswith(".d.ts"):
            continue

        content = _read_text(source_file)
        if not content:
            continue

        rel = str(source_file.relative_to(root))
        for match in any_pattern.finditer(content):
            violations.append({
                "rule": "typescript-any-type",
                "file": rel,
                "line": _line_number(content, match.start()),
                "message": "TypeScript uses `any`; prefer a concrete type or `unknown` with narrowing",
                "severity": "warn",
            })

        for match in inline_import_pattern.finditer(content):
            violations.append({
                "rule": "typescript-inline-import",
                "file": rel,
                "line": _line_number(content, match.start()),
                "message": "Inline import detected; use top-level imports for agent-readable dependencies",
                "severity": "warn",
            })

        if source_file.suffix in {".tsx", ".jsx"}:
            for match in barrel_import_pattern.finditer(content):
                violations.append({
                    "rule": "typescript-barrel-import",
                    "file": rel,
                    "line": _line_number(content, match.start()),
                    "message": "Barrel import obscures component/module boundaries",
                    "severity": "info",
                })

    return violations


def _check_rust_practices(root: Path) -> list[dict[str, Any]]:
    """Detect conservative Rust best-practice violations."""
    violations = []
    unwrap_pattern = re.compile(r"\.unwrap\s*\(")
    debug_output_pattern = re.compile(r"\b(?:dbg!|eprintln!)\s*\(")

    for source_file in _iter_files(root, _RUST_SUFFIXES):
        rel = str(source_file.relative_to(root))
        if "/tests/" in f"/{rel}/" or rel.endswith("_test.rs"):
            continue

        content = _read_text(source_file)
        if not content:
            continue

        for match in unwrap_pattern.finditer(content):
            violations.append({
                "rule": "rust-unwrap",
                "file": rel,
                "line": _line_number(content, match.start()),
                "message": "Rust production code uses `.unwrap()`; return context or document an invariant",
                "severity": "warn",
            })

        for match in debug_output_pattern.finditer(content):
            violations.append({
                "rule": "rust-debug-output",
                "file": rel,
                "line": _line_number(content, match.start()),
                "message": "Rust debug output detected; use tracing or a deliberate user-facing output path",
                "severity": "warn",
            })

    return violations


def _is_prompt_file(path: Path, root: Path) -> bool:
    """Return whether a text file is likely to be an LLM prompt template."""
    if path.suffix not in _PROMPT_SUFFIXES:
        return False

    rel_parts = tuple(part.lower() for part in path.relative_to(root).parts)
    if set(rel_parts) & _PROMPT_DIR_NAMES:
        return True
    return "prompt" in path.stem.lower()


def _has_prompt_output_format(content: str) -> bool:
    """Detect explicit prompt output contracts without trying to parse prose."""
    lowered = content.lower()
    return any(
        marker in lowered
        for marker in (
            "output format",
            "output schema",
            "return only",
            "json schema",
            "pydantic",
            "schema:",
            "exact schema",
        )
    )


def _has_review_payload(path: Path) -> bool:
    """Check for a nearby review payload consumed by review-prompt."""
    review_dir = path.parent / "review"
    if not review_dir.is_dir():
        return False

    stem = path.stem.replace("_system", "").replace("_user", "")
    payloads = list(review_dir.glob("*_payload.txt"))
    if not payloads:
        return False
    return any(stem in payload.stem for payload in payloads) or len(payloads) == 1


def _check_prompt_practices(root: Path) -> list[dict[str, Any]]:
    """Detect best-practices-prompt issues in prompt templates."""
    violations = []
    word_pattern = re.compile(
        r"\b(" + "|".join(re.escape(word) for word in _PROMPT_WEASEL_WORDS) + r")\b",
        re.IGNORECASE,
    )

    for prompt_file in _iter_files(root, _PROMPT_SUFFIXES):
        if not _is_prompt_file(prompt_file, root):
            continue

        content = _read_text(prompt_file)
        if not content:
            continue

        rel = str(prompt_file.relative_to(root))
        if "# RATIONALE" not in content[:800]:
            violations.append({
                "rule": "prompt-missing-rationale",
                "file": rel,
                "line": 1,
                "message": "Prompt template is missing a best-practices-prompt rationale header",
                "severity": "warn",
            })

        for match in word_pattern.finditer(content):
            violations.append({
                "rule": "prompt-weasel-word",
                "file": rel,
                "line": _line_number(content, match.start()),
                "message": f"Prompt uses vague word `{match.group(0)}`; replace it with concrete criteria",
                "severity": "info",
            })

        if not _has_prompt_output_format(content):
            violations.append({
                "rule": "prompt-missing-output-format",
                "file": rel,
                "line": 1,
                "message": "Prompt template does not name an exact output format or schema",
                "severity": "warn",
            })

        if "_system" in prompt_file.stem or "_user" in prompt_file.stem:
            if not _has_review_payload(prompt_file):
                violations.append({
                    "rule": "prompt-missing-review-payload",
                    "file": rel,
                    "line": 1,
                    "message": "Prompt pair is missing a review/*_payload.txt file for review-prompt audit",
                    "severity": "warn",
                })

    return violations


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def scan_project(project_path: str, include_dirs: list[str] | None = None) -> dict[str, Any]:
    """Run all quality checks against a project directory."""
    root = Path(project_path).resolve()
    if not root.is_dir():
        return {
            "schema_version": SCHEMA_VERSION,
            "error": f"Not a directory: {root}",
            "violations": [],
        }

    scan_roots = []
    if include_dirs:
        for d in include_dirs:
            p = root / d
            if p.is_dir():
                scan_roots.append(p)
    if not scan_roots:
        scan_roots = [root]

    all_violations: list[dict[str, Any]] = []

    # Determine treesitter exclusions
    # Memory project is exempt from AQL checks
    exclude_rules = None
    if root.name == "memory" or "experiments/memory" in str(root):
        exclude_rules = ["bespoke-aql", "bespoke-aql-api"]

    for scan_root in scan_roots:
        logger.info("Quality scanning: {}", scan_root)

        # AST-based checks via /treesitter violations
        ts_violations = _run_treesitter_violations(scan_root, exclude_rules)
        all_violations.extend(ts_violations)

        # File-content checks (test quality — not AST)
        all_violations.extend(_check_handwritten_tests(scan_root))
        all_violations.extend(_check_mock_only_tests(scan_root))
        all_violations.extend(_check_typescript_practices(scan_root))
        all_violations.extend(_check_rust_practices(scan_root))
        all_violations.extend(_check_prompt_practices(scan_root))

    all_violations = [
        _normalize_violation(v, root, "quality_checks.py")
        for v in all_violations
    ]

    # Group by rule
    by_rule: dict[str, int] = {}
    for v in all_violations:
        by_rule[v["rule"]] = by_rule.get(v["rule"], 0) + 1

    return {
        "schema_version": SCHEMA_VERSION,
        "project": str(root),
        "total_violations": len(all_violations),
        "by_rule": by_rule,
        "violations": all_violations,
        "languages": {
            "python": bool(_iter_py_files(root)),
            "typescript": bool(_iter_files(root, _TYPESCRIPT_SUFFIXES)),
            "rust": bool(_iter_files(root, _RUST_SUFFIXES)),
            "prompts": any(
                _is_prompt_file(path, root)
                for path in _iter_files(root, _PROMPT_SUFFIXES)
            ),
        },
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    import typer

    app = typer.Typer(help="Cross-project quality checks for monitor-codebase.")

    @app.command()
    def scan(
        project: str = typer.Argument(help="Project directory to scan"),
        json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
    ) -> None:
        result = scan_project(project)
        if json_output:
            print(json.dumps(result, indent=2))
        else:
            total = result["total_violations"]
            print(f"\n=== Quality Check: {result['project']} ===")
            print(f"Total violations: {total}")
            if result["by_rule"]:
                print("\nBy rule:")
                for rule, count in sorted(result["by_rule"].items()):
                    print(f"  {rule}: {count}")
            if total > 0:
                print(f"\nTop violations:")
                for v in result["violations"][:30]:
                    print(f"  [{v['rule']}] {v.get('file', '?')}: {v['message']}")
                if total > 30:
                    print(f"  ... and {total - 30} more")

    app()


if __name__ == "__main__":
    main()
