#!/usr/bin/env python3
# Generated by test-lab — blind adversarial evaluation
"""test_backend_defaults - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[3]
CODE_RUNNER = ROOT / "skills" / "code-runner" / "code_runner.py"
sys.path.insert(0, str(CODE_RUNNER.parent))


def load_code_runner():
    spec = importlib.util.spec_from_file_location("code_runner_under_test", CODE_RUNNER)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


@pytest.fixture()
def module():
    return load_code_runner()


def test_call_llm_uses_sse_and_reasoning(module) -> None:
    captured = {}

    def fake_stream(payload, **kwargs):
        captured["payload"] = payload
        captured["kwargs"] = kwargs
        return {"choices": [{"message": {"content": "OK"}, "finish_reason": "stop"}]}

    module._stream_chat_completion = fake_stream
    result = module._call_llm("prompt", "codex", ".", reasoning="high", task_id="task", round_num=2)
    assert result == "OK"
    assert captured["payload"]["reasoning_effort"] == "high"
    assert captured["payload"]["model"] == "gpt-5.5"
    assert captured["kwargs"]["headers"]["X-Caller-Skill"] == "code-runner:task:2"


def test_removed_runner_features_are_rejected(module) -> None:
    base = {
        "task_id": "bounded",
        "title": "bounded",
        "prompt": "Read app.py and fix the bounded behavior in the allowlisted file.",
        "backend": "test",
        "cwd": ".",
        "output_dir": "/tmp/code-runner-test",
        "allowlist": ["app.py"],
        "definition_of_done": {"command": "python app.py", "assertion": "OK"},
    }
    module.TaskSpec.model_validate({**base, "dirty_worktree_policy": "isolated_worktree"})
    for extra in (
        {"dirty_worktree_policy": "fail_closed"},
        {"predecessor_patches": ["/tmp/parent.patch"]},
        {"escalation_chain": [["codex", "high"], ["claude", "high"]]},
    ):
        try:
            module.TaskSpec.model_validate({**base, **extra})
        except Exception:
            pass
        else:
            raise AssertionError(f"removed feature was accepted: {extra}")


def test_source_apply_options_are_explicit(module) -> None:
    base = {
        "task_id": "bounded",
        "title": "bounded",
        "prompt": "Read app.py and fix the bounded behavior in the allowlisted file.",
        "backend": "test",
        "cwd": ".",
        "output_dir": "/tmp/code-runner-test",
        "allowlist": ["app.py"],
        "definition_of_done": {"command": "python app.py", "assertion": "OK"},
    }
    spec = module.TaskSpec.model_validate(base)
    assert spec.apply_to_source is False
    assert spec.commit_on_success is False
    assert spec.rollback_on_failure is True
    spec = module.TaskSpec.model_validate({**base, "apply_to_source": True, "commit_on_success": True})
    assert spec.apply_to_source is True
    assert spec.commit_on_success is True
    try:
        module.TaskSpec.model_validate({**base, "commit_on_success": True})
    except Exception:
        pass
    else:
        raise AssertionError("commit_on_success must require apply_to_source")


def test_commit_source_allowlist_rejects_unrelated_staged_paths(module, tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True, text=True)
    subprocess.run(["git", "config", "user.email", "code-runner@example.test"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Code Runner"], cwd=repo, check=True)
    (repo / "app.py").write_text("print('old')\n")
    (repo / "unrelated.py").write_text("print('old')\n")
    subprocess.run(["git", "add", "app.py", "unrelated.py"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, capture_output=True, text=True)

    (repo / "app.py").write_text("print('new')\n")
    (repo / "unrelated.py").write_text("print('dirty staged')\n")
    subprocess.run(["git", "add", "unrelated.py"], cwd=repo, check=True)

    try:
        module._commit_source_allowlist(str(repo), ["app.py"], "task", "title")
    except RuntimeError as exc:
        assert "outside allowlist" in str(exc)
    else:
        raise AssertionError("commit_source_allowlist must reject unrelated staged paths")


def test_source_apply_rolls_back_failed_source_dod_and_cleans_byproducts(module, tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True, text=True)
    subprocess.run(["git", "config", "user.email", "code-runner@example.test"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Code Runner"], cwd=repo, check=True)
    (repo / "app.py").write_text("print('BASELINE')\n")
    subprocess.run(["git", "add", "app.py"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, capture_output=True, text=True)

    patch_file = tmp_path / "bad.patch"
    patch_file.write_text(
        "diff --git a/app.py b/app.py\n"
        "index 8490b48..1d6f2c1 100644\n"
        "--- a/app.py\n"
        "+++ b/app.py\n"
        "@@ -1 +1 @@\n"
        "-print('BASELINE')\n"
        "+print('BROKEN')\n"
    )

    state = module._finalize_source_apply(
        source_cwd=str(repo),
        patch_artifact=patch_file,
        allowlist=["app.py"],
        dod_command="mkdir -p __pycache__ && python app.py",
        dod_assertion="contains:UNIQUE_SUCCESS_SENTINEL",
        lang="python",
        task_id="rollback",
        title="Rollback fixture",
        commit_on_success=True,
        rollback_on_failure=True,
    )

    assert state["source_patch_applied"] is True
    assert state["source_dod_passed"] is False
    assert state["source_rollback_applied"] is True
    assert state["source_commit"] == ""
    assert "BROKEN" in state["source_apply_error"]
    assert (repo / "app.py").read_text() == "print('BASELINE')\n"
    assert subprocess.check_output(["git", "status", "--short"], cwd=repo, text=True) == ""


def main() -> None:
    module = load_code_runner()
    assert module._backend_model_name("codex") == "gpt-5.5"
    assert module._backend_model_name("text") == "text"
    assert module._backend_model_name("deepseek") == "deepseek-ai/DeepSeek-V3"
    assert module._default_escalation_chain("codex") == [["codex", "high"]]
    try:
        module._backend_model_name("unknown")
    except ValueError:
        pass
    else:
        raise AssertionError("unknown backend must not silently map to gpt-5.5")
    test_call_llm_uses_sse_and_reasoning(module)
    test_removed_runner_features_are_rejected(module)
    test_source_apply_options_are_explicit(module)
    print("BACKEND_DEFAULTS_OK")


if __name__ == "__main__":
    main()
