# Generated by test-lab — blind adversarial evaluation
"""test_gap_analysis_hooks - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

import copy

from candidate_qra import build_gap_review_candidate
from gate import classify


def test_malformed_question_surface_is_gated_before_gap_review():
    rule, verdict, blocking = classify([], "Decision Surface\nCAPEC-649\n000a5d68cbd446e5")

    assert rule == "RULE_0B_FAIL_NON_QUESTION_SURFACE"
    assert verdict == "NONSENSICAL"
    assert blocking


def test_dangling_payload_referent_is_failed_not_clarified():
    rule, verdict, blocking = classify([], "Why is CAPEC-649 relevant to T1036.006 in this payload?")

    assert rule == "RULE_0_FAIL_AMBIGUOUS_REFERENT"
    assert verdict == "CLARIFY"
    assert blocking == ["this payload"]


def test_gap_review_candidate_is_advisory_and_does_not_mutate_case_result():
    case_result = {
        "case_id": "case-1",
        "evidence_case_version": "v3",
        "evidence_case_hash": "hash-1",
        "verdict": {"state": "INCONCLUSIVE"},
        "gate_trace": [
            {"gate": "entity_resolution", "passed": True, "detail": "CAPEC-649 resolved"},
            {
                "gate": "technique_bridge",
                "passed": False,
                "detail": "No retrieved bridge connected the entities.",
                "blocking_entities": ["CAPEC-649", "T10"],
            },
        ],
        "entities": [{"entity": "CAPEC-649", "status": "resolved"}],
        "evidence": [{"source_id": "src-1", "excerpt": "retrieved text"}],
    }
    before = copy.deepcopy(case_result)

    candidate = build_gap_review_candidate(
        question="Why is CAPEC-649 relevant to T10 command-path risk?",
        case_result=case_result,
        clarify_result={"needed": "source artifact"},
    )

    assert case_result == before
    assert candidate["kind"] == "cae_gap_review_candidate"
    assert candidate["advisory_only"] is True
    assert candidate["mutation_policy"] == "no_qra_mutation"
    assert candidate["evidence_case_id"] == "case-1"
    assert candidate["evidence_case_version"] == "v3"
    assert candidate["source_evidence_case_hash"] == "hash-1"
    assert candidate["final_status"] == "NEEDS_VERIFICATION"
    assert candidate["qra_correction_recommendation"]["requires_new_evidence_case"] is True
    assert candidate["missing_spans"][0]["gate"] == "technique_bridge"
    assert candidate["source_artifacts"][0]["source_id"] == "src-1"
