#!/usr/bin/env python3
# Generated by test-lab — blind adversarial evaluation
"""Tests for voice design interview question generation."""

import pytest
from pathlib import Path
import sys

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

from design import (
    generate_interview_questions,
    process_interview_results,
    ACCENT_DATABASE,
    CULTURAL_EMOTIONAL_NORMS,
)


def test_interview_questions_count():
    """Verify 17 questions generated correctly."""
    questions = generate_interview_questions("Test Person")
    assert "questions" in questions
    # Should have all 17 question categories
    assert len(questions["questions"]) == 17, f"Expected 17 questions, got {len(questions['questions'])}"


def test_interview_questions_structure():
    """Verify question structure has required fields."""
    questions = generate_interview_questions("Marcus Aurelius")
    
    for q in questions["questions"]:
        assert "id" in q, "Question missing 'id' field"
        assert "header" in q, "Question missing 'header' field"
        assert "text" in q, "Question missing 'text' field"
        assert "options" in q, "Question missing 'options' field"
        assert "multi_select" in q, "Question missing 'multi_select' field"
        
        # Verify options structure
        for opt in q["options"]:
            assert "label" in opt, "Option missing 'label'"
            assert "description" in opt, "Option missing 'description'"


def test_interview_question_ids():
    """Verify all expected question IDs are present."""
    expected_ids = [
        "geographic_origin",
        "time_period",
        "birth_death_years",
        "formative_events",
        "prime_events",
        "late_events",
        "social_class",
        "personality",
        "emotional_coloring",
        "family_structure",
        "religion",
        "religiosity_level",
        "cultural_emotional_norms",
        "current_persona_age",
        "recent_impactful_event",
        "suppression_level",
        "modern_reference",
    ]
    
    questions = generate_interview_questions("Test Person")
    actual_ids = [q["id"] for q in questions["questions"]]
    
    for expected_id in expected_ids:
        assert expected_id in actual_ids, f"Missing question ID: {expected_id}"


def test_multi_select_questions():
    """Verify multi-select questions are correctly marked."""
    questions = generate_interview_questions("Test Person")
    
    multi_select_ids = ["formative_events", "prime_events", "late_events", 
                        "personality", "emotional_coloring", "family_structure", 
                        "modern_reference"]
    
    for q in questions["questions"]:
        if q["id"] in multi_select_ids:
            assert q["multi_select"] is True, f"Question {q['id']} should be multi-select"
        else:
            assert q["multi_select"] is False, f"Question {q['id']} should be single-select"


def test_process_interview_results_structure():
    """Verify interview processing produces correct structure."""
    mock_responses = {
        "responses": {
            "geographic_origin": "Rome, Italy",
            "time_period": "Ancient (before 500 CE)",
            "birth_death_years": "121-180 CE",
            "formative_events": ["Loss of parent/family"],
            "prime_events": ["Political Power"],
            "late_events": ["Reflection/Writing"],
            "social_class": "Aristocracy/Nobility",
            "personality": ["Stoic/Measured"],
            "emotional_coloring": ["Serene"],
            "family_structure": ["Eldest child"],
            "religion": "Stoic philosophy",
            "religiosity_level": "Devout/Practicing",
            "cultural_emotional_norms": "Greco-Roman Stoic",
            "current_persona_age": "Elder (65+)",
            "recent_impactful_event": "None significant",
            "suppression_level": "Moderately suppressed",
            "modern_reference": ["Richard Harris"],
        }
    }
    
    design = process_interview_results("Marcus Aurelius", mock_responses)
    
    assert "persona" in design
    assert design["persona"] == "Marcus Aurelius"
    assert "voice_design" in design
    
    vd = design["voice_design"]
    assert "geographic_origin" in vd
    assert "emotional_layers" in vd
    assert "life_events" in vd
    assert "family_structure" in vd
    assert "religion" in vd
    assert "cultural_emotional_norms" in vd


def test_emotional_layers_generation():
    """Verify emotional layers are generated from life events."""
    mock_responses = {
        "responses": {
            "formative_events": ["Loss of parent/family", "Privileged education"],
            "prime_events": ["War/Conflict", "Political Power"],
            "late_events": ["Reflection/Writing"],
            "family_structure": ["Eldest child"],
            "religion": "Stoic philosophy",
            "religiosity_level": "Devout/Practicing",
            "cultural_emotional_norms": "Greco-Roman Stoic",
            "current_persona_age": "Elder (65+)",
            "recent_impactful_event": "None significant",
            "suppression_level": "Moderately suppressed",
            "social_class": "Aristocracy/Nobility",
            "personality": ["Stoic/Measured"],
            "emotional_coloring": [],
            "geographic_origin": "Rome",
            "time_period": "Ancient",
            "birth_death_years": "121-180",
            "modern_reference": [],
        }
    }
    
    design = process_interview_results("Test", mock_responses)
    layers = design["voice_design"]["emotional_layers"]
    
    assert "foundational" in layers
    assert "defining" in layers
    assert "current" in layers
    
    # Verify foundational layer includes early loss
    assert len(layers["foundational"]) > 0
    assert any("grief" in layer.lower() for layer in layers["foundational"])
    
    # Verify defining layer includes political power
    assert len(layers["defining"]) > 0
    
    # Verify current layer includes reflection
    assert len(layers["current"]) > 0


def test_accent_database_coverage():
    """Verify accent database has expected entries."""
    expected_regions = [
        "boston_colonial",
        "charleston_southern",
        "philadelphia_colonial",
        "london_victorian",
        "rome_classical",
        "hawaii_modern",
    ]
    
    for region in expected_regions:
        assert region in ACCENT_DATABASE, f"Missing accent: {region}"
        accent = ACCENT_DATABASE[region]
        assert "region" in accent
        assert "era" in accent
        assert "characteristics" in accent
        assert "modern_reference" in accent


def test_cultural_norms_database():
    """Verify cultural emotional norms have TTS impact."""
    for culture, data in CULTURAL_EMOTIONAL_NORMS.items():
        assert "display_rules" in data
        assert "grief_norms" in data
        assert "suppression_level" in data
        assert "tts_impact" in data
        assert isinstance(data["suppression_level"], float)
        assert 0.0 <= data["suppression_level"] <= 1.0


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
