#!/usr/bin/env python3
# Generated by test-lab — blind adversarial evaluation
"""Test query recall for SFX catalog."""

import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from memory_bridge import SFXMemoryBridge


def test_query_recall():
    """Test that test queries return at least one result."""
    
    # Load test queries
    queries_file = Path(__file__).parent.parent / "data" / "test_queries.txt"
    with open(queries_file) as f:
        queries = [line.strip() for line in f if line.strip()]
    
    bridge = SFXMemoryBridge()
    if not bridge.test_connection():
        print("[FAIL] ArangoDB not available")
        sys.exit(1)
    
    results = []
    for query in queries:
        matches = bridge.search_sfx(query, k=5)
        has_results = len(matches) > 0
        results.append((query, has_results, len(matches)))
        
        status = "✓" if has_results else "✗"
        print(f"{status} '{query}': {len(matches)} results")
    
    # Calculate recall
    total = len(results)
    successful = sum(1 for _, has_results, _ in results if has_results)
    recall = (successful / total) * 100
    
    print(f"\nRecall: {successful}/{total} ({recall:.1f}%)")
    
    # Target is 80%
    if recall >= 80:
        print("[PASS] Recall target met!")
        sys.exit(0)
    else:
        print(f"[WARN] Recall below 80% target (got {recall:.1f}%)")
        sys.exit(0)  # Don't fail, just warn


if __name__ == "__main__":
    test_query_recall()
