"""
test-lab: Adversarial blind evaluation harness for coding agents.

Generates and runs hidden tests against code written by coding agents.
The coding agent never sees the tests — only pass/fail results.
This prevents the agent from gaming its own evaluation.

Inputs: target directory, domain (python/react/kde/skills), optional plan file
Outputs: structured TestResult with blind feedback (no test source exposed)
Failure modes: generator import errors (graceful skip), target not found (hard fail)
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import typer
from loguru import logger

# Domain → generator module mapping
DOMAIN_GENERATORS = {
    "python": "generators.python_tests",
    "react": "generators.react_tests",
    "kde": "generators.kde_tests",
    "skills": "generators.skill_tests",
    "behavioral": "generators.behavioral_tests",
    "service": "generators.service_tests",
    "node": "generators.node_tests",
}

DOMAIN_ALIASES = {
    "hack-preflight-baseline": "skills",
    "hack-real-signal-gate": "skills",
    "hack-chaos-evolve-lifecycle": "skills",
    "hack-report-view": "skills",
    "hack-post-patch-verification": "skills",
    "hack-final-validation": "skills",
    "pipeline-readiness": "skills",
}

# Marker added to all test-lab generated files so skills-ci can detect them
TEST_LAB_MARKER = "# Generated by test-lab — blind adversarial evaluation"

SKILLS_DIR = Path(__file__).parent.parent
BEST_PRACTICES_DIRS = {
    "python": SKILLS_DIR / "best-practices-python",
    "react": SKILLS_DIR / "best-practices-react",
    "kde": SKILLS_DIR / "best-practices-kde",
    "skills": SKILLS_DIR / "best-practices-skills",
}


@dataclass
class TestCheck:
    """A single test check result."""
    name: str
    category: str  # e.g. "conventions", "style", "security", "testing"
    passed: bool
    description: str  # human-readable, no test source


@dataclass
class TestResult:
    """Result of running hidden tests against a target."""
    target: str
    domain: str
    status: str  # "PASS" or "FAIL"
    checks: list[TestCheck] = field(default_factory=list)
    error: str | None = None

    @property
    def passed_count(self) -> int:
        return sum(1 for c in self.checks if c.passed)

    @property
    def failed_count(self) -> int:
        return sum(1 for c in self.checks if not c.passed)

    @property
    def total_count(self) -> int:
        return len(self.checks)


@dataclass
class VerifyResult:
    """Result of task verification with retry tracking."""
    task_id: str
    target: str
    status: str  # "PASS", "FAIL", "EXHAUSTED"
    attempt: int
    max_retries: int
    test_result: TestResult | None = None
    blind_feedback: str = ""


def format_blind_result(result: TestResult, attempt: int = 1, max_retries: int = 5) -> str:
    """
    Format test results for the coding agent.

    Strips all test source, file paths, and assertion code.
    Returns only rule categories and natural-language descriptions.
    """
    lines = []
    lines.append(f"STATUS: {result.status} (attempt {attempt}/{max_retries})")

    failures = [c for c in result.checks if not c.passed]
    passes = [c for c in result.checks if c.passed]

    if failures:
        lines.append("FAILURES:")
        for check in failures:
            lines.append(f"  - [{check.category}] {check.description}")

    lines.append(f"PASSES: {result.passed_count}/{result.total_count}")

    if result.error:
        lines.append(f"ERROR: {result.error}")

    return "\n".join(lines)


def _detect_domains_for_task(task_description: str) -> list[str]:
    """Detect which best-practices domains apply to a task description."""
    domains = []
    desc_lower = task_description.lower()

    python_signals = [
        "python", ".py", "pip", "uv ", "pyproject", "loguru", "typer",
        "httpx", "fastapi", "flask", "django", "pytest",
    ]
    if any(s in desc_lower for s in python_signals):
        domains.append("python")

    react_signals = [
        "react", "next.js", "nextjs", "jsx", "tsx", "component",
        "tailwind", "shadcn", "frontend",
    ]
    if any(s in desc_lower for s in react_signals):
        domains.append("react")

    kde_signals = ["qml", "kde", "plasma", "kirigami", "qt", "horus style"]
    if any(s in desc_lower for s in kde_signals):
        domains.append("kde")

    skill_signals = [
        "skill", "skill.md", "run.sh", "sanity.sh", "provides:",
        "composes:", ".pi/skills",
    ]
    if any(s in desc_lower for s in skill_signals):
        domains.append("skills")

    behavioral_signals = [
        "ingest", "crawl", "fetch", "e2e", "end-to-end", "behavioral",
        "dry-run", "eval.json",
    ]
    if any(s in desc_lower for s in behavioral_signals):
        domains.append("behavioral")

    node_signals = [
        "node.js", "nodejs", ".cjs", ".mjs", "commonjs", "npm", "run-batch",
        "cdp-harness", "puppeteer", "headless chrome", "binary explorer",
    ]
    if any(s in desc_lower for s in node_signals):
        domains.append("node")

    # Default: if creating/modifying Python files, assume python
    if not domains and any(s in desc_lower for s in ["create", "add", "implement", "fix", "refactor"]):
        domains.append("python")

    return domains


def _parse_tasks_from_plan(plan_path: Path) -> list[dict[str, Any]]:
    """Parse tasks from YAML (.yaml/.yml) or markdown (.md) plan files."""
    content = plan_path.read_text()
    suffix = plan_path.suffix.lower()

    # YAML plan files (preferred — from /plan YAML-first pipeline)
    if suffix in (".yaml", ".yml"):
        return _parse_yaml_plan(content)

    # Legacy markdown task files
    return _parse_markdown_plan(content)


def _parse_yaml_plan(content: str) -> list[dict[str, Any]]:
    """Parse tasks from YAML plan format (orchestrate-plan-v1 schema)."""
    try:
        import yaml as _yaml
        plan = _yaml.safe_load(content)
    except Exception as e:
        logger.error(f"Failed to parse YAML plan: {e}")
        return []

    if not isinstance(plan, dict):
        return []

    tasks = []
    for task in plan.get("tasks", []):
        task_id = task.get("id", "")
        title = task.get("title", "")
        description = task.get("prompt", title)

        # Extract definition of done for test generation
        dod = task.get("definition_of_done", {})
        if isinstance(dod, dict):
            test_file = dod.get("test_file", "")
            assertion = dod.get("assertion", "")
            sanity_cmd = dod.get("sanity_command", "")
        else:
            test_file = ""
            assertion = str(dod) if dod else ""
            sanity_cmd = ""

        tasks.append({
            "id": task_id,
            "title": title,
            "description": description,
            "runner": task.get("runner", "code-runner"),
            "backend": task.get("backend", "sonnet"),
            "mode": task.get("mode", "iterative"),
            "implementation": task.get("implementation", []),
            "tests": task.get("tests", []),
            "definition_of_done": {
                "test_file": test_file,
                "assertion": assertion,
                "sanity_command": sanity_cmd,
            },
        })

    return tasks


def _parse_markdown_plan(content: str) -> list[dict[str, Any]]:
    """Parse tasks from legacy markdown 0N_TASKS.md files."""
    tasks = []
    pattern = r'-\s*\[\s*[x ]?\s*\]\s*\*\*(.+?)\*\*:\s*(.+?)(?=\n-\s*\[|\n##|\Z)'
    for match in re.finditer(pattern, content, re.DOTALL):
        task_id = match.group(1).strip()
        task_body = match.group(2).strip()
        tasks.append({"id": task_id, "description": task_body})
    return tasks


def generate_tests_for_plan(plan_path: Path) -> dict[str, Any]:
    """Parse a task file and generate hidden tests per task.

    Supports both YAML (preferred) and markdown plan formats.
    Returns dict with generation results per domain.
    """
    if not plan_path.exists():
        return {"error": f"Plan file not found: {plan_path}", "generated": {}}

    tasks = _parse_tasks_from_plan(plan_path)
    if not tasks:
        return {"error": "No tasks found in plan file", "generated": {}}

    results: dict[str, Any] = {}

    for task in tasks:
        description = task.get("description", task.get("title", ""))
        domains = _detect_domains_for_task(description)

        # Service domain detection: tasks with Docker signals
        runner = task.get("runner", "")
        if "docker" in description.lower() or "service" in description.lower():
            if "service" not in domains:
                domains.append("service")

        for domain in domains:
            bp_dir = BEST_PRACTICES_DIRS.get(domain)
            if not bp_dir or not bp_dir.exists():
                continue

            tests_dir = bp_dir / "tests"
            tests_dir.mkdir(exist_ok=True)

            if domain not in results:
                results[domain] = {"tasks": [], "tests_dir": str(tests_dir)}
            results[domain]["tasks"].append(task.get("id", task.get("title", "")))

    return {"generated": results, "task_count": len(tasks)}


def run_tests(target_dir: Path, domain: str) -> TestResult:
    """
    Run hidden tests for a domain against a target directory.

    Dynamically loads the appropriate generator and runs checks.
    """
    if not target_dir.exists():
        return TestResult(
            target=str(target_dir),
            domain=domain,
            status="FAIL",
            error=f"Target directory not found: {target_dir}",
        )

    # Import the generator
    try:
        gen_module = _import_generator(domain)
    except Exception as e:
        return TestResult(
            target=str(target_dir),
            domain=domain,
            status="FAIL",
            error=f"Generator load failed for domain '{domain}': {e}",
        )

    # Run checks
    try:
        checks = gen_module.run_checks(target_dir)
    except Exception as e:
        logger.error(f"Generator {domain} failed: {e}")
        return TestResult(
            target=str(target_dir),
            domain=domain,
            status="FAIL",
            error=f"Test execution failed: {e}",
        )

    status = "PASS" if all(c.passed for c in checks) else "FAIL"
    return TestResult(
        target=str(target_dir),
        domain=domain,
        status=status,
        checks=checks,
    )


def _import_generator(domain: str):
    """Import a generator module by domain name."""
    import importlib

    domain = DOMAIN_ALIASES.get(domain, domain)
    module_name = DOMAIN_GENERATORS.get(domain)
    if not module_name:
        raise ValueError(f"Unknown domain: {domain}. Valid: {list(DOMAIN_GENERATORS)}")

    # Add skill dir to path for relative imports
    skill_dir = str(Path(__file__).parent)
    if skill_dir not in sys.path:
        sys.path.insert(0, skill_dir)

    return importlib.import_module(module_name)


def verify_task(
    task_id: str,
    target_dir: Path,
    domain: str | None = None,
    max_retries: int = 5,
    attempt: int = 1,
) -> VerifyResult:
    """
    Verify a task passes hidden tests, with retry tracking.

    Returns VerifyResult with blind feedback for the coding agent.
    """
    domains = [domain] if domain else _detect_domains_for_task(task_id)
    if not domains:
        domains = ["python"]  # default

    all_checks: list[TestCheck] = []
    errors: list[str] = []

    for d in domains:
        result = run_tests(target_dir, d)
        all_checks.extend(result.checks)
        if result.error:
            errors.append(result.error)

    overall_status = "PASS" if all(c.passed for c in all_checks) and not errors else "FAIL"

    if overall_status == "FAIL" and attempt >= max_retries:
        overall_status = "EXHAUSTED"

    combined_result = TestResult(
        target=str(target_dir),
        domain=",".join(domains),
        status=overall_status,
        checks=all_checks,
        error="; ".join(errors) if errors else None,
    )

    blind = format_blind_result(combined_result, attempt, max_retries)

    return VerifyResult(
        task_id=task_id,
        target=str(target_dir),
        status=overall_status,
        attempt=attempt,
        max_retries=max_retries,
        test_result=combined_result,
        blind_feedback=blind,
    )


# --- CLI ---

app = typer.Typer(help="Adversarial blind evaluation harness")


@app.command("generate")
def cmd_generate(
    plan_file: str = typer.Argument(..., help="Path to 0N_TASKS.md plan file"),
) -> None:
    """Generate hidden tests from a task file."""
    plan_path = Path(plan_file)
    result = generate_tests_for_plan(plan_path)

    if result.get("error"):
        logger.error(result["error"])
        raise typer.Exit(1)

    generated = result.get("generated", {})
    task_count = result.get("task_count", 0)

    logger.info(f"Parsed {task_count} tasks")
    for domain, info in generated.items():
        tasks = info["tasks"]
        logger.info(f"  {domain}: {len(tasks)} tasks → {info['tests_dir']}")

    print(json.dumps(result, indent=2))


@app.command("run")
def cmd_run(
    target_dir: str = typer.Argument(..., help="Directory to test"),
    domain: str = typer.Option("python", "--domain", "-d", help="Best-practices domain"),
    json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
) -> None:
    """Run hidden tests against a target directory."""
    result = run_tests(Path(target_dir), domain)

    if json_output:
        output = {
            "target": result.target,
            "domain": result.domain,
            "status": result.status,
            "passed": result.passed_count,
            "failed": result.failed_count,
            "total": result.total_count,
            "checks": [asdict(c) for c in result.checks],
        }
        if result.error:
            output["error"] = result.error
        print(json.dumps(output, indent=2))
    else:
        print(format_blind_result(result))

    raise typer.Exit(0 if result.status == "PASS" else 1)


@app.command("report")
def cmd_report(
    results_file: str = typer.Argument(..., help="Path to results JSON"),
) -> None:
    """Rich table report from results JSON."""
    from rich.console import Console
    from rich.table import Table

    data = json.loads(Path(results_file).read_text())

    console = Console()
    table = Table(title="Blind Evaluation Results")
    table.add_column("Check", style="cyan")
    table.add_column("Category", style="magenta")
    table.add_column("Status", style="green")
    table.add_column("Description")

    for check in data.get("checks", []):
        status_style = "green" if check["passed"] else "red"
        status_text = "PASS" if check["passed"] else "FAIL"
        table.add_row(
            check["name"],
            check["category"],
            f"[{status_style}]{status_text}[/{status_style}]",
            check["description"],
        )

    console.print(table)
    console.print(f"\nOverall: {data.get('status', 'UNKNOWN')} "
                  f"({data.get('passed', 0)}/{data.get('total', 0)} checks passed)")


@app.command("verify-task")
def cmd_verify_task(
    task_id: str = typer.Argument(..., help="Task identifier"),
    target_dir: str = typer.Argument(..., help="Directory to verify"),
    domain: str = typer.Option(None, "--domain", "-d", help="Best-practices domain"),
    max_retries: int = typer.Option(5, "--max-retries", help="Maximum retry attempts"),
    attempt: int = typer.Option(1, "--attempt", help="Current attempt number"),
    blind: bool = typer.Option(False, "--blind", help="Compatibility flag; verify-task is always blind"),
    json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
) -> None:
    """Verify a task with retry budget."""
    result = verify_task(
        task_id=task_id,
        target_dir=Path(target_dir),
        domain=domain,
        max_retries=max_retries,
        attempt=attempt,
    )

    if json_output:
        output = {
            "task_id": result.task_id,
            "status": result.status,
            "attempt": result.attempt,
            "max_retries": result.max_retries,
            "blind_feedback": result.blind_feedback,
        }
        if result.test_result:
            output["passed"] = result.test_result.passed_count
            output["failed"] = result.test_result.failed_count
            output["total"] = result.test_result.total_count
        print(json.dumps(output, indent=2))
    else:
        print(f"TASK: {result.task_id}")
        print(result.blind_feedback)

    exit_code = 0 if result.status == "PASS" else (2 if result.status == "EXHAUSTED" else 1)
    raise typer.Exit(exit_code)


if __name__ == "__main__":
    app()
