# Generated by test-lab — blind adversarial evaluation
"""Tests for runner.py focusing on gate semantics and evidence collection."""
from __future__ import annotations

import builtins
from types import SimpleNamespace

import runner
import collect
from runner import EvidenceCaseRunner
from candidate_qra import EvidenceCaseStore2
from collect import (
    EntityExtractionFailure,
    _filter_meta_items,
    _invoke_skill,
    collect_entities,
)


def _fake_case_result(verdict_state: str, gates: list[dict], answer: str = "ok") -> dict:
    return {
        "claim": {"id": "claim_1", "text": "q", "category": "compliance", "control_ids": ["CM0028"]},
        "strategies": [{"id": "s1", "name": "agent_driven", "skills": ["/memory recall"]}],
        "evidence": [{"id": "e1", "method": "EXAMINE", "layer": "sparta_qra", "control_ids": ["CM0028"]}],
        "verdict": {"state": verdict_state, "grade": "A+" if verdict_state == "satisfied" else "C", "score": 1.0 if verdict_state == "satisfied" else 0.8},
        "answer": answer,
        "gate_trace": gates,
        "gates_passed": sum(1 for g in gates if g.get("passed")),
        "gates_total": len(gates),
    }


def _patch_happy_path(monkeypatch, *, provability: dict | None, proof: dict | None):
    qra_items = [
        {
            "control_id": "CM0028",
            "tactical_tags": ["Harden"],
            "question": "How to protect firmware?",
            "answer": "Use tamper protection with integrity checks.",
        },
        {
            "control_id": "SI-7(2)",
            "tactical_tags": ["Harden"],
            "question": "How to detect tampering?",
            "answer": "Use boot integrity verification and monitoring.",
        },
    ]

    monkeypatch.setattr(runner, "collect_topic", lambda _: {"on_topic": True, "category": "compliance", "method": "test"})
    monkeypatch.setattr(runner, "collect_recall", lambda *_args, **_kwargs: qra_items)
    monkeypatch.setattr(
        runner,
        "collect_entities",
        lambda _q: {"all_control_ids": ["CM0028", "SI-7(2)"], "related_pairs": [{"source": "CM0028", "target": "SI-7(2)"}], "method": "extract_entities", "grounding_ok": True, "warnings": [], "resolution_map": {}, "unresolved_terms": [], "headline": "2 resolved"},
    )
    monkeypatch.setattr(
        runner,
        "decompose_sentence",
        lambda q, _agent=None: {
            "question": q,
            "given_components": ["firmware tampering"],
            "then_components": ["countermeasures"],
            "component_queries": {},
            "component_entity_types": {},
        },
    )
    monkeypatch.setattr(runner, "collect_per_component", lambda _d: {})
    monkeypatch.setattr(runner, "collect_lean4_provable", lambda _q, _ids: provability)
    monkeypatch.setattr(runner, "collect_lean4_proof", lambda _req: proof)


def test_filter_meta_items():
    items = [
        {"tags": ["routing"], "solution": "meta"},
        {"tags": ["compliance"], "solution": "real"},
    ]
    assert _filter_meta_items(items) == [{"tags": ["compliance"], "solution": "real"}]


def test_invoke_skill_handles_nonzero_without_json(monkeypatch, tmp_path):
    run_sh = tmp_path / "run.sh"
    run_sh.write_text("#!/bin/sh\nexit 1\n")
    run_sh.chmod(0o755)

    def fake_run(*_args, **_kwargs):
        return SimpleNamespace(returncode=1, stdout="", stderr="boom")

    monkeypatch.setattr(collect.subprocess, "run", fake_run)
    assert _invoke_skill(run_sh, ["x"]) is None


def test_collect_entities_failure_raises_when_no_valid_result(monkeypatch):
    """Entity extraction must fail loudly instead of fabricating a fallback success."""
    real_import = builtins.__import__

    def fake_import(name, globals=None, locals=None, fromlist=(), level=0):
        if name == "graph_memory.entity_extraction":
            raise ImportError("forced import failure")
        return real_import(name, globals, locals, fromlist, level)

    monkeypatch.setattr(builtins, "__import__", fake_import)
    monkeypatch.setattr(collect, "_invoke_skill", lambda *_args, **_kwargs: None)

    try:
        collect_entities("CM0028 and SI-7(2)")
        assert False, "Expected EntityExtractionFailure"
    except EntityExtractionFailure as exc:
        assert "Entity extraction failed" in str(exc)


def test_collect_entities_direct_import_with_mock(monkeypatch):
    """When graph_memory is available, direct import path returns agent_view."""
    from types import SimpleNamespace

    class FakeResult:
        def agent_view(self):
            return {"headline": "2 controls", "grounding_ok": True, "controls": [
                {"id": "SI-7", "name": "Software Integrity"}]}
        def to_dict(self):
            return {"all_control_ids": ["CM0028", "SI-7"], "control_ids": ["CM0028", "SI-7"],
                    "related_pairs": [], "resolution_map": {}, "unresolved_terms": [],
                    "misspellings": [], "not_in_corpus": []}

    fake_module = SimpleNamespace(extract_entities=lambda q: FakeResult())
    import importlib
    monkeypatch.setitem(__import__('sys').modules, 'graph_memory.entity_extraction', fake_module)
    monkeypatch.setattr(collect, "_invoke_skill", lambda *_args, **_kwargs: None)

    result = collect_entities("CM0028 and SI-7(2)")
    assert result is not None
    assert result["method"] == "extract_entities"
    assert "SI-7" in result["all_control_ids"]
    assert "headline" in result
    assert "grounding_ok" in result


def test_persist_case_materializes_decomposition_id(monkeypatch):
    learned_nodes: list[dict] = []
    learned_edges: list[tuple[str, str, str]] = []

    class FakeStore:
        def learn_node(self, node, scope="evidence_cases"):
            learned_nodes.append(node)
            return True

        def learn_edge(self, from_id, to_id, relation, scope="evidence_cases"):
            learned_edges.append((from_id, to_id, relation))
            return True

        def append_audit(self, *_args, **_kwargs):
            return None

        def load_uct_cache(self, *_args, **_kwargs):
            return []

        def save_uct_cache(self, *_args, **_kwargs):
            return None

    store = EvidenceCaseStore2()
    store.store = FakeStore()
    result = store.persist_case(
        question="q",
        category="compliance",
        verdict_state="satisfied",
        grade="A+",
        score=1.0,
        gates=[{"gate": "step_1_topic", "passed": True}],
        evidence_items=[],
        answer="ok",
        decomposition={"question": "q", "given_components": [], "then_components": []},
    )
    assert result["decomposition"] is not None
    assert result["decomposition"]["id"]
    assert any(rel == "decomposed_as" and to_id for _, to_id, rel in learned_edges)


def test_gate2b_grounding_blocks_satisfied_when_fabricated(monkeypatch):
    """When grounding_ok=False (fabricated IDs), gate 2b fails → not SATISFIED."""
    _patch_happy_path(monkeypatch, provability={"prediction": "not_formalizable", "confidence": 0.99}, proof=None)
    # Override collect_entities to return fabricated ID warning
    monkeypatch.setattr(
        runner,
        "collect_entities",
        lambda _q: {
            "all_control_ids": ["CM0028"],
            "related_pairs": [],
            "method": "extract_entities",
            "grounding_ok": False,
            "warnings": [{"category": "fabricated_id", "term": "X23-MUSTARD", "detail": "No match in 8,979 controls"}],
            "resolution_map": {"CM0028": {"exists": True}, "X23-MUSTARD": {"exists": False}},
            "unresolved_terms": [{"term": "X23-MUSTARD", "type": "id_like"}],
            "headline": "1 resolved, 1 fabricated",
        },
    )
    monkeypatch.setattr(
        EvidenceCaseStore2,
        "persist_case",
        lambda self, **kwargs: _fake_case_result(kwargs["verdict_state"], kwargs["gates"], kwargs["answer"]),
    )

    r = EvidenceCaseRunner()
    result = r.run("How does X23-MUSTARD protect firmware?", show_progress=False)
    assert result["verdict"]["state"] != "satisfied"
    step2b = [g for g in result["gate_trace"] if g["gate"] == "step_2b_grounding"][0]
    assert step2b["passed"] is False


def test_gate2b_grounding_passes_for_real_entities(monkeypatch):
    """When grounding_ok=True, gate 2b passes normally."""
    _patch_happy_path(monkeypatch, provability={"prediction": "not_formalizable", "confidence": 0.99}, proof=None)
    monkeypatch.setattr(
        EvidenceCaseStore2,
        "persist_case",
        lambda self, **kwargs: _fake_case_result(kwargs["verdict_state"], kwargs["gates"], kwargs["answer"]),
    )

    r = EvidenceCaseRunner()
    result = r.run("What controls protect firmware?", show_progress=False)
    assert result["verdict"]["state"] == "satisfied"
    step2b = [g for g in result["gate_trace"] if g["gate"] == "step_2b_grounding"][0]
    assert step2b["passed"] is True


def test_entity_extraction_system_failure_blocks_case(monkeypatch):
    monkeypatch.setattr(runner, "collect_topic", lambda _: {"on_topic": True, "category": "compliance", "method": "test"})
    monkeypatch.setattr(runner, "collect_recall", lambda *_args, **_kwargs: [])
    monkeypatch.setattr(
        runner,
        "decompose_sentence",
        lambda q, _agent=None: {
            "question": q,
            "given_components": [],
            "then_components": [q],
            "component_queries": {},
            "component_entity_types": {},
        },
    )
    monkeypatch.setattr(
        runner,
        "collect_entities",
        lambda _q: (_ for _ in ()).throw(EntityExtractionFailure("extract-entities skill returned no valid result")),
    )
    monkeypatch.setattr(
        EvidenceCaseStore2,
        "persist_case",
        lambda self, **kwargs: _fake_case_result(kwargs["verdict_state"], kwargs["gates"], kwargs["answer"]),
    )

    r = EvidenceCaseRunner()
    result = r.run("How does CM0028 relate to SI-7(2)?", show_progress=False)
    assert result["verdict"]["state"] == "inconclusive"
    step2 = [g for g in result["gate_trace"] if g["gate"] == "step_2_entities"][0]
    assert step2["passed"] is False
    assert step2["data"]["system_failure"] is True
    assert "entity extraction failed" in result["answer"].lower()


def test_gate5_classifier_unavailable_blocks_satisfied(monkeypatch):
    _patch_happy_path(monkeypatch, provability=None, proof=None)
    monkeypatch.setattr(
        EvidenceCaseStore2,
        "persist_case",
        lambda self, **kwargs: _fake_case_result(kwargs["verdict_state"], kwargs["gates"], kwargs["answer"]),
    )

    r = EvidenceCaseRunner()
    result = r.run("What controls protect firmware?", show_progress=False)
    assert result["verdict"]["state"] == "inconclusive"
    step5 = [g for g in result["gate_trace"] if g["gate"] == "step_5_lean4"][0]
    assert step5["passed"] is False
    assert result["lean4_result"]["gate_blocked"] is True


def test_semantic_relation_missing_blocks_satisfied_for_explicit_pair(monkeypatch):
    _patch_happy_path(
        monkeypatch,
        provability={"prediction": "not_formalizable", "confidence": 0.99},
        proof=None,
    )
    monkeypatch.setattr(
        runner,
        "_find_explicit_question_controls",
        lambda _q, _m: [
            {"mention": "CM0028", "control_id": "CM0028", "name": "Firmware Protection", "tactic": "Harden", "technique_context": "Harden"},
            {"mention": "SI-7(2)", "control_id": "SI-7(2)", "name": "Integrity Checks", "tactic": "Harden", "technique_context": "Harden"},
        ],
    )
    monkeypatch.setattr(runner, "collect_semantic_relation", lambda *_args, **_kwargs: None)
    monkeypatch.setattr(runner, "collect_clarify", lambda _q: {"clarify_questions": [{"question": "Which relationship do you mean?"}]})
    monkeypatch.setattr(
        EvidenceCaseStore2,
        "persist_case",
        lambda self, **kwargs: _fake_case_result(kwargs["verdict_state"], kwargs["gates"], kwargs["answer"]),
    )

    r = EvidenceCaseRunner()
    result = r.run("How does CM0028 relate to SI-7(2)?", show_progress=False)
    assert result["verdict"]["state"] == "inconclusive"
    step4 = [g for g in result["gate_trace"] if g["gate"] == "step_4_semantic_relation"][0]
    assert step4["passed"] is False
    assert "required" in step4["detail"].lower()


def test_gate5_non_formalizable_skip_can_still_satisfy(monkeypatch):
    _patch_happy_path(
        monkeypatch,
        provability={"prediction": "not_formalizable", "confidence": 0.99},
        proof=None,
    )
    monkeypatch.setattr(
        EvidenceCaseStore2,
        "persist_case",
        lambda self, **kwargs: _fake_case_result(kwargs["verdict_state"], kwargs["gates"], kwargs["answer"]),
    )

    r = EvidenceCaseRunner()
    result = r.run("What policy controls apply?", show_progress=False)
    assert result["verdict"]["state"] == "satisfied"
    step5 = [g for g in result["gate_trace"] if g["gate"] == "step_5_lean4"][0]
    assert step5["passed"] is True
    assert result["lean4_result"]["proof_skipped"] is True


def test_gate5_failed_formal_proof_blocks_satisfied(monkeypatch):
    _patch_happy_path(
        monkeypatch,
        provability={"prediction": "formalizable", "confidence": 0.95},
        proof={"success": False, "errors": ["type mismatch"]},
    )
    monkeypatch.setattr(
        EvidenceCaseStore2,
        "persist_case",
        lambda self, **kwargs: _fake_case_result(kwargs["verdict_state"], kwargs["gates"], kwargs["answer"]),
    )

    r = EvidenceCaseRunner()
    result = r.run("Prove this control chain formally", show_progress=False)
    assert result["verdict"]["state"] == "inconclusive"
    assert "not verified" in result["answer"]
    step5 = [g for g in result["gate_trace"] if g["gate"] == "step_5_lean4"][0]
    assert step5["passed"] is False
