# Generated by test-lab — blind adversarial evaluation
"""triage-error classification: canonical match + ambiguous minting."""
from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import triage_error as t


def test_known_signal_maps_to_canonical_code() -> None:
    r = t.classify("attach_file_preflight_failed: zip contains 9 files; maximum is 5", "surf")
    assert r["code"] == "webgpt_attachment_bundle_rejected"
    assert r["ambiguous"] is False
    assert "open-bind" in r["not_this"] or "tab binding" in r["not_this"]


def test_scillm_route_signal_maps_to_canonical() -> None:
    r = t.classify("404 path /v4/v1/chat/completions", "scillm")
    assert r["code"] == "scillm_api_base_double_version_segment"
    assert r["recoverable"] is True


def test_ambiguous_signal_mints_deterministic_code() -> None:
    a = t.classify("novel gizmo exploded 0xdeadbeef", "tau")
    b = t.classify("novel gizmo exploded 0xdeadbeef", "tau")
    assert a["ambiguous"] is True
    assert a["code"] == b["code"]  # deterministic
    assert a["code"].startswith("tau_unclassified_")


def test_layer_filter_prevents_cross_layer_false_match() -> None:
    # The zip-limit tokens belong to surf; asking as scillm must not match it.
    r = t.classify("zip contains 9 files; maximum is 5", "scillm")
    assert r["ambiguous"] is True


def test_monitor_opportunities_revision_mismatch_maps_to_scheduler_repair() -> None:
    r = t.classify(
        '{"code":"NIGHTLY_REVISION_MISMATCH","message":"Expected 06f73f000188c5f448f7184335058506b86c5211, got 1368ee62e3a8fe5fd4d991ff897019267df2d34b","status":"ERROR"}',
        "monitor-opportunities",
    )
    assert r["code"] == "monitor_opportunities_nightly_revision_mismatch"
    assert r["ambiguous"] is False
    assert r["recoverable"] is True
    assert "schedule --promoted-stage0" in r["next_command"]
    assert "skills/ticket" in r["next_command"]
    assert "project-watchdog" in r["next_command"]
