#!/usr/bin/env python3
"""Cross-project quality checks for monitor-codebase.

Composes /treesitter violations command for AST-based checks (banned imports,
inline prompts, regex classifiers, hardcoded paths, AQL, file length, etc.)
and adds test-quality checks (handwritten tests, mock-only tests) that are
file-content based, not AST.

Replaces the previous bespoke ast.walk() implementation.
"""
from __future__ import annotations
import os

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from loguru import logger

SKILL_DIR = Path(__file__).resolve().parent
SKILLS_DIR = SKILL_DIR.parent
TREESITTER_RUN = SKILLS_DIR / "treesitter" / "run.sh"

# Directories always excluded from scanning
_EXCLUDE_DIRS = {
    ".venv", "venv", "node_modules", "__pycache__", ".git", "dist", "build",
    ".eggs", ".mypy_cache", ".pytest_cache", ".uv", ".tox", ".ruff_cache",
    "site-packages", ".worktrees", ".cache", "archive-v0",
}

# Test-lab markers that distinguish generated blind tests from handwritten tests
_TEST_LAB_MARKERS = [
    "test-lab", "test_lab", "blind evaluation", "adversarial", "Generated by",
]


def _should_skip(path: Path) -> bool:
    parts = path.parts
    if set(parts) & _EXCLUDE_DIRS:
        return True
    # Catch .venv-batch, .venv_old, .venv.bak and any other venv variant
    return any(part.startswith(".venv") for part in parts)


def _iter_py_files(root: Path) -> list[Path]:
    return [f for f in root.rglob("*.py") if not _should_skip(f)]


# ---------------------------------------------------------------------------
# Treesitter-based checks (compose /treesitter violations)
# ---------------------------------------------------------------------------

def _run_treesitter_violations(
    root: Path,
    exclude_rules: list[str] | None = None,
) -> list[dict[str, Any]]:
    """Call /treesitter violations and return parsed results."""
    cmd = [str(TREESITTER_RUN), "violations", str(root), "--json"]
    if exclude_rules:
        cmd.extend(["--exclude-rules", ",".join(exclude_rules)])

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=120,
            env={k: v for k, v in os.environ.items() if k != 'VIRTUAL_ENV'},
        )
        # Exit code 1 means violations found (not an error)
        if result.stdout.strip():
            return json.loads(result.stdout)
        return []
    except (subprocess.TimeoutExpired, json.JSONDecodeError, OSError) as e:
        logger.warning("treesitter violations failed: {}", e)
        return []


# ---------------------------------------------------------------------------
# File-content checks (not AST — test quality detection)
# ---------------------------------------------------------------------------

def _check_handwritten_tests(root: Path) -> list[dict[str, Any]]:
    """Detect test files without test-lab markers."""
    violations = []
    for py_file in _iter_py_files(root):
        if not py_file.name.startswith("test_"):
            continue
        try:
            content = py_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if not any(marker in content for marker in _TEST_LAB_MARKERS):
            violations.append({
                "rule": "handwritten-tests",
                "file": str(py_file.relative_to(root)),
                "line": 0,
                "message": "Test file has no test-lab markers — use /test-lab generate",
                "severity": "warn",
            })
    return violations


def _check_mock_only_tests(root: Path) -> list[dict[str, Any]]:
    """Detect projects where ALL tests use mocks with no integration tests."""
    test_files = [f for f in _iter_py_files(root) if f.name.startswith("test_")]
    if not test_files:
        return []

    has_sanity = (root / "sanity.sh").exists()
    all_mocked = True
    for tf in test_files:
        try:
            content = tf.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if not any(p in content for p in [
            "unittest.mock", "MagicMock", "AsyncMock", "@patch", "mock.patch",
        ]):
            all_mocked = False
            break

    if all_mocked and not has_sanity:
        return [{
            "rule": "mock-only-tests",
            "file": str(root),
            "line": 0,
            "message": "All tests use mocks but no sanity.sh — mock tests pass while real service may be broken",
            "severity": "warn",
        }]
    return []


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def scan_project(project_path: str, include_dirs: list[str] | None = None) -> dict[str, Any]:
    """Run all quality checks against a project directory."""
    root = Path(project_path).resolve()
    if not root.is_dir():
        return {"error": f"Not a directory: {root}", "violations": []}

    scan_roots = []
    if include_dirs:
        for d in include_dirs:
            p = root / d
            if p.is_dir():
                scan_roots.append(p)
    if not scan_roots:
        scan_roots = [root]

    all_violations: list[dict[str, Any]] = []

    # Determine treesitter exclusions
    # Memory project is exempt from AQL checks
    exclude_rules = None
    if root.name == "memory" or "experiments/memory" in str(root):
        exclude_rules = ["bespoke-aql", "bespoke-aql-api"]

    for scan_root in scan_roots:
        logger.info("Quality scanning: {}", scan_root)

        # AST-based checks via /treesitter violations
        ts_violations = _run_treesitter_violations(scan_root, exclude_rules)
        all_violations.extend(ts_violations)

        # File-content checks (test quality — not AST)
        all_violations.extend(_check_handwritten_tests(scan_root))
        all_violations.extend(_check_mock_only_tests(scan_root))

    # Group by rule
    by_rule: dict[str, int] = {}
    for v in all_violations:
        by_rule[v["rule"]] = by_rule.get(v["rule"], 0) + 1

    return {
        "project": str(root),
        "total_violations": len(all_violations),
        "by_rule": by_rule,
        "violations": all_violations,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    import typer

    app = typer.Typer(help="Cross-project quality checks for monitor-codebase.")

    @app.command()
    def scan(
        project: str = typer.Argument(help="Project directory to scan"),
        json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
    ) -> None:
        result = scan_project(project)
        if json_output:
            print(json.dumps(result, indent=2))
        else:
            total = result["total_violations"]
            print(f"\n=== Quality Check: {result['project']} ===")
            print(f"Total violations: {total}")
            if result["by_rule"]:
                print("\nBy rule:")
                for rule, count in sorted(result["by_rule"].items()):
                    print(f"  {rule}: {count}")
            if total > 0:
                print(f"\nTop violations:")
                for v in result["violations"][:30]:
                    print(f"  [{v['rule']}] {v.get('file', '?')}: {v['message']}")
                if total > 30:
                    print(f"  ... and {total - 30} more")

    app()


if __name__ == "__main__":
    main()
