"""Interview question generation for voice design."""


def generate_interview_questions(persona: str) -> dict:
    """Generate interview questions for voice design."""
    return {
        "title": f"Voice Design: {persona}",
        "context": f"We need to design a voice for {persona}. Since no recordings exist, "
                   "we'll infer their voice from their background, era, and personality.",
        "questions": [
            {
                "id": "geographic_origin",
                "header": "Origin",
                "text": f"Where was {persona} born or primarily lived?",
                "options": [
                    {"label": "Boston, Massachusetts", "description": "Colonial non-rhotic accent"},
                    {"label": "Charleston, South Carolina", "description": "Soft Southern cadence"},
                    {"label": "Philadelphia, Pennsylvania", "description": "Colonial, less formal"},
                    {"label": "London, England", "description": "British Received Pronunciation"},
                    {"label": "Rome, Italy", "description": "Classical Latin influence"},
                ],
                "multi_select": False,
            },
            {
                "id": "time_period",
                "header": "Era",
                "text": f"What era did {persona} live in?",
                "options": [
                    {"label": "Ancient (before 500 CE)", "description": "Classical oratory patterns"},
                    {"label": "Medieval (500-1400)", "description": "Limited recordings basis"},
                    {"label": "Renaissance (1400-1600)", "description": "Formal, educated speech"},
                    {"label": "Colonial (1600-1800)", "description": "Period-appropriate cadence"},
                    {"label": "Victorian (1800-1900)", "description": "Formal, measured speech"},
                    {"label": "Modern (1900+)", "description": "Contemporary patterns"},
                ],
                "multi_select": False,
            },
            {
                "id": "birth_death_years",
                "header": "Lifespan",
                "text": f"What years did {persona} live? (e.g., '1706-1790' for Franklin)",
                "options": [
                    {"label": "Ancient (before 500 CE)", "description": "Enter specific years if known"},
                    {"label": "Medieval (500-1400)", "description": "Approximate is fine"},
                    {"label": "Early Modern (1400-1700)", "description": "Enter birth-death years"},
                    {"label": "Modern (1700-1900)", "description": "Enter birth-death years"},
                    {"label": "Contemporary (1900+)", "description": "Enter birth-death years"},
                ],
                "multi_select": False,
            },
            {
                "id": "formative_events",
                "header": "Formative",
                "text": f"What events shaped {persona} in childhood/youth? (ages ~5-25)",
                "options": [
                    {"label": "Loss of parent/family", "description": "Early grief - guarded or resilient"},
                    {"label": "War witnessed young", "description": "Trauma, hypervigilance in voice"},
                    {"label": "Poverty/hardship", "description": "Scrappy determination"},
                    {"label": "Privileged education", "description": "Confidence, formal speech"},
                    {"label": "Religious awakening", "description": "Fervor, conviction"},
                    {"label": "Early success", "description": "Confidence, sometimes arrogance"},
                    {"label": "Displacement/migration", "description": "Adaptable, guarded"},
                ],
                "multi_select": True,
            },
            {
                "id": "prime_events",
                "header": "Prime Years",
                "text": f"What defined {persona}'s prime years? (ages ~25-50)",
                "options": [
                    {"label": "War/Conflict", "description": "Urgency, weathered quality"},
                    {"label": "Revolution/Upheaval", "description": "Hopeful intensity, conviction"},
                    {"label": "Plague/Hardship", "description": "Stoic fatigue, mortality awareness"},
                    {"label": "Scientific Discovery", "description": "Wonder, precision"},
                    {"label": "Political Power", "description": "Authority, measured weight"},
                    {"label": "Artistic Achievement", "description": "Passion, expressiveness"},
                    {"label": "Loss of loved one", "description": "Grief undertone, gravitas"},
                    {"label": "Persecution/Exile", "description": "Resilience, guarded quality"},
                ],
                "multi_select": True,
            },
            {
                "id": "late_events",
                "header": "Later Life",
                "text": f"What marked {persona}'s later years? (ages 50+)",
                "options": [
                    {"label": "Reflection/Writing", "description": "Measured, contemplative"},
                    {"label": "Continued activism", "description": "Urgency despite age"},
                    {"label": "Illness/Decline", "description": "Fragility, earned wisdom"},
                    {"label": "Recognition/Honor", "description": "Serene confidence"},
                    {"label": "Tragedy/Loss", "description": "Profound sadness, acceptance"},
                    {"label": "Teaching/Mentoring", "description": "Warm, patient delivery"},
                    {"label": "Bitterness/Regret", "description": "Edge, sardonic tone"},
                ],
                "multi_select": True,
            },
            {
                "id": "social_class",
                "header": "Class",
                "text": f"What was {persona}'s social/educational background?",
                "options": [
                    {"label": "Aristocracy/Nobility", "description": "Formal, refined vocabulary"},
                    {"label": "Educated Professional", "description": "Precise, articulate"},
                    {"label": "Self-Made/Merchant", "description": "Practical, direct"},
                    {"label": "Religious/Clerical", "description": "Measured, rhetorical"},
                    {"label": "Military", "description": "Clipped, commanding"},
                    {"label": "Common/Working", "description": "Colloquial, grounded"},
                ],
                "multi_select": False,
            },
            {
                "id": "personality",
                "header": "Personality",
                "text": f"How would you describe {persona}'s speaking demeanor?",
                "options": [
                    {"label": "Authoritative", "description": "Commands attention, measured pace"},
                    {"label": "Warm/Avuncular", "description": "Friendly, approachable"},
                    {"label": "Intense/Passionate", "description": "Quick pace, emotional range"},
                    {"label": "Stoic/Measured", "description": "Controlled, deliberate"},
                    {"label": "Witty/Playful", "description": "Light, quick, ironic"},
                    {"label": "Humble/Deferential", "description": "Soft, hesitant at times"},
                ],
                "multi_select": True,
            },
            {
                "id": "emotional_coloring",
                "header": "Emotion",
                "text": "What emotional undertones should the voice carry?",
                "options": [
                    {"label": "Hopeful", "description": "Optimism despite challenges"},
                    {"label": "Weathered", "description": "Experience and endurance"},
                    {"label": "Urgent", "description": "Sense of mission or purpose"},
                    {"label": "Wry/Ironic", "description": "Humor as wisdom or armor"},
                    {"label": "Serene", "description": "Inner peace, acceptance"},
                    {"label": "Fierce", "description": "Controlled intensity"},
                ],
                "multi_select": True,
            },
            {
                "id": "family_structure",
                "header": "Family",
                "text": f"What was {persona}'s family situation?",
                "options": [
                    {"label": "Large family (5+ children)", "description": "Competition, communal identity"},
                    {"label": "Small family (1-2 children)", "description": "Individual attention, pressure"},
                    {"label": "Only child", "description": "Self-reliant, less sibling rivalry"},
                    {"label": "Eldest child", "description": "Responsibility, leadership tendency"},
                    {"label": "Youngest child", "description": "Protected, sometimes overlooked"},
                    {"label": "Orphaned early", "description": "Self-made, guarded attachment"},
                    {"label": "Unstable/fractured family", "description": "Adaptable, trust issues"},
                ],
                "multi_select": True,
            },
            {
                "id": "religion",
                "header": "Religion",
                "text": f"What was {persona}'s religious/spiritual context?",
                "options": [
                    {"label": "Devout Christian", "description": "Strong moral conviction, hope"},
                    {"label": "Cultural Christian", "description": "Tradition without fervor"},
                    {"label": "Buddhist/Eastern", "description": "Equanimity, detachment"},
                    {"label": "Jewish", "description": "Questioning, scholarly tradition"},
                    {"label": "Muslim", "description": "Submission, community focus"},
                    {"label": "Pagan/Folk", "description": "Nature-connected, cyclical"},
                    {"label": "Atheist/Secular", "description": "Rationalist, humanist"},
                    {"label": "Stoic philosophy", "description": "Self-mastery, acceptance"},
                ],
                "multi_select": False,
            },
            {
                "id": "religiosity_level",
                "header": "Devotion",
                "text": "How deeply religious/spiritual was this person?",
                "options": [
                    {"label": "Devout/Practicing", "description": "Daily practice, central identity"},
                    {"label": "Moderate", "description": "Regular observance, meaningful but not central"},
                    {"label": "Cultural only", "description": "Tradition without deep belief"},
                    {"label": "Private/Personal", "description": "Deep but not outwardly expressed"},
                    {"label": "Skeptical/Questioning", "description": "Doubt, intellectual distance"},
                ],
                "multi_select": False,
            },
            {
                "id": "cultural_emotional_norms",
                "header": "Culture",
                "text": "What cultural norms governed emotional expression?",
                "options": [
                    {"label": "Greco-Roman Stoic", "description": "Philosophical detachment, controlled"},
                    {"label": "Victorian Restraint", "description": "Stiff upper lip, suppression valued"},
                    {"label": "Buddhist Equanimity", "description": "Non-attachment, centered"},
                    {"label": "Mediterranean Expressive", "description": "Open emotion, dramatic gestures"},
                    {"label": "East Asian Collectivist", "description": "Restraint for group harmony"},
                    {"label": "American Individualist", "description": "Self-expression valued"},
                ],
                "multi_select": False,
            },
            {
                "id": "current_persona_age",
                "header": "Age Now",
                "text": f"At what age should we portray {persona}? (affects voice quality)",
                "options": [
                    {"label": "Young adult (20-35)", "description": "Energy, idealism, some uncertainty"},
                    {"label": "Prime years (35-50)", "description": "Authority, experience, drive"},
                    {"label": "Mature (50-65)", "description": "Wisdom, weathered, gravitas"},
                    {"label": "Elder (65+)", "description": "Reflection, acceptance, fragility"},
                ],
                "multi_select": False,
            },
            {
                "id": "recent_impactful_event",
                "header": "Recent",
                "text": "What recent event (last 1-5 years) most affects their current emotional state?",
                "options": [
                    {"label": "Recent loss/grief", "description": "Still processing, rawness"},
                    {"label": "Major achievement", "description": "Confidence, satisfaction"},
                    {"label": "Health crisis", "description": "Mortality awareness, fragility"},
                    {"label": "Relationship change", "description": "Adjustment, emotional flux"},
                    {"label": "Career transition", "description": "Uncertainty or new purpose"},
                    {"label": "Conflict/betrayal", "description": "Wariness, controlled anger"},
                    {"label": "Spiritual awakening", "description": "Centered, transformed"},
                    {"label": "None significant", "description": "Baseline emotional state"},
                ],
                "multi_select": False,
            },
            {
                "id": "suppression_level",
                "header": "Suppression",
                "text": "How much does this person suppress their true emotions?",
                "options": [
                    {"label": "Highly suppressed", "description": "Tight control, microstructural leakage"},
                    {"label": "Moderately suppressed", "description": "Professional mask, private release"},
                    {"label": "Contextually suppressed", "description": "Varies by situation"},
                    {"label": "Openly expressive", "description": "What you see is what you get"},
                ],
                "multi_select": False,
            },
            {
                "id": "modern_reference",
                "header": "Reference",
                "text": "Any modern actor/speaker whose voice might fit? (Optional)",
                "options": [
                    {"label": "Morgan Freeman", "description": "Warm, authoritative, wisdom"},
                    {"label": "Richard Harris", "description": "Gravitas, classical dignity"},
                    {"label": "Sam Elliott", "description": "Deep, folksy, trustworthy"},
                    {"label": "Ian McKellen", "description": "Theatrical, versatile"},
                    {"label": "Helen Mirren", "description": "Regal, intelligent, powerful"},
                    {"label": "Cate Blanchett", "description": "Precise, otherworldly quality"},
                ],
                "multi_select": True,
            },
        ],
    }
