# Generated by test-lab — blind adversarial evaluation
"""test_validate_pipeline_evidence_bundle - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

import hashlib
import json
import struct
import sys
import tempfile
import unittest
import zlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from validate_pipeline_evidence_bundle import validate_pipeline_evidence_bundle  # noqa: E402
from write_one_scene_kling_review_packet import install_one_scene_kling_review_packet  # noqa: E402


PNG_BYTES = b"\x89PNG\r\n\x1a\nfixture"


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload) + "\n", encoding="utf-8")


def _png_chunk(kind: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)


def _write_png(path: Path, *, width: int = 2, height: int = 1) -> str:
    raw = b"".join(b"\x00" + (b"\xff\xff\xff" * width) for _ in range(height))
    data = (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + _png_chunk(b"IDAT", zlib.compress(raw))
        + _png_chunk(b"IEND", b"")
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return hashlib.sha256(data).hexdigest()


def _write_report(report_dir: Path, *, forbidden_claim: str = "") -> Path:
    sha256 = _write_png(report_dir / "assets/panel.png")
    bundle = report_dir / "pipeline_evidence_bundle_validation.json"
    _write_json(
        bundle,
        {
            "schema": "persona_dream.pipeline_evidence_bundle_validation.v1",
            "status": "BLOCKED",
            "first_blocker": {
                "phase": "provider_media_publication_authorization",
                "reason": "authorization_receipt_required",
            },
            "validations": {
                "panel_comparison_report": {"status": "PASS_PANEL_COMPARISON_REPORT"},
                "pipeline_loop_run": {"status": "PASS_PIPELINE_LOOP_RUN_RECEIPT"},
            },
        },
    )
    _write_json(
        report_dir / "status.json",
        {
            "schema": "persona_dream.panel_comparison_status.v1",
            "status": "BLOCKED",
            "acceptance_state": "Not asserted by this report.",
            "first_blocker": {
                "phase": "provider_media_publication_authorization",
                "reason": "authorization_receipt_required",
            },
            "policy": {
                "kling_call_allowed": False,
                "nano_banana_final_panel_allowed": False,
            },
            "receipts": {
                "pipeline_evidence_bundle": {
                    "status": "BLOCKED",
                    "path": str(bundle),
                    "first_blocker": {
                        "phase": "provider_media_publication_authorization",
                        "reason": "authorization_receipt_required",
                    },
                    "validation_statuses": {
                        "panel_comparison_report": "PASS_PANEL_COMPARISON_REPORT",
                        "pipeline_loop_run": "PASS_PIPELINE_LOOP_RUN_RECEIPT",
                    },
                },
            },
        },
    )
    report = report_dir / "report.html"
    report.write_text(
        f"""<!doctype html>
<html><body>
<h1>Panel 01 Comparison</h1>
<p>Real candidate images gathered for visual comparison only; it does not assert final panel acceptance or Kling readiness.</p>
<p>Acceptance state: Not asserted by this report.</p>
<p>status.json first_blocker: provider_media_publication_authorization is BLOCKED.</p>
<p>receipts/pipeline_evidence_bundle_validation.json is the single where-is-stuck artifact.</p>
<p>Nano Banana fallback imagery is non-eligible for final panels.</p>
<p>Next useful action: rerun validation. Do not call Kling.</p>
<p>{forbidden_claim}</p>
<img src="assets/panel.png" alt="candidate">
<dl><dt>Dimensions</dt><dd>2 x 1 RGB</dd><dt>SHA-256</dt><dd>{sha256}</dd></dl>
</body></html>
""",
        encoding="utf-8",
    )
    return report


def _write_bundle_fixture(root: Path) -> dict[str, Path]:
    run_root = root / "run-root"
    image = run_root / "storyboard/panel_01.png"
    image.parent.mkdir(parents=True)
    image.write_bytes(PNG_BYTES)
    panel_hash = "sha256:" + hashlib.sha256(image.read_bytes()).hexdigest()
    source_receipt = run_root / "work/panel_source_receipt.json"
    repair_receipt = run_root / "work/panel_repair_gate_receipt.json"
    publication_work_order = (
        run_root / "storyboard/panel_repair_gate/provider_media_publication_work_orders/panel_01_publication_request.json"
    )
    staging_receipt = (
        run_root / "storyboard/panel_repair_gate/provider_media_publication_work_orders/panel_01_local_staging_receipt.json"
    )
    public_probe_receipt = (
        run_root
        / "storyboard/panel_repair_gate/final_provider_eligibility_work_orders/panel_01_run_fixture/provider_media_url_probe_receipt.json"
    )
    publication_preflight_receipt = run_root / "receipts/provider_media_publication_preflight.json"
    publication_authorization_receipt = run_root / "receipts/provider_media_publication_authorization.json"
    target_repo_path = f"skills/persona-dream/provider_media/{run_root.name}/panel_01.png"
    proposed_url = f"https://raw.githubusercontent.com/grahama1970/agent-skills/main/{target_repo_path}"

    _write_json(
        source_receipt,
        {
            "schema": "persona_dream.panel_source_receipt.v1",
            "run_id": "fixture",
            "panel_id": "panel_01",
            "status": "BLOCKED",
            "image_path": "storyboard/panel_01.png",
            "sha256": panel_hash,
            "producer": {
                "kind": "subagent",
                "name": "persona-dream-panel-repair-gate",
                "receipt": str(repair_receipt),
            },
            "photoreal_status": "UNKNOWN",
            "nano_banana_fallback_used": False,
            "final_panel_eligible": False,
            "blockers": ["provider_eligibility_not_true"],
        },
    )
    _write_json(
        repair_receipt,
        {
            "schema": "persona_dream.panel_repair_gate_receipt.v1",
            "run_id": "fixture",
            "panel_id": "panel_01",
            "status": "BLOCKED_PROVIDER_MEDIA_URLS",
            "provider_media_status": "FAIL",
            "provider_packet_status": "BLOCKED_PROVIDER_GATE",
            "provider_eligibility": False,
            "provider_media_probe_receipt": str(public_probe_receipt),
            "remaining_blockers": ["provider_media_url_missing"],
        },
    )
    install_one_scene_kling_review_packet(
        run_root=run_root,
        panel_source_receipt=source_receipt,
        panel_repair_gate_receipt=repair_receipt,
    )
    _write_json(
        publication_work_order,
        {
            "schema": "persona_dream.provider_media_publication_work_order.v1",
            "status": "WORK_ORDER_READY_PUBLIC_UPLOAD_AUTH_REQUIRED",
            "authorization_required": [
                "public_upload_of_panel_image",
                "git_commit_and_push_or_equivalent_public_asset_publish",
            ],
            "forbidden_actions": [
                "direct_kling_submit",
                "paid_provider_call",
                "nano_banana_final_panel_generation",
                "gemini_final_panel_generation",
                "provider_readiness_without_live_url_probe",
                "hash_or_receipt_rewrite_without_matching_public_fetch",
            ],
            "source_paths": {
                "run_root": str(run_root),
                "panel_repair_gate_receipt": str(repair_receipt),
                "provider_media_probe_receipt": str(public_probe_receipt),
                "panel_image": str(image),
            },
            "locked_media": {"local_path": str(image), "sha256": panel_hash, "bytes": image.stat().st_size},
            "proposed_publication": {
                "method": "git_raw_asset_after_authorized_commit_push",
                "target_repo_path": target_repo_path,
                "proposed_url": proposed_url,
                "rollback_path": str(run_root / "rollback"),
            },
            "verification_commands": [
                f"./run.sh validate-provider-media-url --url {proposed_url} --expected-sha256 {panel_hash} --json",
                "./run.sh validate-panel-repair-gate <panel_repair_gate_receipt> --require-provider-eligible",
            ],
        },
    )
    _write_json(
        staging_receipt,
        {
            "schema": "persona_dream.provider_media_local_staging_receipt.v1",
            "status": "PASS_PROVIDER_MEDIA_LOCAL_STAGING",
            "staged_asset_path": str(image),
            "target_repo_path": target_repo_path,
            "proposed_url": proposed_url,
            "staged_sha256": panel_hash,
            "does_not_authorize": [
                "git_push",
                "public_upload",
                "provider_readiness",
                "direct_kling_submit",
                "paid_provider_call",
            ],
            "next_required_probe_command": (
                f"./run.sh validate-provider-media-url --url {proposed_url} --expected-sha256 {panel_hash} --json"
            ),
        },
    )
    _write_json(
        public_probe_receipt,
        {
            "schema": "persona_dream.provider_media_url_probe_receipt.v1",
            "status": "BLOCKED",
            "url": proposed_url,
            "expected_sha256": panel_hash,
            "observed_sha256": None,
            "http_status": None,
            "content_length": None,
            "blockers": ["fetch_failed:HTTP Error 404: Not Found"],
            "mocked": "no",
            "live": "yes",
        },
    )
    _write_json(
        publication_preflight_receipt,
        {
            "schema": "persona_dream.provider_media_publication_preflight_validation.v1",
            "status": "BLOCKED_AWAITING_PUBLICATION_AUTHORIZATION",
            "first_blocker": {
                "phase": "provider_media_publication_authorization",
                "reason": "public_upload_or_git_push_authorization_required",
            },
            "preflight_ready": True,
            "proposed_url": proposed_url,
            "target_repo_path": target_repo_path,
            "locked_sha256": panel_hash,
            "staged_sha256": panel_hash,
            "mocked": "no",
            "live": "no",
        },
    )
    _write_json(
        publication_authorization_receipt,
        {
            "schema": "persona_dream.provider_media_publication_authorization_validation.v1",
            "status": "BLOCKED_AWAITING_PUBLICATION_AUTHORIZATION",
            "first_blocker": {
                "phase": "provider_media_publication_authorization",
                "reason": "authorization_receipt_required",
            },
            "locked_sha256": panel_hash,
            "proposed_url": proposed_url,
            "mocked": "no",
            "live": "no",
        },
    )
    _write_json(
        run_root / "receipts/pipeline_loop_run.json",
        {
            "schema": "persona_dream.pipeline_loop_run.v1",
            "generated_at": "2026-06-28T23:45:00Z",
            "run_root": str(run_root),
            "direction": "backward",
            "status": "BLOCKED",
            "stop_reason": "external_action_required",
            "active_loop": {
                "loop": "provider_media_loop",
                "phase": "provider_media_publication_authorization",
                "blocker": "authorization_receipt_required",
                "default_repair": "Supply an explicit authorization receipt for the exact staged asset.",
                "validator": "validate-provider-media-publication-authorization",
                "external_action_required": True,
            },
            "iterations": [
                {
                    "iteration": 1,
                    "status": "BLOCKED",
                    "active_loop": {
                        "loop": "provider_media_loop",
                        "phase": "provider_media_publication_authorization",
                        "blocker": "authorization_receipt_required",
                        "default_repair": "Supply an explicit authorization receipt for the exact staged asset.",
                        "validator": "validate-provider-media-publication-authorization",
                        "external_action_required": True,
                    },
                    "first_blocker": {"phase": "provider_media_publication_authorization"},
                    "phase_count": 11,
                }
            ],
            "policy": {
                "implicit_local_repair_allowed": False,
                "kling_call_allowed": False,
                "nano_banana_final_panel_allowed": False,
                "public_upload_allowed_without_explicit_authorization": False,
            },
            "live": "no",
            "mocked": "no",
        },
    )
    report = _write_report(root / "report")
    return {
        "run_root": run_root,
        "loop": run_root / "receipts/pipeline_loop_run.json",
        "publication": publication_work_order,
        "staging": staging_receipt,
        "probe": public_probe_receipt,
        "preflight": publication_preflight_receipt,
        "authorization": publication_authorization_receipt,
        "report": report,
    }


class TestValidatePipelineEvidenceBundle(unittest.TestCase):
    def test_bundle_reports_publication_authorization_as_first_blocker_with_report_pass(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            paths = _write_bundle_fixture(Path(tmp))
            result = validate_pipeline_evidence_bundle(
                run_root=paths["run_root"],
                pipeline_loop_run_receipt=paths["loop"],
                publication_work_order=paths["publication"],
                local_staging_receipt=paths["staging"],
                public_probe_receipt=paths["probe"],
                publication_preflight_receipt=paths["preflight"],
                publication_authorization_receipt=paths["authorization"],
                panel_report=paths["report"],
            )

        self.assertEqual(result["status"], "BLOCKED")
        self.assertEqual(result["first_blocker"]["phase"], "provider_media_publication_authorization")
        self.assertIn("authorization_receipt_required", result["first_blocker"]["reason"])
        self.assertEqual(result["validations"]["panel_comparison_report"]["status"], "PASS_PANEL_COMPARISON_REPORT")
        self.assertEqual(
            result["validations"]["provider_media_publication_preflight"]["status"],
            "BLOCKED_AWAITING_PUBLICATION_AUTHORIZATION",
        )
        self.assertTrue(result["publication_preflight"]["preflight_ready"])
        self.assertEqual(
            result["validations"]["provider_media_publication_authorization"]["status"],
            "BLOCKED_AWAITING_PUBLICATION_AUTHORIZATION",
        )
        self.assertEqual(
            result["publication_authorization"]["first_blocker"]["reason"],
            "authorization_receipt_required",
        )
        self.assertTrue(any(item["phase"] == "provider_media_public_probe" for item in result["phase_backlog"]))
        self.assertEqual(result["validations"]["provider_media_public_handoff"]["status"], "BLOCKED")
        self.assertEqual(result["live"], "yes")
        self.assertIs(result["policy"]["kling_call_allowed"], False)
        self.assertIn("direct_kling_submit", result["does_not_authorize"])

    def test_bundle_blocks_on_invalid_report_before_trusting_reality_check(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            paths = _write_bundle_fixture(root)
            bad_report = _write_report(root / "bad-report", forbidden_claim="ready for Kling")
            result = validate_pipeline_evidence_bundle(
                run_root=paths["run_root"],
                pipeline_loop_run_receipt=paths["loop"],
                publication_work_order=paths["publication"],
                local_staging_receipt=paths["staging"],
                public_probe_receipt=paths["probe"],
                publication_preflight_receipt=paths["preflight"],
                publication_authorization_receipt=paths["authorization"],
                panel_report=bad_report,
            )

        self.assertEqual(result["status"], "BLOCKED")
        self.assertEqual(result["first_blocker"]["phase"], "panel_comparison_report")
        self.assertIn("forbidden_report_claim", result["first_blocker"]["reason"])


if __name__ == "__main__":
    unittest.main()
