# Generated by test-lab — blind adversarial evaluation
"""An idea must steer the dream, or be refused.

The failure this guards against is silent substitution: an idea that matches no
residue quietly falling back to autonomous selection, so the run receipt claims
an idea the dream ignored. That is worse than refusing, because it is a receipt
that lies rather than a run that stops.

The second guard is that an idea never INVENTS residue. Selection is restricted
to memories she already has; steering changes which of them surface, never what
exists. A dream about material she was never given would be confabulation with a
provenance trail.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

_spec = importlib.util.spec_from_file_location(
    "adc_mod", ROOT / "scripts" / "autonomous_dream_cycle.py")
adc = importlib.util.module_from_spec(_spec)
sys.modules["adc_mod"] = adc
_spec.loader.exec_module(adc)


def _root(key: str, text: str) -> tuple[str, dict]:
    return key, {"_key": key, "claim": text, "claim_text": text,
                 "evidence_text": "", "retrieval_text": text}


ROOTS = dict([
    _root("m1", "Kai stood on the seawall and I said nothing at all."),
    _root("m2", "The succulent on my desk was already dying that first day."),
    _root("m3", "Moana played on a Sunday and I turned it off at the grandmother scene."),
])


def test_an_idea_restricts_selection_to_residue_it_touches():
    seeded, prov = adc.seed_roots_with_idea(ROOTS, "kai on the seawall")
    assert set(seeded) == {"m1"}
    assert prov["roots_before"] == 3 and prov["roots_after"] == 1


def test_a_different_idea_selects_different_residue():
    """Steering, not coincidence. Live: three ideas chose three clusters."""
    a, _ = adc.seed_roots_with_idea(ROOTS, "the dying succulent on my desk")
    b, _ = adc.seed_roots_with_idea(ROOTS, "moana grandmother scene")
    assert set(a) == {"m2"}
    assert set(b) == {"m3"}
    assert set(a) != set(b)


def test_an_idea_with_no_residue_is_refused_not_substituted():
    """The whole point. A silent fallback makes the receipt claim an idea the
    dream ignored."""
    with pytest.raises(SystemExit) as exc:
        adc.seed_roots_with_idea(ROOTS, "quantum chromodynamics in tungsten")
    message = str(exc.value)
    assert "BLOCKED_IDEA_NO_RESIDUE" in message
    # The refusal must name what it looked for, or it is unactionable.
    assert "chromodynamics" in message and "tungsten" in message


def test_an_idea_of_only_stopwords_is_refused():
    with pytest.raises(SystemExit) as exc:
        adc.seed_roots_with_idea(ROOTS, "the things that were about it")
    assert "BLOCKED_IDEA_EMPTY" in str(exc.value)


def test_every_matching_root_is_kept_not_just_the_best():
    """A top-1 filter would starve the cluster engine's conflict search."""
    roots = dict([
        _root("a", "Kai laughed."),
        _root("b", "Kai and the seawall and the silence."),
        _root("c", "Nothing relevant here."),
    ])
    seeded, prov = adc.seed_roots_with_idea(roots, "kai seawall")
    assert set(seeded) == {"a", "b"}
    assert prov["best_term_hits"] == 2


def test_stopword_list_stays_small():
    """Over-filtering an idea quietly changes what she dreams about. An idea is
    a sentence a human typed, not a query language."""
    assert len(adc._IDEA_STOPWORDS) < 60


def test_eval_can_reuse_variation_after_ledger_exhaustion_without_mutating_ledger(tmp_path, monkeypatch):
    """Retained evals run repeatedly; they must not consume a finite production ledger."""
    (tmp_path / "GOAL_V3.md").write_text("goal", encoding="utf-8")
    (tmp_path / "reports" / "goal_v5").mkdir(parents=True)

    roots = {
        "a": {"retrieval_text": "Kai box warmth", "claim": "Kai box warmth"},
        "b": {"retrieval_text": "Kai bottle rocket", "claim": "Kai bottle rocket"},
        "c": {"retrieval_text": "Kai ocean light", "claim": "Kai ocean light"},
    }

    class Profile:
        persona_id = "embry"
        strategy = "entity_mediated"

        def roots(self, docs):
            return roots

        def band(self, key, doc):
            return "recent"

        def counterparts(self, doc):
            return ["kai"]

        def entities_of(self, doc):
            return []

        def intra_neighbors(self, seed_key, doc, members, entity_index):
            return []

        def conflict_score(self, doc):
            return {"Kai box warmth": 3, "Kai bottle rocket": 2, "Kai ocean light": 1}[doc["claim"]]

        def recency_index(self, band):
            return 0

    monkeypatch.setattr(adc, "ROOT", tmp_path)
    monkeypatch.setattr(adc, "fetch_persona_docs", lambda persona_id: list(roots.values()))
    monkeypatch.setattr(adc, "charged_interaction_pulls", lambda persona_id: [])
    monkeypatch.setattr(adc, "_load", lambda name: type("Ledger", (), {"read_ledger": staticmethod(lambda persona_id, docs: {})})())

    members = set(roots)
    exhausted = []
    for vi, seed_key in enumerate(["a", "b", "c"]):
        selected = [seed_key] + [m for m in sorted(members) if m != seed_key]
        emphasis = "negative" if vi % 2 == 1 else "positive"
        exhausted.append(adc.sha256_text("recent:kai" + "|" + "|".join(sorted(selected[:3])) + "|" + emphasis))
    ledger_path = tmp_path / "reports" / "goal_v5" / "variation_ledger.json"
    ledger_path.write_text(json.dumps({"variation_keys": exhausted}, indent=2), encoding="utf-8")

    with pytest.raises(SystemExit) as exc:
        adc.select_cluster(Profile(), tmp_path / "blocked")
    assert "BLOCKED_CYCLE_ALL_VARIATIONS_EXHAUSTED" in str(exc.value)

    monkeypatch.setenv("PERSONA_DREAM_ALLOW_VARIATION_REUSE", "1")
    reuse_out = tmp_path / "reused"
    reuse_out.mkdir()
    result = adc.select_cluster(Profile(), reuse_out)
    assert result["cluster"]["reused_after_ledger_exhaustion"] is True
    assert json.loads(ledger_path.read_text(encoding="utf-8"))["variation_keys"] == exhausted
