[project]
name = "create-streamdeck-page"
version = "0.1.0"
description = "Create and optimize dynamic Stream Deck pages"
requires-python = ">=3.10,<3.13"
dependencies = [
    "loguru>=0.7.0,<0.7.3",
    "pyyaml",
    "typer",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
