# Generated by test-lab — blind adversarial evaluation
"""Tests for workspace mount bug fixes in orchestrate + subagent-service.

Bug 1: subagent-service/run.sh reuses containers without checking workspace mount mismatch
Bug 2: orchestrate lane-shared containers silently use first task's cwd for all tasks
Bug 3: structured_execute.py used Path.cwd() instead of plan file parent as repo_root

These tests verify the Python-side fixes without requiring Docker.
"""
from __future__ import annotations

import ast
import re
import subprocess
import tempfile
import textwrap
from pathlib import Path

ORCHESTRATE_DIR = Path(__file__).resolve().parent
STRUCTURED_EXECUTE = ORCHESTRATE_DIR / "structured_execute.py"
SUBAGENT_RUN_SH = ORCHESTRATE_DIR.parent / "subagent-service" / "run.sh"


# ---------------------------------------------------------------------------
# Bug 3: repo_root defaults to plan file parent, not Path.cwd()
# ---------------------------------------------------------------------------

def test_run_command_uses_plan_parent_not_cwd():
    """The run() CLI command must pass plan_file.parent as repo_root, not Path.cwd()."""
    source = STRUCTURED_EXECUTE.read_text()
    tree = ast.parse(source)

    # Find the run() function
    run_func = None
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "run":
            run_func = node
            break

    assert run_func is not None, "run() function not found in structured_execute.py"

    # Extract source lines of the run function
    func_source = ast.get_source_segment(source, run_func)
    assert func_source is not None, "Could not extract run() source"

    # It must NOT call Path.cwd() as an argument in executable code (comments are OK)
    executable_lines = [
        line for line in func_source.splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    executable_code = "\n".join(executable_lines)
    assert "Path.cwd()" not in executable_code, (
        "run() still uses Path.cwd() as repo_root — should use plan_file.resolve().parent"
    )
    # Must NOT pass a hardcoded repo_root — it's now read from the plan file
    assert "execute_plan(plan_file.resolve()" in executable_code, (
        "run() should delegate to execute_plan with plan file path"
    )


def test_repo_root_read_from_plan():
    """_execute_plan_async must read repo_root from the plan file, not from args."""
    source = STRUCTURED_EXECUTE.read_text()

    # Find _execute_plan_async
    tree = ast.parse(source)
    func_node = None
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == "_execute_plan_async":
            func_node = node
            break

    assert func_node is not None, "_execute_plan_async not found"
    func_source = ast.get_source_segment(source, func_node)

    # Must read repo_root from the plan dict
    assert 'plan.get("repo_root")' in func_source or "plan.get('repo_root')" in func_source, (
        "_execute_plan_async must read repo_root from plan file"
    )
    # repo_root param should be optional (None default)
    assert "repo_root: Path | None = None" in func_source, (
        "repo_root parameter should be optional with None default"
    )


# ---------------------------------------------------------------------------
# Bug 2: _lane_workspace tracking
# ---------------------------------------------------------------------------

def test_lane_workspace_dict_exists():
    """structured_execute must have _lane_workspace module-level dict for tracking."""
    source = STRUCTURED_EXECUTE.read_text()
    assert "_lane_workspace" in source, (
        "_lane_workspace tracking dict not found in structured_execute.py"
    )
    # Verify it's a dict type annotation
    assert "dict[str, Path]" in source or "Dict[str, Path]" in source, (
        "_lane_workspace should be typed as dict[str, Path]"
    )


def test_run_subagent_updates_lane_workspace():
    """_run_subagent must check and update _lane_workspace before starting container."""
    source = STRUCTURED_EXECUTE.read_text()

    # Find the _run_subagent function
    tree = ast.parse(source)
    func_node = None
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == "_run_subagent":
            func_node = node
            break

    assert func_node is not None, "_run_subagent function not found"
    func_source = ast.get_source_segment(source, func_node)

    # Must reference _lane_workspace
    assert "_lane_workspace" in func_source, (
        "_run_subagent does not reference _lane_workspace — cwd changes between tasks in same lane will be silent"
    )
    # Must update it
    assert "_lane_workspace[" in func_source or "_lane_workspace.get" in func_source, (
        "_run_subagent doesn't read/write _lane_workspace"
    )


# ---------------------------------------------------------------------------
# Bug 1: subagent-service/run.sh workspace mismatch detection
# ---------------------------------------------------------------------------

def test_start_container_checks_workspace_mismatch():
    """start_container() must detect workspace mismatch on existing containers and restart."""
    if not SUBAGENT_RUN_SH.exists():
        raise FileNotFoundError(f"subagent-service/run.sh not found at {SUBAGENT_RUN_SH}")

    content = SUBAGENT_RUN_SH.read_text()

    # Must contain docker inspect for mount destination check
    assert "docker inspect" in content and "/home/node/workspace" in content, (
        "start_container() must inspect running container's mount destination to detect workspace mismatch"
    )

    # Must contain the workspace-changed restart logic (docker rm -f before falling through)
    assert "Workspace changed" in content or "workspace changed" in content.lower(), (
        "start_container() must log when workspace has changed and needs restart"
    )

    # Must NOT just return 0 unconditionally when container is already running
    # The old code had: if already running → return 0 (ignoring workspace)
    # The new code must check workspace BEFORE returning
    func_match = re.search(
        r'start_container\(\).*?^}', content, re.DOTALL | re.MULTILINE,
    )
    assert func_match, "Could not find start_container() function in run.sh"
    func_body = func_match.group()

    # Within the "already running" block, there must be a workspace check
    already_running_block = re.search(
        r'already running.*?(?=# Remove stopped|# Auto-allocate)',
        func_body, re.DOTALL,
    )
    assert already_running_block, "Could not find 'already running' block in start_container()"
    block = already_running_block.group()

    assert "workspace" in block.lower(), (
        "The 'already running' check doesn't examine workspace — will silently reuse stale mount"
    )
    assert "docker rm" in block or "docker stop" in block, (
        "When workspace mismatches, the container must be stopped/removed before recreation"
    )


def test_start_container_no_unconditional_early_return():
    """The old bug was 'return 0' without checking workspace. Verify that's fixed."""
    content = SUBAGENT_RUN_SH.read_text()

    # Extract the full already-running block (bash if with nested if/else/fi)
    # Look from the "# Check if already running" comment to the closing fi
    match = re.search(
        r'# Check if already running\n(.*?)(?=\n    # Remove stopped|    # Auto-allocate)',
        content, re.DOTALL,
    )
    assert match, "Could not find the 'already running' block"
    block = match.group()

    # Count the return 0 statements — there should be conditional returns,
    # not a single unconditional one at the top
    returns = re.findall(r'return 0', block)
    workspace_checks = re.findall(r'workspace', block, re.IGNORECASE)

    # If there are return 0s, there must also be workspace checks
    if returns:
        assert workspace_checks, (
            f"Found {len(returns)} 'return 0' in already-running block but no workspace "
            f"checks — container will be reused with stale mount"
        )


# ---------------------------------------------------------------------------
# Schema: repo_root is required
# ---------------------------------------------------------------------------

def test_schema_requires_repo_root():
    """The JSON schema must list repo_root as a required field."""
    import json
    schema_path = ORCHESTRATE_DIR.parent / "_shared" / "orchestrate-plan-v1.schema.json"
    assert schema_path.exists(), f"Schema not found at {schema_path}"
    schema = json.loads(schema_path.read_text())
    assert "repo_root" in schema.get("required", []), (
        "repo_root must be in the schema's required fields"
    )
    assert "repo_root" in schema.get("properties", {}), (
        "repo_root must be defined in schema properties"
    )


def test_validation_rejects_missing_repo_root():
    """validate_structured_plan must reject plans without repo_root."""
    import sys
    sys.path.insert(0, str(ORCHESTRATE_DIR.parent / "_shared"))
    from structured_plan import validate_structured_plan

    plan_without_repo_root = {
        "version": 1,
        "kind": "orchestrate-plan",
        "metadata": {"title": "Test", "goal": "Test goal"},
        "capability_overlap": ["none"],
        "questions_blockers": ["None"],
        "tasks": [],
    }
    result = validate_structured_plan(plan_without_repo_root)
    assert not result["valid"], "Plan without repo_root should fail validation"
    assert any("repo_root" in issue for issue in result["issues"]), (
        "Validation should mention repo_root in its issues"
    )


def test_validation_accepts_repo_root():
    """validate_structured_plan must accept plans with valid repo_root."""
    import sys
    sys.path.insert(0, str(ORCHESTRATE_DIR.parent / "_shared"))
    from structured_plan import validate_structured_plan

    plan_with_repo_root = {
        "version": 1,
        "kind": "orchestrate-plan",
        "repo_root": "/home/test/project",
        "metadata": {"title": "Test", "goal": "Test goal"},
        "capability_overlap": ["none"],
        "questions_blockers": ["None"],
        "tasks": [],
    }
    result = validate_structured_plan(plan_with_repo_root)
    repo_root_issues = [i for i in result["issues"] if "repo_root" in i]
    assert not repo_root_issues, f"Valid repo_root should not cause issues: {repo_root_issues}"


# ---------------------------------------------------------------------------
# Run all tests
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import traceback

    tests = [
        test_run_command_uses_plan_parent_not_cwd,
        test_repo_root_read_from_plan,
        test_lane_workspace_dict_exists,
        test_run_subagent_updates_lane_workspace,
        test_start_container_checks_workspace_mismatch,
        test_start_container_no_unconditional_early_return,
        test_schema_requires_repo_root,
        test_validation_rejects_missing_repo_root,
        test_validation_accepts_repo_root,
    ]

    passed = 0
    failed = 0
    for test in tests:
        try:
            test()
            print(f"  PASS  {test.__name__}")
            passed += 1
        except Exception as e:
            print(f"  FAIL  {test.__name__}: {e}")
            traceback.print_exc()
            failed += 1

    print(f"\n{passed}/{passed + failed} passed")
    if failed:
        exit(1)
