import { BarChart3, ImagePlus, Plus, Type, Workflow } from 'lucide-react'
import { useRef, useState } from 'react'
import { useRegisterAction } from '../hooks'
import type { UiSlide } from '../types'
import { Button } from './ui/button'

type Kind = 'chart' | 'diagram'
const DEFAULT_SPEC: Record<Kind, string> = {
  chart: '{\n  "Search": 42,\n  "Review": 17,\n  "Approve": 9\n}',
  diagram: '# create-svg scene YAML. Start from a template: skills/create-svg/run.sh new positive-negative scene.yml\n',
}

/** Insert text, an image file, a $create-figure chart, or a $create-svg diagram.
 * Charts/diagrams are generated by the owning skills from the spec you paste;
 * the result enters as an ILLUSTRATION asset (decorates, never evidences, a claim). */
export function InsertMenu({ slide, onChanged, onPickFile }: { slide: UiSlide; onChanged: () => void; onPickFile: (file: File) => void }) {
  const [open, setOpen] = useState(false)
  const [kind, setKind] = useState<Kind | null>(null)
  const [spec, setSpec] = useState('')
  const [alt, setAlt] = useState('')
  const [title, setTitle] = useState('Figure')
  const [chartType, setChartType] = useState('bar')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const fileInput = useRef<HTMLInputElement | null>(null)
  useRegisterAction('deck:insert:menu', { app: 'pitchdeck', action: 'DECK_INSERT_MENU', label: 'Insert', description: 'Insert text, image, chart, or diagram into the current slide' })
  useRegisterAction('deck:insert:text', { app: 'pitchdeck', action: 'DECK_INSERT_TEXT', label: 'Insert text', description: 'Add a text element' })
  useRegisterAction('deck:insert:image', { app: 'pitchdeck', action: 'DECK_INSERT_IMAGE', label: 'Insert image', description: 'Pick an image file' })
  useRegisterAction('deck:insert:chart', { app: 'pitchdeck', action: 'DECK_INSERT_CHART', label: 'Insert chart', description: 'Generate a chart with create-figure from metrics JSON' })
  useRegisterAction('deck:insert:diagram', { app: 'pitchdeck', action: 'DECK_INSERT_DIAGRAM', label: 'Insert diagram', description: 'Render a create-svg scene' })
  useRegisterAction('deck:insert:generate', { app: 'pitchdeck', action: 'DECK_INSERT_GENERATE', label: 'Generate', description: 'Run the generator and place the result on the slide' })

  const post = async (body: Record<string, string>) => {
    setBusy(true); setError(null)
    try {
      const response = await fetch('/api/insert', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ slide_id: slide.id, ...body }) })
      const data = (await response.json()) as { error?: string }
      if (!response.ok) throw new Error(data.error ?? `insert failed (${response.status})`)
      setKind(null); setOpen(false); onChanged()
    } catch (e) { setError(String(e instanceof Error ? e.message : e)) } finally { setBusy(false) }
  }
  const item = 'flex w-full cursor-pointer items-center gap-2 rounded px-2 py-1.5 text-left text-sm hover:bg-slate-800'
  return <div className="relative">
    <Button type="button" data-qid="deck:insert:menu" data-qs-action="DECK_INSERT_MENU" title="Insert into this slide" aria-expanded={open} variant="ghost" onClick={() => setOpen(v => !v)}><Plus size={16} aria-hidden /> Insert</Button>
    <input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,image/gif" hidden data-qid="deck:insert:file" title="Image file" onChange={e => { const f = e.target.files?.[0]; if (f) onPickFile(f); e.target.value = ''; setOpen(false) }} />
    {open ? <div role="menu" className="absolute left-0 top-full z-30 mt-1 w-80 rounded-xl border border-slate-700 bg-slate-900 p-2 shadow-2xl">
      {kind === null ? <>
        <Button type="button" role="menuitem" data-qid="deck:insert:text" data-qs-action="DECK_INSERT_TEXT" title="Add a text element" variant="ghost" className={item} onClick={() => void post({ kind: 'text', text: 'New text' })}><Type size={16} aria-hidden /> Text</Button>
        <Button type="button" role="menuitem" data-qid="deck:insert:image" data-qs-action="DECK_INSERT_IMAGE" title="Pick an image file (or paste / drop one onto the slide)" variant="ghost" className={item} onClick={() => fileInput.current?.click()}><ImagePlus size={16} aria-hidden /> Image file…</Button>
        <Button type="button" role="menuitem" data-qid="deck:insert:chart" data-qs-action="DECK_INSERT_CHART" title="Chart from metrics JSON via create-figure" variant="ghost" className={item} onClick={() => { setKind('chart'); setSpec(DEFAULT_SPEC.chart); setAlt('') }}><BarChart3 size={16} aria-hidden /> Chart (create-figure)…</Button>
        <Button type="button" role="menuitem" data-qid="deck:insert:diagram" data-qs-action="DECK_INSERT_DIAGRAM" title="Diagram from a create-svg scene" variant="ghost" className={item} onClick={() => { setKind('diagram'); setSpec(DEFAULT_SPEC.diagram); setAlt('') }}><Workflow size={16} aria-hidden /> Diagram (create-svg)…</Button>
        <p className="m-0 px-2 pt-1 text-xs text-slate-500">Paste (Ctrl+V) or drop an image anywhere on the slide.</p>
      </> : <form className="flex flex-col gap-2" onSubmit={e => { e.preventDefault(); void post({ kind, spec, alt, title, chart_type: chartType }) }}>
        <label className="text-xs text-slate-400">{kind === 'chart' ? 'Metrics JSON {label: number}' : 'create-svg scene YAML'}
          <textarea data-qid="deck:insert:spec" title="Generator input" value={spec} onChange={e => setSpec(e.target.value)} rows={6} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2 font-mono text-xs text-slate-100" /></label>
        {kind === 'chart' ? <div className="flex gap-2">
          <select data-qid="deck:insert:chart-type" data-qs-action="DECK_INSERT_CHART_TYPE" title="Chart type" value={chartType} onChange={e => setChartType(e.target.value)} className="rounded border border-slate-700 bg-slate-950 p-1 text-sm">{['bar', 'hbar', 'pie', 'line'].map(t => <option key={t}>{t}</option>)}</select>
          <input data-qid="deck:insert:title" title="Chart title" value={title} onChange={e => setTitle(e.target.value)} className="min-w-0 flex-1 rounded border border-slate-700 bg-slate-950 p-1 text-sm" />
        </div> : null}
        <input data-qid="deck:insert:alt" title="Alt text (required)" placeholder="Alt text (required)" value={alt} onChange={e => setAlt(e.target.value)} className="rounded border border-slate-700 bg-slate-950 p-1 text-sm" />
        <div className="flex gap-2">
          <Button type="submit" data-qid="deck:insert:generate" data-qs-action="DECK_INSERT_GENERATE" title="Generate and place on slide" disabled={busy || !alt.trim() || !spec.trim()}>{busy ? 'Generating…' : 'Generate'}</Button>
          <Button type="button" variant="ghost" data-qid="deck:insert:cancel" data-qs-action="DECK_INSERT_CANCEL" title="Cancel" onClick={() => setKind(null)}>Cancel</Button>
        </div>
        {error ? <p role="alert" className="m-0 text-xs text-rose-300">{error}</p> : null}
      </form>}
    </div> : null}
  </div>
}
