"""Export accepted candidates into a TTS-ready dataset."""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

from lib.tags import (
    alignment_metadata,
    effective_transcript,
    emotion_tags,
    exportable_tts_text,
    plain_caption,
    strip_tags,
    tag_confidence,
    tag_source,
    validate_tagged_transcript,
)


ORPHEUS_MIN_EXAMPLES = 50
ORPHEUS_RECOMMENDED_EXAMPLES = 300
ORPHEUS_SAMPLE_RATE = 24000
EVENT_WORDS_BY_TAG = {
    "laugh": ("laugh", "laughs", "laughing", "laughed"),
    "chuckle": ("chuckle", "chuckles", "chuckling", "chuckled"),
    "sigh": ("sigh", "sighs", "sighing", "sighed"),
    "cough": ("cough", "coughs", "coughing", "coughed"),
    "sniffle": ("sniffle", "sniffles", "sniffling", "sniffled"),
    "groan": ("groan", "groans", "groaning", "groaned"),
    "yawn": ("yawn", "yawns", "yawning", "yawned"),
    "gasp": ("gasp", "gasps", "gasping", "gasped"),
}


def _load_orpheus_audio_example(path: Path) -> dict:
    """Build a datasets Audio example without torchcodec."""
    import numpy as np
    import soundfile as sf

    array, sampling_rate = sf.read(str(path), always_2d=False)
    if array.ndim > 1:
        array = array.mean(axis=1)
    if sampling_rate != ORPHEUS_SAMPLE_RATE:
        raise ValueError(f"Expected {ORPHEUS_SAMPLE_RATE} Hz, got {sampling_rate} for {path}")
    return {"array": np.asarray(array, dtype=np.float32), "sampling_rate": ORPHEUS_SAMPLE_RATE}



def _convert_audio_for_orpheus(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-y", "-i", str(src), "-ac", "1", "-ar", str(ORPHEUS_SAMPLE_RATE), str(dest)],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def _tag_names(tags: list[str]) -> list[str]:
    names: list[str] = []
    for tag in tags:
        name = str(tag).strip().lower().strip("<>")
        if name in EVENT_WORDS_BY_TAG and name not in names:
            names.append(name)
    return names


def _literal_tag_asr_check_clip(clip_path: Path, tags: list[str], allowed_spoken_text: str = "") -> dict:
    """Reject generated clips where the audio speaks the tag word literally."""
    expected_tags = _tag_names(tags)
    if not expected_tags:
        return {"status": "PASS", "expected_tags": []}
    try:
        from lib.transcribe import transcribe_clip

        transcript, confidence = transcribe_clip(clip_path)
    except Exception as exc:
        return {
            "status": "FAIL",
            "reason": "literal_tag_check_unavailable",
            "expected_tags": expected_tags,
            "error": str(exc),
        }

    lowered = transcript.lower()
    allowed_lowered = allowed_spoken_text.lower()
    spoken = []
    for tag in expected_tags:
        words = [
            word
            for word in EVENT_WORDS_BY_TAG[tag]
            if not re.search(rf"\b{re.escape(word)}\b", allowed_lowered)
        ]
        if words and any(re.search(rf"\b{re.escape(word)}\b", lowered) for word in words):
            spoken.append(tag)
    return {
        "status": "FAIL" if spoken else "PASS",
        "reason": "literal_tag_spoken" if spoken else "",
        "expected_tags": expected_tags,
        "spoken_literal_tags": spoken,
        "asr_transcript": transcript,
        "asr_confidence": confidence,
    }


def _write_orpheus_lora_config(out_dir: Path, summary: dict) -> Path:
    config_path = out_dir / "orpheus_unsloth_lora_config.yaml"
    config_path.write_text(
        f"""# Generated by voice-segment-selector.
# Copy or symlink this into ${HOME}/workspace/experiments/Orpheus-TTS/finetune/config.yaml
# before running the selected LoRA training script.
TTS_dataset: "{summary["out_dir"]}"

model_name: "unsloth/orpheus-3b-0.1-ft"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-5

# LoRA / Unsloth defaults for Orpheus experiments
training_method: "unsloth_lora"
audio_sampling_rate: {ORPHEUS_SAMPLE_RATE}
load_in_4bit: false
lora_rank: 64
lora_alpha: 64
lora_dropout: 0.0
use_gradient_checkpointing: "unsloth"

# Naming and paths
save_folder: "checkpoints/{summary["speaker"]}_orpheus_lora"
project_name: "tuning-orpheus"
run_name: "{summary["speaker"]}-unsloth-lora"
""",
        encoding="utf-8",
    )
    return config_path


def _write_orpheus_dataset_card(out_dir: Path, summary: dict) -> Path:
    card_path = out_dir / "README.md"
    limitations = "\n".join(f"- {item}" for item in summary["limitations"])
    card_path.write_text(
        f"""---
dataset_info:
  features:
  - name: audio
    dtype: audio
  - name: text
    dtype: string
  - name: speaker
    dtype: string
  splits:
  - name: train
    num_examples: {summary["example_count"]}
---

# {summary["speaker"]} Voice Dataset

This dataset was exported by `voice-segment-selector` for Orpheus-compatible
text-to-speech fine-tuning.

## Contents

- Speaker/persona id: `{summary["speaker"]}`
- Example count: `{summary["example_count"]}`
- Status: `{summary["status"]}`
- Minimum examples for useful Orpheus fine-tuning: `{summary["minimum_examples_for_good_results"]}`
- Recommended examples per speaker: `{summary["recommended_examples_per_speaker"]}`
- Source job: `{summary["job_dir"]}`
- Dataset path: `{summary["hf_dataset"]}`
- Parquet path: `{summary["parquet"]}`

## Intended Use

Fine-tuning and evaluating a TTS voice for the named speaker/persona after
human review of the accepted clips and transcripts.

## Limitations

{limitations}

## Publication Boundary

This is a local dataset-card draft. Validate and publish through
`$ops-huggingface`; do not upload without a dry-run receipt and explicit
execution approval.
""",
        encoding="utf-8",
    )
    return card_path


def load_selection_order(job_dir: Path) -> list[str]:
    path = job_dir / "selection.json"
    if not path.exists():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    ids = payload.get("ordered_ids", payload.get("ids", []))
    return [str(item) for item in ids]


def load_candidates(job_dir: Path) -> list[dict]:
    path = job_dir / "candidates.jsonl"
    if not path.exists():
        raise FileNotFoundError(f"Missing {path}; run prepare first.")
    rows: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    decisions_path = job_dir / "decisions.jsonl"
    if decisions_path.exists():
        decisions = {}
        for line in decisions_path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            row = json.loads(line)
            decisions[row["id"]] = row["decision"]
        filtered: list[dict] = []
        for row in rows:
            decision = decisions.get(row["id"], row.get("status", "pending"))
            if decision == "accept":
                row = {**row, "status": "accepted", "accepted_by": "human", "review_status": "human"}
                filtered.append(row)
        rows = filtered
    selected_ids = load_selection_order(job_dir)
    if selected_ids:
        order = {clip_id: index for index, clip_id in enumerate(selected_ids)}
        rows.sort(key=lambda row: order.get(str(row.get("id")), len(order)))
    return rows


def export_dataset(
    *,
    job_dir: Path,
    out_dir: Path,
    gender: str | None = None,
    min_quality: float = 0.0,
    min_rank: float = 0.0,
    auto_accept_top: int = 0,
    allow_empty_transcript: bool = False,
) -> dict:
    rows = load_candidates(job_dir)
    if auto_accept_top > 0 and not (job_dir / "decisions.jsonl").exists():
        rows = sorted(rows, key=lambda row: row.get("rank_score", 0.0), reverse=True)
        if gender:
            rows = [row for row in rows if row.get("gender_label") == gender]
        rows = rows[:auto_accept_top]
        for row in rows:
            row["status"] = "accepted"
            row["accepted_by"] = "auto"
    elif gender:
        rows = [row for row in rows if row.get("gender_label") == gender]

    rows = [
        row
        for row in rows
        if row.get("status") in {"accepted", "accept"}
        and float(row.get("quality_score") or 0.0) >= min_quality
        and float(row.get("rank_score") or 0.0) >= min_rank
    ]

    clips_dir = out_dir / "clips"
    male_dir = out_dir / "male"
    female_dir = out_dir / "female"
    unknown_dir = out_dir / "unknown"
    for directory in (clips_dir, male_dir, female_dir, unknown_dir):
        directory.mkdir(parents=True, exist_ok=True)

    metadata_rows: list[dict] = []
    rejected_rows: list[dict] = []
    for index, row in enumerate(rows, start=1):
        src = job_dir / row["clip"]
        if not src.exists():
            continue
        transcript = effective_transcript(row)
        if not allow_empty_transcript and not transcript:
            rejected_rows.append(
                {
                    "id": row.get("id"),
                    "clip": row.get("clip"),
                    "reason": "missing_transcript",
                    "required_for": "tts_training_metadata",
                }
            )
            continue
        label = row.get("gender_label", "unknown")
        bucket = {"male": male_dir, "female": female_dir, "unknown": unknown_dir}.get(label, unknown_dir)
        dest_name = f"{index:04d}.wav"
        shutil.copy2(src, clips_dir / dest_name)
        shutil.copy2(src, bucket / dest_name)
        caption = plain_caption(row)
        candidate = str(row.get("tts_text_candidate") or row.get("transcript_tagged") or "")
        reviewed = exportable_tts_text(row)
        metadata_rows.append(
            {
                "clip": f"clips/{dest_name}",
                "bucket_clip": f"{label}/{dest_name}",
                "source": row.get("source"),
                "start": row.get("start_sec"),
                "end": row.get("end_sec"),
                "duration_sec": row.get("duration_sec"),
                "plain_caption": caption,
                "alignment": alignment_metadata(row),
                "tts_text_candidate": candidate,
                "tts_text": reviewed or caption,
                "transcript": transcript,
                "transcript_draft": caption,
                "transcript_tagged": candidate,
                "transcript_final": reviewed,
                "emotion_tags": emotion_tags(row),
                "tag_source": tag_source(row),
                "tag_confidence": tag_confidence(row),
                "review_status": row.get("review_status", "pending"),
                "asr_confidence": row.get("asr_confidence"),
                "quality_score": row.get("quality_score"),
                "rank_score": row.get("rank_score"),
                "gender_label": label,
                "gender_score": row.get("gender_score"),
                "accepted_by": row.get("accepted_by", "human"),
            }
        )

    (out_dir / "metadata.jsonl").write_text(
        "\n".join(json.dumps(row) for row in metadata_rows) + ("\n" if metadata_rows else "")
    )
    (out_dir / "rejected.jsonl").write_text(
        "\n".join(json.dumps(row) for row in rejected_rows) + ("\n" if rejected_rows else "")
    )
    summary = {
        "exported_clips": len(metadata_rows),
        "rejected_clips": len(rejected_rows),
        "out_dir": str(out_dir.resolve()),
        "metadata_jsonl": str((out_dir / "metadata.jsonl").resolve()),
        "allow_empty_transcript": allow_empty_transcript,
    }
    (out_dir / "export_summary.json").write_text(json.dumps(summary, indent=2))
    return summary


def export_orpheus_dataset(
    *,
    job_dir: Path,
    out_dir: Path,
    speaker: str,
    gender: str | None = None,
    min_quality: float = 0.0,
    min_rank: float = 0.0,
) -> dict:
    try:
        from datasets import Audio, Dataset, Features, Value
    except ImportError as exc:
        raise RuntimeError("Install Orpheus export extras: uv sync --extra orpheus") from exc

    rows = [
        row
        for row in load_candidates(job_dir)
        if row.get("status") in {"accepted", "accept"}
        and (not gender or row.get("gender_label") == gender)
        and float(row.get("quality_score") or 0.0) >= min_quality
        and float(row.get("rank_score") or 0.0) >= min_rank
    ]

    out_dir.mkdir(parents=True, exist_ok=True)
    records = []
    rejected_rows = []
    clips_dir = out_dir / "clips"
    for row in rows:
        caption = plain_caption(row)
        tts_text = exportable_tts_text(row)
        review_status = str(row.get("review_status") or "pending")
        if review_status not in {"human", "auto_high_confidence"}:
            rejected_rows.append(
                {
                    "id": row.get("id"),
                    "clip": row.get("clip"),
                    "reason": "tts_text_not_reviewed",
                    "review_status": review_status,
                    "required_for": "orpheus_huggingface_dataset",
                }
            )
            continue
        if not tts_text:
            rejected_rows.append(
                {
                    "id": row.get("id"),
                    "clip": row.get("clip"),
                    "reason": "missing_tts_text",
                    "required_for": "orpheus_huggingface_dataset",
                }
            )
            continue
        tag_errors = validate_tagged_transcript(caption, tts_text)
        if tag_errors:
            rejected_rows.append(
                {
                    "id": row.get("id"),
                    "clip": row.get("clip"),
                    "reason": "invalid_tts_text_tags",
                    "errors": tag_errors,
                    "required_for": "orpheus_huggingface_dataset",
                }
            )
            continue
        clip_path = job_dir / row["clip"]
        if not clip_path.exists():
            rejected_rows.append(
                {
                    "id": row.get("id"),
                    "clip": row.get("clip"),
                    "reason": "missing_clip_file",
                    "required_for": "orpheus_huggingface_dataset",
                }
            )
            continue
        literal_tag_check = _literal_tag_asr_check_clip(clip_path, emotion_tags(row), strip_tags(tts_text))
        if literal_tag_check.get("status") != "PASS":
            rejected_rows.append(
                {
                    "id": row.get("id"),
                    "clip": row.get("clip"),
                    "reason": literal_tag_check.get("reason", "literal_tag_check_failed"),
                    "literal_tag_check": literal_tag_check,
                    "tts_text": tts_text,
                    "required_for": "orpheus_huggingface_dataset",
                }
            )
            continue
        dest_clip = clips_dir / f"{speaker}_{row.get('id')}.wav"
        _convert_audio_for_orpheus(clip_path, dest_clip)
        records.append(
            {
                "audio": {"path": str(dest_clip.resolve())},
                "text": tts_text,
                "plain_caption": caption,
                "tts_text": tts_text,
                "emotion_tags": json.dumps(emotion_tags(row)),
                "tag_source": tag_source(row),
                "tag_confidence": float(tag_confidence(row) or 0.0),
                "review_status": review_status,
                "speaker": speaker,
                "clip_id": str(row.get("id")),
                "source": row.get("source"),
                "start_sec": float(row.get("start_sec") or 0.0),
                "end_sec": float(row.get("end_sec") or 0.0),
                "duration_sec": float(row.get("duration_sec") or 0.0),
                "quality_score": float(row.get("quality_score") or 0.0),
                "rank_score": float(row.get("rank_score") or 0.0),
                "accepted_by": row.get("accepted_by", "human"),
            }
        )

    manifest_path = out_dir / "training_manifest.jsonl"
    manifest_path.write_text(
        "\n".join(json.dumps(record) for record in records) + ("\n" if records else ""),
        encoding="utf-8",
    )

    hf_dataset_path = out_dir / "hf_dataset"
    parquet_path = out_dir / "dataset.parquet"
    hf_export_mode = "manifest_only"
    hf_export_error = ""

    manifest_records = []
    for record in records:
        audio_path = Path(record["audio"]["path"] if isinstance(record["audio"], dict) else record["audio"])
        manifest_records.append({**record, "audio_path": str(audio_path.resolve()), "audio": str(audio_path.name)})

    try:
        import pyarrow as pa
        import pyarrow.parquet as pq

        table = pa.table(
            {
                "audio_path": [row["audio_path"] for row in manifest_records],
                "text": [row["text"] for row in manifest_records],
                "plain_caption": [row["plain_caption"] for row in manifest_records],
                "tts_text": [row["tts_text"] for row in manifest_records],
                "emotion_tags": [row["emotion_tags"] for row in manifest_records],
                "tag_source": [row["tag_source"] for row in manifest_records],
                "tag_confidence": [row["tag_confidence"] for row in manifest_records],
                "review_status": [row["review_status"] for row in manifest_records],
                "speaker": [row["speaker"] for row in manifest_records],
                "clip_id": [row["clip_id"] for row in manifest_records],
            }
        )
        pq.write_table(table, parquet_path)
        hf_export_mode = "parquet_manifest"
    except Exception as exc:
        hf_export_error = str(exc)

    try:
        from datasets import Audio, Dataset, Features, Value

        hf_records = []
        for record in records:
            audio_value = record["audio"]
            if isinstance(audio_value, dict) and "path" not in audio_value and "array" in audio_value:
                audio_value = {"path": str((clips_dir / f"{record['clip_id']}.wav").resolve())}
            elif isinstance(audio_value, dict) and "path" in audio_value:
                audio_value = {"path": audio_value["path"]}
            else:
                audio_value = {"path": str(audio_value)}
            hf_records.append({**record, "audio": audio_value})

        features = Features(
            {
                "audio": Audio(sampling_rate=ORPHEUS_SAMPLE_RATE),
                "text": Value("string"),
                "plain_caption": Value("string"),
                "tts_text": Value("string"),
                "emotion_tags": Value("string"),
                "tag_source": Value("string"),
                "tag_confidence": Value("float32"),
                "review_status": Value("string"),
                "speaker": Value("string"),
                "clip_id": Value("string"),
                "source": Value("string"),
                "start_sec": Value("float32"),
                "end_sec": Value("float32"),
                "duration_sec": Value("float32"),
                "quality_score": Value("float32"),
                "rank_score": Value("float32"),
                "accepted_by": Value("string"),
            }
        )
        dataset = Dataset.from_list(hf_records, features=features)
        dataset.save_to_disk(str(hf_dataset_path))
        if not parquet_path.exists():
            dataset.to_parquet(str(parquet_path))
        hf_export_mode = "hf_dataset"
    except Exception as exc:
        hf_export_error = hf_export_error or str(exc)
        hf_dataset_path.mkdir(parents=True, exist_ok=True)
        (hf_dataset_path / "README.txt").write_text(
            "HF Audio encoding requires torch+torchcodec. Use training_manifest.jsonl + clips/ for Unsloth/Orpheus fine-tuning.\n",
            encoding="utf-8",
        )

    status = "CANARY_BELOW_MINIMUM"
    if len(records) >= ORPHEUS_RECOMMENDED_EXAMPLES:
        status = "RECOMMENDED_EXAMPLES_MET"
    elif len(records) >= ORPHEUS_MIN_EXAMPLES:
        status = "MINIMUM_EXAMPLES_MET"

    (out_dir / "rejected.jsonl").write_text(
        "\n".join(json.dumps(row) for row in rejected_rows) + ("\n" if rejected_rows else "")
    )
    summary = {
        "schema": "voice_segment_selector.orpheus_dataset.v1",
        "status": status,
        "speaker": speaker,
        "example_count": len(records),
        "rejected_clips": len(rejected_rows),
        "minimum_examples_for_good_results": ORPHEUS_MIN_EXAMPLES,
        "recommended_examples_per_speaker": ORPHEUS_RECOMMENDED_EXAMPLES,
        "audio_sampling_rate_hz": ORPHEUS_SAMPLE_RATE,
        "literal_tag_asr_gate": {
            "enabled": True,
            "fail_closed": True,
            "rejection_reasons": ["literal_tag_spoken", "literal_tag_check_unavailable"],
        },
        "out_dir": str(out_dir.resolve()),
        "job_dir": str(job_dir.resolve()),
        "hf_dataset": str((out_dir / "hf_dataset").resolve()),
        "training_manifest": str((out_dir / "training_manifest.jsonl").resolve()),
        "hf_export_mode": hf_export_mode,
        "hf_export_error": hf_export_error,
        "parquet": str((out_dir / "dataset.parquet").resolve()),
        "rejected_jsonl": str((out_dir / "rejected.jsonl").resolve()),
        "orpheus_repo": "${HOME}/workspace/experiments/Orpheus-TTS",
        "ops_huggingface_handoff": {
            "skill": "ops-huggingface",
            "dry_run_first": True,
            "recommended_commands": [
                "skills/voice-segment-selector/run.sh inference-smoke --speaker SPEAKER",
                "skills/voice-segment-selector/run.sh publish-orpheus --speaker SPEAKER --execute",
                "skills/ops-huggingface/run.sh validate-card README.md --type model",
            ],
        },
        "orpheus_training_handoff": {
            "default_method": "unsloth_lora",
            "fallback_script": "${HOME}/workspace/experiments/Orpheus-TTS/finetune/lora.py",
            "full_finetune_script": "${HOME}/workspace/experiments/Orpheus-TTS/finetune/train.py",
            "full_finetune_requires_explicit_approval": True,
            "local_gpu_docker_inference_required_for_ready": True,
            "notes": [
            "Use Unsloth LoRA as the default experimental fine-tuning path.",
            "Audio clips are converted to 24 kHz mono for Orpheus/Unsloth training.",
            "Use the local Orpheus finetune/lora.py config shape as a repo-compatible fallback.",
                "Run voice-segment-selector/run.sh inference-smoke after training; do not mark inference-ready until inference_receipt.json status is PASS.",
            ],
        },
        "limitations": [
            "Only accepted clips with non-empty transcripts are included.",
            "Vocal-characteristic buckets are classifier guesses, not speaker identity proof.",
            "Human transcript and voice-quality review should happen before training or publication.",
            "This export does not train a model and does not publish to Hugging Face Hub.",
            "Orpheus-native tags only (<laugh>, <chuckle>, <sigh>, <cough>, <sniffle>, <groan>, <yawn>, <gasp>). Never train from raw auto-tags.",
        ],
        "notes": [
            "Orpheus README states fine-tuning uses a Hugging Face dataset.",
            "Expect usable quality around 50 examples; aim for 300 examples per speaker.",
            "This export requires accepted clips with non-empty transcripts.",
        ],
    }
    card_path = _write_orpheus_dataset_card(out_dir, summary)
    summary["dataset_card"] = str(card_path.resolve())
    config_path = _write_orpheus_lora_config(out_dir, summary)
    summary["orpheus_lora_config"] = str(config_path.resolve())
    (out_dir / "dataset_info.json").write_text(json.dumps(summary, indent=2))
    return summary
