# Generated by test-lab — blind adversarial evaluation
"""Sanity tests for create-architecture."""
from pathlib import Path
import importlib.util
import sys

SKILL_DIR = Path(__file__).parent.parent


def load_module():
    spec = importlib.util.spec_from_file_location(
        "create_architecture", SKILL_DIR / "create_architecture.py"
    )
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module

def test_skill_md_exists():
    assert (SKILL_DIR / "SKILL.md").exists()

def test_run_sh_exists():
    assert (SKILL_DIR / "run.sh").exists()

def test_run_sh_executable():
    run_sh = SKILL_DIR / "run.sh"
    assert run_sh.stat().st_mode & 0o111, "run.sh is not executable"


def test_execution_lock_rejects_unclassified_components():
    module = load_module()
    spec = {
        "components": [{"id": "now"}, {"id": "drift"}],
        "execution_lock": {
            "objective": "run campaign",
            "deadline": "tonight",
            "current_phase": "now",
            "critical_path": ["now"],
            "deferred": [],
            "stop_condition": "runner starts",
            "max_attempts_per_blocker": 2,
            "max_identical_failures_per_family": 3,
            "systemic_failure_action": "stop_family_mark_remaining_blocked_continue_independent_families",
            "reviewer_scope_authority": "none",
            "update_interval_minutes": 5,
        },
    }
    assert "unclassified_components" in module.validate_execution_lock(spec)


def test_execution_lock_accepts_closed_scope():
    module = load_module()
    spec = {
        "components": [{"id": "now"}, {"id": "later"}],
        "execution_lock": {
            "objective": "run campaign",
            "deadline": "tonight",
            "current_phase": "now",
            "critical_path": ["now"],
            "deferred": ["later"],
            "stop_condition": "runner starts",
            "max_attempts_per_blocker": 2,
            "max_identical_failures_per_family": 3,
            "systemic_failure_action": "stop_family_mark_remaining_blocked_continue_independent_families",
            "reviewer_scope_authority": "none",
            "update_interval_minutes": 5,
        },
    }
    assert module.validate_execution_lock(spec) == []


def test_execution_lock_rejects_campaign_without_systemic_fail_fast():
    module = load_module()
    spec = {
        "components": [{"id": "campaign"}],
        "execution_lock": {
            "objective": "run campaign",
            "deadline": "tonight",
            "current_phase": "campaign",
            "critical_path": ["campaign"],
            "deferred": [],
            "stop_condition": "runner finishes",
            "max_attempts_per_blocker": 2,
            "max_identical_failures_per_family": 20,
            "systemic_failure_action": "finish_all_cases",
            "reviewer_scope_authority": "implicit",
            "update_interval_minutes": 5,
        },
    }
    errors = module.validate_execution_lock(spec)
    assert "max_identical_failures_per_family_must_be_one_to_three" in errors
    assert "systemic_failure_action_must_fail_fast_by_family" in errors
    assert "reviewer_scope_authority_must_be_none" in errors
