# Generated by test-lab — blind adversarial evaluation
"""Unit tests for /review-plan ask-gate backend routing and verdict mapping."""

from __future__ import annotations

import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
REVIEW_PLAN_DIR = THIS_DIR.parent
if str(REVIEW_PLAN_DIR) not in sys.path:
    sys.path.insert(0, str(REVIEW_PLAN_DIR))

import review_plan as rp  # noqa: E402


def test_gate_verdict_accepts_webgpt_pass_labels():
    result = rp.ReviewResult(file="plan.md")
    ask_artifacts = {"status": "passed", "verdict": "PASS", "backend": "webgpt"}
    verdict, reason = rp._gate_verdict(result, ask_artifacts)
    assert verdict == "PASS"
    assert reason == "no_warn_fail_or_blocking_ask_gate_findings"


def test_gate_verdict_blocks_needs_changes():
    result = rp.ReviewResult(file="plan.md")
    ask_artifacts = {"status": "passed", "verdict": "NEEDS_CHANGES", "backend": "webgpt"}
    verdict, reason = rp._gate_verdict(result, ask_artifacts)
    assert verdict == "NEEDS_CHANGES"
    assert reason == "ask_gate_returned_blocking_verdict"


def test_extract_verdict_from_text_plain_label():
    assert rp._extract_verdict_from_text("Summary\nVERDICT: BLOCKED\n") == "BLOCKED"


def test_run_ask_gate_rejects_unknown_backend(tmp_path: Path):
    target = tmp_path / "plan.md"
    target.write_text("# plan\n", encoding="utf-8")
    out = rp._run_ask_gate(
        backend="unknown",
        target=target,
        review_bundle=None,
        attach_file="",
        ask_id="test",
        ask_model="gpt-5.5",
        ask_reasoning="high",
        ask_timeout=30,
        focus="plan-contract",
        webgpt_tab_id="",
        webgpt_project="",
        oracle_iterations=1,
        run_output_root="",
    )
    assert out["status"] == "blocked"
    assert "unsupported" in out.get("reason", "")


def test_validate_review_evidence_bundle_requires_sections(tmp_path: Path):
    bundle = tmp_path / "bundle.md"
    bundle.write_text("# only title\n", encoding="utf-8")
    issues = rp.validate_review_evidence_bundle(bundle)
    assert any("Review request" in i for i in issues)


def test_validate_review_attach_zip_requires_request_or_plan_md(tmp_path: Path):
    import zipfile

    zpath = tmp_path / "bad.zip"
    with zipfile.ZipFile(zpath, "w") as zf:
        zf.writestr("only.png", b"png")
    issues = rp.validate_review_attach_zip(zpath)
    assert any("REQUEST.md" in i or "PLAN.md" in i or "REVIEW.md" in i for i in issues)

def test_build_webgpt_prompt_never_contains_review_plan_substring(tmp_path: Path):
    bundle = tmp_path / "bundle.md"
    bundle.write_text(
        "## Review request\nplan\n## This round acceptance\nok\n## Local gates\npass\n",
        encoding="utf-8",
    )
    target = tmp_path / "plan.md"
    target.write_text("# plan\n", encoding="utf-8")
    prompt = rp._build_webgpt_readiness_prompt(
        attach_file="",
        review_bundle=bundle,
        target=target,
    )
    assert "/review-plan" not in prompt.lower()


def test_apply_spiral_guards_caps_max_rounds_without_allow_flag():
    rounds, oracle, notes = rp._apply_spiral_guards(
        max_rounds=5,
        allow_extended_review=False,
        ask_gate=False,
        oracle_iterations=3,
        ask_gate_backend="webgpt",
    )
    assert rounds == rp.REVIEW_PLAN_MAX_ROUNDS_DEFAULT
    assert any("capped" in n for n in notes)


def test_apply_spiral_guards_caps_webgpt_oracle_iterations():
    rounds, oracle, notes = rp._apply_spiral_guards(
        max_rounds=1,
        allow_extended_review=False,
        ask_gate=True,
        oracle_iterations=5,
        ask_gate_backend="webgpt",
    )
    assert oracle == rp.REVIEW_PLAN_MAX_WEBGPT_ORACLE_ITERATIONS
    assert any("oracle-iterations" in n for n in notes)


def test_next_iteration_plan_pass_recommends_orchestrate():
    result = rp.ReviewResult(file="plan.md")
    steps = rp._next_iteration_plan(result, verdict="PASS")
    assert any("/orchestrate" in s for s in steps)

