"""Quality enforcement scanners for skills-ci.

Detects violations of prompt hygiene, blind test requirements,
regex-as-classifier anti-patterns, and AQL in shell scripts.

Composes /treesitter violations for AST-based checks (inline prompts,
regex classifiers). File-content checks remain here.

Split from scanners.py to stay under 800-line limit.
"""
from __future__ import annotations

import os

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, List

_THIS_DIR = str(Path(__file__).resolve().parent)
if _THIS_DIR not in sys.path:
    sys.path.insert(0, _THIS_DIR)

from models import Violation
from scanners import iter_python_files, should_skip_path

# Resolve /treesitter run.sh path
_SKILLS_DIR = Path(__file__).resolve().parent.parent
_TREESITTER_RUN = _SKILLS_DIR / "treesitter" / "run.sh"


def _run_treesitter_violations(
    skill_dir: Path,
    rules: list[str],
) -> list[dict[str, Any]]:
    """Call /treesitter violations for specific rules and return parsed results."""
    cmd = [
        str(_TREESITTER_RUN), "violations", str(skill_dir),
        "--rules", ",".join(rules), "--json",
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60,
            env={k: v for k, v in os.environ.items() if k != 'VIRTUAL_ENV'},
        )
        if result.stdout.strip():
            return json.loads(result.stdout)
        return []
    except (subprocess.TimeoutExpired, json.JSONDecodeError, OSError):
        return []


# Skills that ARE prompt management tools — exempt from inline prompt detection
_PROMPT_EXEMPT_SKILLS = {
    "prompt-lab", "scillm", "assistant", "create-gpt", "train-convo-steering",
}


def scan_prompt_hygiene(skill_dir: Path) -> List[Violation]:
    """Detect inline LLM prompts in Python files via /treesitter violations.

    Rules:
    - prompt.inline_prompt: string containing LLM prompt patterns.
      Should use /prompt-lab for versioning and evaluation.
    """
    skill_name = skill_dir.name
    if skill_name in _PROMPT_EXEMPT_SKILLS:
        return []

    violations: List[Violation] = []
    for v in _run_treesitter_violations(skill_dir, ["inline-prompt"]):
        file_path = Path(v.get("file", str(skill_dir)))
        if should_skip_path(file_path):
            continue
        violations.append(Violation(
            rule="prompt.inline_prompt",
            severity="error",
            skill=skill_name,
            path=v.get("file", str(skill_dir)),
            message=v.get("message", "Inline LLM prompt — use /prompt-lab"),
        ))
    return violations


# ---------------------------------------------------------------------------
# Scan: blind test enforcement
# ---------------------------------------------------------------------------

_TEST_EXEMPT_SKILLS = {
    "test-lab", "skills-ci", "eval-skills",  # meta-testing tools
}


def scan_blind_test_enforcement(skill_dir: Path) -> List[Violation]:
    """Check that skills use /test-lab for blind adversarial testing.

    Rules:
    - testing.no_blind_tests: skill has Python code but no tests at all
    - testing.handwritten_tests: test_*.py files without test-lab markers
    """
    violations: List[Violation] = []
    skill_name = skill_dir.name

    if skill_name in _TEST_EXEMPT_SKILLS:
        return violations

    test_files = [f for f in skill_dir.rglob("test_*.py") if not should_skip_path(f)]
    has_sanity = (skill_dir / "sanity.sh").exists()

    if not test_files and not has_sanity:
        py_files = list(iter_python_files(skill_dir))
        if len(py_files) > 1:  # more than just __init__.py
            violations.append(Violation(
                rule="testing.no_blind_tests",
                severity="warn",
                skill=skill_name,
                path=str(skill_dir),
                message="Skill has Python code but no tests or sanity.sh — add /test-lab blind tests.",
            ))
        return violations

    for test_file in test_files:
        try:
            content = test_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue

        is_test_lab = any(marker in content for marker in [
            "test-lab", "test_lab", "blind evaluation", "adversarial", "Generated by",
        ])

        if not is_test_lab:
            violations.append(Violation(
                rule="testing.handwritten_tests",
                severity="warn",
                skill=skill_name,
                path=str(test_file),
                message="Test file appears handwritten (no test-lab markers) — agents can game their own tests. Use /test-lab generate.",
                fixable=True,
            ))

    return violations


# ---------------------------------------------------------------------------
# Scan: regex-as-classifier (small scale)
# ---------------------------------------------------------------------------

def scan_regex_classifier(skill_dir: Path) -> List[Violation]:
    """Detect regex used as classifiers/entity extractors via /treesitter violations.

    Rules:
    - regex.classifier_pattern: 3+ regex calls with branching in same function
    """
    skill_name = skill_dir.name

    _REGEX_EXEMPT = {
        "skills-ci", "extractor", "extract-tables", "extract-controls",
        "extract-entities", "extract-html", "taxonomy", "treesitter",
        "review-plan", "prompt-lab", "no-regex-silo",
        # Legitimate pattern matching (not NL classification) — added 2026-03-29
        "code-runner",          # parse file blocks + diff detection from LLM output
        "create-cast",          # infer physical descriptions from script text
        "create-intent-map",    # extract JSON from LLM output
        "create-movie",         # hardware detection (GPU/CPU probing)
        "create-paper",         # citation verification + paper pattern analysis
        "create-peer-review",   # benchmark metric extraction
        "create-storyboard",    # extract unknown techniques from research
        "cui-marker",           # CUI pattern verification
        "debug-pdf",            # PDF structure analysis
        "doc2qra",              # PDF preflight checks
        "figure-lab",           # HTML evaluation + distance-aware checks
        "formalize-request",    # structural ambiguity detection
        "ingest-yt-history",    # ISO duration parsing
        "interview",            # structural ambiguity detection
        "memory",               # audiobook chunking + lore ingestion
        "ops-darpa",            # DARPA opportunity analysis
        "ops-runpod",           # training progress parsing from logs
        "plan",                 # design pipeline validation
        "project-state",        # best practices collection
        "reality-check-sparta", # URL/file alignment + technique extraction
        "review-code",          # diff parsing
        "sparta-stress-test",   # entity feature extraction + quality scoring
        "test-lab",             # skill/react file structure checks
        "train-persona",        # trace complexity computation
    }
    if skill_name in _REGEX_EXEMPT:
        return []

    violations: List[Violation] = []
    for v in _run_treesitter_violations(skill_dir, ["regex-classifier"]):
        violations.append(Violation(
            rule="regex.classifier_pattern",
            severity="warn",
            skill=skill_name,
            path=v.get("file", str(skill_dir)),
            message=v.get("message", "Regex classifier pattern — use /taxonomy or /extract-entities"),
        ))
    return violations


# ---------------------------------------------------------------------------
# Scan: AQL in shell scripts
# ---------------------------------------------------------------------------

def scan_shell_aql(skill_dir: Path) -> List[Violation]:
    """Detect raw AQL queries in shell scripts.

    Rules:
    - subprocess.shell_aql: AQL in .sh files — must use /memory endpoints.

    The AQL keyword regex matches per-line (no DOTALL) to avoid false
    positives from Python ``for x in y`` loops inside heredocs.  Lines
    containing ``# skills-ci-exempt: shell_aql`` are skipped.
    """
    violations: List[Violation] = []
    skill_name = skill_dir.name

    _AQL_EXCEPTIONS = {"monitor-memory", "ops-arango", "monitor-personas"}
    if skill_name in _AQL_EXCEPTIONS:
        return violations

    # AQL pattern: FOR <var> IN <collection> ... FILTER/RETURN/COLLECT/SORT
    # on a single line.  Case-sensitive FOR/IN to avoid matching Python/bash.
    _AQL_LINE_RE = re.compile(
        r"FOR\s+\w+\s+IN\s+\w+.*(?:FILTER|RETURN|COLLECT|SORT)"
    )
    _EXEMPT_RE = re.compile(r"#\s*skills-ci-exempt:\s*shell_aql")

    for sh_file in skill_dir.rglob("*.sh"):
        if should_skip_path(sh_file):
            continue
        try:
            text = sh_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue

        # Check for file-level exemption (anywhere in the file)
        if _EXEMPT_RE.search(text):
            continue

        # Per-line AQL keyword check (case-sensitive — AQL uses uppercase)
        for line in text.splitlines():
            if _EXEMPT_RE.search(line):
                continue
            if _AQL_LINE_RE.search(line):
                violations.append(Violation(
                    rule="subprocess.shell_aql",
                    severity="warn",
                    skill=skill_name,
                    path=str(sh_file),
                    message="Shell script contains AQL query — use /memory skill endpoints instead.",
                ))
                break  # one violation per file is enough

        if re.search(r"arangosh|_api/cursor|_api/gharial", text):
            violations.append(Violation(
                rule="subprocess.shell_aql",
                severity="warn",
                skill=skill_name,
                path=str(sh_file),
                message="Shell script calls ArangoDB API directly — use /memory skill endpoints.",
            ))

    return violations


# ---------------------------------------------------------------------------
# Scan: SKILL.md bloat
# ---------------------------------------------------------------------------

_SKILLMD_WARN_LINES = 500


def scan_skill_md_length(skill_dir: Path) -> List[Violation]:
    """Detect bloated SKILL.md files that should be split.

    Rules:
    - skills.skill_md_bloat: SKILL.md > 500 lines. Move rules to best-practices-*.
    """
    violations: List[Violation] = []
    skill_md = skill_dir / "SKILL.md"

    if not skill_md.exists():
        return violations

    try:
        line_count = len(skill_md.read_text(encoding="utf-8", errors="ignore").splitlines())
    except Exception:
        return violations

    if line_count > _SKILLMD_WARN_LINES:
        violations.append(Violation(
            rule="skills.skill_md_bloat",
            severity="warn",
            skill=skill_dir.name,
            path=str(skill_md),
            message=f"SKILL.md is {line_count} lines (limit {_SKILLMD_WARN_LINES}). Move rules to best-practices-* skill.",
        ))

    return violations


# ---------------------------------------------------------------------------
# Scan: hardcoded skill paths
# ---------------------------------------------------------------------------

def scan_hardcoded_skill_paths(skill_dir: Path) -> List[Violation]:
    """Detect hardcoded ~/.pi/skills/ paths that break in non-standard layouts.

    Rules:
    - subprocess.hardcoded_skill_path: use SKILLS_DIR env var instead.
    """
    violations: List[Violation] = []
    skill_name = skill_dir.name

    _PATH_EXEMPT = {"skills-ci", "skills-broadcast", "skill-lab"}
    if skill_name in _PATH_EXEMPT:
        return violations

    for py_file in iter_python_files(skill_dir):
        try:
            text = py_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue

        if re.search(r'["\']~?/\.pi/skills/|HOME.*\.pi/skills|home/.*\.pi/skills', text):
            violations.append(Violation(
                rule="subprocess.hardcoded_skill_path",
                severity="warn",
                skill=skill_name,
                path=str(py_file),
                message="Hardcoded ~/.pi/skills/ path — use SKILLS_DIR env var with fallback.",
            ))
            break

    for sh_file in skill_dir.rglob("*.sh"):
        if should_skip_path(sh_file):
            continue
        try:
            text = sh_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue

        if re.search(r'\$HOME/\.pi/skills/|~/\.pi/skills/', text):
            if "SKILLS_DIR" not in text:
                violations.append(Violation(
                    rule="subprocess.hardcoded_skill_path",
                    severity="warn",
                    skill=skill_name,
                    path=str(sh_file),
                    message="Hardcoded ~/.pi/skills/ path — use ${SKILLS_DIR:-$HOME/.pi/skills}.",
                ))
                break

    return violations


# ---------------------------------------------------------------------------
# Scan: mock-only tests (no integration)
# ---------------------------------------------------------------------------

def scan_mock_only_tests(skill_dir: Path) -> List[Violation]:
    """Detect skills where ALL tests use mocks with no integration tests.

    Rules:
    - testing.mock_only: every test uses mocks, no sanity.sh exists.
    """
    violations: List[Violation] = []
    skill_name = skill_dir.name

    _MOCK_EXEMPT = {"test-lab", "skills-ci", "eval-skills"}
    if skill_name in _MOCK_EXEMPT:
        return violations

    test_files = [f for f in skill_dir.rglob("test_*.py") if not should_skip_path(f)]
    if not test_files:
        return violations

    has_sanity = (skill_dir / "sanity.sh").exists()
    all_mocked = True

    for test_file in test_files:
        try:
            content = test_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue

        uses_mock = any(p in content for p in [
            "unittest.mock", "MagicMock", "AsyncMock", "@patch", "mock.patch",
        ])
        if not uses_mock:
            all_mocked = False
            break

    if all_mocked and not has_sanity:
        violations.append(Violation(
            rule="testing.mock_only",
            severity="warn",
            skill=skill_name,
            path=str(skill_dir),
            message="All tests use mocks but no sanity.sh — mocked tests pass while real service may be broken.",
        ))

    return violations
