# Generated by test-lab — blind adversarial evaluation
"""
Tests for grounding_checker.py with good and bad fixtures.

These tests help tune thresholds:
- min_sentence_token_overlap (default 0.45)
- min_sentence_quote_jaccard (default 0.20)
- redundancy_threshold (default 0.72)
"""
import pytest

from grounding_checker import (
    CheckerConfig,
    run_grounding_checks,
    check_sentence_support,
    check_pair_usefulness,
    check_redundancy,
    content_tokens,
    jaccard_similarity,
    overlap_ratio,
    format_grounding_report,
)
from qra_schema import QRAResult, QRAPair, EvidenceItem, PairType, ActionableFor, Confidence, EvidenceField


def make_pair(
    pair_id: str,
    pair_type: str,
    question: str,
    reasoning: str,
    answer: str,
    evidence: list[dict],
    actionable_for: list[str] | None = None,
    confidence: str = "high",
) -> QRAPair:
    """Helper to build QRAPair."""
    return QRAPair(
        pair_id=pair_id,
        pair_type=PairType(pair_type),
        actionable_for=[ActionableFor(a) for a in (actionable_for or ["vulnerability_assessment"])],
        question=question,
        reasoning=reasoning,
        answer=answer,
        confidence=Confidence(confidence),
        evidence=[
            EvidenceItem(field=EvidenceField(e["field"]), quote=e["quote"])
            for e in evidence
        ],
    )


def make_result(pairs: list[QRAPair]) -> QRAResult:
    """Helper to build QRAResult."""
    return QRAResult(
        source_framework="CWE",
        source_id="CWE-119",
        pair_count=len(pairs),
        abstained=False,
        pairs=pairs,
    )


# ---------------------------------------------------------------------
# Good fixtures: should pass grounding checks
# ---------------------------------------------------------------------

class TestGoodGrounding:
    """QRA pairs that should pass grounding checks."""

    def test_well_grounded_scope_clarification(self):
        """Reasoning and answer closely match evidence quotes."""
        pair = make_pair(
            pair_id="CWE-119-QRA-1",
            pair_type="scope_clarification",
            question="What kinds of memory operations are covered by CWE-119?",
            reasoning="The description defines the weakness as operations on a memory buffer that read from or write to a memory location outside the buffer's intended boundary.",
            answer="CWE-119 covers operations on a memory buffer where the product reads from or writes to a memory location outside the buffer's intended boundary.",
            evidence=[
                {
                    "field": "description",
                    "quote": "The product performs operations on a memory buffer, but it reads from or writes to a memory location outside the buffer's intended boundary.",
                }
            ],
        )
        result = make_result([pair])
        report = run_grounding_checks(result)

        assert report.passed, f"Expected pass but got errors: {report.errors}"
        assert report.pair_checks[0].passed

    def test_well_grounded_risk_context(self):
        """Risk context with multiple evidence quotes."""
        pair = make_pair(
            pair_id="CWE-119-QRA-2",
            pair_type="risk_context",
            question="Why is CWE-119 a serious security risk?",
            reasoning="The record states that out-of-bounds memory access can lead to arbitrary code execution and the likelihood of exploit is high.",
            answer="CWE-119 is a serious security risk because it may be possible to execute arbitrary code. The likelihood of exploit is high.",
            evidence=[
                {
                    "field": "likelihood_of_exploit",
                    "quote": "High",
                },
                {
                    "field": "common_consequences",
                    "quote": "If the memory accessible by the attacker can be effectively controlled, it may be possible to execute arbitrary code.",
                },
            ],
        )
        result = make_result([pair])
        report = run_grounding_checks(result)

        assert report.passed, f"Expected pass but got errors: {report.errors}"

    def test_well_grounded_implementation_guidance(self):
        """Implementation guidance directly from mitigations."""
        pair = make_pair(
            pair_id="CWE-119-QRA-3",
            pair_type="implementation_guidance",
            question="How should a developer mitigate CWE-119?",
            reasoning="The mitigation section recommends using languages that make the weakness easier to avoid and replacing unbounded copy functions with bounded alternatives.",
            answer="A developer should mitigate CWE-119 by using a language that does not allow this weakness to occur and replacing unbounded copy functions with analogous functions that support length arguments.",
            actionable_for=["implementation"],
            evidence=[
                {
                    "field": "potential_mitigations",
                    "quote": "Use a language that does not allow this weakness to occur or provides constructs that make this weakness easier to avoid.",
                },
                {
                    "field": "potential_mitigations",
                    "quote": "Replace unbounded copy functions with analogous functions that support length arguments, such as strcpy with strncpy.",
                },
            ],
        )
        result = make_result([pair])
        report = run_grounding_checks(result)

        assert report.passed, f"Expected pass but got errors: {report.errors}"


# ---------------------------------------------------------------------
# Bad fixtures: should fail grounding checks
# ---------------------------------------------------------------------

class TestBadGrounding:
    """QRA pairs that should fail grounding checks."""

    def test_answer_introduces_unsupported_claims(self):
        """Answer makes claims not in evidence."""
        pair = make_pair(
            pair_id="CWE-119-QRA-1",
            pair_type="risk_context",
            question="Why is CWE-119 dangerous in embedded systems?",
            reasoning="The record mentions memory buffer operations.",
            # This answer introduces "embedded systems", "real-time", "RTOS" - not in evidence
            answer="CWE-119 is particularly dangerous in embedded systems because real-time operating systems often lack memory protection, making buffer overflows easier to exploit in RTOS environments.",
            evidence=[
                {
                    "field": "description",
                    "quote": "The product performs operations on a memory buffer.",
                }
            ],
        )
        result = make_result([pair])
        report = run_grounding_checks(result)

        # Should fail because answer introduces many tokens not in evidence
        assert not report.passed, "Expected failure for unsupported claims"

    def test_reasoning_adds_new_mechanisms(self):
        """Reasoning invents mechanisms not stated in evidence."""
        pair = make_pair(
            pair_id="CWE-119-QRA-1",
            pair_type="scope_clarification",
            question="What mechanisms cause CWE-119 in practice?",
            # Reasoning invents "stack smashing", "heap spraying", "return-oriented programming"
            reasoning="CWE-119 is typically caused by stack smashing attacks, heap spraying techniques, and return-oriented programming exploits that manipulate memory layouts.",
            answer="Buffer overflows occur when memory boundaries are exceeded.",
            evidence=[
                {
                    "field": "description",
                    "quote": "reads from or writes to a memory location outside the buffer's intended boundary",
                }
            ],
        )
        result = make_result([pair])
        report = run_grounding_checks(result)

        # Should flag reasoning as unsupported
        unsupported_reasoning = [
            c for c in report.pair_checks[0].reasoning_checks if not c.supported
        ]
        assert len(unsupported_reasoning) > 0, "Expected unsupported reasoning sentences"

    def test_generic_question_no_cwe_specifics(self):
        """Question and answer are too generic."""
        pair = make_pair(
            pair_id="CWE-119-QRA-1",
            pair_type="risk_context",
            question="What is CWE-119 and why does it matter?",
            reasoning="Security vulnerabilities can cause problems.",
            answer="Security issues can lead to system compromise and data breaches.",
            evidence=[
                {
                    "field": "description",
                    "quote": "memory buffer",
                }
            ],
        )
        result = make_result([pair])
        report = run_grounding_checks(result)

        # Should have usefulness warnings about genericness
        warnings = report.pair_checks[0].usefulness_warnings
        assert any("generic" in w.lower() for w in warnings), f"Expected genericness warning, got: {warnings}"


# ---------------------------------------------------------------------
# Redundancy tests
# ---------------------------------------------------------------------

class TestRedundancy:
    """Test redundancy detection between pairs."""

    def test_near_duplicate_questions_flagged(self):
        """Two questions that are paraphrases should be flagged."""
        pair1 = make_pair(
            pair_id="CWE-119-QRA-1",
            pair_type="scope_clarification",
            question="What memory operations does CWE-119 cover?",
            reasoning="The description defines memory buffer operations.",
            answer="CWE-119 covers read and write operations on memory buffers.",
            evidence=[{"field": "description", "quote": "operations on a memory buffer"}],
        )
        pair2 = make_pair(
            pair_id="CWE-119-QRA-2",
            pair_type="scope_clarification",
            question="Which memory operations are covered by CWE-119?",
            reasoning="The weakness involves memory buffer operations.",
            answer="CWE-119 involves read and write operations on memory buffers.",
            evidence=[{"field": "description", "quote": "operations on a memory buffer"}],
        )
        result = make_result([pair1, pair2])
        report = run_grounding_checks(result)

        # Should flag redundancy
        flagged = [r for r in report.redundancy_checks if r.flagged]
        assert len(flagged) > 0, "Expected redundancy flag for near-duplicate questions"

    def test_distinct_pairs_not_flagged(self):
        """Two genuinely different pairs should not be flagged."""
        pair1 = make_pair(
            pair_id="CWE-119-QRA-1",
            pair_type="scope_clarification",
            question="What memory operations does CWE-119 cover?",
            reasoning="The description defines memory buffer operations.",
            answer="CWE-119 covers read and write operations on memory buffers.",
            evidence=[{"field": "description", "quote": "operations on a memory buffer"}],
        )
        pair2 = make_pair(
            pair_id="CWE-119-QRA-2",
            pair_type="implementation_guidance",
            question="How should developers prevent CWE-119 vulnerabilities?",
            reasoning="The mitigations recommend using safe languages and bounded functions.",
            answer="Developers should use memory-safe languages and replace unbounded copy functions with strncpy.",
            actionable_for=["implementation"],
            evidence=[{"field": "potential_mitigations", "quote": "Replace unbounded copy functions with analogous functions that support length arguments"}],
        )
        result = make_result([pair1, pair2])
        report = run_grounding_checks(result)

        flagged = [r for r in report.redundancy_checks if r.flagged]
        assert len(flagged) == 0, f"Expected no redundancy flags, got: {flagged}"


# ---------------------------------------------------------------------
# Threshold tuning tests
# ---------------------------------------------------------------------

class TestThresholdTuning:
    """Tests to help tune checker thresholds."""

    def test_token_overlap_calculation(self):
        """Verify token overlap behaves as expected."""
        # High overlap case
        sentence = "reads from or writes to memory location outside boundary"
        quote = "reads from or writes to a memory location outside the buffer's intended boundary"

        sent_tokens = content_tokens(sentence)
        quote_tokens = content_tokens(quote)
        overlap = overlap_ratio(sent_tokens, quote_tokens)

        # Should have high overlap since most sentence tokens are in quote
        assert overlap > 0.7, f"Expected high overlap, got {overlap}"

    def test_jaccard_similarity_calculation(self):
        """Verify Jaccard similarity behaves as expected."""
        set_a = {"memory", "buffer", "operations", "read", "write"}
        set_b = {"memory", "buffer", "boundary", "overflow"}

        sim = jaccard_similarity(set_a, set_b)
        # Intersection: memory, buffer (2)
        # Union: memory, buffer, operations, read, write, boundary, overflow (7)
        # Jaccard = 2/7 ≈ 0.286
        assert 0.25 < sim < 0.35, f"Expected ~0.286, got {sim}"

    def test_relaxed_config_passes_borderline(self):
        """A relaxed config should pass borderline cases."""
        relaxed = CheckerConfig(
            min_sentence_token_overlap=0.30,  # Lower than default 0.45
            min_sentence_quote_jaccard=0.15,   # Lower than default 0.20
        )

        pair = make_pair(
            pair_id="CWE-119-QRA-1",
            pair_type="risk_context",
            question="What are the consequences of CWE-119?",
            # Reasoning has some overlap but introduces synthesis
            reasoning="Memory operations outside intended boundaries can corrupt data and crash systems.",
            answer="Out-of-bounds memory access leads to crashes and data corruption.",
            evidence=[
                {"field": "description", "quote": "memory location outside the buffer's intended boundary"},
                {"field": "common_consequences", "quote": "corruption of relevant memory, possibly leading to a crash"},
            ],
        )
        result = make_result([pair])

        # Default config might fail
        default_report = run_grounding_checks(result)

        # Relaxed config should pass
        relaxed_report = run_grounding_checks(result, config=relaxed)

        # At minimum, relaxed should have fewer failures
        default_unsupported = sum(
            1 for c in default_report.pair_checks[0].reasoning_checks + default_report.pair_checks[0].answer_checks
            if not c.supported
        )
        relaxed_unsupported = sum(
            1 for c in relaxed_report.pair_checks[0].reasoning_checks + relaxed_report.pair_checks[0].answer_checks
            if not c.supported
        )

        assert relaxed_unsupported <= default_unsupported, "Relaxed config should not be stricter"


# ---------------------------------------------------------------------
# Format report test
# ---------------------------------------------------------------------

class TestFormatReport:
    """Test report formatting."""

    def test_format_passing_report(self):
        """Format a passing report."""
        pair = make_pair(
            pair_id="CWE-119-QRA-1",
            pair_type="scope_clarification",
            question="What does CWE-119 cover?",
            reasoning="The description states memory buffer operations.",
            answer="CWE-119 covers memory buffer operations outside intended boundaries.",
            evidence=[{"field": "description", "quote": "operations on a memory buffer"}],
        )
        result = make_result([pair])
        report = run_grounding_checks(result)

        formatted = format_grounding_report(report)
        assert "passed=" in formatted
        assert "CWE-119-QRA-1" in formatted
