# Generated by test-lab — blind adversarial evaluation
"""Reviewer publication hook: fires for ANY first published answer.

Regression guard (2026-08-31 live incident): the hook originally existed only
on the fast-solver branch, so oracle/summarizer-answered cards (the DriveWealth
path) were never reviewed - 0 answer_review journal rows across a full replay.
"""

from __future__ import annotations

import json

import pytest

from live_evidence.config import AppSettings, InterviewProfile
from live_evidence.coordinator import EvidenceCoordinator
from live_evidence.persistence import SessionJournal
from live_evidence.reviewer import ReviewOutcome
from live_evidence.state import RuntimeState


@pytest.mark.asyncio
async def test_review_hook_labels_weak_and_records_journal(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("LIVE_EVIDENCE_DATA_DIR", str(tmp_path))
    settings = AppSettings.from_env()
    profile = InterviewProfile(name="review-hook-test")
    state = RuntimeState(settings, profile)
    await state.start_session(consent_confirmed=True)
    journal = SessionJournal(tmp_path)
    coordinator = EvidenceCoordinator(settings, profile, state, journal)

    # Publish a card the normal way so update_card_fields can find it.
    question_id, revision = await state.adopt_question("q_review_hook", "Propose a rollout")
    from live_evidence.models import EvidenceCard, EvidenceSource, Freshness, RetrievalLane

    card = EvidenceCard(
        card_id="card-review-hook",
        query="Propose a rollout",
        thread="review · hook",
        question="Propose a rollout",
        answer="A long prose answer.",
        talking_point="tp",
        proof="proof",
        qualifier="verified against fixture",
        confidence=0.9,
        status="supported",
        sources=[EvidenceSource(
            source_id="src-review-hook", lane=RetrievalLane.MEMORY, label="label",
            excerpt="excerpt", score=1.0, path="/tmp/review-hook-source.md",
            freshness=Freshness.CURRENT, metadata={},
        )],
        lanes=[RetrievalLane.MEMORY],
        clarifications=[],
        question_id=question_id,
        question_revision=revision,
    )
    snapshot = await state.publish_card_fenced(card)
    assert snapshot is not None

    def fake_review(self, question, answer, transcript_after, *, evidence_excerpts=None):  # noqa: ANN001
        return ReviewOutcome(
            verdict="weak",
            reasons=("SCANNABILITY: prose_line long prose answer",),
            amendment_instruction="Rewrite as bullets.",
            deterministic=True,
        )

    monkeypatch.setattr("live_evidence.reviewer.AnswerReviewer.review", fake_review)

    async def no_amendment(*args, **kwargs):  # noqa: ANN002, ANN003 - isolate the hook
        return None

    monkeypatch.setattr(
        "live_evidence.coordinator.asyncio.to_thread",
        lambda fn, *a, **k: _immediate(fn, *a, **k),
    )

    await coordinator._review_published_answer(
        card_id=card.card_id,
        question="Propose a rollout",
        answer="A long prose answer.",
        question_id=question_id,
        question_revision=revision,
        evidence_excerpts=[],
    )

    refreshed = await state.snapshot()
    reviewed = next(c for c in refreshed.cards if c.card_id == card.card_id)
    assert reviewed.review_verdict == "weak"
    assert reviewed.review_reasons and "SCANNABILITY" in reviewed.review_reasons[0]

    session_id = state.session_id()
    rows = []
    for path in tmp_path.glob(f"**/{session_id}*/*.jsonl"):
        rows.extend(json.loads(line) for line in path.read_text().splitlines() if line.strip())
    if not rows:
        for path in tmp_path.glob("**/*.jsonl"):
            rows.extend(json.loads(line) for line in path.read_text().splitlines() if line.strip())
    kinds = [row.get("kind") for row in rows]
    assert "answer_review" in kinds


async def _immediate(fn, *args, **kwargs):  # noqa: ANN002, ANN003
    return fn(*args, **kwargs)
