# Generated by test-lab — blind adversarial evaluation
"""Regression tests for transcript-meeting answer-quality scoring."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import eval_transcript_meeting as etm  # noqa: E402
from eval_transcript_meeting import _card_for  # noqa: E402


def test_judge_similarity_returns_fail_closed_on_timeout(monkeypatch) -> None:
    def boom(*args, **kwargs):
        raise TimeoutError("timed out")

    monkeypatch.setattr(etm.urllib.request, "urlopen", boom)

    verdict = etm.judge_similarity("q", "expected", "answer", "evidence", "key")

    assert verdict["similar"] is False
    assert verdict["reason"].startswith("judge_error:TimeoutError")


def test_card_for_prefers_exact_answer_key_over_generic_coding_card() -> None:
    tokens = ["coding", "minutes"]
    wrong = {
        "query": "Live coding. You have ten minutes. Implement another function.",
        "answer": "A long answer for a different coding question.",
        "sources": [{"metadata": {"answer_key_id": "DW-AI-04-T03"}, "label": "wrong"}],
    }
    right = {
        "query": "Live coding. You have ten minutes. Implement decide_next.",
        "answer": "The decide_next answer.",
        "sources": [{"metadata": {"answer_key_id": "DW-AI-01-T03"}, "label": "right"}],
    }

    assert _card_for([wrong, right], tokens, "DW-AI-01-T03") is right


def test_card_for_prefers_latest_answer_bearing_card_over_initial_echo() -> None:
    tokens = ["decide_next", "retrieval", "fail_closed"]
    draft = {
        "query": "Implement decide_next with retrieval_count and fail_closed.",
        "question": "Implement decide_next with retrieval_count and fail_closed.",
        "answer": "Answer key: DW-AI-01-T03 Q: Implement decide_next with retrieval_count.",
    }
    final = {
        "query": "Implement decide_next with retrieval_count and fail_closed.",
        "question": "Implement decide_next with retrieval_count and fail_closed.",
        "answer": "Use a typed state machine: fail_closed on tool_error or exhausted retries, ask_human when human_required, retrieve_again below confidence, answer only with support.",
    }

    assert _card_for([draft, final], tokens) is final
