"""Tests for proposal-first monitor-codebase docstring remediation."""

from __future__ import annotations

import importlib.util
import json
import sys
import textwrap
from pathlib import Path

import pytest

MODULE_PATH = Path(__file__).resolve().parents[1] / "autofix_docstrings.py"
SPEC = importlib.util.spec_from_file_location("autofix_docstrings", MODULE_PATH)
assert SPEC and SPEC.loader
autofix_docstrings = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = autofix_docstrings
SPEC.loader.exec_module(autofix_docstrings)


def write_module(root: Path, rel: str, text: str) -> Path:
    """Write a Python fixture module."""
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(text).lstrip(), encoding="utf-8")
    return path


def candidates_for(root: Path, path: Path, include_optional: bool = False) -> list[dict]:
    """Return candidates for a fixture file."""
    return autofix_docstrings.scan_file(root, path, include_optional=include_optional)


def by_name(candidates: list[dict], name: str) -> dict:
    """Return one candidate by qualified name."""
    for candidate in candidates:
        if candidate["symbol"]["qualified_name"] == name:
            return candidate
    raise AssertionError(f"missing candidate {name}; got {[c['symbol']['qualified_name'] for c in candidates]}")


def approve(candidate: dict, docstring: str) -> dict:
    """Return an approved candidate with static unsupported claims cleared."""
    result = json.loads(json.dumps(candidate))
    result["approval"] = {"status": "approved", "approved_by": "tests"}
    result["proposed_docstring"] = docstring
    result["contract"]["unsupported_claims"] = []
    return result


def test_public_api_missing_docstring_is_required(tmp_path: Path) -> None:
    source = write_module(
        tmp_path,
        "api.py",
        """
        def load_user(user_id):
            return {"id": user_id}
        """,
    )
    candidate = by_name(candidates_for(tmp_path, source), "load_user")
    assert candidate["documentation_need"] == "required"
    assert "public_api" in candidate["documentation_need_reasons"]
    assert candidate["proposed_docstring"] == ""


def test_complex_private_function_is_recommended(tmp_path: Path) -> None:
    source = write_module(
        tmp_path,
        "worker.py",
        """
        def _shape(items):
            total = 0
            for item in items:
                if item:
                    total += item
            return total
        """,
    )
    candidate = by_name(candidates_for(tmp_path, source), "_shape")
    assert candidate["documentation_need"] == "recommended"
    assert "complex_private_logic" in candidate["documentation_need_reasons"]


def test_trivial_private_helper_is_optional_and_hidden_by_default(tmp_path: Path) -> None:
    source = write_module(tmp_path, "helpers.py", "def _id(value):\n    return value\n")
    assert [c["symbol"]["qualified_name"] for c in candidates_for(tmp_path, source)] == ["<module>"]
    candidate = by_name(candidates_for(tmp_path, source, include_optional=True), "_id")
    assert candidate["documentation_need"] == "optional"


def test_test_function_boundary_is_optional(tmp_path: Path) -> None:
    source = write_module(tmp_path, "tests/test_api.py", "def test_round_trip():\n    assert True\n")
    candidate = by_name(candidates_for(tmp_path, source, include_optional=True), "test_round_trip")
    assert candidate["documentation_need"] == "optional"
    assert "test_symbol" in candidate["documentation_need_reasons"]


def test_generated_file_is_exempt(tmp_path: Path) -> None:
    source = write_module(
        tmp_path,
        "generated/client.py",
        """
        # Generated by tool
        def generated_client():
            return None
        """,
    )
    candidate = by_name(candidates_for(tmp_path, source, include_optional=True), "generated_client")
    assert candidate["documentation_need"] == "exempt"
    assert candidate["status"] == "exempt"


def test_multiline_signature_and_decorator_apply_preserves_ast(tmp_path: Path) -> None:
    source = write_module(
        tmp_path,
        "decorated.py",
        """
        def deco(fn):
            return fn

        @deco
        def public_api(
            first,
            second,
        ):
            return first + second
        """,
    )
    candidate = approve(by_name(candidates_for(tmp_path, source), "public_api"), "Return the combined value.")
    receipt = autofix_docstrings.apply_candidate(tmp_path, candidate)
    assert receipt["applied"] is True
    assert '"""Return the combined value."""' in source.read_text(encoding="utf-8")


def test_nested_function_and_class_are_addressable(tmp_path: Path) -> None:
    source = write_module(
        tmp_path,
        "nested.py",
        """
        class Outer:
            def method(self, value):
                def inner(extra):
                    return value + extra
                return inner(1)
        """,
    )
    candidates = candidates_for(tmp_path, source)
    assert by_name(candidates, "Outer")["symbol"]["symbol_kind"] == "class"
    assert by_name(candidates, "Outer.method")["symbol"]["symbol_kind"] == "function"
    assert by_name(candidates, "Outer.method.inner")["symbol"]["symbol_kind"] == "function"


def test_stale_proposal_after_source_edit_is_rejected(tmp_path: Path) -> None:
    source = write_module(tmp_path, "api.py", "def load_user(user_id):\n    return user_id\n")
    candidate = approve(by_name(candidates_for(tmp_path, source), "load_user"), "Return the user identifier.")
    source.write_text("def load_user(user_id):\n    return str(user_id)\n", encoding="utf-8")
    receipt = autofix_docstrings.apply_candidate(tmp_path, candidate)
    assert receipt["applied"] is False
    assert "stale_source_hash" in receipt["errors"]
    assert '"""' not in source.read_text(encoding="utf-8")


def test_model_outage_or_malformed_response_makes_no_change(tmp_path: Path) -> None:
    source = write_module(tmp_path, "api.py", "def load_user(user_id):\n    return user_id\n")
    candidate = by_name(candidates_for(tmp_path, source), "load_user")
    candidate["approval"] = {"status": "approved"}
    receipt = autofix_docstrings.apply_candidate(tmp_path, candidate)
    assert receipt["applied"] is False
    assert "missing_proposed_docstring" in receipt["errors"]
    assert '"""' not in source.read_text(encoding="utf-8")


def test_unsupported_claim_is_rejected(tmp_path: Path) -> None:
    source = write_module(tmp_path, "security.py", "def write_file(path, value):\n    path.write_text(value)\n")
    candidate = approve(by_name(candidates_for(tmp_path, source), "write_file"), "Safely write the file atomically.")
    receipt = autofix_docstrings.apply_candidate(tmp_path, candidate)
    assert receipt["applied"] is False
    assert "unsupported_claim_in_docstring" in receipt["errors"]


def test_return_yield_raise_mismatch_is_rejected(tmp_path: Path) -> None:
    source = write_module(tmp_path, "api.py", "def notify(user_id):\n    print(user_id)\n")
    candidate = approve(by_name(candidates_for(tmp_path, source), "notify"), "Return notification status.")
    candidate["contract"]["returns"] = {"returns_value": True}
    receipt = autofix_docstrings.apply_candidate(tmp_path, candidate)
    assert receipt["applied"] is False
    assert "return_claim_without_return" in receipt["errors"]


def test_ast_changing_patch_attempt_rolls_back(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source = write_module(tmp_path, "api.py", "def load_user(user_id):\n    return user_id\n")
    candidate = approve(by_name(candidates_for(tmp_path, source), "load_user"), "Return the user identifier.")
    monkeypatch.setattr(autofix_docstrings, "docstring_line", lambda _docstring, indent: f"{indent}x = 1\n")
    receipt = autofix_docstrings.apply_candidate(tmp_path, candidate)
    assert receipt["applied"] is False
    assert any("non_docstring_ast_changed" in error for error in receipt["errors"])
    assert "x = 1" not in source.read_text(encoding="utf-8")
