# Generated by test-lab — blind adversarial evaluation
"""CLI dry-run coverage for delegate envelope artifacts."""

from __future__ import annotations

import json

from typer.testing import CliRunner

import ask.ask as ask_module


def test_delegate_dry_run_writes_envelope_artifacts(tmp_path):
    result = CliRunner().invoke(
        ask_module.app,
        [
            "$code-reviewer",
            "to",
            "review",
            "src/foo.rs",
            "with",
            "$review-code",
            "--delegate-dry-run",
            "--ask-id",
            "delegate-cli-code-reviewer",
            "--run-output-root",
            str(tmp_path),
            "--overwrite",
            "--json",
        ],
    )

    assert result.exit_code == 0, result.output
    payload = json.loads(result.stdout)
    assert payload["delegate"]["schema"] == "agent_skills.delegate.v1"
    assert payload["delegate"]["actor"]["id"] == "code-reviewer"
    assert payload["delegate"]["actor"]["kind"] == "agent"
    assert payload["delegate"]["runtime"]["selected"] == "opencode_serve"

    run_dir = tmp_path / "delegate-cli-code-reviewer"
    request = json.loads((run_dir / "delegate-cli-code-reviewer.request.json").read_text())
    status = json.loads((run_dir / "delegate-cli-code-reviewer.status.json").read_text())
    events = (run_dir / "delegate-cli-code-reviewer.events.jsonl").read_text()
    assert request["delegate_dry_run"] is True
    assert request["orchestrate"] is False
    assert request["route_decision"]["selected_mode"] == "delegate_dry_run"
    assert request["route_decision"]["selected_backend"] == "delegate"
    assert "dag_orchestration_clarification" not in request
    assert request["delegate"]["actor"]["source_kind"] == "worker"
    assert request["delegate"]["invocation_id"] == "delegate-cli-code-reviewer"
    assert request["delegate"]["caller"] == {"type": "agent", "id": "ask-cli"}
    assert request["delegate"]["skills"][0]["version_or_digest"].startswith("sha256:")
    assert request["delegate"]["override_policy"]["skill_composition"] == "strict"
    assert request["delegate"]["override_policy"]["prompt_level_override_allowed"] is False
    assert request["delegate"]["receipt_requirements"] == {
        "preserve_invocation_id": True,
        "preserve_caller": True,
        "preserve_actor_id": True,
        "preserve_skill_ids": True,
        "preserve_skill_versions_or_digests": True,
        "include_target": True,
        "include_mode": True,
        "include_runtime": True,
        "include_override_policy": True,
        "include_materialized_skill_bundle": True,
        "include_artifact_paths": True,
    }
    assert status["request"]["delegate"]["receipt_requirements"] == request["delegate"]["receipt_requirements"]
    assert status["state"] == "completed"
    assert "delegate_resolved" in events


def test_delegate_dry_run_fails_closed_with_artifacts(tmp_path):
    result = CliRunner().invoke(
        ask_module.app,
        [
            "$missing-agent",
            "to",
            "review",
            "src/foo.rs",
            "--delegate-dry-run",
            "--ask-id",
            "delegate-cli-missing-agent",
            "--run-output-root",
            str(tmp_path),
            "--overwrite",
            "--json",
        ],
    )

    assert result.exit_code == 2, result.output
    payload = json.loads(result.stdout)
    assert payload["needs_attention"]["reason"] == "unknown_actor"
    assert payload["needs_attention"]["safe_default"] == "do_not_delegate"

    run_dir = tmp_path / "delegate-cli-missing-agent"
    request = json.loads((run_dir / "delegate-cli-missing-agent.request.json").read_text())
    status = json.loads((run_dir / "delegate-cli-missing-agent.status.json").read_text())
    assert request["delegate_error"]["reason"] == "unknown_actor"
    assert status["state"] == "needs_attention"
