# Generated by test-lab — blind adversarial evaluation
"""Citation normalization regressions."""

from ask.scillm_runtime import CODE_REVIEW_CITATION_KINDS, normalize_citation, validate_citations


def test_bare_target_source_id_normalizes_to_target_bundle_citation():
    citation = normalize_citation("TARGET.1", supports="section")

    assert citation == {
        "source_id": "TARGET.1",
        "source_kind": "target_bundle",
        "quote_or_summary": "TARGET.1",
        "supports": "section",
    }


def test_quote_only_target_source_id_is_admissible_for_code_review():
    citations = [{"quote_or_summary": "TARGET.1", "supports": "finding"}]

    assert validate_citations(
        "finding evidence_citations",
        citations,
        allowed_source_kinds=CODE_REVIEW_CITATION_KINDS,
        require_any=True,
    ) == []
