"""Protocol regression tests for roundtable and parallel review state handling."""

# Generated by test-lab — blind adversarial evaluation
"""test_review_protocols - ask.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from pathlib import Path

from ask.ask_routing import _parse_natural_argue_query, _parse_natural_roundtable_query
from ask.review_protocols import (
    ARGUE_JUDGE_RUBRIC,
    ARGUE_VERDICTS,
    build_argue_prompt_payload,
    default_parallel_participants,
    is_date_sensitive_question,
    normalize_argue_personas,
    parse_argue_verdict_payload,
    parse_participant_specs,
    parse_protocol_turn,
    validate_argue_verdict_payload,
)

ASK_DIR = Path(__file__).resolve().parents[1]


def test_parse_natural_roundtable_query():
    question, personas, inferred = _parse_natural_roundtable_query(
        [
            "Brandon,",
            "Margaret,",
            "and",
            "Jennifer",
            "to",
            "debate",
            "the",
            "relevance",
            "of",
            "Formal",
            "Methods",
            "in",
            "large",
            "scale",
            "aerospace",
            "projects",
            "in",
            "2026",
        ]
    )

    assert inferred is True
    assert personas == "Brandon,Margaret,Jennifer"
    assert question == "the relevance of Formal Methods in large scale aerospace projects in 2026"


def test_parse_natural_argue_query_with_explicit_for_against():
    question, personas, inferred = _parse_natural_argue_query(
        ["Brandon", "argue", "for", "and", "Margaret", "argue", "against", "using", "queues"]
    )

    assert inferred is True
    assert personas == "Brandon:for,Margaret:against"
    assert question == "using queues"


def test_parse_natural_argue_query_with_devil_advocate():
    question, personas, inferred = _parse_natural_argue_query(
        ["devil's", "advocate:", "should", "we", "enable", "deep-review", "by", "default?"]
    )

    assert inferred is True
    assert personas is None
    assert question == "should we enable deep-review by default?"


def test_parse_participant_specs_separates_persona_from_protocol_role():
    participants = parse_participant_specs(
        "Brandon:failure_mode,Margaret:evidence_auditor,Jennifer:complexity_minimizer"
    )

    assert [p["persona"] for p in participants] == ["Brandon", "Margaret", "Jennifer"]
    assert [p["protocol_role"] for p in participants] == [
        "failure_mode",
        "evidence_auditor",
        "complexity_minimizer",
    ]
    assert participants[0]["role_label"] == "Failure Mode Analyst"


def test_normalize_argue_personas_assigns_for_against_roles():
    assert normalize_argue_personas("Brandon,Margaret") == "Brandon:for,Margaret:against"
    assert normalize_argue_personas(None) == "Affirmative:for,Devil's Advocate:against"


def test_argue_prompt_payload_contains_fixed_judge_contract():
    payload = build_argue_prompt_payload(
        base_prompt="Question:\nShould this service use retries or queues?",
        persona_specs="Brandon,Margaret",
        rounds=2,
    )

    assert payload["schema_version"] == "ask.argue.prompt_payload.v1"
    assert payload["personas"] == "Brandon:for,Margaret:against"
    assert payload["judge_rubric"] == list(ARGUE_JUDGE_RUBRIC)
    assert payload["verdicts"] == list(ARGUE_VERDICTS)
    assert len(payload["turn_prompts"]) == 4
    assert "Structured argue protocol:" in payload["turn_prompts"][0]["prompt"]
    assert "Assigned side: FOR Advocate (for)" in payload["turn_prompts"][0]["prompt"]
    assert "Assigned side: AGAINST Advocate (against)" in payload["turn_prompts"][1]["prompt"]
    assert "Judge rubric:" in payload["moderator_prompt"]
    assert '"verdict": "FOR | AGAINST | NO_CLEAR_WINNER | INSUFFICIENT_EVIDENCE"' in payload["moderator_prompt"]
    assert '"rubric_scores": {"<each judge rubric key>"' in payload["moderator_prompt"]


def test_argue_prompt_review_bundle_documents_payload_contract():
    bundle = (ASK_DIR / "docs" / "prompts_review" / "ASK_ARGUE_PROMPT_PAYLOAD.md").read_text()

    for required in [
        "ask.argue.prompt_payload.v1",
        "Structured argue protocol:",
        "evidence_strength",
        "failure_mode_coverage",
        "NO_CLEAR_WINNER",
        "INSUFFICIENT_EVIDENCE",
        "Project Agent Decision",
    ]:
        assert required in bundle


def test_parse_argue_verdict_payload_accepts_fenced_json():
    parsed = parse_argue_verdict_payload(
        """Verdict follows:
```json
{"verdict": "NO_CLEAR_WINNER", "winner": "none", "rubric_scores": {}, "decisive_reasons": [], "confidence": "low"}
```
"""
    )

    assert parsed["verdict"] == "NO_CLEAR_WINNER"
    assert parsed["winner"] == "none"


def test_validate_argue_verdict_payload_accepts_complete_gate():
    payload = {
        "verdict": "FOR",
        "winner": "for",
        "rubric_scores": {
            rubric_key: {"for": 4, "against": 2, "winner": "for"}
            for rubric_key in ARGUE_JUDGE_RUBRIC
        },
        "decisive_reasons": ["FOR side cites inspected implementation cost and rollback evidence."],
        "confidence": "medium",
    }

    result = validate_argue_verdict_payload(payload)

    assert result == {"valid": True, "errors": []}


def test_validate_argue_verdict_payload_rejects_bad_winner_and_missing_rubric():
    payload = {
        "verdict": "FOR",
        "winner": "against",
        "rubric_scores": {
            "evidence_strength": {"for": 0, "against": 5, "winner": "against"},
        },
        "decisive_reasons": [],
        "confidence": "certain",
    }

    result = validate_argue_verdict_payload(payload)

    assert result["valid"] is False
    assert "FOR verdict requires winner=for" in result["errors"]
    assert "FOR/AGAINST verdicts require decisive_reasons" in result["errors"]
    assert "confidence must be high, medium, or low" in result["errors"]
    assert "missing rubric_scores.failure_mode_coverage" in result["errors"]


def test_validate_argue_verdict_payload_rejects_unsupported_decisive_verdict():
    payload = {
        "verdict": "AGAINST",
        "winner": "against",
        "rubric_scores": {
            rubric_key: {"for": 0, "against": 0, "winner": "tie"}
            for rubric_key in ARGUE_JUDGE_RUBRIC
        },
        "decisive_reasons": ["AGAINST sounds safer."],
        "confidence": "low",
    }

    result = validate_argue_verdict_payload(payload)

    assert result["valid"] is False
    assert "FOR/AGAINST verdict requires positive evidence_strength for the winning side" in result["errors"]


def test_default_parallel_participants_uses_focus_labels():
    participants = default_parallel_participants(3, focus="correctness,tests,maintainability")

    assert [p["protocol_role"] for p in participants] == [
        "failure_mode",
        "test_proof",
        "complexity_minimizer",
    ]
    assert [p["reviewer_spec"]["name"] for p in participants] == [
        "failure-mode",
        "test-proof",
        "complexity-minimizer",
    ]


def test_parse_protocol_turn_keeps_raw_when_invalid_json():
    parsed = parse_protocol_turn("not json")

    assert parsed["parse_ok"] is False
    assert parsed["raw_content"] == "not json"
    assert parsed["critiques"][0]["issue_type"] == "format"


def test_date_sensitive_question_detection():
    assert is_date_sensitive_question("formal methods in aerospace projects in 2026")
    assert is_date_sensitive_question("latest aerospace certification guidance")
    assert not is_date_sensitive_question("formal methods in aerospace")
