# Generated by test-lab — blind adversarial evaluation
"""test_setup_orchestration - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

from ask.setup_bootstrap import SetupBootstrapOptions, plan_setup


def test_local_dev_dry_run_reports_no_start_without_explicit_consent() -> None:
    plan = plan_setup(SetupBootstrapOptions(profile="local-dev", dry_run=True, start_missing=False))

    assert plan["schema"] == "ask.setup_plan.v1"
    assert plan["profile"] == "local-dev"
    assert plan["start_missing_requested"] is False
    assert plan["explicit_start_consent"] is False
    assert plan["actions"] == []


def test_local_dev_start_missing_records_explicit_start_action() -> None:
    plan = plan_setup(SetupBootstrapOptions(profile="local-dev", dry_run=True, start_missing=True))

    assert plan["start_missing_requested"] is True
    assert plan["explicit_start_consent"] is True
    assert plan["actions"] == ["start_missing_services"]


def test_shared_stack_validates_urls_without_starting_local_containers() -> None:
    plan = plan_setup(SetupBootstrapOptions(profile="shared-stack", dry_run=True, start_missing=False))

    assert plan["profile"] == "shared-stack"
    assert plan["actions"] == []
    assert "start_local_containers" in plan["skipped"]
