# Generated by test-lab — blind adversarial evaluation
"""The Ask browser-window reaper must reclaim leaks without ever closing live seats.

Context: eight provider windows were open on 2026-08-04, the oldest created by
a batch run on 2026-07-27. Cleanup lived only in a `finally` (lost to SIGKILL)
and skipped `fresh-keep` entirely (no expiry, no second chance).
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

import pytest

SKILL_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_ROOT / "src"))

from ask import tau_dag_cli as cli  # noqa: E402


@pytest.fixture
def registry(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    path = tmp_path / "browser-windows.jsonl"
    monkeypatch.setattr(cli, "ASK_WINDOW_REGISTRY", path)
    return path


def _write(registry: Path, entries: list[dict]) -> None:
    registry.write_text(
        "".join(json.dumps(e, sort_keys=True) + "\n" for e in entries), encoding="utf-8"
    )


@pytest.fixture
def closed(monkeypatch: pytest.MonkeyPatch) -> list[str]:
    seen: list[str] = []

    def fake(command, **kwargs):
        seen.append(command[-1])
        return {"returncode": 0}

    monkeypatch.setattr(cli, "_lifecycle_command", fake)
    return seen


def _dead_pid() -> int:
    """A pid that is certainly not running."""
    pid = 999_000
    while True:
        try:
            os.kill(pid, 0)
        except ProcessLookupError:
            return pid
        except OSError:
            return pid
        pid += 1


def test_a_live_owner_is_never_reaped(registry: Path, closed: list[str]) -> None:
    """The failure that would matter most: closing a running roundtable's seats."""
    _write(registry, [{"window_id": "111", "mode": "fresh-temporary", "pid": os.getpid(), "created_at": 0}])
    receipt = cli._reap_stale_ask_windows(Path("/nonexistent/surf"))
    assert closed == []
    assert receipt["kept"][0]["reason"] == "owner_alive"


def test_a_dead_owner_past_ttl_is_reclaimed(registry: Path, closed: list[str]) -> None:
    _write(
        registry,
        [{"window_id": "222", "mode": "fresh-temporary", "pid": _dead_pid(), "created_at": time.time() - 5000}],
    )
    receipt = cli._reap_stale_ask_windows(Path("/nonexistent/surf"))
    assert closed == ["222"]
    assert receipt["closed"][0]["window_id"] == "222"
    assert registry.read_text(encoding="utf-8").strip() == ""


def test_a_dead_owner_inside_ttl_is_left_alone(registry: Path, closed: list[str]) -> None:
    """A just-finished run may still be extracting from its tab."""
    _write(
        registry,
        [{"window_id": "333", "mode": "fresh-temporary", "pid": _dead_pid(), "created_at": time.time() - 60}],
    )
    receipt = cli._reap_stale_ask_windows(Path("/nonexistent/surf"))
    assert closed == []
    assert receipt["kept"][0]["reason"] == "within_ttl"


def test_fresh_keep_expires_instead_of_leaking_forever(registry: Path, closed: list[str]) -> None:
    """fresh-keep is inspect-then-reclaim, not keep-until-heat-death."""
    dead = _dead_pid()
    _write(
        registry,
        [
            {"window_id": "444", "mode": "fresh-keep", "pid": dead, "created_at": time.time() - 3600},
            {"window_id": "555", "mode": "fresh-keep", "pid": dead, "created_at": time.time() - 5 * 3600},
        ],
    )
    cli._reap_stale_ask_windows(Path("/nonexistent/surf"))
    assert closed == ["555"], "an hour-old fresh-keep window is still inspectable"


def test_registration_survives_for_a_later_run_to_reclaim(registry: Path) -> None:
    cli._register_ask_windows(
        {
            "mode": "fresh-temporary",
            "run_dir": "/tmp/run",
            "created_tabs": [
                {"window_id": "777", "handler": "webgpt"},
                {"window_id": "777", "handler": "webgpt"},
                {"window_id": "888", "handler": "webclaude"},
            ],
        }
    )
    entries = [json.loads(x) for x in registry.read_text(encoding="utf-8").splitlines()]
    assert [e["window_id"] for e in entries] == ["777", "888"], "duplicates collapse"
    assert entries[0]["pid"] == os.getpid()


def test_a_corrupt_registry_line_never_blocks_a_run(registry: Path, closed: list[str]) -> None:
    registry.write_text(
        "not json\n"
        + json.dumps({"window_id": "999", "mode": "fresh-temporary", "pid": _dead_pid(), "created_at": 0})
        + "\n",
        encoding="utf-8",
    )
    receipt = cli._reap_stale_ask_windows(Path("/nonexistent/surf"))
    assert receipt["closed"][0]["window_id"] == "999"


def test_an_unwritable_registry_never_takes_the_run_down(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(cli, "ASK_WINDOW_REGISTRY", tmp_path / "nope" / "reg.jsonl")
    monkeypatch.setattr(Path, "mkdir", lambda *a, **k: (_ for _ in ()).throw(OSError("readonly")))
    cli._register_ask_windows({"mode": "fresh-temporary", "created_tabs": [{"window_id": "1"}]})
