# Generated by test-lab — blind adversarial evaluation
"""Regression for agent-skills#1217: join must not stamp handler_timeout on a PASS lane.

A live WebGPT lane passed (node receipt PASS/ok/failure_code=null,
provider_result response_proven) but the join's handler_response_index carried
failure_code=handler_timeout because _run_join re-classified every receipt and
the classifier greps the serialized submit_meta, where the config field
"timeout_s": 900 reads as a timeout.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from types import SimpleNamespace
from pathlib import Path

WORKER_PATH = Path(__file__).resolve().parents[1] / "scripts" / "tau_roundtable_worker.py"
WORKER_SPEC = importlib.util.spec_from_file_location("tau_roundtable_worker_join_regression", WORKER_PATH)
assert WORKER_SPEC and WORKER_SPEC.loader
worker = importlib.util.module_from_spec(WORKER_SPEC)
sys.modules[WORKER_SPEC.name] = worker
WORKER_SPEC.loader.exec_module(worker)


def _write_handler_receipt(root: Path, *, ok: bool, failure: str | None, failure_code: str | None, response: str) -> None:
    node_dir = root / "handler-webgpt"
    node_dir.mkdir(parents=True)
    response_path = node_dir / "response.md"
    response_path.write_text(response, encoding="utf-8")
    receipt = {
        "schema": "ask.tau_dag_handler_receipt.v1",
        "node_id": "handler-webgpt",
        "handler": "webgpt",
        "status": "PASS" if ok else "NEEDS_ATTENTION",
        "ok": ok,
        "live": True,
        "provider_live": ok,
        "failure": failure,
        "failure_code": failure_code,
        "response_path": str(response_path),
        "response_chars": len(response),
        # The trigger from the live run: a passing lane whose submit_meta
        # contains a timeout *config* field, not a timeout failure.
        "submit_meta": {"timeout_s": 900, "model": "gpt-5"},
    }
    (node_dir / "node-receipt.json").write_text(json.dumps(receipt), encoding="utf-8")


def _join(tmp_path: Path) -> dict:
    join_dir = tmp_path / "join"
    join_dir.mkdir()
    args = SimpleNamespace(
        workflow_mode="roundtable",
        node_id="join",
        handler="join",
        topology="concurrent",
        request="regression",
        immutable_goal="regression",
        next_agent="human",
        evidence=["roundtable_join_receipt", "handler_response_index"],
        prior_node=[],
    )
    start = {
        "goal": {
            "goal_id": "ask-regression",
            "goal_version": 1,
            "immutable_goal": "regression",
            "goal_hash": "0" * 64,
        },
        "github": {"repo": "grahama1970/agent-skills", "target": "skills/ask"},
    }
    return worker._run_join(args, start, join_dir)


def test_passing_lane_keeps_null_failure_code(tmp_path: Path) -> None:
    _write_handler_receipt(tmp_path, ok=True, failure=None, failure_code=None, response="seat output")
    result = _join(tmp_path)
    receipt = json.loads((tmp_path / "join" / "node-receipt.json").read_text(encoding="utf-8"))
    assert receipt["status"] == "PASS"
    entry = receipt["handler_response_index"][0]
    assert entry["ok"] is True
    assert entry["failure_code"] is None, entry["failure_code"]


def test_failed_lane_still_classifies_real_timeout(tmp_path: Path) -> None:
    _write_handler_receipt(
        tmp_path,
        ok=False,
        failure="surf webgpt.submit timed out after 900s",
        failure_code=None,
        response="",
    )
    _join(tmp_path)
    receipt = json.loads((tmp_path / "join" / "node-receipt.json").read_text(encoding="utf-8"))
    entry = receipt["handler_response_index"][0]
    assert entry["failure_code"] == "handler_timeout"
    assert receipt["failed_seat_count"] == 1


def test_failed_lane_preserves_explicit_failure_code(tmp_path: Path) -> None:
    _write_handler_receipt(
        tmp_path,
        ok=False,
        failure="auth broke",
        failure_code="scillm_auth_invalid_api_key",
        response="",
    )
    _join(tmp_path)
    receipt = json.loads((tmp_path / "join" / "node-receipt.json").read_text(encoding="utf-8"))
    assert receipt["handler_response_index"][0]["failure_code"] == "scillm_auth_invalid_api_key"
