# Generated by test-lab — blind adversarial evaluation
"""ask.capability_report.v1 must not collapse readiness into optimism (#1405).

The failure this guards is a plan launched against a target that cannot do the
thing the plan needs: a seat that answers text but cannot take an attachment,
a provider reachable by API and rate-limited on its web surface, or a config
value read as proof of a live subsystem.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

SKILL_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_ROOT / "src"))

from ask.capability_report import (  # noqa: E402
    BROWSER_HANDLERS,
    SCHEMA,
    STATES,
    build_report,
    render_text,
)


def _availability(**providers: dict) -> dict:
    return {"providers": providers}


def _by_id(report: dict) -> dict[str, dict]:
    return {entry["capability_id"]: entry for entry in report["capabilities"]}


def test_the_default_report_touches_no_subsystem() -> None:
    """Required proof 3: no generation, submission, or mutation by default."""
    report = build_report(live=False)
    assert report["live"] is False
    remote = {"tau.harness", "scillm.transport", "memory.graph", "session.herdr"}
    for capability_id in remote:
        assert _by_id(report)[capability_id]["state"] == "NOT_TESTED"


def test_skipped_probes_are_listed_not_defaulted() -> None:
    """Required proof 4: a report that hides what it declined to run is a lie."""
    report = build_report(live=False)
    assert report["skipped_probes"], "skipped probes must be enumerated"
    for capability_id in report["skipped_probes"]:
        assert _by_id(report)[capability_id]["state"] == "NOT_TESTED"


def test_there_is_no_global_healthy_flag() -> None:
    """Rule 2: one optimistic boolean is exactly what hides a blocked lane."""
    report = build_report(live=False)
    assert "healthy" not in report
    assert "ok" not in report


def test_every_browser_handler_is_reported_separately() -> None:
    """Rule 3: one seat's failure must not imply anything about the others."""
    report = build_report(live=False)
    ids = _by_id(report)
    for handler in BROWSER_HANDLERS:
        assert f"browser.{handler}" in ids


def test_one_failed_seat_does_not_contaminate_the_others() -> None:
    """Required proof 8."""
    report = build_report(
        live=True,
        availability=_availability(
            webgpt={"provider_limited": True},
            webclaude={"provider_limited": False, "probe_failed": False, "probe_degraded": False},
        ),
    )
    ids = _by_id(report)
    assert ids["browser.webgpt"]["state"] == "BLOCKED"
    assert ids["browser.webclaude"]["state"] == "READY"
    assert ids["browser.webclaude"]["operations"]["text"] is True


def test_text_ready_and_attachment_blocked_stay_distinct() -> None:
    """Required proof 5: dimensions must not collapse."""
    report = build_report(
        live=True,
        availability=_availability(
            webdeepseek={"provider_limited": False, "probe_failed": False, "probe_degraded": False}
        ),
    )
    seat = _by_id(report)["browser.webdeepseek"]
    assert seat["state"] == "READY"
    assert seat["operations"]["text"] is True
    assert seat["operations"]["attachment"] is False


def test_a_degraded_probe_never_reports_text_ready() -> None:
    """Uncertainty must not read as readiness (rule 1)."""
    report = build_report(
        live=True,
        availability=_availability(
            webgpt={"probe_degraded": True, "failure_code": "browser_provider_probe_timeout"}
        ),
    )
    seat = _by_id(report)["browser.webgpt"]
    assert seat["state"] == "DEGRADED"
    assert seat["operations"]["text"] is None
    assert seat["reason_code"] == "browser_provider_probe_timeout"


def test_api_and_web_readiness_are_separate_capabilities() -> None:
    """Required proof 6: same provider family, different surfaces."""
    report = build_report(live=False)
    ids = _by_id(report)
    assert ids["scillm.transport"]["kind"] == "model_api"
    assert ids["browser.webclaude"]["kind"] == "browser_seat"
    assert ids["scillm.transport"]["capability_id"] != ids["browser.webclaude"]["capability_id"]


def test_human_and_json_derive_from_one_report() -> None:
    """Required proof 2."""
    report = build_report(live=False)
    text = "\n".join(render_text(report))
    for entry in report["capabilities"]:
        assert entry["capability_id"] in text
        assert entry["state"] in text


def test_every_state_is_from_the_declared_vocabulary() -> None:
    report = build_report(live=False)
    for entry in report["capabilities"]:
        assert entry["state"] in STATES


def test_next_commands_carry_no_secrets() -> None:
    """Required proof 9."""
    report = build_report(live=False)
    for entry in report["capabilities"]:
        command = entry.get("next_command", "")
        lowered = command.lower()
        assert "sk-" not in lowered
        assert "api_key" not in lowered
        assert "token" not in lowered


def test_the_schema_is_declared() -> None:
    assert build_report(live=False)["schema"] == SCHEMA


@pytest.mark.parametrize(
    ("payload", "expected"),
    [
        ({"provider_limited": True}, "BLOCKED"),
        ({"probe_failed": True, "failure_code": "boom"}, "UNAVAILABLE"),
        ({"probe_degraded": True}, "DEGRADED"),
        ({"provider_limited": False, "probe_failed": False, "probe_degraded": False}, "READY"),
    ],
)
def test_every_browser_state_is_reachable(payload: dict, expected: str) -> None:
    """Required proof 1: fixtures cover every state for the seat family."""
    report = build_report(live=True, availability=_availability(webgpt=payload))
    assert _by_id(report)["browser.webgpt"]["state"] == expected


def test_required_blocked_targets_are_surfaced() -> None:
    report = build_report(live=False)
    assert "required_blocked" in report
    assert isinstance(report["required_blocked"], list)


def _live_report() -> dict:
    return build_report(
        live=True,
        availability=_availability(
            webgpt={"provider_limited": False, "probe_failed": False, "probe_degraded": False}
        ),
    )


def test_a_fresh_live_verdict_is_not_stale() -> None:
    seat = _by_id(_live_report())["browser.webgpt"]
    assert seat["stale"] is False
    assert seat["ttl_seconds"] > 0
    assert seat["observed_at"] > 0


def test_a_verdict_past_its_ttl_goes_stale() -> None:
    """Required proof 7: age alone invalidates."""
    import time

    from ask.capability_report import mark_stale

    report = _live_report()
    aged = mark_stale(
        {**report, "capabilities": [dict(c) for c in report["capabilities"]]},
        now=time.time() + 10_000,
        fingerprint=report["identity_fingerprint"],
    )
    seat = _by_id(aged)["browser.webgpt"]
    assert seat["stale"] is True
    assert seat["stale_reason"] == "ttl_expired"


def test_changed_identity_invalidates_even_a_recent_verdict() -> None:
    """Required proof 7: a readiness about a world that no longer exists.

    Recency is not relevance -- a verdict observed against a different browser
    tab, Herdr session, or Tau revision describes something else.
    """
    from ask.capability_report import mark_stale

    report = _live_report()
    moved = mark_stale(
        {**report, "capabilities": [dict(c) for c in report["capabilities"]]},
        fingerprint="a-different-world",
    )
    seat = _by_id(moved)["browser.webgpt"]
    assert seat["stale"] is True
    assert seat["stale_reason"] == "identity_changed"
    assert moved["identity_changed"] is True


def test_a_never_tested_capability_is_never_marked_stale() -> None:
    """NOT_TESTED was never fresh, so it cannot go stale."""
    from ask.capability_report import mark_stale

    report = build_report(live=False)
    marked = mark_stale(
        {**report, "capabilities": [dict(c) for c in report["capabilities"]]},
        fingerprint="anything-else",
    )
    for entry in marked["capabilities"]:
        if entry["state"] == "NOT_TESTED":
            assert entry["stale"] is False


def test_browser_seats_expire_faster_than_local_capabilities() -> None:
    """Tabs are reassigned constantly; a local entrypoint is not."""
    report = _live_report()
    ids = _by_id(report)
    assert ids["browser.webgpt"]["ttl_seconds"] < ids["ask.cli"]["ttl_seconds"]
