# Generated by test-lab — blind adversarial evaluation
"""Deep-review target resolution and prompt construction tests."""

from ask.deep_review import build_deep_review_prompt, infer_deep_review, resolve_deep_review_target


def test_deep_review_inference_detects_human_safe_to_proceed_prompt():
    assert infer_deep_review("Can you do a deep review and tell me if this is safe to proceed?")


def test_deep_review_target_fails_closed_for_vague_safe_to_proceed():
    target = resolve_deep_review_target("safe to proceed?")

    assert target["status"] == "missing"
    assert target["requires_target"] is True
    assert "explicit target" in target["message"]


def test_deep_review_target_accepts_explicit_paths():
    target = resolve_deep_review_target("safe to proceed?", "src/ask/ask.py tests/test_ask_cli_protocols.py")

    assert target["status"] == "explicit"
    assert target["target"] == "src/ask/ask.py tests/test_ask_cli_protocols.py"
    assert target["requires_target"] is False
    assert target["target_bundle"]["total_entries"] == 2


def test_deep_review_prompt_includes_explicit_target_file_material(tmp_path):
    target_file = tmp_path / "target.md"
    target_file.write_text("Important target bundle content for review.", encoding="utf-8")
    request = {
        "target": resolve_deep_review_target("deep review this", str(target_file)),
        "original_question": "deep review this",
        "profile": "max_available",
        "reviewers": 5,
        "focus": "correctness,tests,auditability",
        "dogpile_mode": "auto",
    }

    prompt = build_deep_review_prompt({"items": []}, request)

    assert "[TARGET.1]" in prompt
    assert "Important target bundle content for review." in prompt
    assert "Use `TARGET.N` source IDs" in prompt


def test_deep_review_prompt_includes_required_contract():
    request = {
        "target": {"status": "explicit", "target": "src/ask/ask.py", "requires_target": False},
        "original_question": "deep review this implementation",
        "profile": "max_available",
        "reviewers": 5,
        "focus": "correctness,tests,auditability",
        "dogpile_mode": "auto",
    }
    result = {
        "items": [
            {
                "problem": "ask routing",
                "solution": "Deep review should be read-only and artifact-backed.",
            }
        ]
    }

    prompt = build_deep_review_prompt(result, request)

    assert "Web-GPT-heavy-reasoning-equivalent deep review" in prompt
    assert "Treat memory recall as context, not evidence" in prompt
    assert "Final verdict must be SAFE" in prompt
    assert '"sections"' in prompt
