# Generated by test-lab — blind adversarial evaluation
"""test_docs_setup_examples - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOC_PATH = ROOT / "docs" / "SETUP_WIZARD.md"


def test_setup_docs_preserve_install_vs_start_boundary() -> None:
    text = DOC_PATH.read_text(encoding="utf-8")

    assert "Installing `/ask` does not start containers" in text
    assert "--start-missing" in text
    assert "start_missing_services" in text
    assert "arangodb" in text.lower()
    assert "qdrant" in text.lower()
    assert "scillm" in text.lower()
    assert "memory_upsert_recall" in text


def test_documented_ask_dry_run_path_dispatches_through_run_sh() -> None:
    import json
    import subprocess

    result = subprocess.run(
        [
            str(ROOT / "run.sh"),
            "ask",
            "Should ask dry-run work?",
            "--dry-run",
            "--json",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr or result.stdout
    payload = json.loads(result.stdout)
    assert payload["command"] == "ask"
    assert payload["dry_run"] is True
    assert payload["options"]["question"] == "Should ask dry-run work?"
