# Generated by test-lab — blind adversarial evaluation
"""Regression guards for the deterministic lane-failure diagnostic series.

These cover the pure decision layer only: which diagnosis a set of check
results implies, and which recovery rungs that diagnosis promotes. The probe
itself is proven by a live run against a real provider tab, not here.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pytest

SKILL_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_ROOT / "scripts"))
sys.path.insert(0, str(SKILL_ROOT / "src"))

import tau_roundtable_worker as worker  # noqa: E402
from ask.seam_models import SeamViolation, enforce  # noqa: E402


def _args() -> argparse.Namespace:
    return argparse.Namespace(surf_run="", handler="webgpt", node_id="n1")


def _diagnose(monkeypatch: pytest.MonkeyPatch, checks: list[dict]) -> str:
    monkeypatch.setattr(worker, "_probe_lane_state", lambda *a, **k: checks)
    result = worker._lane_diagnostics(
        _args(),
        failure_code="missing_sentinel",
        submit_meta={"controlled_tab_id": "1"},
        browser_oracle={},
        sentinel="<<<S>>>",
    )
    return result["diagnosis"]


@pytest.mark.parametrize(
    ("checks", "expected"),
    [
        ([{"check": "surf_transport", "status": "FAIL"}], "surf_transport_down"),
        (
            [
                {"check": "surf_transport", "status": "PASS"},
                {"check": "tab_identity", "status": "FAIL"},
            ],
            "controlled_tab_vanished",
        ),
        (
            [
                {"check": "surf_transport", "status": "PASS"},
                {"check": "tab_identity", "status": "PASS"},
                {"check": "provider_url", "status": "FAIL"},
            ],
            "tab_drifted_off_provider",
        ),
        (
            [
                {"check": "surf_transport", "status": "PASS"},
                {"check": "tab_identity", "status": "PASS"},
                {"check": "provider_url", "status": "PASS"},
                {"check": "page_state", "status": "FAIL"},
            ],
            "tab_unresponsive_to_js",
        ),
        (
            [
                {"check": "surf_transport", "status": "PASS"},
                {"check": "tab_identity", "status": "PASS"},
                {"check": "sentinel_rendered", "status": "PASS"},
            ],
            "response_rendered_capture_missed",
        ),
        (
            [
                {"check": "surf_transport", "status": "PASS"},
                {"check": "tab_identity", "status": "PASS"},
                {"check": "sentinel_rendered", "status": "FAIL", "still_generating": True},
            ],
            "provider_still_generating_at_timeout",
        ),
        (
            [
                {"check": "surf_transport", "status": "PASS"},
                {"check": "tab_identity", "status": "PASS"},
                {"check": "provider_banner", "status": "FAIL"},
            ],
            "provider_banner_blocked",
        ),
    ],
)
def test_diagnosis_is_a_deterministic_lookup(
    monkeypatch: pytest.MonkeyPatch, checks: list[dict], expected: str
) -> None:
    assert _diagnose(monkeypatch, checks) == expected


def test_a_rendered_sentinel_outranks_a_banner() -> None:
    """Capture-missed must win: extraction recovers the round for free."""
    order = worker._ladder_order_for_diagnosis("response_rendered_capture_missed")
    assert order[0] == "provider_extract"


def test_a_vanished_tab_never_tries_to_extract_from_it() -> None:
    order = worker._ladder_order_for_diagnosis("controlled_tab_vanished")
    assert "provider_extract" not in order
    assert order == ["packet_next_command"]


def test_unknown_diagnosis_leaves_the_default_prior_alone() -> None:
    assert worker._ladder_order_for_diagnosis("no_live_defect_observed") == []


def test_a_failed_lane_cannot_report_without_running_the_series() -> None:
    with pytest.raises(SeamViolation) as excinfo:
        enforce(
            "ask.lane_diagnostics.v1",
            {"schema": "ask.lane_diagnostics.v1", "handler": "webgpt", "checks": [], "diagnosis": ""},
        )
    assert any("no diagnostic checks run" in e["error"] for e in excinfo.value.errors)


def test_a_partially_run_series_is_also_refused() -> None:
    with pytest.raises(SeamViolation) as excinfo:
        enforce(
            "ask.lane_diagnostics.v1",
            {
                "schema": "ask.lane_diagnostics.v1",
                "handler": "webgpt",
                "checks": [{"check": "provider_banner", "status": "PASS"}],
                "diagnosis": "no_live_defect_observed",
            },
        )
    assert any("skipped the surf_transport check" in e["error"] for e in excinfo.value.errors)
