"""test_model_alias_live_e2e - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""


from dotenv import find_dotenv, load_dotenv

load_dotenv(find_dotenv(usecwd=True), override=False)
# Generated by test-lab — blind adversarial evaluation
"""Opt-in live checks for `$ask` model shorthand through /scillm."""

import json
import os

import pytest
from typer.testing import CliRunner

import ask.ask as ask_module
import ask.ask_oracle as ask_oracle


@pytest.mark.skipif(
    os.environ.get("ASK_LIVE_SCILLM_E2E") != "1",
    reason="set ASK_LIVE_SCILLM_E2E=1 to run the real /scillm model-alias smoke test",
)
def test_live_model_alias_shorthand_resolves_and_calls_scillm_oracle(monkeypatch):
    dry_run = CliRunner().invoke(
        ask_module.app,
        ["oc", "kimi", "answer", "with", "one", "word", "--dry-run", "--json"],
    )

    assert dry_run.exit_code == 0
    dry_run_payload = json.loads(dry_run.stdout)
    alias = dry_run_payload["options"]["oracle_model_alias"]
    assert alias["provider_hint"] == "opencode"
    assert alias["family"] == "kimi"
    assert alias["source"] == "live-opencode-go-models"
    assert alias["resolved_model"].startswith("opencode-go/")

    result = {
        "question": "Answer with exactly one word: READY.",
        "scope": "ask",
        "items": [{"problem": "sanity", "solution": "The expected answer is READY."}],
        "answer": "The expected answer is READY.",
        "oracle": {
            "model_alias": alias,
            "dogpile_mode": "off",
            "dogpile_recommended": False,
        },
    }

    monkeypatch.setattr(ask_oracle, "_load_oracle_persona_profiles", lambda **_kwargs: {})
    ask_oracle._apply_oracle_synthesis(
        result,
        k=1,
        model=alias["resolved_model"],
        reasoning_effort="high",
        timeout=90,
        idle_timeout=90,
        heartbeat_interval=10,
        persona=None,
        consult_personas=[],
        peer=None,
        iterations=1,
        backend="scillm",
        persona_model=None,
        peer_model=None,
        persona_scope="personas",
    )

    assert result["answer"].strip()
    assert "error" not in result["oracle"]
    assert result["oracle"]["backend"] == "scillm"
    assert result["oracle"]["model_alias"]["resolved_model"] == alias["resolved_model"]
    assert result["oracle"]["model_served"]
