# Generated by test-lab — blind adversarial evaluation
"""test_code_memory_client - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

MODULE_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(MODULE_DIR))

for module_name in ["code_symbol_record", "code_memory_client"]:
    spec = importlib.util.spec_from_file_location(module_name, MODULE_DIR / f"{module_name}.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)

from code_memory_client import CodeMemoryClient
from code_symbol_record import CodeSymbolRecord


class FakeResponse:
    def __init__(self, status_code: int, text: str = "") -> None:
        self.status_code = status_code
        self.text = text


class FakeHttpClient:
    def __init__(self, fail_names: set[str] | None = None, fail_multi: bool = True) -> None:
        self.batch_sizes: list[int] = []
        self.batch_names: list[list[str]] = []
        self.fail_names = fail_names or set()
        self.fail_multi = fail_multi

    def __enter__(self):
        return self

    def __exit__(self, *args):
        return False

    def post(self, path: str, json: dict):
        assert path == "/upsert"
        documents = json["documents"]
        size = len(documents)
        names = [document["symbol_name"] for document in documents]
        self.batch_sizes.append(size)
        self.batch_names.append(names)
        if (self.fail_multi and size > 1) or any(name in self.fail_names for name in names):
            return FakeResponse(500, "embed batch failed")
        return FakeResponse(200)


def _record(name: str) -> CodeSymbolRecord:
    return CodeSymbolRecord(
        scope="test",
        repo="repo",
        root="/repo",
        branch="main",
        commit="abc",
        path="app.py",
        language="python",
        symbol_kind="function",
        symbol_name=name,
        qualified_name=name,
        start_line=1,
        end_line=2,
        code=f"def {name}():\n    return 1\n",
    )


def test_upsert_code_symbols_splits_failed_batches_before_legacy_fallback(monkeypatch) -> None:
    fake = FakeHttpClient()
    client = CodeMemoryClient()
    monkeypatch.setattr(client, "_client", lambda: fake)
    def unexpected_legacy_fallback(*args, **kwargs):
        raise AssertionError("unexpected legacy fallback")

    monkeypatch.setattr(client, "store_legacy_code_symbol", unexpected_legacy_fallback)

    result = client.upsert_code_symbols([_record("first"), _record("second")], batch_size=2)

    assert result.stored == 2
    assert result.attempted == 2
    assert result.errors == []
    assert fake.batch_sizes == [2, 1, 1]


def test_upsert_code_symbols_uses_env_batch_size(monkeypatch) -> None:
    fake = FakeHttpClient()
    client = CodeMemoryClient()
    monkeypatch.setenv("CODE_SYMBOLS_QDRANT_BATCH_SIZE", "1")
    monkeypatch.setattr(client, "_client", lambda: fake)

    result = client.upsert_code_symbols([_record("first"), _record("second")])

    assert result.stored == 2
    assert result.attempted == 2
    assert fake.batch_sizes == [1, 1]


def test_upsert_code_symbols_recursively_splits_larger_failed_batches(monkeypatch) -> None:
    fake = FakeHttpClient()
    client = CodeMemoryClient()
    monkeypatch.setattr(client, "_client", lambda: fake)
    legacy_calls: list[str] = []

    def record_legacy_fallback(record, *args, **kwargs):
        legacy_calls.append(record.qualified_name)
        return True

    monkeypatch.setattr(client, "store_legacy_code_symbol", record_legacy_fallback)

    result = client.upsert_code_symbols(
        [_record("first"), _record("second"), _record("third"), _record("fourth")],
        batch_size=4,
    )

    assert result.stored == 4
    assert result.attempted == 4
    assert result.errors == []
    assert fake.batch_sizes == [4, 2, 1, 1, 2, 1, 1]
    assert legacy_calls == []


def test_upsert_code_symbols_ignores_invalid_env_batch_sizes(monkeypatch) -> None:
    records = [_record("first"), _record("second")]
    for raw in ["", "not-an-integer", "0", "-1"]:
        fake = FakeHttpClient(fail_multi=False)
        client = CodeMemoryClient()
        monkeypatch.setenv("CODE_SYMBOLS_QDRANT_BATCH_SIZE", raw)
        monkeypatch.setattr(client, "_client", lambda fake=fake: fake)

        result = client.upsert_code_symbols(records)

        assert result.stored == 2
        assert result.attempted == 2
        assert result.errors == []
        assert fake.batch_sizes == [2]


def test_upsert_code_symbols_explicit_batch_size_takes_precedence(monkeypatch) -> None:
    fake = FakeHttpClient(fail_multi=False)
    client = CodeMemoryClient()
    monkeypatch.setenv("CODE_SYMBOLS_QDRANT_BATCH_SIZE", "1")
    monkeypatch.setattr(client, "_client", lambda: fake)

    result = client.upsert_code_symbols([_record("first"), _record("second")], batch_size=2)

    assert result.stored == 2
    assert result.attempted == 2
    assert result.errors == []
    assert fake.batch_sizes == [2]


def test_upsert_code_symbols_records_singleton_upsert_and_legacy_failure(monkeypatch) -> None:
    fake = FakeHttpClient(fail_names={"first"}, fail_multi=False)
    client = CodeMemoryClient()
    monkeypatch.setattr(client, "_client", lambda: fake)
    monkeypatch.setattr(client, "store_legacy_code_symbol", lambda *args, **kwargs: False)

    result = client.upsert_code_symbols([_record("first")], batch_size=1)

    assert result.stored == 0
    assert result.attempted == 1
    assert len(result.errors) == 1
    assert "first" in result.errors[0]
    assert "HTTP 500" in result.errors[0]
    assert "legacy=fallback failed" in result.errors[0]


def test_upsert_code_symbols_mixed_singleton_recovery(monkeypatch) -> None:
    fake = FakeHttpClient(fail_names={"second"})
    client = CodeMemoryClient()
    monkeypatch.setattr(client, "_client", lambda: fake)
    legacy_calls: list[str] = []

    def record_legacy_fallback(record, *args, **kwargs):
        legacy_calls.append(record.qualified_name)
        return True

    monkeypatch.setattr(client, "store_legacy_code_symbol", record_legacy_fallback)

    result = client.upsert_code_symbols([_record("first"), _record("second")], batch_size=2)

    assert result.stored == 2
    assert result.attempted == 2
    assert result.errors == []
    assert fake.batch_sizes == [2, 1, 1]
    assert legacy_calls == ["second"]
