/**
 * common styles from the legacy `styles` object.
 *
 * Split for the same reason as `nvis`: a 1,033-line literal is not reviewable,
 * and each cluster belongs with the surface that uses it.
 */
import type { CSSProperties } from 'react'

export const baseCommonStyles: Record<string, CSSProperties> = {
  agentSuccessBox: {
    borderRadius: 12,
    border: '1px solid rgba(52, 211, 153, 0.24)',
    background: 'rgba(52, 211, 153, 0.08)',
    padding: 12,
    color: '#a7f3d0',
    fontSize: 13,
    lineHeight: 1.45,
  },
  agentPane: {
    minWidth: 0,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    borderLeft: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'linear-gradient(180deg, rgba(13, 17, 23, 0.96), rgba(5, 7, 10, 0.98))',
    padding: 16,
    overflow: 'auto',
    boxShadow: '-16px 0 38px rgba(0, 0, 0, 0.24)',
  },
  agentPaneHeader: {
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    paddingBottom: 12,
  },
  agentPaneTitle: {
    margin: '4px 0 0',
    color: '#fff',
    fontSize: 17,
    lineHeight: 1.25,
  },
  agentContext: {
    display: 'grid',
    gap: 10,
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: 14,
    background: 'rgba(255, 255, 255, 0.045)',
    padding: 10,
  },
  agentContextMotion: {
    display: 'grid',
    gap: 12,
    animation: 'dream-agent-slide 240ms ease-out both',
    willChange: 'opacity, transform',
  },
  agentTextarea: {
    width: '100%',
    minHeight: 146,
    resize: 'vertical',
    borderRadius: 12,
    border: '1px solid rgba(255, 255, 255, 0.12)',
    background: 'rgba(0, 0, 0, 0.28)',
    color: '#f8fafc',
    padding: 10,
    font: 'inherit',
    fontSize: 13,
    lineHeight: 1.4,
    outline: 'none',
  },
  artifactChips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  artifactChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    maxWidth: '100%',
    borderRadius: 5,
    border: '1px solid rgba(125, 211, 252, 0.28)',
    background: 'rgba(125, 211, 252, 0.08)',
    padding: '6px 8px',
    color: '#bae6fd',
    textDecoration: 'none',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 11,
    overflowWrap: 'anywhere',
  },
  artifactBox: {
    borderRadius: 7,
    border: '1px solid rgba(255, 255, 255, 0.1)',
    background: 'rgba(255, 255, 255, 0.025)',
    padding: 14,
  },
  artifactTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 10,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: '#cbd5e1',
  },
  artifactList: {
    display: 'grid',
    gap: 12,
    margin: 0,
  },
  artifactLabel: {
    color: '#64748b',
    fontSize: 11,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  artifactValue: {
    margin: '4px 0 0',
    color: '#cbd5e1',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 12,
    lineHeight: 1.35,
    overflowWrap: 'anywhere',
  },
  badgeRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    border: '1px solid',
    borderRadius: 999,
    padding: '5px 9px',
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    fontSize: 11,
    letterSpacing: '0',
    textTransform: 'uppercase',
    lineHeight: 1,
  },
  commitWorkOrderButton: {
    minHeight: 38,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 8,
    border: '1px solid rgba(96, 165, 250, 0.48)',
    background: 'rgba(37, 99, 235, 0.88)',
    color: '#fff',
    padding: '0 12px',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 760,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  deployButton: {
    flex: '0 0 auto',
    maxWidth: 220,
    minHeight: 34,
    borderRadius: 999,
    border: '1px solid rgba(255, 255, 255, 0.14)',
    background: '#1f2937',
    color: '#e5e7eb',
    padding: '0 12px',
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  deployButtonReady: {
    borderColor: 'rgba(52, 211, 153, 0.55)',
    background: 'rgba(21, 128, 61, 0.9)',
    color: '#dcfce7',
    cursor: 'pointer',
  },
  detail: {
    minWidth: 0,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    background: 'radial-gradient(circle at 50% 0%, rgba(59, 130, 246, 0.1), transparent 34%), #05070a',
  },
  detailHeader: {
    minHeight: 72,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'rgba(5, 7, 10, 0.9)',
    padding: '16px 20px',
  },
  detailEyebrow: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 10,
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
    color: '#64748b',
  },
  detailTitle: {
    margin: '4px 0 0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: 20,
    lineHeight: 1.25,
    color: '#fff',
  },
  detailBody: {
    minHeight: 0,
    flex: 1,
    display: 'grid',
    gridTemplateColumns: 'minmax(310px, 420px) minmax(0, 1fr)',
  },
  disabledButton: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  emptyBox: {
    border: '1px solid rgba(251, 191, 36, 0.35)',
    borderRadius: 7,
    background: 'rgba(251, 191, 36, 0.1)',
    padding: 14,
    color: '#fde68a',
    fontSize: 14,
  },
  errorBox: {
    border: '1px solid rgba(248, 113, 113, 0.35)',
    borderRadius: 7,
    background: 'rgba(248, 113, 113, 0.1)',
    padding: 14,
    color: '#fecaca',
    fontSize: 14,
  },
  eyebrow: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 11,
    letterSpacing: '0.22em',
    textTransform: 'uppercase',
    color: '#7dd3fc',
  },
  gapBox: {
    borderRadius: 12,
    border: '1px solid rgba(251, 191, 36, 0.28)',
    background: 'rgba(251, 191, 36, 0.1)',
    padding: 12,
    color: '#fde68a',
    fontSize: 13,
    lineHeight: 1.45,
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  iconButton: {
    width: 40,
    height: 40,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    border: '1px solid rgba(255, 255, 255, 0.09)',
    background: 'rgba(255, 255, 255, 0.045)',
    color: '#cbd5e1',
    cursor: 'pointer',
  },
  iframe: {
    width: '100%',
    height: '100%',
    border: 0,
    background: '#fff',
  },
  imageGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 10,
  },
  imageFigure: {
    margin: 0,
    borderRadius: 12,
    border: '1px solid rgba(255, 255, 255, 0.1)',
    background: 'rgba(0, 0, 0, 0.35)',
    overflow: 'hidden',
  },
  imageCaption: {
    padding: '7px 9px',
    color: '#cbd5e1',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 11,
    overflowWrap: 'anywhere',
  },
  inspector: {
    minHeight: 0,
    overflow: 'auto',
    borderRight: '1px solid rgba(255, 255, 255, 0.1)',
    padding: 20,
  },
  inspectorSection: {
    marginBottom: 16,
  },
  klingGate: {
    height: 54,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: 14,
    background: 'rgba(13, 17, 23, 0.72)',
    padding: '0 16px',
    overflow: 'hidden',
  },
  legacyReportLink: {
    justifySelf: 'start',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    borderRadius: 6,
    border: '1px solid rgba(255, 255, 255, 0.12)',
    color: '#e2e8f0',
    textDecoration: 'none',
    padding: '8px 10px',
    fontSize: 13,
  },
  noReport: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    textAlign: 'center',
    color: '#94a3b8',
  },
  noReportTitle: {
    marginTop: 12,
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: 700,
  },
  noReportCopy: {
    maxWidth: 420,
    margin: '8px 0 0',
    fontSize: 14,
    lineHeight: 1.45,
  },
  phaseHeaderText: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 7,
  },
  rail: {
    minWidth: 0,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    borderRight: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'linear-gradient(180deg, rgba(13, 17, 23, 0.96), rgba(5, 7, 10, 0.98))',
    boxShadow: '16px 0 38px rgba(0, 0, 0, 0.24)',
  },
  railCollapsed: {
    alignItems: 'center',
  },
  railHeader: {
    padding: 16,
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
  },
  railCollapsedHeader: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    padding: '12px 8px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
  },
  railTitleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  railTitle: {
    margin: '4px 0 0',
    fontSize: 18,
    lineHeight: 1.25,
    fontWeight: 700,
    color: '#fff',
  },
  receiptAccordion: {
    borderRadius: 8,
    border: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'rgba(0, 0, 0, 0.28)',
    padding: 0,
  },
  receiptAccordionSummary: {
    cursor: 'pointer',
    padding: '12px 14px',
    color: '#94a3b8',
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    userSelect: 'none',
  },
  receiptGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: 8,
    padding: '0 14px 14px',
  },
  receiptPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    minWidth: 0,
    maxWidth: '100%',
    borderRadius: 4,
    border: '1px solid rgba(75, 85, 99, 0.9)',
    background: 'rgba(255, 255, 255, 0.03)',
    padding: '7px 9px',
    color: '#9ca3af',
    textDecoration: 'none',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 11,
    transition: 'background 160ms ease, border-color 160ms ease, color 160ms ease',
    overflow: 'hidden',
  },
  receiptPillLabel: {
    minWidth: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  reportLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    borderRadius: 6,
    border: '1px solid rgba(255, 255, 255, 0.12)',
    padding: '8px 10px',
    color: '#e2e8f0',
    textDecoration: 'none',
    fontSize: 13,
    whiteSpace: 'nowrap',
  },
  reportPane: {
    minWidth: 0,
    minHeight: 0,
    background: '#030608',
  },
  runList: {
    minHeight: 0,
    flex: 1,
    overflow: 'auto',
    padding: 12,
  },
  runCard: {
    width: '100%',
    display: 'block',
    margin: '0 0 10px',
    padding: 12,
    textAlign: 'left',
    borderRadius: 14,
    border: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'rgba(13, 17, 23, 0.72)',
    color: '#f8fafc',
    cursor: 'pointer',
    boxShadow: '0 10px 28px rgba(0, 0, 0, 0.22)',
  },
  runCardSelected: {
    borderColor: 'rgba(96, 165, 250, 0.48)',
    background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.18), rgba(13, 17, 23, 0.84))',
    boxShadow: '0 0 0 1px rgba(96, 165, 250, 0.08), 0 16px 36px rgba(37, 99, 235, 0.12)',
  },
  runCardTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  runTitle: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: 14,
    fontWeight: 700,
    color: '#f8fafc',
  },
  runSource: {
    marginTop: 4,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 10,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: '#64748b',
  },
  runMetadata: {
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    background: 'rgba(13, 17, 23, 0.48)',
    overflow: 'hidden',
  },
  runMetadataSummary: {
    minHeight: 34,
    display: 'flex',
    alignItems: 'center',
    padding: '0 12px',
    color: '#94a3b8',
    cursor: 'pointer',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 10,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    userSelect: 'none',
  },
  searchWrap: {
    marginTop: 16,
    height: 38,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    borderRadius: 12,
    border: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'rgba(255, 255, 255, 0.045)',
    padding: '0 12px',
  },
  searchInput: {
    minWidth: 0,
    flex: 1,
    border: 0,
    outline: 0,
    background: 'transparent',
    color: '#f8fafc',
    fontSize: 14,
  },
  sectionLabel: {
    marginBottom: 8,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 10,
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
    color: '#64748b',
  },
  sourceLine: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: 12,
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: 14,
    background: 'rgba(13, 17, 23, 0.7)',
    padding: 12,
  },
  spinIcon: {
    animation: 'spin 1s linear infinite',
  },
  stateBox: {
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: 7,
    background: 'rgba(255, 255, 255, 0.035)',
    padding: 14,
    color: '#94a3b8',
    fontSize: 14,
  },
  warningBox: {
    marginTop: 16,
    borderRadius: 7,
    border: '1px solid rgba(251, 191, 36, 0.28)',
    background: 'rgba(251, 191, 36, 0.1)',
    padding: 14,
    color: '#fde68a',
    fontSize: 13,
    lineHeight: 1.45,
  },
  workOrderConstructor: {
    marginTop: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    borderTop: '1px solid rgba(255, 255, 255, 0.06)',
    background: 'rgba(17, 24, 39, 0.46)',
    paddingTop: 14,
  },
  workOrderLabel: {
    color: '#6b7280',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    lineHeight: 1.35,
  },
  workspace: {
    flex: 1,
    height: '100%',
    minHeight: 0,
    display: 'grid',
    gridTemplateColumns: '320px minmax(0, 1fr) 340px',
    overflow: 'hidden',
    background: 'radial-gradient(circle at top right, #0f172a, #030711 62%, #05070a)',
    color: '#e5e7eb',
    fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
}
