/**
 * media styles from the legacy `styles` object.
 *
 * Split for the same reason as `nvis`: a 1,033-line literal is not reviewable,
 * and each cluster belongs with the surface that uses it.
 */
import type { CSSProperties } from 'react'

export const baseMediaStyles: Record<string, CSSProperties> = {
  mediaLockPanel: {
    display: 'grid',
    gap: 14,
  },
  mediaLockStatusBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 0,
    border: '1px solid rgba(74, 158, 255, 0.28)',
    borderLeft: '8px solid #4a9eff',
    background: 'rgba(74, 158, 255, 0.08)',
    padding: '11px 13px',
    color: '#bfdbfe',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '0.10em',
    textTransform: 'uppercase',
  },
  mediaLockGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(420px, 1fr))',
    gap: 18,
  },
  mediaLockFrameGroup: {
    display: 'grid',
    gridTemplateRows: 'auto 1fr',
    minWidth: 0,
    borderRadius: 8,
    border: '1px solid rgba(148, 163, 184, 0.18)',
    background: 'rgba(15, 23, 42, 0.28)',
    overflow: 'hidden',
  },
  mediaLockGroupHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderBottom: '1px solid rgba(255,255,255,0.08)',
    background: '#050505',
    padding: '9px 11px',
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: 850,
    letterSpacing: '0.11em',
    textTransform: 'uppercase',
  },
  mediaLockGroupTitle: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  mediaLockLockedBadge: {
    flex: '0 0 auto',
    border: '1px solid rgba(16, 185, 129, 0.3)',
    background: 'rgba(16, 185, 129, 0.1)',
    color: '#10b981',
    padding: '2px 8px',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.05em',
  },
  mediaLockGroupFrames: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 8,
    padding: 8,
  },
  mediaLockFrame: {
    display: 'grid',
    gridTemplateRows: 'auto 1fr',
    minWidth: 0,
    borderRadius: 0,
    border: '1px solid rgba(255,255,255,0.10)',
    background: '#070707',
    overflow: 'hidden',
  },
  mediaLockThumb: {
    width: '100%',
    aspectRatio: '16 / 9',
    objectFit: 'cover',
    display: 'block',
    background: '#000',
  },
  mediaLockFrameBody: {
    display: 'grid',
    gap: 10,
    padding: 10,
    minWidth: 0,
  },
  mediaLockFrameTitle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: 850,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  mediaLockFacts: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    margin: 0,
    color: '#94a3b8',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 10,
    lineHeight: 1.25,
  },
  mediaLockFactRow: {
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    boxSizing: 'border-box',
    display: 'grid',
    gridTemplateColumns: '58px minmax(0, 1fr)',
    alignItems: 'center',
    columnGap: 8,
    overflow: 'hidden',
    borderBottom: '1px solid rgba(55, 65, 81, 0.42)',
    paddingBottom: 4,
  },
  mediaLockFactLabel: {
    flex: '0 0 auto',
    color: '#9ca3af',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  mediaLockFactValue: {
    minWidth: 0,
    justifySelf: 'end',
    maxWidth: '100%',
    color: '#e5e7eb',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    textAlign: 'right',
  },
  mediaLockPassValue: {
    color: '#d1d5db',
    fontWeight: 600,
  },
  mediaLockHashValue: {
    minWidth: 0,
    justifySelf: 'end',
    maxWidth: 'min(180px, 100%)',
    display: 'inline-block',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    color: '#9ca3af',
    fontWeight: 500,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    textAlign: 'right',
    verticalAlign: 'middle',
  },
}
