/**
 * stage styles from the legacy `styles` object.
 *
 * Split for the same reason as `nvis`: a 1,033-line literal is not reviewable,
 * and each cluster belongs with the surface that uses it.
 */
import type { CSSProperties } from 'react'

export const baseStageStyles: Record<string, CSSProperties> = {
  stageBoard: {
    minHeight: 0,
    flex: 1,
    overflow: 'auto',
    overflowX: 'hidden',
    padding: '0 0 20px',
    display: 'grid',
    gap: 14,
    alignContent: 'start',
    background: 'transparent',
  },
  stageAnchor: {
    scrollMarginTop: 76,
  },
  stageCard: {
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    background: 'rgba(13, 17, 23, 0.7)',
    padding: 24,
    display: 'grid',
    gap: 20,
    boxShadow: '0 20px 40px -10px rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(20px)',
    maxWidth: 'none',
    width: '100%',
    justifySelf: 'stretch',
    outline: '2px solid rgba(59, 130, 246, 0.12)',
    outlineOffset: 0,
    willChange: 'opacity, transform',
  },
  stageCardHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
  },
  stageHeaderStack: {
    display: 'grid',
    gap: 10,
  },
  stageIdentity: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 10,
    minWidth: 0,
  },
  stageHeaderActions: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    flexWrap: 'wrap',
    flex: '0 0 auto',
  },
  stageHeaderCopyBtn: {
    height: 32,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    padding: '0 12px',
    borderRadius: 999,
    border: '1px solid rgba(148, 163, 184, 0.22)',
    background: 'rgba(15, 23, 42, 0.42)',
    color: '#9fb5d1',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
    transition: 'color 180ms ease, border-color 180ms ease, background 180ms ease',
  },
  stageHeaderCopyLabel: {
    display: 'inline-block',
  },
  stageStatusHelp: {
    justifySelf: 'end',
    maxWidth: 760,
    borderRadius: 12,
    border: '1px solid rgba(251, 191, 36, 0.28)',
    background: 'rgba(251, 191, 36, 0.08)',
    padding: '10px 12px',
    color: '#fde68a',
    fontSize: 12,
    lineHeight: 1.45,
  },
  stageIcon: {
    width: 42,
    height: 42,
    flex: '0 0 auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    border: '1px solid rgba(96, 165, 250, 0.26)',
    background: 'rgba(59, 130, 246, 0.14)',
    color: '#93c5fd',
  },
  stageId: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 11,
    letterSpacing: '0.25em',
    textTransform: 'uppercase',
    color: 'rgba(59, 130, 246, 0.72)',
    lineHeight: 1.1,
  },
  stageTitle: {
    margin: 0,
    padding: 0,
    color: '#f9fafb',
    fontSize: 30,
    lineHeight: 1.1,
    fontWeight: 300,
    letterSpacing: '-0.02em',
  },
  stageTitleRule: {
    width: 64,
    height: 2,
    borderRadius: 999,
    marginTop: 4,
    background: 'rgba(37, 99, 235, 0.55)',
  },
  stageContentWell: {
    minHeight: 220,
    display: 'grid',
    gap: 14,
    borderRadius: 14,
    border: '1px solid rgba(255, 255, 255, 0.055)',
    background: 'rgba(0, 0, 0, 0.22)',
    padding: 16,
  },
  stageSummary: {
    margin: 0,
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 1.45,
  },
  stageImage: {
    width: '100%',
    aspectRatio: '16 / 10',
    objectFit: 'cover',
    display: 'block',
    background: '#000',
  },
  stageActionBox: {
    borderTop: '1px solid rgba(255, 255, 255, 0.06)',
    paddingTop: 18,
    display: 'grid',
    gap: 10,
  },
  stageTextarea: {
    width: '100%',
    minHeight: 78,
    resize: 'vertical',
    borderRadius: 12,
    border: '1px solid rgba(255, 255, 255, 0.12)',
    background: 'rgba(0, 0, 0, 0.25)',
    color: '#f8fafc',
    padding: 10,
    font: 'inherit',
    fontSize: 13,
    lineHeight: 1.4,
    outline: 'none',
  },
  stageActionRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  stageActionButton: {
    minHeight: 36,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    borderRadius: 999,
    border: '1px solid rgba(255, 255, 255, 0.1)',
    background: 'rgba(255, 255, 255, 0.055)',
    color: '#f8fafc',
    padding: '0 13px',
    cursor: 'pointer',
    fontSize: 13,
  },
  stageActionMeta: {
    color: '#94a3b8',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 11,
    lineHeight: 1.35,
    overflowWrap: 'anywhere',
  },
}
