/**
 * common styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const commonStyles: Record<string, CSSProperties> = {
  blockedCard: {
    borderColor: '#ff4444',
  },
  blockedBorder: {
    borderColor: '#ff4444',
  },
  chevronBtn: {
    width: 24,
    height: 24,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    border: 'none',
    background: 'transparent',
    color: 'rgba(255,255,255,0.5)',
    cursor: 'pointer',
    padding: 0,
    flexShrink: 0,
    transition: 'color 150ms ease, transform 150ms ease',
  },
  codeText: {
    color: '#e2e8f0',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 13,
    lineHeight: 1.4,
  },
  contextSummaryBar: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 12,
    margin: '0 16px 10px',
    padding: 14,
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 6,
    background: 'rgba(8,8,8,0.88)',
  },
  dataSpine: {
    display: 'grid',
    gridTemplateColumns: '40px minmax(0, 1fr)',
    gap: 20,
    padding: '20px 0',
    borderTop: '1px solid rgba(255,255,255,0.08)',
  },
  dimUppercase: {
    color: '#64748b',
    fontSize: 10,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  disabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  evidenceCard: {
    background: '#0b1220',
    border: '1px solid rgba(255,255,255,0.13)',
    borderRadius: 10,
    padding: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  evidenceCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  evidenceCardTitle: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  graphBtn: {
    position: 'absolute' as const,
    bottom: 8,
    right: 8,
    width: 28,
    height: 28,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.4)',
    color: '#64748b',
    cursor: 'pointer',
    padding: 0,
    transition: 'color 200ms ease, border-color 200ms ease',
  },
  graphInlineBtn: {
    width: 24,
    height: 24,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    border: '1px solid rgba(74,158,255,0.24)',
    background: 'transparent',
    color: '#4a9eff',
    cursor: 'pointer',
    padding: 0,
    flexShrink: 0,
    transition: 'color 200ms ease, border-color 200ms ease, background 200ms ease',
  },
  graphGhostBtn: {
    width: 28,
    height: 28,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    border: 'none',
    background: 'transparent',
    color: 'rgba(255,255,255,0.5)',
    cursor: 'pointer',
    padding: 0,
    flexShrink: 0,
    transition: 'color 150ms ease, background 150ms ease',
  },
  inspectorPrompt: {
    borderColor: '#7c3aed',
  },
  klingDeployBtn: {
    height: 28,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 0,
    border: 0,
    background: '#334155',
    color: '#64748b',
    padding: '0 14px',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    cursor: 'pointer',
  },
  klingDeployBtnReady: {
    background: '#10b981',
    color: '#022c22',
    boxShadow: '0 0 12px rgba(16, 185, 129, 0.3)',
    cursor: 'pointer',
  },
  modalCloseBtn: {
    position: 'absolute' as const,
    top: 12,
    right: 12,
    zIndex: 2,
    width: 34,
    height: 34,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(0,0,0,0.35)',
    color: '#e2e8f0',
    cursor: 'pointer',
    backdropFilter: 'blur(14px)',
  },
  moduleLabel: {
    color: '#64748b',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
  },
  moduleTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: 650,
    lineHeight: 1.25,
  },
  moduleBody: {
    margin: 0,
    color: '#aab7c9',
    fontSize: 13,
    lineHeight: 1.58,
    maxWidth: '55ch',
  },
  pathTraceHop: {
    color: '#4a9eff',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontWeight: 800,
  },
  pathTraceTarget: {
    color: '#fca5a5',
    fontWeight: 900,
  },
  pipelineNav: {
    display: 'flex',
    height: 40,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 8px',
    background: '#111111',
    flexShrink: 0,
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  pipelineNavInner: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    height: '100%',
    background: '#111111',
    position: 'relative' as const,
    isolation: 'isolate' as const,
  },
  pipelinePhaseBtn: {
    position: 'relative' as const,
    zIndex: 1,
    height: 40,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    gap: 8,
    border: 0,
    background: '#111111',
    color: '#64748b',
    cursor: 'pointer',
    transition: 'color 150ms ease',
  },
  pipelinePhaseBtnActive: {
    color: '#4a9eff',
    width: 'auto',
    minWidth: 96,
    padding: '0 12px',
  },
  pipelinePhaseLabel: {
    lineHeight: 1,
    color: '#e2e8f0',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  pipelineUnderline: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    width: '100%',
    height: 2,
    background: '#4a9eff',
  },
  pulseIcon: {
    animation: 'dream-pulse 1.5s ease-in-out infinite',
  },
  rerunIdeaBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    color: '#4a9eff',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    background: 'transparent',
    border: 0,
    cursor: 'pointer',
    padding: 0,
    textDecoration: 'none',
  },
  spineIconSlot: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingTop: 3,
  },
  spineIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 999,
    border: '1px solid rgba(122,167,232,0.26)',
    background: 'rgba(8,13,22,0.62)',
    color: '#7aa7e8',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spineContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 7,
    minWidth: 0,
  },
  stageGateAlert: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    margin: '8px 0 0',
    padding: '8px 28px',
    borderTop: '1px solid rgba(247,200,111,0.10)',
    borderBottom: '1px solid rgba(247,200,111,0.10)',
    background: 'rgba(247,200,111,0.035)',
  },
  stageGateAlertText: {
    color: '#aab7c9',
    fontSize: 12,
    lineHeight: 1.35,
  },
  storyMatrixBelowBoard: {
    width: '100%',
    margin: '24px 0 0',
  },
}
