/**
 * crew styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const crewStyles: Record<string, CSSProperties> = {
  crewConsole: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    marginBottom: 28,
    padding: '14px 0 18px',
    borderRadius: 0,
    border: 0,
    borderBottom: '1px solid rgba(255,255,255,0.10)',
    background: 'rgba(5,5,5,0.72)',
    boxShadow: 'none',
    backdropFilter: 'blur(14px)',
  },
  crewTopBar: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    alignItems: 'start',
    gap: 14,
    padding: '0 16px 16px',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  },
  crewTopMeta: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  crewStepPill: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 22,
    padding: '0 9px',
    borderRadius: 999,
    border: '1px solid rgba(122,167,232,0.18)',
    background: 'rgba(74,158,255,0.06)',
    color: '#9fb7d7',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  crewGatePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    minHeight: 22,
    padding: '0 9px',
    borderRadius: 999,
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  crewGatePillMissing: {
    color: '#f7c86f',
    border: '1px solid rgba(247,200,111,0.30)',
    background: 'rgba(247,200,111,0.08)',
  },
  crewGatePillReady: {
    color: '#6ee7b7',
    border: '1px solid rgba(110,231,183,0.26)',
    background: 'rgba(16,185,129,0.10)',
  },
  crewIntro: {
    margin: '8px 0 0',
    color: '#dbe4ef',
    fontSize: 16,
    lineHeight: 1.55,
    maxWidth: 980,
  },
  crewActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    gap: 12,
    minWidth: 0,
    width: '100%',
  },
  crewButtonGroup: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0,
    border: '1px solid rgba(122,167,232,0.14)',
    borderRadius: 12,
    overflow: 'hidden',
    background: 'rgba(5,5,5,0.42)',
  },
  crewStatusBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    minHeight: 36,
    margin: '0 16px',
    padding: '8px 0 10px',
    borderBottom: '1px solid rgba(247,200,111,0.14)',
  },
  crewStatusBannerText: {
    color: '#aab7c9',
    fontSize: 11,
    lineHeight: 1.35,
    minWidth: 0,
    flex: 1,
    maxWidth: 720,
  },
  crewMissingStrong: {
    color: '#e2e8f0',
    fontWeight: 800,
  },
  crewMissingCode: {
    color: '#f7c86f',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 11,
    background: 'rgba(247,200,111,0.07)',
    border: '1px solid rgba(247,200,111,0.14)',
    borderRadius: 5,
    padding: '1px 5px',
  },
  crewStatusBannerHint: {
    color: '#7f8fa5',
    fontSize: 10,
    marginTop: 2,
  },
  crewStatusBannerButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 28,
    padding: '0 10px',
    borderRadius: 999,
    border: '1px solid rgba(247,200,111,0.24)',
    background: 'rgba(247,200,111,0.06)',
    color: '#f7c86f',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  crewRoleGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 14,
    padding: '0 16px',
  },
  crewRoleCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    minWidth: 0,
    minHeight: 198,
    padding: 14,
    borderRadius: 12,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(16,16,16,0.72)',
    overflow: 'hidden',
  },
  crewRoleCardDisabled: {
    opacity: 0.52,
  },
  crewRoleLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    color: '#64748b',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
  },
  crewRoleDescription: {
    margin: 0,
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 1.55,
    maxHeight: 112,
    overflow: 'auto',
    paddingRight: 4,
  },
  crewRationale: {
    margin: 0,
    color: '#b7c4d8',
    fontSize: 12,
    lineHeight: 1.55,
    maxWidth: '55ch',
  },
  crewRoleHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    width: '100%',
    minHeight: 34,
  },
  crewRepairBridge: {
    display: 'grid',
    gridTemplateColumns: '40px minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 18,
    margin: '0 16px 4px',
    padding: '14px 0',
    borderTop: '1px solid rgba(247,200,111,0.22)',
    borderBottom: '1px solid rgba(247,200,111,0.14)',
  },
  crewRepairIcon: {
    width: 32,
    height: 32,
    borderRadius: 999,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#f7c86f',
    border: '1px solid rgba(247,200,111,0.30)',
    background: 'rgba(247,200,111,0.08)',
  },
  crewRepairCopy: {
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
    minWidth: 0,
  },
  crewRepairButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 34,
    padding: '0 12px',
    borderRadius: 10,
    border: '1px solid rgba(247,200,111,0.28)',
    background: 'rgba(247,200,111,0.07)',
    color: '#f7c86f',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  crewContextCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    minWidth: 0,
    minHeight: 0,
    padding: 0,
    borderRadius: 0,
    border: 0,
    background: 'transparent',
    overflow: 'hidden',
  },
  crewContextText: {
    margin: 0,
    color: '#aab7c9',
    fontSize: 12,
    lineHeight: 1.5,
  },
  crewThumbStrip: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 54,
    overflow: 'hidden',
  },
  crewThumb: {
    width: 56,
    height: 42,
    objectFit: 'cover' as const,
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#111111',
    flex: '0 0 auto',
  },
  crewProductionSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: '0 16px',
  },
  crewProductionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 12,
  },
  crewProductionCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    minHeight: 130,
    padding: 12,
    borderRadius: 12,
    border: '1px solid rgba(74,158,255,0.14)',
    background: 'rgba(8,13,22,0.64)',
    overflow: 'hidden',
  },
  crewPromptGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 14,
    padding: '0 16px',
  },
  crewPromptCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    minWidth: 0,
    minHeight: 148,
    padding: 14,
    borderRadius: 12,
    border: '1px solid rgba(74,158,255,0.14)',
    background: 'rgba(8,13,22,0.64)',
    overflow: 'hidden',
  },
  crewPromptTitle: {
    color: '#7aa7e8',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  crewPromptText: {
    margin: 0,
    color: '#cbd5e1',
    fontSize: 12,
    lineHeight: 1.55,
    maxHeight: 142,
    overflow: 'auto',
    paddingRight: 4,
  },
  crewMainWorkspace: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    padding: '0 16px',
  },
  crewSectionHeader: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    padding: '14px 0 8px',
  },
  crewPersonaThumb: {
    width: 34,
    height: 34,
    objectFit: 'cover' as const,
    borderRadius: 999,
    border: '1px solid rgba(122,167,232,0.32)',
    background: '#111111',
  },
}
