/**
 * director styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const directorStyles: Record<string, CSSProperties> = {
  directorConsole: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    marginBottom: 28,
    padding: '14px 0 18px',
    borderRadius: 0,
    border: 0,
    borderBottom: '1px solid rgba(255,255,255,0.10)',
    background: 'rgba(5,5,5,0.72)',
    boxShadow: 'none',
    backdropFilter: 'blur(14px)',
    transition: 'border-color 220ms ease, box-shadow 220ms ease',
  },
  directorHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
  },
  directorEyebrow: {
    color: '#e2e8f0',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
    paddingLeft: 12,
    borderLeft: '3px solid #4a9eff',
  },
  directorTitle: {
    margin: '4px 0 0',
    color: '#e2e8f0',
    fontSize: 18,
    fontWeight: 500,
    letterSpacing: 0,
  },
  directorGenerateBtn: {
    height: 30,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minWidth: 112,
    padding: '0 16px',
    borderRadius: 10,
    border: '1px solid rgba(255,255,255,0.10)',
    background: 'transparent',
    color: 'rgba(255,255,255,0.72)',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
    transition: 'color 260ms ease, border-color 260ms ease, background 260ms ease, box-shadow 260ms ease',
  },
  directorBtnDisabled: {
    cursor: 'wait',
    opacity: 0.62,
  },
  directorDebugBtn: {
    height: 30,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minWidth: 98,
    padding: '0 11px',
    borderRadius: 10,
    border: '1px solid rgba(255,255,255,0.10)',
    background: 'transparent',
    color: '#64748b',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
    transition: 'color 220ms ease, border-color 220ms ease, background 220ms ease',
  },
  directorControls: {
    display: 'grid',
    gridTemplateColumns: '120px minmax(0, 1fr)',
    alignItems: 'start',
    gap: 18,
    padding: '0 16px',
    width: '100%',
  },
  directorCommandColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    minWidth: 0,
    width: '100%',
  },
  directorCommandStrip: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    gap: 16,
    minWidth: 0,
    width: '100%',
  },
  directorIdeaBand: {
    display: 'grid',
    gridTemplateColumns: '120px minmax(0, 1fr)',
    alignItems: 'start',
    gap: 18,
    padding: '0 16px 16px',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  },
  directorIdeaText: {
    margin: 0,
    color: '#dbe4ef',
    fontSize: 17,
    lineHeight: 1.55,
    fontWeight: 400,
    letterSpacing: 0,
  },
  directorControlGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
    flex: '1 1 190px',
  },
  directorAuthorGroup: {
    display: 'inline-flex',
    alignItems: 'center',
    minWidth: 150,
    flex: '0 0 auto',
  },
  directorLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    color: '#64748b',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
  },
  directorSliderGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    minWidth: 0,
    flex: '1 1 220px',
    maxWidth: 560,
  },
  directorSliderHeader: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
    flex: '0 0 auto',
  },
  directorRange: {
    width: '100%',
    height: 1,
    accentColor: '#4a9eff',
    cursor: 'pointer',
  },
  directorNumberGroup: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 9,
    flex: '0 0 auto',
  },
  directorNumberInput: {
    width: 52,
    height: 30,
    borderRadius: 10,
    border: '1px solid rgba(255,255,255,0.10)',
    background: 'rgba(255,255,255,0.03)',
    color: '#e2e8f0',
    padding: '0 8px',
    fontSize: 12,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    outline: 'none',
    boxShadow: 'none',
  },
  directorInlineStylePreview: {
    display: 'grid',
    gridTemplateColumns: '110px minmax(0, 1fr)',
    alignItems: 'start',
    gap: 12,
    padding: '10px 0 0',
    borderTop: '1px solid rgba(255,255,255,0.05)',
  },
  directorInlineStyleLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    color: '#64748b',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  directorStyleText: {
    margin: 0,
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 1.55,
    maxWidth: 980,
  },
  directorValue: {
    color: '#94a3b8',
    fontSize: 11,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  directorSelect: {
    height: 30,
    borderRadius: 0,
    border: 0,
    background: 'transparent',
    color: '#e2e8f0',
    padding: '0 20px 0 2px',
    fontSize: 12,
    minWidth: 0,
    width: '100%',
    outline: 'none',
    boxShadow: 'none',
    WebkitAppearance: 'none' as const,
    appearance: 'none' as const,
    cursor: 'pointer',
  },
  directorSelectWrap: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    minWidth: 150,
    maxWidth: 220,
  },
  directorSelectIcon: {
    position: 'absolute',
    right: 2,
    color: '#64748b',
    pointerEvents: 'none' as const,
  },
  directorStatusRow: {
    display: 'grid',
    gridTemplateColumns: '120px minmax(0, 1fr)',
    alignItems: 'start',
    gap: 18,
    padding: '0 16px',
  },
  directorStatus: {
    color: '#94a3b8',
    fontSize: 11,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    paddingTop: 2,
  },
  directorStoryAreaWrap: {
    display: 'grid',
    gridTemplateColumns: '120px minmax(0, 1fr)',
    alignItems: 'start',
    gap: 18,
    padding: '0 16px',
  },
  directorStoryContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    minWidth: 0,
  },
  directorStoryCanvas: {
    minHeight: 156,
    padding: 0,
    borderRadius: 12,
    border: 'none',
    background: 'transparent',
    color: '#d1d5db',
    fontSize: 16,
    lineHeight: 1.7,
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    whiteSpace: 'pre-wrap' as const,
    overflow: 'hidden',
  },
  directorStoryPlaceholder: {
    color: '#64748b',
    display: 'block',
    padding: 20,
  },
  directorJsonDetails: {
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 10,
    background: 'rgba(255,255,255,0.02)',
    padding: '8px 10px',
  },
  directorJsonSummary: {
    cursor: 'pointer',
    color: '#64748b',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
  },
  directorStoryArea: {
    minHeight: 140,
    resize: 'vertical' as const,
    width: '100%',
    margin: 0,
    marginTop: 10,
    padding: 16,
    borderRadius: 12,
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#101010',
    color: '#e2e8f0',
    fontSize: 14,
    lineHeight: 1.65,
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    outline: 'none',
  },
}
