/**
 * idea styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const ideaStyles: Record<string, CSSProperties> = {
  ideaMemoryCanvas: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    padding: 0,
    background: 'transparent',
    borderRadius: 0,
    transition: 'background 420ms ease',
  },
  ideaMemoryCanvasEditing: {
    background: 'linear-gradient(180deg, rgba(23, 24, 21, 0.72) 0%, rgba(20, 20, 20, 0) 42%)',
  },
  ideaComposer: {
    position: 'relative' as const,
    width: 'min(896px, calc(100% - 64px))',
    margin: '0 auto',
    padding: '34px 32px 22px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 18,
    borderRadius: 0,
    border: 0,
    background: 'transparent',
  },
  ideaComposerHeader: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  ideaEditAffordance: {
    minWidth: 0,
    height: 24,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 999,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(255,255,255,0.035)',
    color: '#64748b',
    cursor: 'pointer',
    padding: '0 9px',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    transition: 'color 180ms ease, border-color 180ms ease, background 180ms ease',
  },
  ideaComposerLabel: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.25em',
    lineHeight: 1,
    textTransform: 'uppercase' as const,
  },
  ideaComposerInput: {
    width: '100%',
    resize: 'none' as const,
    overflow: 'hidden',
    minHeight: 0,
    border: 0,
    outline: 0,
    background: 'transparent',
    color: '#e2e8f0',
    fontSize: 30,
    fontWeight: 300,
    lineHeight: 1.4,
    textAlign: 'center' as const,
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    borderBottom: 0,
    padding: '14px 18px',
    borderRadius: 14,
    transition: 'border-color 220ms ease, color 220ms ease, opacity 420ms ease, background 220ms ease, box-shadow 220ms ease',
    animation: 'dream-soft-fade 420ms ease-out both',
  },
  ideaComposerActions: {
    minHeight: 18,
    display: 'flex',
    justifyContent: 'center',
    marginTop: 8,
    opacity: 0.6,
    transition: 'opacity 180ms ease',
  },
  ideaComposerAction: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    color: '#4a9eff',
    background: 'transparent',
    border: 0,
    padding: 0,
    cursor: 'pointer',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
  },
  ideaComposerDot: {
    width: 32,
    height: 1,
    borderRadius: 0,
    background: '#4a9eff',
  },
  ideaComposerStatus: {
    color: '#ffaa00',
    fontSize: 10,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    animation: 'dream-pulse 1.5s ease-in-out infinite',
  },
}
