/**
 * matrix styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const matrixStyles: Record<string, CSSProperties> = {
  matrixCard: {
    background: 'transparent',
    padding: '28px 0 0',
    borderRadius: 0,
    border: 0,
    borderTop: '1px solid rgba(255,255,255,0.08)',
  },
  matrixMetaGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 0.8fr) minmax(0, 1.2fr)',
    gap: 14,
    marginBottom: 24,
  },
  matrixReadyPill: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    minWidth: 58,
    height: 20,
    borderRadius: 999,
    border: '1px solid rgba(34,197,94,0.24)',
    background: 'rgba(34,197,94,0.10)',
    color: '#4ade80',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  },
  matrixMutedPill: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    minWidth: 58,
    height: 20,
    borderRadius: 999,
    border: '1px solid rgba(148,163,184,0.18)',
    background: 'rgba(148,163,184,0.08)',
    color: '#94a3b8',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  },
  matrixPendingPill: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    minWidth: 0,
    height: 24,
    borderRadius: 5,
    border: '1px solid rgba(255,255,255,0.06)',
    background: 'rgba(26,26,26,0.72)',
    color: 'rgba(255,255,255,0.72)',
    padding: '0 8px',
    fontSize: 8,
    fontWeight: 800,
    letterSpacing: '0.10em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
  },
  matrixMetaItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: 14,
    borderRadius: 14,
    border: '1px solid rgba(255,255,255,0.07)',
    background: 'rgba(20,20,20,0.62)',
  },
  matrixMetaLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    color: '#64748b',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
  },
  matrixMetaValue: {
    color: '#e2e8f0',
    fontSize: 13,
    lineHeight: 1.5,
  },
  matrixSectionTitle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    margin: '0 0 12px',
    color: '#64748b',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
  },
  matrixEnv: {
    marginBottom: 14,
    fontSize: 11,
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  matrixTable: {
    width: '100%',
    fontSize: 12,
    color: '#e2e8f0',
    borderCollapse: 'collapse' as const,
  },
  matrixHeaderRow: {
    color: '#64748b',
    textAlign: 'left' as const,
    borderBottom: '1px solid #334155',
  },
  matrixTh: {
    padding: '6px 4px',
    fontWeight: 600,
  },
  matrixRow: {
    borderBottom: '1px solid #334155',
  },
  matrixTd: {
    padding: '8px 4px',
  },
}
