/**
 * memory styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const memoryStyles: Record<string, CSSProperties> = {
  memoryBoardSection: {
    minHeight: '100%',
    width: '100%',
  },
  memoryNode: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: 12,
    padding: 24,
    borderRadius: 24,
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.05)',
    backdropFilter: 'blur(20px)',
    boxShadow: '0 2px 12px rgba(0,0,0,0.08)',
    transition: 'all 300ms ease',
    cursor: 'default',
    overflow: 'hidden',
  },
  memoryTextNode: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: 12,
    padding: 24,
    borderRadius: 20,
    background: 'rgba(26,26,26,0.4)',
    border: '1px solid transparent',
    boxShadow: 'none',
    transition: 'all 300ms ease',
    cursor: 'grab',
    overflow: 'hidden',
  },
  memoryMediaNode: {
    width: '100%',
    position: 'relative' as const,
    display: 'block',
    padding: 0,
    borderRadius: 14,
    background: 'transparent',
    border: 'none',
    boxShadow: 'none',
    transition: 'transform 300ms ease, filter 300ms ease',
    cursor: 'default',
    overflow: 'hidden',
  },
  memoryMediaCard: {
    width: '100%',
    position: 'relative' as const,
    display: 'block',
    padding: 0,
    borderRadius: 18,
    background: '#141414',
    border: '1px solid rgba(255,255,255,0.05)',
    boxShadow: 'none',
    transition: 'transform 300ms ease, border-color 300ms ease, box-shadow 300ms ease',
    cursor: 'default',
    overflow: 'hidden',
  },
  memoryTextCard: {
    width: '100%',
    position: 'relative' as const,
    display: 'block',
    padding: 20,
    borderRadius: 18,
    background: '#141414',
    border: '1px solid rgba(255,255,255,0.05)',
    boxShadow: 'none',
    transition: 'transform 300ms ease, border-color 300ms ease, box-shadow 300ms ease',
    cursor: 'grab',
    overflow: 'hidden',
  },
  memoryUnifiedCard: {
    width: '100%',
    position: 'relative' as const,
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    padding: 0,
    borderRadius: 18,
    background: 'rgba(26,26,26,0.4)',
    border: '1px solid rgba(255,255,255,0.05)',
    boxShadow: 'none',
    transition: 'transform 300ms ease, background 300ms ease, border-color 300ms ease, box-shadow 300ms ease',
    cursor: 'grab',
    overflow: 'hidden',
  },
  memoryMediaButton: {
    width: '100%',
    display: 'block',
    padding: 0,
    margin: 0,
    border: 0,
    background: 'transparent',
    borderRadius: 0,
    overflow: 'hidden',
    cursor: 'zoom-in',
  },
  memoryFullBleedMedia: {
    width: '100%',
    height: 'auto',
    objectFit: 'contain' as const,
    display: 'block',
    pointerEvents: 'none' as const,
    transition: 'transform 700ms ease',
  },
  memoryAudioPreview: {
    width: '100%',
    minHeight: 160,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 0,
    padding: 16,
    borderRadius: 0,
    background: 'rgba(26,26,26,0.4)',
    cursor: 'zoom-in',
  },
  memoryMediaShelf: {
    position: 'absolute' as const,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 10,
    minHeight: 44,
    padding: '9px 12px 10px',
    background: 'linear-gradient(to top, rgba(0,0,0,0.74), rgba(0,0,0,0.34))',
    backdropFilter: 'blur(10px)',
    pointerEvents: 'auto' as const,
    transition: 'transform 260ms ease',
  },
  memoryOverlayText: {
    margin: 0,
    color: '#f8fafc',
    fontSize: 12,
    lineHeight: 1.38,
    fontWeight: 500,
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  memoryTextCardBody: {
    display: 'block',
  },
  memoryTextParagraph: {
    margin: 0,
    color: '#a0aec0',
    fontSize: 13,
    lineHeight: 1.62,
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
  },
  memoryTextDisclosure: {
    position: 'relative' as const,
    alignSelf: 'flex-end' as const,
    marginTop: 14,
    padding: '4px 8px',
    borderTop: 0,
    background: 'rgba(20,20,20,0.88)',
    backdropFilter: 'blur(8px)',
    borderRadius: 10,
    display: 'inline-flex',
    alignItems: 'center',
    transition: 'transform 260ms ease',
  },
  memorySemanticSignal: {
    position: 'absolute' as const,
    left: 16,
    bottom: 16,
    zIndex: 4,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 5,
    pointerEvents: 'auto' as const,
  },
  memoryTraceNodeRow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    opacity: 0,
    transform: 'translateY(4px)',
    transition: 'opacity 180ms ease, transform 180ms ease',
  },
  memoryTraceNode: {
    height: 22,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(0,0,0,0.46)',
    backdropFilter: 'blur(8px)',
    color: 'rgba(255,255,255,0.78)',
    padding: '0 7px',
    cursor: 'help',
    flex: '0 0 auto',
  },
  memoryTraceNodeDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    flex: '0 0 auto',
  },
  memoryTraceNodeDepth: {
    color: '#f8fafc',
    fontSize: 8,
    fontWeight: 900,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    letterSpacing: '0.05em',
  },
  memoryTraceNodeLabel: {
    maxWidth: 78,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    color: '#cbd5e1',
    fontSize: 8,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  },
  memoryPathTraceStack: {
    display: 'inline-flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 3,
    opacity: 0,
    transform: 'translateY(4px)',
    transition: 'opacity 180ms ease, transform 180ms ease',
    pointerEvents: 'none' as const,
  },
  memoryPathTraceChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 3,
    color: 'rgba(255,255,255,0.74)',
    background: 'rgba(0,0,0,0.52)',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 5,
    padding: '3px 6px',
    fontSize: 8,
    fontWeight: 800,
    letterSpacing: '0.10em',
    textTransform: 'uppercase' as const,
    whiteSpace: 'nowrap' as const,
  },
  memoryPathTraceHop: {
    color: '#4a9eff',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  memoryPathTraceTarget: {
    color: '#f8fafc',
    fontWeight: 900,
  },
  memorySemanticActive: {
    borderColor: 'rgba(74,158,255,0.42)',
    boxShadow: '0 0 0 1px rgba(74,158,255,0.14), 0 18px 42px rgba(74,158,255,0.10)',
  },
  memoryCardBody: {
    width: '100%',
    padding: '16px 16px 10px',
  },
  memoryCardActions: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '0 16px 16px',
  },
  memoryMediaOverlay: {
    position: 'absolute' as const,
    inset: '8px 8px auto auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
    pointerEvents: 'auto' as const,
  },
  memoryTextActions: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  memoryLabel: {
    color: '#a0aec0',
    fontSize: 13,
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    lineHeight: 1.6,
    display: '-webkit-box',
    WebkitLineClamp: 8,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  memoryScore: {
    color: '#64748b',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    marginTop: 2,
  },
  memorySelect: {
    background: 'transparent',
    color: '#4a9eff',
    fontSize: 10,
    padding: '4px 6px',
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.08)',
    cursor: 'pointer',
    flexShrink: 0,
  },
  memoryList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  memoryMasonry: {
    width: '100%',
    maxWidth: 1240,
    margin: '0 auto',
    padding: '18px 32px 80px',
    overflow: 'visible',
  },
  memoryInspectorModal: {
    position: 'relative' as const,
    width: 'min(720px, calc(100vw - 48px))',
    maxHeight: 'calc(100vh - 48px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    borderRadius: 24,
    border: '1px solid rgba(255,255,255,0.1)',
    background: 'rgba(20,20,20,0.9)',
    boxShadow: '0 28px 80px rgba(0,0,0,0.48)',
    backdropFilter: 'blur(22px)',
    cursor: 'default',
  },
  memoryInspectorMedia: {
    width: '100%',
    maxHeight: 'calc(100vh - 120px)',
    objectFit: 'contain' as const,
    borderRadius: 16,
    background: 'rgba(0,0,0,0.22)',
    display: 'block',
  },
  memoryInspectorAudio: {
    width: '100%',
    padding: '52px 24px 24px',
    borderRadius: 18,
    background: 'rgba(255,255,255,0.04)',
  },
}
