/**
 * provider styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const providerStyles: Record<string, CSSProperties> = {
  providerContractPanel: {
    display: 'grid',
    gap: 16,
  },
  providerContractMissing: {
    display: 'grid',
    gap: 12,
    padding: 16,
    borderRadius: 8,
    border: '1px solid rgba(251, 191, 36, 0.32)',
    borderLeft: '8px solid #f59e0b',
    background: 'rgba(120, 53, 15, 0.18)',
    color: '#fde68a',
    lineHeight: 1.45,
  },
  providerContractCommand: {
    margin: 0,
    padding: 12,
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.42)',
    color: '#e5e7eb',
    fontSize: 11,
    lineHeight: 1.45,
    whiteSpace: 'pre-wrap',
    overflowX: 'auto',
  },
  providerContractKpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: 12,
  },
  providerContractKpiCard: {
    minHeight: 96,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: 10,
    padding: 14,
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#0a0a0a',
    overflow: 'hidden',
  },
  providerContractKpiPass: {
    borderLeft: '6px solid #22c55e',
  },
  providerContractKpiDry: {
    borderLeft: '6px solid #4a9eff',
  },
  providerContractKpiBlocked: {
    borderLeft: '6px solid #f59e0b',
    background: 'rgba(120, 53, 15, 0.12)',
  },
  providerContractKpiLabel: {
    color: '#a8b3c7',
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  providerContractKpiValue: {
    color: '#f8fafc',
    fontSize: 18,
    lineHeight: 1.08,
    fontWeight: 900,
    letterSpacing: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  providerContractKpiDetail: {
    color: '#a8b3c7',
    fontSize: 11,
    lineHeight: 1.3,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  providerContractRibbon: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(160px, 1fr))',
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(2,6,23,0.48)',
    overflowX: 'auto',
    overflowY: 'hidden',
  },
  providerContractRibbonMetric: {
    minWidth: 0,
    display: 'grid',
    gap: 6,
    padding: '12px 14px',
    borderRight: '1px solid rgba(255,255,255,0.07)',
  },
  providerContractRibbonLabel: {
    color: '#64748b',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  providerContractRibbonValue: {
    minWidth: 0,
    fontSize: 12,
    lineHeight: 1.25,
    fontWeight: 800,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  providerContractRibbonValuePass: {
    color: '#4ade80',
  },
  providerContractRibbonValueDry: {
    color: '#facc15',
  },
  providerContractRibbonValueBlocked: {
    color: '#fb7185',
  },
  providerContractSplit: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: 14,
  },
  providerContractValidationGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))',
    gap: 14,
    alignItems: 'start',
  },
  providerContractBlockersPanel: {
    borderColor: 'rgba(245,158,11,0.22)',
    background: 'rgba(120,53,15,0.08)',
  },
  providerContractNonClaimsPanel: {
    borderColor: 'rgba(148,163,184,0.16)',
    background: 'rgba(15,23,42,0.22)',
  },
  providerContractSection: {
    minWidth: 0,
    padding: 16,
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#0a0a0a',
  },
  providerContractPanelPayloadList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(520px, 1fr))',
    gap: 12,
  },
  providerContractPanelPayload: {
    minWidth: 0,
    display: 'grid',
    gap: 10,
    padding: 12,
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(255,255,255,0.018)',
  },
  providerContractPanelPayloadSelected: {
    minWidth: 0,
    display: 'grid',
    gap: 10,
    padding: 12,
    borderRadius: 6,
    border: '1px solid rgba(34,197,94,0.28)',
    borderLeft: '6px solid #22c55e',
    background: 'rgba(20,83,45,0.12)',
  },
  providerContractPanelPayloadHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: 850,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  providerContractPanelPayloadFrames: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 10,
  },
  providerContractFrameState: {
    minWidth: 0,
    display: 'grid',
    gap: 8,
    padding: 10,
    borderRadius: 4,
    border: '1px solid rgba(255,255,255,0.07)',
    background: 'rgba(0,0,0,0.28)',
  },
  providerContractFrameHeader: {
    display: 'grid',
    gridTemplateColumns: '52px minmax(0, 1fr)',
    gap: 10,
    alignItems: 'center',
    color: '#dbeafe',
    fontSize: 11,
    fontWeight: 850,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    overflow: 'hidden',
  },
  providerContractFramePreview: {
    position: 'relative',
    display: 'grid',
    gap: 6,
  },
  providerContractFrameImage: {
    width: '100%',
    aspectRatio: '16 / 9',
    objectFit: 'cover',
    borderRadius: 4,
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#020617',
  },
  providerContractFrameCaption: {
    minHeight: 24,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: '0 7px',
    borderRadius: 4,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(15,23,42,0.46)',
    color: '#64748b',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  providerContractFrameCaptionIcon: {
    color: 'rgba(245,158,11,0.76)',
    flex: '0 0 auto',
  },
  providerContractFrameRows: {
    display: 'grid',
    gap: 0,
    padding: 10,
    borderRadius: 4,
    border: '1px solid rgba(255,255,255,0.06)',
    background: 'rgba(2,6,23,0.46)',
  },
  providerContractMetadataRow: {
    display: 'grid',
    gridTemplateColumns: '92px minmax(0, 1fr)',
    alignItems: 'center',
    gap: 14,
    minWidth: 0,
    padding: '5px 0',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    fontSize: 10,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  providerContractMetaLabel: {
    color: '#64748b',
    fontWeight: 850,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  providerContractMetaValue: {
    minWidth: 0,
    color: '#cbd5e1',
    fontWeight: 650,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    textAlign: 'left',
  },
  providerContractMetaValueSuccess: {
    minWidth: 0,
    color: '#22c55e',
    fontWeight: 850,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    textAlign: 'left',
  },
  providerContractMetaValueWarning: {
    minWidth: 0,
    color: '#f59e0b',
    fontWeight: 850,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    textAlign: 'left',
  },
  providerContractMetaValueMuted: {
    minWidth: 0,
    color: '#64748b',
    fontWeight: 650,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    textAlign: 'left',
  },
  providerContractPanelPayloadJson: {
    display: 'grid',
    gap: 8,
    padding: 10,
    borderRadius: 4,
    border: '1px solid rgba(74,158,255,0.18)',
    background: 'rgba(74,158,255,0.07)',
    color: '#bfdbfe',
    fontSize: 10,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    overflow: 'hidden',
  },
  providerContractPanelPayloadJsonMuted: {
    display: 'grid',
    gap: 8,
    padding: 10,
    borderRadius: 4,
    border: '1px solid rgba(148,163,184,0.16)',
    background: 'rgba(15,23,42,0.36)',
    color: '#94a3b8',
    fontSize: 10,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    overflow: 'hidden',
  },
  providerContractDistillationTextBlock: {
    display: 'grid',
    gap: 9,
    padding: 10,
    borderRadius: 4,
    border: '1px solid rgba(255,255,255,0.07)',
    background: 'rgba(2,6,23,0.42)',
  },
  providerContractDistillationTextItem: {
    display: 'grid',
    gap: 5,
    minWidth: 0,
  },
  providerContractDistillationLabel: {
    color: '#64748b',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  providerContractDistillationText: {
    whiteSpace: 'pre-wrap',
    margin: 0,
    color: '#cbd5e1',
    fontSize: 11,
    lineHeight: 1.45,
    overflowWrap: 'anywhere',
  },
  providerContractDistillationAudio: {
    justifySelf: 'start',
    maxWidth: '100%',
    padding: '3px 7px',
    borderRadius: 4,
    border: '1px solid rgba(34,211,238,0.22)',
    background: 'rgba(8,145,178,0.12)',
    color: '#67e8f9',
    fontSize: 10,
    fontWeight: 850,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  providerContractPanelSummary: {
    display: 'block',
    minWidth: 0,
    color: '#8ba1bd',
    fontSize: 10,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  providerContractAudioPillRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    minWidth: 0,
  },
  providerContractAudioPill: {
    display: 'inline-flex',
    alignItems: 'stretch',
    minHeight: 22,
    borderRadius: 4,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(2,6,23,0.42)',
    overflow: 'hidden',
  },
  providerContractAudioPillLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0 6px',
    borderRight: '1px solid rgba(255,255,255,0.08)',
    color: '#64748b',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  providerContractAudioPillValue: {
    display: 'inline-flex',
    alignItems: 'center',
    maxWidth: 160,
    padding: '0 7px',
    fontSize: 10,
    fontWeight: 850,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  providerContractAudioPillValueNeutral: {
    color: '#67e8f9',
  },
  providerContractAudioPillValueWarning: {
    color: '#fbbf24',
  },
  providerContractPanelPayloadDetails: {
    borderRadius: 4,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.24)',
    overflow: 'hidden',
  },
  providerContractPanelPayloadSummary: {
    minHeight: 36,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: '0 10px',
    color: '#bfdbfe',
    cursor: 'pointer',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    userSelect: 'none',
  },
  providerContractPanelPayloadPre: {
    margin: 0,
    maxHeight: 260,
    overflow: 'auto',
    padding: 10,
    borderTop: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.38)',
    color: '#dbeafe',
    fontSize: 10,
    lineHeight: 1.45,
    whiteSpace: 'pre',
  },
  providerContractSyntaxShell: {
    borderRadius: 4,
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#1e1e1e',
    overflow: 'hidden',
  },
  providerContractSyntaxToolbar: {
    minHeight: 32,
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    padding: '0 10px',
    borderBottom: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(15,23,42,0.72)',
    color: '#94a3b8',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  providerContractSyntaxHighlighter: {
    margin: 0,
    padding: 12,
    background: 'transparent',
    fontSize: 10,
    lineHeight: 1.45,
    overflow: 'auto',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
  },
  providerContractSyntaxCode: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  providerContractSyntaxKey: {
    color: '#9cdcfe',
  },
  providerContractSyntaxString: {
    color: '#ce9178',
  },
  providerContractSyntaxNumber: {
    color: '#b5cea8',
  },
  providerContractSyntaxBoolean: {
    color: '#569cd6',
  },
  providerContractSyntaxPunctuation: {
    color: '#d4d4d4',
  },
  providerContractMapping: {
    display: 'grid',
    borderRadius: 6,
    overflow: 'hidden',
    border: '1px solid rgba(255,255,255,0.07)',
  },
  providerContractMappingHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '9px 10px',
    background: 'rgba(255,255,255,0.04)',
    color: '#a8b3c7',
    fontSize: 9,
    fontWeight: 850,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  providerContractMappingHeaderField: {
    flex: '0 1 34%',
    minWidth: 132,
  },
  providerContractMappingHeaderSource: {
    flex: '1 1 auto',
    minWidth: 0,
  },
  providerContractMappingHeaderStatus: {
    flex: '0 0 auto',
    minWidth: 170,
    textAlign: 'right' as const,
  },
  providerContractMappingRow: {
    display: 'flex',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px',
    borderTop: '1px solid rgba(255,255,255,0.06)',
    color: '#dbeafe',
    fontSize: 11,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    minWidth: 0,
  },
  providerContractMappingField: {
    flex: '0 1 34%',
    minWidth: 132,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  providerContractMappingSource: {
    flex: '1 1 auto',
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: '#8ba1bd',
  },
  providerContractMappingStatus: {
    flex: '0 0 auto',
    display: 'flex',
    justifyContent: 'flex-end',
    minWidth: 170,
  },
  providerContractBoundaryGrid: {
    display: 'grid',
    gap: 0,
    padding: '4px 2px',
    borderRadius: 5,
    border: '1px solid rgba(255,255,255,0.06)',
    background: 'rgba(15,23,42,0.20)',
  },
  providerContractStateCard: {
    display: 'grid',
    gridTemplateColumns: '116px minmax(0, 1fr)',
    alignItems: 'center',
    gap: 12,
    padding: '9px 10px',
    borderTop: '1px solid rgba(255,255,255,0.055)',
  },
  providerContractStateLabel: {
    color: '#a8b3c7',
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  providerContractStateDetail: {
    gridColumn: '2',
    color: '#a8b3c7',
    fontSize: 11,
    lineHeight: 1.3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  providerContractPillPass: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 24,
    borderRadius: 5,
    border: '1px solid rgba(34,197,94,0.28)',
    background: 'rgba(34,197,94,0.10)',
    color: '#86efac',
    padding: '3px 8px',
    fontSize: 9,
    fontWeight: 850,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    justifySelf: 'end',
  },
  providerContractPillDry: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 24,
    borderRadius: 5,
    border: '1px solid rgba(74,158,255,0.28)',
    background: 'rgba(74,158,255,0.10)',
    color: '#bfdbfe',
    padding: '3px 8px',
    fontSize: 9,
    fontWeight: 850,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    justifySelf: 'end',
  },
  providerContractPillBlocked: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 24,
    borderRadius: 5,
    border: '1px solid rgba(245,158,11,0.35)',
    background: 'rgba(245,158,11,0.12)',
    color: '#fcd34d',
    padding: '3px 8px',
    fontSize: 9,
    fontWeight: 850,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    justifySelf: 'end',
  },
  providerContractBlockerGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))',
    gap: 8,
  },
  providerContractBlockerPill: {
    borderRadius: 5,
    border: '1px solid rgba(248,113,113,0.32)',
    background: 'rgba(127,29,29,0.18)',
    color: '#fecaca',
    padding: '8px 9px',
    fontSize: 10,
    fontWeight: 800,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    overflowWrap: 'anywhere',
    textTransform: 'uppercase',
  },
  providerContractLiveBlockerPill: {
    borderRadius: 5,
    border: '1px solid rgba(245,158,11,0.32)',
    background: 'rgba(120,53,15,0.18)',
    color: '#fde68a',
    padding: '8px 9px',
    fontSize: 10,
    fontWeight: 800,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    overflowWrap: 'anywhere',
    textTransform: 'uppercase',
  },
  providerContractNeutralPill: {
    borderRadius: 5,
    border: '1px solid rgba(34,197,94,0.22)',
    background: 'rgba(20,83,45,0.14)',
    color: '#bbf7d0',
    padding: '8px 9px',
    fontSize: 10,
    fontWeight: 800,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    overflowWrap: 'anywhere',
    textTransform: 'uppercase',
  },
  providerContractNonClaims: {
    display: 'grid',
    gap: 8,
    margin: 0,
    padding: 0,
    listStyle: 'none',
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 1.45,
  },
  providerContractNonClaimItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    minWidth: 0,
    color: '#94a3b8',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 11,
  },
  providerContractNonClaimIcon: {
    flex: '0 0 auto',
    marginTop: 1,
    color: '#475569',
  },
  providerContractDetails: {
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#0a0a0a',
    overflow: 'hidden',
  },
  providerContractSummary: {
    minHeight: 48,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '0 14px',
    cursor: 'pointer',
    color: '#cbd5e1',
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    userSelect: 'none',
  },
  providerContractSummaryMeta: {
    color: '#8ba1bd',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    whiteSpace: 'nowrap',
  },
  providerContractJsonToolbar: {
    minHeight: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '0 14px',
    borderTop: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(255,255,255,0.03)',
    color: '#8ba1bd',
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  providerContractCopyButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    height: 30,
    padding: '0 10px',
    borderRadius: 4,
    border: '1px solid rgba(74,158,255,0.34)',
    background: 'rgba(74,158,255,0.10)',
    color: '#bfdbfe',
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  providerContractJsonPre: {
    margin: 0,
    padding: 14,
    maxHeight: 360,
    overflow: 'auto',
    borderTop: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.36)',
    color: '#dbeafe',
    fontSize: 11,
    lineHeight: 1.45,
  },
}
