/**
 * script styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const scriptStyles: Record<string, CSSProperties> = {
  scriptPhaseDescription: {
    margin: 0,
    color: '#9ca3af',
    fontSize: 13,
    lineHeight: 1.5,
    maxWidth: '75ch',
  },
  scriptStoryAreaWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
    padding: '0 16px',
    minWidth: 0,
  },
  scriptSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    marginTop: 18,
    marginBottom: 2,
  },
  scriptSectionRule: {
    flex: '0 0 56px',
    height: 1,
    background: 'rgba(255,255,255,0.10)',
  },
  scriptSectionRuleWide: {
    flex: 1,
    height: 1,
    background: 'rgba(255,255,255,0.10)',
  },
  scriptSectionTitle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    color: '#f3f4f6',
    fontSize: 12,
    fontWeight: 850,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
    whiteSpace: 'nowrap' as const,
  },
  scriptTableShell: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    marginTop: 2,
    paddingLeft: 22,
    position: 'relative',
    background: 'transparent',
    overflow: 'hidden',
  },
  scriptTableShellBefore: {},
  scriptTableRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    position: 'relative',
    padding: '20px 0 20px 22px',
    borderBottom: '1px solid rgba(255,255,255,0.08)',
    borderLeft: '1px solid rgba(74,158,255,0.18)',
  },
  scriptTableRowFailed: {
    borderLeft: '1px solid rgba(239,68,68,0.55)',
  },
  scriptTableHeader: {
    background: 'rgba(255,255,255,0.035)',
    color: '#64748b',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  },
  scriptCell: {
    minWidth: 0,
    padding: 0,
    color: '#dbe4ef',
    fontSize: 13,
    lineHeight: 1.58,
    whiteSpace: 'pre-wrap' as const,
    overflowWrap: 'break-word' as const,
  },
  scriptContentBlock: {
    minWidth: 0,
    padding: '8px 0 0',
    marginLeft: 0,
    borderLeft: 'none',
    color: '#d1d5db',
    fontSize: 15,
    lineHeight: 1.72,
    fontFamily: '"Courier Prime", "Roboto Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    whiteSpace: 'pre-wrap' as const,
    overflowWrap: 'break-word' as const,
  },
  scriptNotesCell: {
    paddingTop: 12,
    borderTop: '1px solid rgba(255,255,255,0.06)',
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 1.5,
    background: 'transparent',
  },
  scriptBeatHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    position: 'relative',
  },
  scriptStatusNodeBase: {
    position: 'absolute',
    left: -5,
    top: 30,
    width: 8,
    height: 8,
    borderRadius: 999,
    display: 'inline-block',
    zIndex: 2,
  },
  scriptStatusNodeVerified: {
    background: '#10B981',
    boxShadow: '0 0 8px rgba(16,185,129,0.4)',
  },
  scriptStatusNodeFailed: {
    background: '#EF4444',
    boxShadow: '0 0 8px rgba(239,68,68,0.5)',
  },
  scriptStatusNodePending: {
    background: 'transparent',
    border: '1px solid #6B7280',
  },
  scriptBeatHeaderDot: {},
  scriptElementTag: {
    display: 'inline-flex',
    alignItems: 'center',
    width: 'fit-content',
    padding: '4px 8px',
    borderRadius: 7,
    background: 'rgba(255,255,255,0.055)',
    color: '#aab7c9',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    whiteSpace: 'nowrap' as const,
  },
  scriptDurationTag: {
    display: 'inline-flex',
    alignItems: 'center',
    width: 'fit-content',
    padding: '4px 8px',
    borderRadius: 999,
    border: '1px solid rgba(74,158,255,0.22)',
    background: 'rgba(74,158,255,0.08)',
    color: '#93c5fd',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    whiteSpace: 'nowrap' as const,
  },
  scriptCoverage: {
    padding: 16,
    background: 'transparent',
  },
  scriptCoverageTitle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    marginBottom: 12,
    color: '#64748b',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
  },
  scriptCoverageGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: 10,
  },
  scriptCoverageRow: {
    padding: 12,
    borderRadius: 10,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(255,255,255,0.025)',
  },
  scriptCoverageMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 8,
  },
  scriptCoverageReady: {
    color: '#5eead4',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
  },
  scriptCoverageMissing: {
    color: '#fbbf24',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
  },
  scriptCoverageEntity: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: 700,
    marginBottom: 6,
  },
  scriptCoverageText: {
    color: '#aab7c9',
    fontSize: 12,
    lineHeight: 1.45,
  },
  scriptCoverageBlocker: {
    marginTop: 8,
    color: '#fbbf24',
    fontSize: 10,
    lineHeight: 1.45,
  },
  scriptCoverageObjects: {
    marginTop: 8,
    color: '#64748b',
    fontSize: 10,
    lineHeight: 1.4,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  scriptAssetGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 12,
    padding: 12,
    borderRadius: 10,
    border: '1px dashed rgba(255,255,255,0.12)',
    background: 'rgba(255,255,255,0.02)',
  },
  scriptAssetTile: {
    width: 128,
    minHeight: 104,
    padding: 0,
    overflow: 'hidden',
    borderRadius: 10,
    border: '1px solid rgba(255,255,255,0.10)',
    background: 'rgba(10,12,16,0.74)',
    color: '#d1d5db',
    display: 'grid',
    gridTemplateRows: '72px auto auto',
    textAlign: 'left' as const,
    cursor: 'pointer',
  },
  scriptAssetThumb: {
    width: '100%',
    height: 72,
    objectFit: 'cover' as const,
    background: '#111827',
    display: 'block',
  },
  scriptAssetFallback: {
    height: 72,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#93c5fd',
    background: 'linear-gradient(135deg, rgba(74,158,255,0.14), rgba(255,255,255,0.025))',
  },
  scriptAssetTitle: {
    padding: '8px 9px 2px',
    color: '#d1d5db',
    fontSize: 11,
    lineHeight: 1.25,
    fontWeight: 700,
  },
  scriptAssetMeta: {
    padding: '0 9px 8px',
    color: '#64748b',
    fontSize: 9,
    lineHeight: 1.2,
    fontWeight: 800,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
  },
  scriptActionBar: {
    position: 'sticky' as const,
    bottom: 0,
    zIndex: 8,
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
    padding: '14px 16px',
    borderTop: '1px solid rgba(255,255,255,0.10)',
    background: 'rgba(5,5,5,0.92)',
    backdropFilter: 'blur(12px)',
    boxShadow: '0 -10px 28px rgba(0,0,0,0.32)',
  },
  scriptPayloadGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    margin: '0 16px 24px',
  },
  scriptPayloadCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    minWidth: 0,
    padding: 16,
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.05)',
    borderLeft: '3px solid rgba(100,116,139,0.78)',
    background: 'rgba(255,255,255,0.03)',
  },
  scriptPayloadLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    color: '#8b9ab1',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
  },
  scriptPayloadContent: {
    margin: 0,
    color: '#d4dbe7',
    fontSize: 13,
    lineHeight: 1.6,
  },
}
