/**
 * storyboard styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const storyboardStyles: Record<string, CSSProperties> = {
  storyboardConsole: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  storyboardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 18,
    alignItems: 'flex-start',
    paddingBottom: 16,
    borderBottom: '1px solid rgba(255,255,255,0.08)',
  },
  storyboardEyebrow: {
    color: '#7f9bbd',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
  },
  storyboardTitle: {
    margin: '8px 0 0',
    color: '#e2e8f0',
    fontSize: 20,
    fontWeight: 650,
    lineHeight: 1.25,
  },
  storyboardMetaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
  },
  storyboardStatusBlocked: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    border: '1px solid rgba(245,158,11,0.45)',
    color: '#facc15',
    background: 'rgba(245,158,11,0.08)',
    borderRadius: 999,
    padding: '7px 12px',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  storyboardStatusPass: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    border: '1px solid rgba(16,185,129,0.45)',
    color: '#34d399',
    background: 'rgba(16,185,129,0.08)',
    borderRadius: 999,
    padding: '7px 12px',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  storyboardMetaPill: {
    border: '1px solid rgba(148,163,184,0.28)',
    color: '#a8b6ca',
    borderRadius: 999,
    padding: '7px 12px',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  storyboardBlockerBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    border: '1px solid rgba(245,158,11,0.32)',
    borderRadius: 10,
    background: 'rgba(245,158,11,0.06)',
    color: '#f8d78a',
    padding: '14px 16px',
    fontSize: 13,
    lineHeight: 1.45,
  },
  storyboardBlockerList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: 12,
    padding: '10px 0 18px',
  },
  storyboardBlockerTitle: {
    color: '#7f9bbd',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  storyboardBlockerItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    minWidth: 0,
    border: '1px solid rgba(180,83,9,0.72)',
    borderRadius: 10,
    background: 'rgba(217,119,6,0.1)',
    padding: 14,
  },
  storyboardBlockerErrorText: {
    color: '#facc15',
    fontSize: 12,
    fontWeight: 800,
    lineHeight: 1.5,
    wordBreak: 'break-all',
    overflowWrap: 'anywhere',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  storyboardBlockerVerdict: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    borderTop: '1px solid rgba(180,83,9,0.42)',
    paddingTop: 10,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  storyboardBlockerVerdictLabel: {
    color: '#9ca3af',
    fontWeight: 700,
  },
  storyboardBlockerVerdictStatus: {
    color: '#f87171',
    fontWeight: 900,
    textAlign: 'right',
    overflowWrap: 'anywhere',
  },
  storyboardBlockerMore: {
    color: '#a8b7ca',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.04em',
    padding: '4px 2px',
  },
  storyboardPanelGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 420px), 1fr))',
    gap: 18,
  },
  storyboardPanelCard: {
    border: '1px solid rgba(148,163,184,0.24)',
    borderRadius: 12,
    overflow: 'hidden',
    background: '#0d1117',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    boxShadow: '0 4px 14px rgba(0,0,0,0.26)',
  },
  storyboardFrame: {
    position: 'relative',
    aspectRatio: '16 / 9',
    background: 'linear-gradient(135deg, rgba(15,23,42,0.95), rgba(2,6,23,0.95))',
    overflow: 'hidden',
  },
  storyboardFrameImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    display: 'block',
    filter: 'saturate(0.88) contrast(0.95)',
  },
  storyboardFrameMissing: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    color: '#64748b',
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  },
  storyboardFrameGuideLabel: {
    color: '#f59e0b',
    fontSize: 18,
    fontWeight: 850,
    letterSpacing: '0.02em',
    textTransform: 'uppercase' as const,
  },
  storyboardFrameGuideLine: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
  },
  storyboardFrameShade: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(180deg, rgba(2,6,23,0.58) 0%, rgba(2,6,23,0.06) 36%, rgba(2,6,23,0.76) 100%)',
    pointerEvents: 'none',
  },
  storyboardFrameTop: {
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  storyboardPanelFrameActions: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    minWidth: 0,
  },
  storyboardCopyButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    border: '1px solid rgba(125,211,252,0.22)',
    background: 'rgba(2,6,23,0.70)',
    color: '#c7e8ff',
    borderRadius: 999,
    width: 28,
    height: 28,
    padding: 0,
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
  },
  storyboardFrameBottom: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
    display: 'grid',
    gap: 7,
  },
  storyboardShotCode: {
    justifySelf: 'start',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    border: '1px solid rgba(74,158,255,0.32)',
    background: 'rgba(2,6,23,0.70)',
    color: '#bfdbfe',
    borderRadius: 999,
    padding: '4px 8px',
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: '0.12em',
  },
  storyboardFrameCaption: {
    color: '#f8fafc',
    fontSize: 13,
    lineHeight: 1.3,
    fontWeight: 750,
    textShadow: '0 1px 12px rgba(0,0,0,0.75)',
  },
  storyboardPanelTopline: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  storyboardPanelId: {
    color: '#dbeafe',
    background: 'rgba(2,6,23,0.66)',
    border: '1px solid rgba(219,234,254,0.18)',
    borderRadius: 999,
    padding: '4px 8px',
    fontSize: 11,
    fontWeight: 850,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  storyboardPanelTime: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    color: '#7dd3fc',
    background: 'rgba(2,6,23,0.66)',
    border: '1px solid rgba(125,211,252,0.20)',
    borderRadius: 999,
    padding: '4px 6px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: 10,
    fontWeight: 800,
  },
  storyboardShot: {
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 1.35,
    fontWeight: 700,
  },
  storyboardAction: {
    margin: 0,
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 1.55,
  },
  storyboardDialogue: {
    margin: 0,
    color: '#e2e8f0',
    fontSize: 13,
    lineHeight: 1.45,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  storyboardSupportGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 10,
    paddingTop: 2,
  },
  storyboardAccordion: {
    background: '#0d1117',
    border: '1px solid #374151',
    borderRadius: 6,
    marginTop: 4,
    overflow: 'hidden',
  },
  storyboardAccordionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    padding: '12px 18px',
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.08em',
    color: '#9ca3af',
    background: 'rgba(255,255,255,0.03)',
    cursor: 'pointer',
    userSelect: 'none' as const,
    listStyle: 'none',
  },
  storyboardAccordionChevron: {
    flex: '0 0 auto',
    color: '#6b7280',
    transition: 'transform 0.22s ease, color 0.2s ease',
  },
  storyboardAccordionContent: {
    padding: 20,
    borderTop: '1px solid #374151',
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    background: '#0a0e14',
  },
  storyboardSupportBlock: {
    minWidth: 0,
    border: 'none',
    borderLeft: '3px solid rgba(59,130,246,0.74)',
    borderRadius: '0 6px 6px 0',
    background: 'rgba(59,130,246,0.055)',
    padding: '10px 11px',
    display: 'flex',
    flexDirection: 'column',
    gap: 7,
  },
  storyboardSupportTitle: {
    color: '#f59e0b',
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
  },
  storyboardSupportBody: {
    margin: 0,
    color: '#dbeafe',
    fontSize: 12,
    lineHeight: 1.45,
  },
  storyboardSupportList: {
    margin: 0,
    paddingLeft: 15,
    color: '#93a4bb',
    fontSize: 11,
    lineHeight: 1.35,
  },
  storyboardPromptBlock: {
    border: 'none',
    borderLeft: '3px solid #eab308',
    borderRadius: '0 6px 6px 0',
    background: 'rgba(234,179,8,0.055)',
    padding: '12px 14px',
    display: 'grid',
    gap: 9,
  },
  storyboardPromptHeader: {
    color: '#fbbf24',
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
  },
  storyboardPromptText: {
    margin: 0,
    color: '#e2e8f0',
    fontSize: 12,
    lineHeight: 1.48,
  },
  storyboardPromptPair: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 9,
    color: '#b6c4d6',
    fontSize: 11,
    lineHeight: 1.38,
  },
  storyboardPromptLabel: {
    display: 'block',
    marginBottom: 3,
    color: '#f59e0b',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
  },
  storyboardPromptRequirements: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
  },
  storyboardNegativePrompt: {
    color: '#fca5a5',
    fontSize: 11,
    lineHeight: 1.38,
  },
  storyboardSeedRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
  },
  storyboardPanelBody: {
    display: 'grid',
    gap: 18,
    padding: 20,
    borderTop: '1px solid rgba(148,163,184,0.18)',
  },
  storyboardTrackRow: {
    display: 'grid',
    gap: 10,
    paddingTop: 2,
  },
  storyboardTagGroup: {
    display: 'grid',
    gap: 6,
  },
  storyboardTagLabel: {
    color: '#64748b',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.18em',
    textTransform: 'uppercase' as const,
  },
  storyboardSeed: {
    color: '#9ed0ff',
    background: 'rgba(74,158,255,0.08)',
    border: '1px solid rgba(74,158,255,0.18)',
    borderRadius: 999,
    padding: '3px 7px',
    fontSize: 10,
    fontWeight: 800,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  storyboardEntityRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
  },
  storyboardEntity: {
    color: '#f9a8d4',
    background: 'rgba(244,114,182,0.075)',
    border: '1px solid rgba(244,114,182,0.20)',
    borderRadius: 999,
    padding: '3px 8px',
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: '0.03em',
  },
  storyboardReferenceRail: {
    display: 'flex',
    gap: 8,
    overflowX: 'auto' as const,
    paddingTop: 4,
  },
  storyboardReferenceGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  storyboardReferenceCard: {
    display: 'grid',
    gridTemplateColumns: '64px 1fr',
    gap: 9,
    alignItems: 'center',
    flex: '0 0 220px',
    minWidth: 0,
    border: '1px solid rgba(255,255,255,0.07)',
    borderRadius: 8,
    background: 'rgba(255,255,255,0.025)',
    padding: 7,
  },
  storyboardReferenceThumb: {
    width: 64,
    height: 44,
    borderRadius: 6,
    objectFit: 'cover' as const,
    display: 'block',
    background: 'rgba(15,23,42,0.78)',
  },
  storyboardReferenceFallback: {
    width: 64,
    height: 44,
    borderRadius: 6,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#7f9bbd',
    background: 'rgba(148,163,184,0.08)',
  },
  storyboardReferenceText: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 0,
    color: '#dbeafe',
    fontSize: 11,
    lineHeight: 1.25,
  },
  storyboardCandidateStrip: {
    borderTop: '1px solid rgba(255,255,255,0.09)',
    paddingTop: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  storyboardCandidateRow: {
    display: 'grid',
    gridTemplateColumns: '88px 1fr',
    gap: 12,
    alignItems: 'center',
    color: '#a8b6ca',
    fontSize: 12,
    lineHeight: 1.45,
  },
  storyboardCandidateThumb: {
    width: 88,
    height: 58,
    objectFit: 'cover' as const,
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.09)',
    filter: 'saturate(0.75)',
  },
  storyboardCandidateStatus: {
    color: '#facc15',
    fontSize: 11,
    fontWeight: 850,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  storyboardCandidateReason: {
    color: '#94a3b8',
    marginTop: 3,
  },
}
