/**
 * trace styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const traceStyles: Record<string, CSSProperties> = {
  traceOverlayBackdrop: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 10000,
    background: 'transparent',
    pointerEvents: 'auto' as const,
  },
  traceOverlayPanel: {
    position: 'fixed' as const,
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    overflow: 'hidden',
    borderRadius: 18,
    border: '1px solid rgba(148, 163, 184, 0.42)',
    background: 'radial-gradient(circle at 44% 36%, rgba(30, 41, 59, 0.92), rgba(3, 7, 18, 0.96) 58%, rgba(0, 0, 0, 0.98))',
    boxShadow: '0 34px 110px rgba(0,0,0,0.66), inset 0 1px 0 rgba(255,255,255,0.06)',
    pointerEvents: 'auto' as const,
  },
  traceHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto auto',
    alignItems: 'center',
    gap: 10,
    padding: '8px 10px',
    borderBottom: '1px solid rgba(255,255,255,0.08)',
  },
  traceHeaderText: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
  },
  traceEyebrow: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: 800,
    letterSpacing: '0.02em',
  },
  traceTitle: {
    margin: 0,
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: 720,
    letterSpacing: 0,
    lineHeight: 1.18,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  traceSubtitle: {
    margin: 0,
    color: '#60a5fa',
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: '0.12em',
    lineHeight: 1.2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  traceToolbar: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  traceHopCycle: {
    height: 32,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '0 12px',
    borderRadius: 999,
    border: '1px solid rgba(148,163,184,0.2)',
    background: 'rgba(2,6,23,0.54)',
    color: '#dbeafe',
    fontSize: 11,
    fontWeight: 820,
    letterSpacing: '0.02em',
    cursor: 'pointer',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.06)',
  },
  traceSegment: {
    height: 34,
    minWidth: 66,
    border: 0,
    borderRight: '1px solid rgba(255,255,255,0.07)',
    background: 'transparent',
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: 750,
    cursor: 'pointer',
  },
  traceSegmentActive: {
    color: '#ffffff',
    background: 'linear-gradient(135deg, rgba(124,58,237,0.9), rgba(74,158,255,0.32))',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.12)',
  },
  traceIconBar: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
  },
  traceIconButton: {
    width: 32,
    height: 32,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    border: '1px solid rgba(148,163,184,0.22)',
    background: 'rgba(15,23,42,0.44)',
    color: '#cbd5e1',
    cursor: 'pointer',
  },
  traceBody: {
    minHeight: 0,
    display: 'block',
    padding: '8px 10px 10px',
  },
  traceGraphCanvas: {
    position: 'relative' as const,
    width: '100%',
    height: '100%',
    minHeight: 0,
    borderRadius: 16,
    overflow: 'hidden',
    background: 'radial-gradient(circle at 50% 50%, rgba(74,158,255,0.13), rgba(45,212,191,0.05) 34%, rgba(2,6,23,0.04) 58%, rgba(0,0,0,0.16))',
  },
  traceSvg: {
    width: '100%',
    height: '100%',
    display: 'block',
  },
  traceEdgeLabel: {
    fill: '#c4b5fd',
    fontSize: 11,
    fontWeight: 650,
    pointerEvents: 'none' as const,
  },
  traceNodeGlyph: {
    fill: '#e2e8f0',
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: '0.08em',
    pointerEvents: 'none' as const,
  },
  traceNodeLabel: {
    fill: '#f8fafc',
    fontSize: 12,
    fontWeight: 700,
    pointerEvents: 'none' as const,
  },
  traceNodePill: {
    fill: '#94a3b8',
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    pointerEvents: 'none' as const,
  },
  traceNodeGlyphPanel: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    color: '#e2e8f0',
    fontSize: 8,
    fontWeight: 900,
    letterSpacing: '0.06em',
    lineHeight: 1,
    pointerEvents: 'none' as const,
    borderRadius: 999,
    background: 'rgba(2,6,23,0.5)',
    border: '1px solid rgba(226,232,240,0.18)',
  },
  traceNodeMediaPanel: {
    position: 'relative' as const,
    width: '100%',
    height: '100%',
    borderRadius: 999,
    overflow: 'hidden',
    background: 'rgba(2,6,23,0.5)',
    border: '1px solid rgba(226,232,240,0.16)',
    pointerEvents: 'none' as const,
  },
  traceNodeMediaImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    display: 'block',
    opacity: 0.78,
  },
  traceNodeIconOverlay: {
    position: 'absolute' as const,
    left: '50%',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    width: 24,
    height: 24,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    color: '#e2e8f0',
    background: 'rgba(0,0,0,0.5)',
    border: '1px solid rgba(255,255,255,0.24)',
    boxShadow: '0 6px 16px rgba(0,0,0,0.34)',
  },
  traceNodeTypeBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2px 5px',
    borderRadius: 999,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(2,6,23,0.72)',
    color: '#e2e8f0',
    fontSize: 7,
    fontWeight: 850,
    letterSpacing: '0.06em',
  },
  traceNodeLabelBox: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: 2,
    pointerEvents: 'none' as const,
  },
  traceNodeLabelText: {
    maxWidth: 176,
    color: '#f8fafc',
    fontSize: 11,
    fontWeight: 760,
    lineHeight: 1.15,
    textAlign: 'center' as const,
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    textShadow: '0 1px 8px rgba(0,0,0,0.8)',
  },
  traceNodeKindText: {
    color: '#94a3b8',
    fontSize: 9,
    fontWeight: 800,
    lineHeight: 1,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  traceTextPreview: {
    width: 230,
    maxHeight: 112,
    padding: '10px 11px',
    borderRadius: 12,
    border: '1px solid rgba(148,163,184,0.22)',
    background: 'rgba(2,6,23,0.92)',
    color: '#dbeafe',
    fontSize: 11,
    lineHeight: 1.35,
    boxShadow: '0 16px 40px rgba(0,0,0,0.42)',
    overflow: 'hidden',
  },
  traceTextPreviewMeta: {
    marginBottom: 5,
    color: '#4a9eff',
    fontSize: 8,
    fontWeight: 900,
    letterSpacing: '0.1em',
    textTransform: 'uppercase' as const,
  },
  traceTextPreviewFloating: {
    position: 'absolute' as const,
    left: 14,
    top: 14,
    zIndex: 5,
    width: 'min(320px, calc(100% - 28px))',
    maxHeight: 132,
    padding: '10px 12px',
    borderRadius: 13,
    border: '1px solid rgba(148,163,184,0.22)',
    background: 'rgba(2,6,23,0.9)',
    color: '#dbeafe',
    fontSize: 12,
    lineHeight: 1.38,
    boxShadow: '0 18px 48px rgba(0,0,0,0.42)',
    backdropFilter: 'blur(12px)',
    overflow: 'hidden',
    pointerEvents: 'none' as const,
  },
  traceVideoPlayer: {
    position: 'absolute' as const,
    right: 14,
    top: 14,
    zIndex: 7,
    width: 'min(360px, calc(100% - 28px))',
    borderRadius: 14,
    overflow: 'hidden',
    border: '1px solid rgba(148,163,184,0.24)',
    background: 'rgba(2,6,23,0.94)',
    boxShadow: '0 22px 62px rgba(0,0,0,0.52)',
    backdropFilter: 'blur(12px)',
  },
  traceVideoHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 8,
    padding: '8px 9px',
    color: '#e2e8f0',
    fontSize: 11,
    fontWeight: 750,
    lineHeight: 1.2,
  },
  traceVideoClose: {
    width: 26,
    height: 26,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    border: '1px solid rgba(148,163,184,0.18)',
    background: 'rgba(15,23,42,0.62)',
    color: '#cbd5e1',
    cursor: 'pointer',
  },
  traceVideoElement: {
    width: '100%',
    display: 'block',
    maxHeight: 240,
    background: '#000',
  },
  traceGestureHint: {
    position: 'absolute' as const,
    left: '50%',
    bottom: 14,
    transform: 'translateX(-50%)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 9,
    padding: '8px 13px',
    borderRadius: 12,
    border: '1px solid rgba(148,163,184,0.16)',
    background: 'rgba(15,23,42,0.72)',
    color: '#cbd5e1',
    fontSize: 11,
    backdropFilter: 'blur(10px)',
  },
  traceMiniHud: {
    position: 'absolute' as const,
    right: 14,
    top: 14,
    width: 220,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: 11,
    borderRadius: 14,
    border: '1px solid rgba(148,163,184,0.14)',
    background: 'rgba(2,6,23,0.58)',
    backdropFilter: 'blur(12px)',
    boxShadow: '0 18px 40px rgba(0,0,0,0.24)',
  },
  traceMiniHudDots: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
  },
  traceGraphStatus: {
    position: 'absolute' as const,
    right: 14,
    bottom: 14,
    display: 'inline-flex',
    alignItems: 'center',
    padding: '6px 9px',
    borderRadius: 999,
    border: '1px solid rgba(148,163,184,0.12)',
    background: 'rgba(2,6,23,0.5)',
    color: '#94a3b8',
    fontSize: 10,
    fontWeight: 700,
    backdropFilter: 'blur(10px)',
  },
  traceLegend: {
    minHeight: 0,
    overflow: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
  },
  traceLegendCard: {
    borderRadius: 14,
    border: '1px solid rgba(148,163,184,0.14)',
    background: 'rgba(15,23,42,0.46)',
    padding: 16,
  },
  traceLegendTitle: {
    margin: '0 0 10px',
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: 800,
  },
  traceLegendCopy: {
    margin: 0,
    color: '#cbd5e1',
    fontSize: 12,
    lineHeight: 1.55,
  },
  traceLegendRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '7px 0',
  },
  traceLegendDot: {
    width: 11,
    height: 11,
    borderRadius: 999,
    flexShrink: 0,
  },
  traceLegendKind: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: 700,
    textTransform: 'capitalize' as const,
  },
  tracePathPreview: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  tracePathChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    color: '#cbd5e1',
    fontSize: 10,
    fontWeight: 750,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  traceLegendMeta: {
    margin: '12px 0 0',
    color: '#64748b',
    fontSize: 11,
  },
  traceHiddenTable: {
    position: 'absolute' as const,
    width: 1,
    height: 1,
    overflow: 'hidden',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap' as const,
  },
}
