/**
 * video styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const videoStyles: Record<string, CSSProperties> = {
  videoProviderPanel: {
    display: 'grid',
    gap: 18,
  },
  videoProviderGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))',
    gap: 12,
  },
  videoProviderCard: {
    minHeight: 126,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: 12,
    padding: 16,
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.08)',
    borderLeft: '8px solid #4a9eff',
    background: '#0a0a0a',
  },
  videoProviderLabel: {
    color: '#94a3b8',
    fontSize: 9,
    fontWeight: 850,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
  },
  videoProviderValue: {
    color: '#f8fafc',
    fontSize: 24,
    lineHeight: 1.05,
    fontWeight: 900,
    letterSpacing: 0,
    overflowWrap: 'anywhere',
  },
  videoProviderSubtle: {
    color: '#94a3b8',
    fontSize: 11,
    lineHeight: 1.35,
    overflowWrap: 'anywhere',
  },
  videoProviderSplit: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.15fr) minmax(0, 0.85fr)',
    gap: 14,
  },
  videoProviderSection: {
    minWidth: 0,
    padding: 16,
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#0a0a0a',
  },
  videoProviderScoreRows: {
    display: 'grid',
    gap: 8,
  },
  videoProviderScoreMatrix: {
    display: 'grid',
    overflow: 'hidden',
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.06)',
    background: '#050505',
  },
  videoProviderScoreHeader: {
    display: 'grid',
    gridTemplateColumns: '1.35fr 1.55fr repeat(5, minmax(44px, 0.7fr)) minmax(72px, 0.8fr)',
    gap: 10,
    alignItems: 'center',
    padding: '10px 12px',
    borderBottom: '1px solid rgba(255,255,255,0.07)',
    background: 'rgba(255,255,255,0.02)',
    color: '#64748b',
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
  },
  videoProviderFeatureHeader: {
    textAlign: 'center' as const,
    cursor: 'help',
  },
  videoProviderScoreHeaderCell: {
    textAlign: 'right' as const,
  },
  videoProviderScoreMatrixRow: {
    display: 'grid',
    gridTemplateColumns: '1.35fr 1.55fr repeat(5, minmax(44px, 0.7fr)) minmax(72px, 0.8fr)',
    gap: 10,
    alignItems: 'center',
    padding: '12px',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    borderLeft: '2px solid transparent',
    color: '#e2e8f0',
    fontSize: 11,
  },
  videoProviderScoreMatrixRowSelected: {
    borderLeftColor: '#22c55e',
    background: 'rgba(34,197,94,0.08)',
  },
  videoProviderRecommendedName: {
    color: '#22c55e',
  },
  videoProviderTinyMuted: {
    marginTop: 2,
    color: '#64748b',
    fontSize: 9,
    fontFamily: 'JetBrains Mono, monospace',
  },
  videoProviderNeutralCell: {
    textAlign: 'center' as const,
    color: '#334155',
    fontSize: 12,
    fontWeight: 800,
    fontFamily: 'JetBrains Mono, monospace',
  },
  videoProviderPenaltyCell: {
    justifySelf: 'center',
    minWidth: 28,
    padding: '3px 5px',
    borderRadius: 5,
    background: 'rgba(245,158,11,0.14)',
    color: '#f59e0b',
    textAlign: 'center' as const,
    fontSize: 10,
    fontWeight: 900,
    fontFamily: 'JetBrains Mono, monospace',
  },
  videoProviderScoreFinalCell: {
    textAlign: 'right' as const,
  },
  videoProviderScoreRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: 12,
    alignItems: 'center',
    padding: '10px 0',
    borderTop: '1px solid rgba(255,255,255,0.06)',
    color: '#e2e8f0',
    fontSize: 12,
  },
  videoProviderScoreMeta: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    flexWrap: 'wrap',
  },
  videoProviderBlockerList: {
    display: 'grid',
    gap: 8,
    margin: 0,
    padding: 0,
    listStyle: 'none',
    color: '#fca5a5',
    fontSize: 12,
    lineHeight: 1.35,
  },
  videoProviderReceiptRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(138px, 1fr))',
    gap: 8,
  },
  videoProviderReceiptReady: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '9px 10px',
    borderRadius: 6,
    border: '1px solid rgba(34,197,94,0.18)',
    background: 'rgba(34,197,94,0.06)',
    color: '#4ade80',
    fontSize: 9,
    fontWeight: 850,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  videoProviderReceiptMissing: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '9px 10px',
    borderRadius: 6,
    border: '1px solid rgba(148,163,184,0.14)',
    background: 'rgba(148,163,184,0.05)',
    color: '#94a3b8',
    fontSize: 9,
    fontWeight: 850,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
}
