/**
 * voice styles, split out of the 4,439-line `nvis` object.
 *
 * Styles live beside the surface that uses them so a panel can be extracted
 * with its own visual vocabulary instead of reaching into one global bag.
 */
import type { CSSProperties } from 'react'

export const voiceStyles: Record<string, CSSProperties> = {
  voicePlugin: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  voiceHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  voiceChannelCard: {
    background: 'rgba(12,12,12,0.72)',
    padding: 18,
    borderRadius: 18,
    display: 'flex',
    alignItems: 'stretch',
    gap: 18,
    border: '1px solid rgba(255,255,255,0.08)',
    backdropFilter: 'blur(12px)',
  },
  voicePortraitFrame: {
    width: 148,
    minHeight: 148,
    borderRadius: 16,
    overflow: 'hidden',
    border: '1px solid rgba(74,158,255,0.24)',
    background: '#050505',
    flexShrink: 0,
  },
  voicePortrait: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    display: 'block',
  },
  voiceCardBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    minWidth: 0,
    flex: 1,
  },
  voiceCardTopline: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 12,
  },
  voiceName: {
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: 600,
    letterSpacing: '0.01em',
  },
  voiceRole: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.2em',
    textTransform: 'uppercase' as const,
  },
  voiceStatus: {
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 1.5,
  },
  voiceAuditionTextarea: {
    background: '#050505',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 12,
    color: '#e2e8f0',
    fontSize: 14,
    lineHeight: 1.55,
    minHeight: 74,
    resize: 'vertical' as const,
    padding: '12px 14px',
    outline: 'none',
  },
  voicePerformanceRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(120px, 1fr))',
    gap: 10,
  },
  voiceControlLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    color: '#64748b',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
  },
  voiceSelect: {
    height: 34,
    borderRadius: 10,
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#050505',
    color: '#cbd5e1',
    padding: '0 10px',
    outline: 'none',
    fontSize: 12,
    letterSpacing: '0.02em',
  },
  voiceActionRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap' as const,
  },
  voiceGhostBtn: {
    height: 34,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 10,
    border: '1px solid rgba(255,255,255,0.1)',
    background: 'transparent',
    color: '#94a3b8',
    cursor: 'pointer',
    padding: '0 12px',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
  },
  voicePrimaryBtn: {
    height: 34,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 10,
    border: '1px solid rgba(74,158,255,0.38)',
    background: 'rgba(74,158,255,0.08)',
    color: '#93c5fd',
    cursor: 'pointer',
    padding: '0 14px',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
  },
  voiceRenderStatus: {
    color: '#64748b',
    fontSize: 11,
    lineHeight: 1.4,
  },
  voiceCommitRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '4px 0',
  },
  voiceMeta: {
    color: '#64748b',
    fontSize: 10,
    letterSpacing: '0.04em',
  },
  voiceCommitBtn: {
    height: 28,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    borderRadius: 6,
    border: '1px solid #334155',
    background: 'transparent',
    color: '#e2e8f0',
    padding: '0 10px',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
  },
}
