# generated by datamodel-codegen:
#   filename:  cinematic_script_dna.v1.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ScriptDna(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    primary_mode: str
    influences_as_techniques: list[str] = Field(..., min_length=1)
    scene_engine: str
    dialogue_style: str
    conflict_pattern: str
    structure: str
    theme: str
    beat_rules: list[str]
    do_not_use: list[str]
    selected_catalog_ids: list[str] | None = None
    rationale: str | None = None


class ScriptDnaSelectionOutput(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    script_dna: ScriptDna
