# generated by datamodel-codegen:
#   filename:  dream_run_state.v1.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, conint, constr


class RuntimeState(Enum):
    LOCAL_RUN_STATE_CONSISTENT = 'LOCAL_RUN_STATE_CONSISTENT'
    LOCAL_RESPAWN_REQUIRED = 'LOCAL_RESPAWN_REQUIRED'
    LOCAL_WORK_QUEUE_READY = 'LOCAL_WORK_QUEUE_READY'
    LOCAL_WORK_IN_PROGRESS = 'LOCAL_WORK_IN_PROGRESS'
    LOCAL_TAU_CONTRACT_GENERATED_NOT_EXECUTED = (
        'LOCAL_TAU_CONTRACT_GENERATED_NOT_EXECUTED'
    )
    LOCAL_DRY_RUN_COMPLETE_NOT_PROVIDER_READY = (
        'LOCAL_DRY_RUN_COMPLETE_NOT_PROVIDER_READY'
    )
    LOCAL_BLOCKED_RUN_STATE = 'LOCAL_BLOCKED_RUN_STATE'
    LOCAL_BLOCKED_PROVIDER_POLICY = 'LOCAL_BLOCKED_PROVIDER_POLICY'
    LOCAL_BLOCKED_HUMAN_DECISION_REQUIRED = 'LOCAL_BLOCKED_HUMAN_DECISION_REQUIRED'
    LOCAL_SUPERSEDED_REVISION_PRESENT = 'LOCAL_SUPERSEDED_REVISION_PRESENT'


class References(BaseModel):
    document_id: str
    path: str | None = None
    sha256: constr(pattern=r'^sha256:')


class PersonaDreamLocalRunState(BaseModel):
    schema_version: Literal['persona-dream.dream-run-state.v1']
    mode: Literal['LOCAL_DETERMINISTIC']
    runtime_state: RuntimeState
    provider_live: Literal[False]
    paid_call_authorized: Literal[False]
    provider_accessible_url_created: Literal[False]
    submitted: Literal[False]
    manual_acceptance_claimed: Literal[False]
    actual_provider_call_attempts: Literal[0]
    references: dict[str, References]
    artifact_decision_counts: dict[str, conint(ge=0)]
    blockers: list[str]
    non_claims: list[str]
