# generated by datamodel-codegen:
#   filename:  generated_image_attempts.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class Model(BaseModel):
    schema_: Literal['persona_dream.generated_image_attempts.v1'] = Field(
        ..., alias='schema'
    )
    status: str
    created_at: str
    attempts: list[Any]
