# generated by datamodel-codegen:
#   filename:  kling_submit_gate_receipt.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, constr


class Decision(Enum):
    BLOCKED_MISSING_INPUT = 'BLOCKED_MISSING_INPUT'
    DRY_RUN_NOT_LIVE_SUBMITTABLE = 'DRY_RUN_NOT_LIVE_SUBMITTABLE'
    LIVE_SUBMITTABLE = 'LIVE_SUBMITTABLE'
    NOT_SUBMITTED = 'NOT_SUBMITTED'


class P0KlingSubmitGateReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_id: Literal['schemas/kling_submit_gate_receipt.schema.json']
    run_id: constr(min_length=1)
    provider: Literal['kling']
    attempted_live_submit: Literal[False]
    decision: Decision
    reason: constr(min_length=1)
    evidence: list[constr(min_length=1)]
