# generated by datamodel-codegen:
#   filename:  kling_scene_packet.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, PositiveFloat, conint, constr


class ImageListItem(BaseModel):
    token: constr(min_length=1)
    path: constr(min_length=1)
    role: constr(min_length=1)
    status: constr(min_length=1)
    hash: constr(pattern=r'^sha256:[0-9a-f]{64}$')


class MultiPromptItem(BaseModel):
    index: conint(ge=0)
    duration_s: PositiveFloat
    prompt: constr(min_length=1)
    provider_text: constr(min_length=1)
    dialogue: list[Any] | None = None
    cinematography: dict[str, Any] | None = None


class ProviderDryRunFields(BaseModel):
    model: constr(min_length=1)
    mode: constr(min_length=1)
    aspect_ratio: constr(min_length=1)
    image_list: list[Any] | None = None
    multi_prompt: list[Any] = Field(..., min_length=1)
    callback_url: str | None = None


class KlingOneSceneDryRunScenePacket(BaseModel):
    """
    Structural contract for a generated-unreviewed one-scene Kling scene packet (kling.scene_packet.v1). This is the dry-run review-packet lane; live-submission value gates (schema id, paid_call_authorized=false, live_call_block_reason presence) are enforced in the Python validators (validate_run_root_pipeline._validate_kling_scene_packet, validate_pipeline_spine) and are intentionally not const-pinned here so the BLOCKED branches remain reachable.
    """

    schema_: str = Field(
        ...,
        alias='schema',
        description='Contract id; the Python validators require the exact value kling.scene_packet.v1.',
    )
    run_id: constr(min_length=1)
    status: constr(min_length=1)
    provider: constr(min_length=1)
    model: constr(min_length=1)
    mode: constr(min_length=1)
    aspect_ratio: constr(min_length=1)
    duration_s: PositiveFloat
    paid_call_authorized: bool = Field(
        ...,
        description='Dry-run packets must keep this false; the Python validator blocks when it is not false.',
    )
    cost_estimate: dict[str, Any]
    callback_url: str | None = None
    polling_plan: str | None = None
    storage_plan: dict[str, Any]
    retry_policy: str | None = None
    audio_strategy: str | None = None
    image_list: list[ImageListItem]
    voice_list: list[Any] | None = None
    voice_examples: list[Any] | None = None
    multi_prompt: list[MultiPromptItem] = Field(..., min_length=1)
    negative_prompt: list[str]
    provider_dry_run_fields: ProviderDryRunFields
    live_call_block_reason: constr(min_length=1) = Field(
        ...,
        description='Human-readable reason the packet is not live-submittable; the Python validator blocks when this is missing or empty.',
    )
    work_backwards_chain: list[str] = Field(..., min_length=1)
