# generated by datamodel-codegen:
#   filename:  panel_source_receipt.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, constr


class Status(Enum):
    PASS_PANEL_SOURCE = 'PASS_PANEL_SOURCE'
    BLOCKED = 'BLOCKED'


class Kind(Enum):
    subagent = 'subagent'


class Name(Enum):
    panel_creator = 'panel-creator'
    persona_dream_panel_repair_gate = 'persona-dream-panel-repair-gate'


class Producer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    name: Name
    receipt: constr(min_length=1) | None = None


class PhotorealStatus(Enum):
    PASS_PHOTOREAL_CINEMATIC = 'PASS_PHOTOREAL_CINEMATIC'
    BLOCKED_NON_PHOTOREAL = 'BLOCKED_NON_PHOTOREAL'
    UNKNOWN = 'UNKNOWN'


class PanelSourceReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: Literal['persona_dream.panel_source_receipt.v1'] = Field(
        ..., alias='schema'
    )
    run_id: constr(min_length=1)
    panel_id: constr(min_length=1)
    status: Status
    image_path: constr(min_length=1)
    sha256: constr(pattern=r'^sha256:[0-9a-f]{64}$')
    producer: Producer
    photoreal_status: PhotorealStatus
    nano_banana_fallback_used: Literal[False]
    final_panel_eligible: bool
    blockers: list[constr(min_length=1)] | None = None
