# generated by datamodel-codegen:
#   filename:  pipeline_terminal_report.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, constr


class Status(Enum):
    PASS = 'PASS'
    BLOCKED_MISSING_INPUT = 'BLOCKED_MISSING_INPUT'
    DRY_RUN_NOT_LIVE_SUBMITTABLE = 'DRY_RUN_NOT_LIVE_SUBMITTABLE'
    BLOCKED_SCHEMA_INVALID = 'BLOCKED_SCHEMA_INVALID'
    BLOCKED_INCONSISTENT_RECEIPTS = 'BLOCKED_INCONSISTENT_RECEIPTS'


class TerminalGate(Enum):
    input = 'input'
    paid_call = 'paid_call'
    kling_submit = 'kling_submit'


class P0PipelineTerminalReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_id: Literal['schemas/pipeline_terminal_report.schema.json']
    run_id: constr(min_length=1)
    status: Status
    terminal_gate: TerminalGate
    live_provider_call_made: Literal[False]
    receipt_paths: list[constr(pattern=r'^receipts/.+\.json$')]
