# generated by datamodel-codegen:
#   filename:  provider_request_dry_run.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class Model(BaseModel):
    schema_: Literal['persona_dream.provider_request_dry_run.v1'] = Field(
        ..., alias='schema'
    )
    artifact_id: str
    status: str
    created_at: str
    provider: str
    model: str
    paid_call_performed: Literal[False]
    live_call_authorized: Literal[False]
    duration_s: float
    prompt_path: str
    storyboard_board: str
    scene_directions_path: str
    scene_payloads_path: str
    reference_images: list[Any] = Field(..., min_length=1)
