# generated by datamodel-codegen:
#   filename:  provider_readiness_receipt.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, constr


class Status(Enum):
    PASS = 'PASS'
    BLOCKED = 'BLOCKED'
    SKIPPED = 'SKIPPED'


class Check(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    status: Status


class P0ProviderReadinessReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_id: Literal['schemas/provider_readiness_receipt.schema.json']
    run_id: constr(min_length=1)
    provider: Literal['kling']
    ready_for_dry_run: bool
    ready_for_live_submit: bool
    checks: list[Check]
    missing: list[constr(min_length=1)]
