# generated by datamodel-codegen:
#   filename:  review_display_interaction_manifest.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class Model(BaseModel):
    schema_: Literal['persona_dream.review_display_interaction_manifest.v1'] = Field(
        ..., alias='schema'
    )
    status: str
    created_at: str
    page: str
    checks: list[Any] = Field(..., min_length=1)
