# generated by datamodel-codegen:
#   filename:  stage_receipt.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, constr


class P0StageReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_id: Literal['schemas/stage_receipt.schema.json']
    run_id: constr(min_length=1)
    stage: constr(min_length=1)
    inputs_complete: bool
    missing_inputs: list[constr(min_length=1)]
    evidence: list[constr(min_length=1)]
