# generated by datamodel-codegen:
#   filename:  storyboard_board_receipt.schema.json
#   timestamp: 2026-09-06T18:42:58+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class Model(BaseModel):
    schema_: Literal['persona_dream.storyboard_board_receipt.v1'] = Field(
        ..., alias='schema'
    )
    artifact_id: str
    status: str
    created_at: str
    path: str
    sha256: str
    width: int
    height: int
    aspect_ratio: str
    expected_panel_count: int
    actual_panel_count: int
    beat_to_panel_map: list[Any] = Field(..., min_length=1)
    manual_review_required: bool
