#!/usr/bin/env python3
"""Build the persona-dream memory-integration Tau DAG contract."""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    out = Path(args.out).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    dag = {
        "schema": "tau.dag_contract.v1",
        "dag_id": "persona-dream-memory-integration",
        "created_at": now_iso(),
        "goal": {
            "goal_id": "persona-dream-memory-integration",
            "goal_version": 1,
            "goal_hash": "sha256:persona-dream-memory-integration-required",
        },
        "target": {
            "repo": "grahama1970/agent-skills",
            "target": "skills/persona-dream memory integration",
            "allowed_paths": [
                "skills/persona-dream/**",
                "agents/story-writer/**",
                "agents/story-reviewer/**",
                "agents/script-writer/**",
                "agents/script-reviewer/**",
                "agents/contact-sheet-writer/**",
                "agents/contact-sheet-reviewer/**",
                "agents/contact-sheet-builder/**",
                "agents/contact-sheet-build-reviewer/**",
            ],
            "forbidden_paths": [
                "/home/graham/workspace/experiments/tau/**",
                "/home/graham/workspace/experiments/pi-mono/**",
            ],
        },
        "entry_node": "persist-persona-dream-artifacts-to-memory",
        "terminal_nodes": ["human"],
        "limits": {
            "resume": True,
            "default_timeout_seconds": 240,
            "max_total_attempts": 6,
            "max_reviewer_repair_iterations": 2,
        },
        "nodes": [
            {
                "id": "persist-persona-dream-artifacts-to-memory",
                "agent": "memory",
                "executor": "local",
                "command_spec": "/home/graham/workspace/experiments/agent-skills/agents/memory/tau-dispatch-command.json",
                "required_evidence": [
                    "story memory_bridge_receipt mocked=false live=true",
                    "script memory_bridge_receipt mocked=false live=true",
                    "contact-sheet memory_bridge_receipt mocked=false live=true",
                    "media asset vertices written through memory /upsert",
                    "TOM/media grounding edges written through memory /upsert",
                    "entity_context.json for story/script/contact-sheet artifacts",
                    "no direct ArangoDB or Qdrant writes",
                ],
                "emits": [
                    "tau.agent_handoff.v1",
                    "persona_dream.memory_tau_receipt.v1",
                    "persona_dream.memory_bridge_receipt.v1",
                    "persona_dream.entity_coverage.v1",
                    "persona_dream.tom_media_edge.v1",
                ],
            },
            {
                "id": "verify-memory-integration-receipts",
                "agent": "project-or-harness-verifier",
                "executor": "local",
                "command_spec": "/home/graham/workspace/experiments/agent-skills/agents/project-or-harness-verifier/tau-dispatch-command.json",
                "required_evidence": [
                    "live /recall response for story/script/contact-sheet artifacts",
                    "BM25 score present",
                    "dense score present",
                    "graph score present where media/TOM edges are expected",
                ],
                "emits": [
                    "tau.agent_handoff.v1",
                    "persona_dream.memory_review_receipt.v1",
                ],
            },
            {
                "id": "human",
                "agent": "human",
                "executor": "human",
                "required_evidence": [
                    "DAG receipt from Tau or explicit Tau integration blocker",
                    "memory audit JSON with all checks PASS",
                ],
            },
        ],
        "edges": [
            {"from": "persist-persona-dream-artifacts-to-memory", "to": "verify-memory-integration-receipts"},
            {"from": "verify-memory-integration-receipts", "to": "human"},
        ],
        "required_evidence": [
            "Tau DAG receipt or explicit Tau DAG runner blocker",
            "memory write receipts for every phase artifact",
            "entity coverage artifacts generated by extract-entities",
            "media/TOM edge upsert receipt",
            "memory recall proof with bm25/dense/graph score counts",
        ],
        "fail_closed_on": [
            "direct_tau_repo_edit",
            "direct_arangodb_write",
            "direct_qdrant_write",
            "missing_memory_receipt",
            "missing_entity_context",
            "missing_media_edge",
            "stale_local_json_read_without_memory_probe",
            "mocked_final_verification",
        ],
    }
    out.write_text(json.dumps(dag, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"ok": True, "dag_contract": str(out), "schema": dag["schema"]}, sort_keys=True))
    return 0


def now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


if __name__ == "__main__":
    raise SystemExit(main())
