#!/usr/bin/env python3
"""Generate operator docs + release receipt from the LIVE implementation (#1288).

Everything between the AUTOGEN markers in docs/COMMANDS.md is owned by this
generator (hand-written conceptual sections outside the markers are
preserved). The release receipt records what THIS commit actually proves —
live test counts, UI contract results, schema inventory, golden-slice hashes
— never inherited numbers. sanity.sh calls `--check`, which regenerates to a
temp location and fails on drift, so docs/receipts cannot go stale silently.
Environment-specific absolute paths are excluded from the receipt.

Determinism: output depends only on the source tree + provided tool results;
regenerating twice on one commit is byte-identical (timestamps come from the
commit, not the wall clock).
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "COMMANDS.md"
RECEIPT = ROOT / "docs" / "release_receipt.json"
BEGIN, END = "<!-- AUTOGEN:COMMANDS BEGIN -->", "<!-- AUTOGEN:COMMANDS END -->"

GROUPS = {
    "Plan": ["scaffold", "plan", "doctor", "version"],
    "Review": ["claim-decide", "simulate", "drift", "undo"],
    "Design": ["image-variations", "compile-document", "render-document", "record-note", "record-transcript"],
    "Present / Publish": ["build", "emit-ui", "emit-html", "emit-md"],
    "Maintain": ["apply-edit"],
}


def _commands() -> dict[str, dict]:
    sys.path.insert(0, str(ROOT / "src"))
    from pitchdeck.cli import app  # noqa: PLC0415

    registered = {}
    for command in app.registered_commands:
        name = command.name or command.callback.__name__.replace("_", "-")
        doc = (command.callback.__doc__ or "").strip().splitlines()[0] if command.callback.__doc__ else ""
        import inspect

        params = [p for p in inspect.signature(command.callback).parameters]
        registered[name] = {"help": doc, "params": params}
    return registered


def _render_docs(commands: dict[str, dict]) -> str:
    lines = [BEGIN, "", "_Generated by scripts/generate_docs.py — do not edit between markers._", ""]
    grouped = {name for names in GROUPS.values() for name in names}
    extra = sorted(set(commands) - grouped)
    for group, names in {**GROUPS, **({"Ungrouped": extra} if extra else {})}.items():
        rows = [name for name in names if name in commands]
        if not rows:
            continue
        lines += [f"### {group}", "", "| Command | Purpose | Options |", "|---|---|---|"]
        for name in rows:
            meta = commands[name]
            opts = " ".join(f"`--{p.replace('_', '-')}`" for p in meta["params"])
            lines.append(f"| `{name}` | {meta['help']} | {opts} |")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def _tree_hash() -> str:
    result = subprocess.run(
        ["git", "ls-files", "-s", "src", "schemas", "run.sh"], cwd=ROOT, capture_output=True, text=True, check=True
    )
    return hashlib.sha256(result.stdout.encode()).hexdigest()


def _schema_inventory() -> list[dict]:
    inventory = []
    for schema_file in sorted((ROOT / "schemas").glob("*.json")):
        inventory.append({
            "schema": schema_file.stem,
            "sha256": hashlib.sha256(schema_file.read_bytes()).hexdigest(),
            "visibility": "public",
        })
    source = (ROOT / "src" / "pitchdeck").glob("*.py")
    versions = sorted({m for f in source for m in re.findall(r'"(pitchdeck\.[a-z_]+\.v\d+)"', f.read_text())})
    return [{"declared_schemas": versions, "artifacts": inventory}]


def generate(*, test_summary: dict | None = None) -> tuple[str, dict]:
    commands = _commands()
    block = _render_docs(commands)
    if DOCS.exists():
        text = DOCS.read_text(encoding="utf-8")
        if BEGIN in text and END in text:
            head, rest = text.split(BEGIN, 1)
            _, tail = rest.split(END, 1)
            doc_text = head + block + tail
        else:
            doc_text = text.rstrip() + "\n\n" + block + "\n"
    else:
        doc_text = "# pitchdeck command reference\n\nHand-written conceptual docs go above/below the markers.\n\n" + block + "\n"
    commit = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
    golden = ROOT / "examples" / "sparta-golden" / "deck.document.json"
    receipt = {
        "schema": "pitchdeck.release_receipt.v1",
        "commit": commit,
        "source_tree_sha256": _tree_hash(),
        "commands": sorted(commands),
        "command_count": len(commands),
        "schema_inventory": _schema_inventory(),
        "golden_slice_sha256": hashlib.sha256(golden.read_bytes()).hexdigest() if golden.exists() else None,
        "tests": test_summary or {"status": "NOT_RUN_BY_GENERATOR", "note": "pass --with-tests for live counts"},
        "known_limitations": [
            "browser-vs-PPTX visual fidelity is unverified (parity gate is #1273)",
            "emitters other than render-document still render from the bundle (#1264)",
        ],
        "does_not_prove": [
            "that any deck is visually approved by a human",
            "that generated design output matches the house style (gate lives in #1262)",
            "that live services (RealtimeSTT mic, codex imagegen) are available on another host",
        ],
    }
    return doc_text, receipt


def main() -> int:
    check = "--check" in sys.argv
    with_tests = "--with-tests" in sys.argv
    test_summary = None
    if with_tests:
        proc = subprocess.run(["uv", "run", "pytest", "tests", "-q", "--tb=no"], cwd=ROOT, capture_output=True, text=True)
        tail = (proc.stdout + proc.stderr).strip().splitlines()
        import re as _re

        counts = next((line for line in tail if _re.search(r"\d+ (passed|failed|xfailed)", line)), "")
        dots = next((line for line in tail if _re.fullmatch(r"[.xFEs]+\s*\[100%\]", line.strip())), "")
        test_summary = {
            "exit_code": proc.returncode,
            "summary": counts.strip() or f"{dots.strip().split()[0].count('.')} passed, {dots.count('x')} xfail",
        }
    doc_text, receipt = generate(test_summary=test_summary)
    receipt_text = json.dumps(receipt, indent=1) + "\n"
    if check:
        stale = []
        if not DOCS.exists() or DOCS.read_text(encoding="utf-8") != doc_text:
            stale.append(str(DOCS))
        if RECEIPT.exists():
            committed = json.loads(RECEIPT.read_text(encoding="utf-8"))
            for key in ("commands", "schema_inventory", "source_tree_sha256"):
                if committed.get(key) != receipt[key]:
                    stale.append(f"{RECEIPT} ({key} drifted)")
        else:
            stale.append(str(RECEIPT))
        if stale:
            print("STALE: regenerate with scripts/generate_docs.py:\n  " + "\n  ".join(stale), file=sys.stderr)
            return 1
        print("docs and release receipt match the implementation")
        return 0
    DOCS.parent.mkdir(parents=True, exist_ok=True)
    DOCS.write_text(doc_text, encoding="utf-8")
    RECEIPT.write_text(receipt_text, encoding="utf-8")
    print(f"wrote {DOCS} ({len(receipt['commands'])} commands) and {RECEIPT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
