# Generated by test-lab — blind adversarial evaluation
"""test_unix_listener - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from embry_voice_control.unix_listener import wake_phrase_detected


def test_wake_phrase_detected_supports_observed_kmb_initialism() -> None:
    assert wake_phrase_detected("K.M.B. What is the capital of France?")
    assert wake_phrase_detected("Hey Embry, open review queue.")
    assert not wake_phrase_detected("Embryless background words.")
