# Generated by test-lab — blind adversarial evaluation
"""
Regression tests for P0 skill integration fixes.

Tests that the fixes for create-image argument contracts and
create-cast type normalization work correctly.
"""

import json
import sys
from pathlib import Path

import pytest

# Add parent paths for imports
SKILL_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(SKILL_DIR))
sys.path.insert(0, str(SKILL_DIR / "create_movie"))

PI_SKILLS_DIR = SKILL_DIR.parent


class TestCreateImageArgumentContract:
    """Verify create-image is called with positional prompt, not --prompt flag."""

    def test_run_sh_uses_uv_run_script(self):
        """run.sh must use 'uv run --script' for PEP 723 deps."""
        run_sh = PI_SKILLS_DIR / "create-image" / "run.sh"
        if not run_sh.exists():
            pytest.skip("create-image skill not found")

        content = run_sh.read_text()
        assert "uv run --script" in content, (
            "run.sh must use 'uv run --script generate.py' for PEP 723 inline deps"
        )
        # Must NOT use bare 'python generate.py'
        assert "python generate.py" not in content.replace("uv run --script generate.py", ""), (
            "run.sh must not use bare 'python generate.py'"
        )

    def test_generate_phase_uses_positional_prompt(self):
        """phases/generate.py must pass prompt as positional arg to create-image."""
        generate_py = SKILL_DIR / "create_movie" / "phases" / "generate.py"
        if not generate_py.exists():
            pytest.skip("phases/generate.py not found")

        content = generate_py.read_text()
        # The create-image call should use positional prompt: ["generate", visual_prompt, ...]
        # NOT: ["generate", "--prompt", visual_prompt, ...]
        # Note: "--prompt" may legitimately appear for OTHER skills (e.g., create-score)
        assert '"generate", visual_prompt,' in content, (
            "create-image must be called with positional prompt"
        )
        assert '"generate", "--prompt", visual_prompt' not in content, (
            "create-image must NOT use --prompt flag"
        )


class TestCreateCastTypeNormalization:
    """Verify create-cast handles list-typed action fields."""

    def test_extract_characters_with_list_action(self):
        """script_analyzer handles action as list of strings."""
        cast_dir = PI_SKILLS_DIR / "create-cast"
        if not cast_dir.exists():
            pytest.skip("create-cast skill not found")

        sys.path.insert(0, str(cast_dir))
        from create_cast.script_analyzer import extract_characters_from_script

        script = {
            "scenes": [
                {
                    "number": 1,
                    "heading": "INT. OFFICE - DAY",
                    "action": ["SARAH enters the room.", "She looks around nervously."],
                    "dialogue": [
                        {"character": "SARAH", "line": "Hello?"},
                    ],
                }
            ]
        }

        # This previously crashed with TypeError on list action
        characters = extract_characters_from_script(script)
        assert "SARAH" in characters

    def test_extract_characters_with_string_action(self):
        """script_analyzer still works with string action (original format)."""
        cast_dir = PI_SKILLS_DIR / "create-cast"
        if not cast_dir.exists():
            pytest.skip("create-cast skill not found")

        sys.path.insert(0, str(cast_dir))
        from create_cast.script_analyzer import extract_characters_from_script

        script = {
            "scenes": [
                {
                    "number": 1,
                    "heading": "EXT. STREET - NIGHT",
                    "action": "MARCUS walks down the alley.",
                    "dialogue": [
                        {"character": "MARCUS", "line": "Who's there?"},
                    ],
                }
            ]
        }

        characters = extract_characters_from_script(script)
        assert "MARCUS" in characters


class TestCastingResultPartialResults:
    """Verify CastingResult has partial_results field."""

    def test_casting_result_has_partial_results(self):
        """CastingResult dataclass includes partial_results field."""
        cast_dir = PI_SKILLS_DIR / "create-cast"
        if not cast_dir.exists():
            pytest.skip("create-cast skill not found")

        sys.path.insert(0, str(cast_dir))
        from create_cast.schemas import CastingResult, CastingPhase

        result = CastingResult(
            status="complete",
            phase=CastingPhase.COMPLETE,
            session_id="test-123",
            partial_results={"characters": ["SARAH", "MARCUS"]},
        )

        assert result.partial_results is not None
        assert result.partial_results["characters"] == ["SARAH", "MARCUS"]

    def test_casting_result_partial_results_defaults_none(self):
        """CastingResult.partial_results defaults to None."""
        cast_dir = PI_SKILLS_DIR / "create-cast"
        if not cast_dir.exists():
            pytest.skip("create-cast skill not found")

        sys.path.insert(0, str(cast_dir))
        from create_cast.schemas import CastingResult, CastingPhase

        result = CastingResult(
            status="complete",
            phase=CastingPhase.COMPLETE,
            session_id="test-123",
        )

        assert result.partial_results is None
        # Safe access pattern used in orchestrator.py
        chars = (result.partial_results or {}).get("characters", [])
        assert chars == []

    def test_casting_result_to_dict_includes_partial_results(self):
        """CastingResult.to_dict() includes partial_results."""
        cast_dir = PI_SKILLS_DIR / "create-cast"
        if not cast_dir.exists():
            pytest.skip("create-cast skill not found")

        sys.path.insert(0, str(cast_dir))
        from create_cast.schemas import CastingResult, CastingPhase

        result = CastingResult(
            status="complete",
            phase=CastingPhase.COMPLETE,
            session_id="test-123",
            partial_results={"characters": ["SARAH"]},
        )

        d = result.to_dict()
        assert "partial_results" in d
        assert d["partial_results"]["characters"] == ["SARAH"]


class TestSoundDesignDuration:
    """Verify create-sound-design reads per-scene durations."""

    def test_load_scene_durations_from_script(self, tmp_path):
        """_load_scene_durations reads actual durations from script JSON."""
        sd_dir = PI_SKILLS_DIR / "create-sound-design"
        if not sd_dir.exists():
            pytest.skip("create-sound-design skill not found")

        sys.path.insert(0, str(sd_dir))
        from create_sound_design.orchestrator import _load_scene_durations

        script_data = {
            "duration_seconds": 120,
            "scenes": [
                {"id": "scene_01", "duration": 45.0},
                {"id": "scene_02", "duration": 75.0},
            ],
        }

        script_file = tmp_path / "script.json"
        script_file.write_text(json.dumps(script_data))

        durations = _load_scene_durations(str(script_file), 2)
        assert durations["scene_01"] == 45.0
        assert durations["scene_02"] == 75.0

    def test_load_scene_durations_fallback_to_split(self, tmp_path):
        """Falls back to evenly splitting total duration when per-scene duration missing."""
        sd_dir = PI_SKILLS_DIR / "create-sound-design"
        if not sd_dir.exists():
            pytest.skip("create-sound-design skill not found")

        sys.path.insert(0, str(sd_dir))
        from create_sound_design.orchestrator import _load_scene_durations

        script_data = {
            "duration_seconds": 90,
            "scenes": [
                {"id": "scene_01"},
                {"id": "scene_02"},
                {"id": "scene_03"},
            ],
        }

        script_file = tmp_path / "script.json"
        script_file.write_text(json.dumps(script_data))

        durations = _load_scene_durations(str(script_file), 3)
        assert durations["scene_01"] == 30.0
        assert durations["scene_02"] == 30.0
        assert durations["scene_03"] == 30.0
