# Generated by test-lab — blind adversarial evaluation
"""test_live_transport_server - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

import json
import threading
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

import pytest

from battle_skill.live_transport_server import (
    LiveControlConfig,
    build_live_transport_source,
    create_live_transport_server,
    prove_live_transport_server,
    prove_production_websocket_transport,
)


FIXTURE = Path("spectator/public/battle-fixtures/battle-004-pr6-genetic-pixi/battle.normalized_ux_fixture.json")
FIXTURE_AUTH_VALUE = "test-production-ws-auth-value"


def test_live_transport_source_builds_snapshot_and_ordered_events():
    source = build_live_transport_source(fixture_path=FIXTURE, battle_id="battle-004")

    assert source.snapshot["schema"] == "battle.snapshot.v1"
    assert source.snapshot["battle_id"] == "battle-004"
    assert source.snapshot["last_seq"] == len(source.events)
    assert len(source.events) > 0
    assert [event["seq"] for event in source.events] == list(range(1, len(source.events) + 1))
    assert all(event["schema"] == "battle.live_event.v1" for event in source.events)


def test_live_transport_source_rejects_battle_id_mismatch():
    with pytest.raises(ValueError, match="battle_id"):
        build_live_transport_source(fixture_path=FIXTURE, battle_id="battle-999")


def test_prove_live_transport_server_exercises_snapshot_sse_and_resume(tmp_path):
    receipt = prove_live_transport_server(fixture_path=FIXTURE, battle_id="battle-004", out_dir=tmp_path)

    assert receipt["status"] == "PASS"
    assert receipt["mocked"] is False
    assert receipt["live"] == "local_http_sse_websocket_adapter"
    assert receipt["snapshot_schema"] == "battle.snapshot.v1"
    assert receipt["event_schema"] == "battle.live_event.v1"
    assert receipt["event_count"] == receipt["last_seq"]
    assert receipt["resume_from_last_event_id"] == 2
    assert receipt["resumed_event_count"] == receipt["event_count"] - 2
    assert receipt["future_last_event_id_status"] == 400
    assert receipt["raw_path_boundary"]["raw_paths_leaked"] is False
    assert "exploit succeeded" not in " ".join(receipt["claim_boundary"]["proves"]).lower()
    assert (tmp_path / "live-transport-server-proof.json").exists()
    assert (tmp_path / "snapshot-response.json").exists()
    assert (tmp_path / "events.sse").read_text(encoding="utf-8").startswith("id: 1\n")
    assert "event: battle.live_event\n" in (tmp_path / "events.sse").read_text(encoding="utf-8")


def test_prove_production_websocket_transport_exercises_auth_reconnect_and_fanout(tmp_path):
    receipt = prove_production_websocket_transport(
        fixture_path=FIXTURE,
        battle_id="battle-004",
        out_dir=tmp_path,
        auth_token=FIXTURE_AUTH_VALUE,
    )

    assert receipt["schema"] == "battle.production_websocket_transport_proof.v1"
    assert receipt["status"] == "PASS"
    assert receipt["mocked"] is False
    assert receipt["live"] == "local_authenticated_websocket_fanout_reconnect_adapter"
    assert receipt["auth"]["unauthenticated_rejection_code"] == 1008
    assert receipt["auth"]["bad_token_rejection_code"] == 1008
    assert receipt["auth"]["token_sha256"] != FIXTURE_AUTH_VALUE
    assert receipt["reconnect"]["resume_from_last_event_id"] == 2
    assert receipt["reconnect"]["resumed_event_count"] == receipt["event_count"] - 2
    assert receipt["reconnect"]["bad_resume_rejection_code"] == 1008
    assert receipt["fanout"]["client_count"] == 2
    assert receipt["fanout"]["identical_streams"] is True
    assert receipt["websocket_snapshot_first"] is True
    assert receipt["websocket_matches_source_events"] is True
    assert receipt["query_token_matches_bearer"] is True
    assert "production ready" not in " ".join(receipt["claim_boundary"]["proves"]).lower()
    assert (tmp_path / "production-websocket-transport-proof.json").exists()
    assert (tmp_path / "authorized-events.jsonl").exists()
    assert (tmp_path / "resumed-events.jsonl").exists()


def test_live_transport_control_post_records_pause_request_and_panel(tmp_path):
    source = build_live_transport_source(fixture_path=FIXTURE, battle_id="battle-004")
    authority_receipt = tmp_path / "authority-receipt.json"
    authority_receipt.write_text(
        json.dumps(
            {
                "schema": "battle.control_authority_receipt.v1",
                "status": "PASS",
                "mocked": False,
                "live": True,
                "run_id": source.run_id,
            }
        ),
        encoding="utf-8",
    )
    config = LiveControlConfig(
        control_dir=tmp_path / "control",
        expected_auth_token="test-control-token",
        authority_receipt=authority_receipt,
        active_run_id=source.run_id,
    )
    server = create_live_transport_server(source=source, host="127.0.0.1", port=0, control_config=config)
    port = int(server.server_address[1])
    thread = threading.Thread(target=server.serve_forever, name="battle-control-post-test", daemon=True)
    thread.start()
    base_url = f"http://127.0.0.1:{port}"
    try:
        request = Request(
            f"{base_url}{source.pause_control_endpoint}",
            method="POST",
            data=json.dumps(
                {
                    "action": "pause_after_round",
                    "run_id": source.run_id,
                    "request_id": "pause-test",
                    "boundary": "round_running",
                }
            ).encode("utf-8"),
            headers={
                "Authorization": "Bearer test-control-token",
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
        )
        with urlopen(request, timeout=10) as response:
            body = json.loads(response.read().decode("utf-8"))
        snapshot = json.loads(urlopen(f"{base_url}{source.snapshot_endpoint}", timeout=10).read().decode("utf-8"))
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)

    assert body["status"] == "ACCEPTED"
    assert body["panel"]["states"][0]["state"] == "accepted"
    assert body["panel"]["control"]["endpoint"] == source.pause_control_endpoint
    assert snapshot["human_interjection_panel"]["states"][0]["request_id"] == "pause-test"
    assert (tmp_path / "control" / "requests" / "pause-test.json").exists()


def test_live_transport_control_rejects_bad_auth(tmp_path):
    source = build_live_transport_source(fixture_path=FIXTURE, battle_id="battle-004")
    authority_receipt = tmp_path / "authority-receipt.json"
    authority_receipt.write_text("{}", encoding="utf-8")
    config = LiveControlConfig(
        control_dir=tmp_path / "control",
        expected_auth_token="test-control-token",
        authority_receipt=authority_receipt,
        active_run_id=source.run_id,
    )
    server = create_live_transport_server(source=source, host="127.0.0.1", port=0, control_config=config)
    port = int(server.server_address[1])
    thread = threading.Thread(target=server.serve_forever, name="battle-control-auth-test", daemon=True)
    thread.start()
    try:
        request = Request(
            f"http://127.0.0.1:{port}{source.pause_control_endpoint}",
            method="POST",
            data=json.dumps(
                {
                    "action": "pause_after_round",
                    "run_id": source.run_id,
                    "request_id": "pause-test",
                    "boundary": "round_running",
                }
            ).encode("utf-8"),
            headers={
                "Authorization": "Bearer wrong-token",
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
        )
        with pytest.raises(HTTPError) as excinfo:
            urlopen(request, timeout=10)
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)

    assert excinfo.value.code == 403
