# Generated by test-lab — blind adversarial evaluation
"""test_team_artifact_pipeline_contract - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from battle_skill.team_artifact_pipeline import (
    review_artifact_errors,
    run_team_artifact_pipeline,
)


def test_team_artifact_pipeline_binds_red_hashes_through_docker(tmp_path: Path) -> None:
    source = tmp_path / "source.py"
    source.write_text(
        "from app import import_zip\nprint(import_zip)\n", encoding="utf-8"
    )
    provider = _provider(tmp_path)
    materialized = _materialized(tmp_path, source, "red_exploit")

    result = run_team_artifact_pipeline(
        battle_id="battle-004",
        run_id="run-1",
        generation=1,
        team="red",
        source_artifact=source,
        provider_receipt=provider,
        materialization_receipt=materialized,
        target_identity_sha256="target-sha",
        out_dir=tmp_path / "pipeline",
    )

    assert result["status"] == "PASS"
    handoff = json.loads(result["handoff_path"].read_text(encoding="utf-8"))
    compile_receipt = json.loads(
        result["compile_receipt_path"].read_text(encoding="utf-8")
    )
    selected_sha = hashlib.sha256(
        result["selected_artifact_path"].read_bytes()
    ).hexdigest()
    assert handoff["selected_artifact_sha256"] == selected_sha
    assert compile_receipt["selected_artifact_sha256"] == selected_sha
    assert handoff["target_identity_sha256"] == "target-sha"
    assert compile_receipt["live"] == "docker_python_compile"


def test_team_artifact_pipeline_blocks_blue_without_public_interface(
    tmp_path: Path,
) -> None:
    source = tmp_path / "source.py"
    source.write_text("def unrelated():\n    return True\n", encoding="utf-8")
    provider = _provider(tmp_path)
    materialized = _materialized(tmp_path, source, "blue_patch")

    result = run_team_artifact_pipeline(
        battle_id="battle-004",
        run_id="run-1",
        generation=1,
        team="blue",
        source_artifact=source,
        provider_receipt=provider,
        materialization_receipt=materialized,
        target_identity_sha256="target-sha",
        out_dir=tmp_path / "pipeline",
    )

    assert result["status"] == "BLOCKED"
    review = json.loads(result["review_receipt_path"].read_text(encoding="utf-8"))
    assert "blue artifact does not preserve import_zip interface" in review["errors"]


def test_red_artifact_review_accepts_importlib_import_module_getattr() -> None:
    text = (
        "import importlib\n"
        "module = importlib.import_module('app')\n"
        "import_zip = getattr(module, 'import_zip')\n"
        "import_zip('payload.zip', 'destination')\n"
    )

    assert review_artifact_errors("red", text) == []


def test_red_artifact_review_accepts_local_spec_loader_getattr() -> None:
    text = (
        "import importlib.util as import_util\n"
        "from pathlib import Path\n"
        "app_path = Path.cwd() / 'app.py'\n"
        "spec = import_util.spec_from_file_location('battle_local_app', str(app_path))\n"
        "module = import_util.module_from_spec(spec)\n"
        "spec.loader.exec_module(module)\n"
        "getattr(module, 'import_zip')('payload.zip', 'destination')\n"
    )

    assert review_artifact_errors("red", text) == []


def test_red_artifact_review_accepts_helper_returned_import_zip() -> None:
    text = (
        "import importlib.util\n"
        "from pathlib import Path\n"
        "def load_import_zip():\n"
        "    app_path = Path.cwd() / 'app.py'\n"
        "    spec = importlib.util.spec_from_file_location('local_app', str(app_path))\n"
        "    module = importlib.util.module_from_spec(spec)\n"
        "    spec.loader.exec_module(module)\n"
        "    fn = getattr(module, 'import_zip')\n"
        "    return fn\n"
        "import_zip = load_import_zip()\n"
        "import_zip('payload.zip', 'destination')\n"
    )

    assert review_artifact_errors("red", text) == []


def test_red_artifact_review_accepts_helper_returned_local_app_module() -> None:
    text = (
        "import importlib.util\n"
        "from pathlib import Path\n"
        "def load_local_app():\n"
        "    app_path = Path.cwd() / 'app.py'\n"
        "    spec = importlib.util.spec_from_file_location('battle_local_app', str(app_path))\n"
        "    module = importlib.util.module_from_spec(spec)\n"
        "    spec.loader.exec_module(module)\n"
        "    return module\n"
        "def run_probe():\n"
        "    app = load_local_app()\n"
        "    app.import_zip('payload.zip', 'destination')\n"
    )

    assert review_artifact_errors("red", text) == []


def test_red_artifact_review_rejects_wrong_module_import() -> None:
    text = (
        "import importlib\n"
        "module = importlib.import_module('other')\n"
        "import_zip = getattr(module, 'import_zip')\n"
        "import_zip('payload.zip', 'destination')\n"
    )

    assert "red artifact does not bind the public app import interface" in (
        review_artifact_errors("red", text)
    )


def _json(path: Path, payload: dict[str, object]) -> Path:
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path


def _provider(root: Path) -> Path:
    return _json(
        root / "provider.json",
        {"schema": "tau.subagent_receipt.v1", "result": {"status": "PASS"}},
    )


def _materialized(root: Path, source: Path, artifact_type: str) -> Path:
    return _json(
        root / "materialized.json",
        {
            "schema": "tau.battle_materialized_artifact_receipt.v1",
            "status": "PASS",
            "artifact_type": artifact_type,
            "path": str(source.resolve()),
            "artifact_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
            "artifact_bytes": source.stat().st_size,
            "strategy_genome_sha256": "genome-sha",
            "scillm_call_receipt_sha256": "call-sha",
        },
    )
