# Generated by test-lab — blind adversarial evaluation
"""test_coverage_loop - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib.coverage_loop import CoverageLoopConfig, build_coverage_loop


def write_json(path: Path, data: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data), encoding="utf-8")


def write_knowledge(path: Path):
    path.write_text(
        "PDF Lab Coverage is not a passive status dump.\n"
        "Persistent Coverage blocker triggers interview or dogpile before replanning.\n",
        encoding="utf-8",
    )


def config(tmp_path: Path, status: dict, active_plan: bool = True) -> CoverageLoopConfig:
    status_path = tmp_path / "status.json"
    knowledge_path = tmp_path / "PROJECT_KNOWLEDGE.md"
    out_path = tmp_path / "pdf-lab-coverage-loop.json"
    plan_path = tmp_path / "active.yaml" if active_plan else None
    if plan_path:
        plan_path.write_text("plan: true\n", encoding="utf-8")
    write_json(status_path, status)
    write_knowledge(knowledge_path)
    return CoverageLoopConfig(
        status_report_path=status_path,
        project_knowledge_path=knowledge_path,
        active_plan_path=plan_path,
        output_path=out_path,
    )


def test_complete_when_no_blockers(tmp_path):
    artifact = build_coverage_loop(config(tmp_path, {"blockers": [], "summary": {}}), append_history=False)
    assert artifact["next_action"] == "complete"
    assert artifact["same_blocker_streak"] == 0
    assert artifact["project_knowledge_checked"] is True
    assert artifact["memory_recall_required"] is True


def test_amends_active_plan_for_first_blocker(tmp_path):
    status = {"blockers": [{"area": "TOC Audit", "severity": "high", "detail": "299 repairs", "next_action": "repair"}], "summary": {}}
    artifact = build_coverage_loop(config(tmp_path, status), append_history=False)
    assert artifact["next_action"] == "amend_plan"
    assert artifact["same_blocker_streak"] == 1
    assert artifact["blocker_signature"]
    assert "orchestrate" in artifact["recommended_command"]


def test_repeated_technical_blocker_stops_for_dogpile(tmp_path):
    status = {"blockers": [{"area": "TOC Audit", "severity": "high", "detail": "299 repairs", "next_action": "repair"}], "summary": {}}
    cfg = config(tmp_path, status)
    first = build_coverage_loop(cfg, append_history=True)
    second = build_coverage_loop(cfg, append_history=True)
    assert first["next_action"] == "amend_plan"
    assert second["same_blocker_streak"] == 2
    assert second["next_action"] == "stop_dogpile"
    assert second["must_stop_for_dogpile"] is True


def test_repeated_human_blocker_stops_for_interview(tmp_path):
    status = {"blockers": [{"area": "Human Triage", "severity": "high", "detail": "2 cards", "next_action": "resolve"}], "summary": {}}
    cfg = config(tmp_path, status)
    build_coverage_loop(cfg, append_history=True)
    artifact = build_coverage_loop(cfg, append_history=True)
    assert artifact["next_action"] == "stop_interview"
    assert artifact["must_stop_for_interview"] is True
