#!/usr/bin/env bash
set -euo pipefail

skill_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$skill_dir/../.." && pwd)"

python "$repo_root/skills/.system/skill-creator/scripts/quick_validate.py" "$skill_dir"

grep -q '^name: create-architecture$' "$skill_dir/SKILL.md"
grep -q 'Do not return a review verdict' "$skill_dir/SKILL.md"
grep -q 'Required Output' "$skill_dir/SKILL.md"
grep -q 'Authority Boundaries' "$skill_dir/SKILL.md"
grep -q 'Deterministic Acceptance Tests' "$skill_dir/SKILL.md"
grep -q 'WebGPT And Reviewer Routing' "$skill_dir/SKILL.md"
grep -q 'WebGPT Clarification And Creation Loop' "$skill_dir/SKILL.md"
grep -q 'Ambiguity Exit Gate' "$skill_dir/SKILL.md"
grep -q 'No material ambiguity remains' "$skill_dir/SKILL.md"
grep -q 'finished-file zip bundle' "$skill_dir/SKILL.md"
grep -q 'Finished-File Zip Bundle Manifest' "$skill_dir/SKILL.md"
grep -q 'Surf/download proof for zip bundle' "$skill_dir/SKILL.md"
grep -q '## Solution zip download and capture' "$skill_dir/SKILL.md"
grep -q 'missing_webgpt_zip_download_capability' "$skill_dir/SKILL.md"
grep -q 'Do not port from prose-only descriptions' "$skill_dir/SKILL.md"
grep -q 'isolated sanity directory' "$skill_dir/SKILL.md"
grep -q 'project agents are weak at greenfield architecture' "$skill_dir/SKILL.md"
grep -q 'not allowed to bespoke the greenfield code' "$skill_dir/SKILL.md"
grep -q 'WebGPT owns greenfield solution creation' "$skill_dir/SKILL.md"
grep -q 'Do not return PASS/NEEDS_CHANGES/BLOCKED' "$skill_dir/SKILL.md"


grep -q 'ask' "$skill_dir/SKILL.md"
grep -q '## Scope (read first)' "$skill_dir/SKILL.md"
grep -q 'single function' "$skill_dir/SKILL.md"
grep -q 'pre-existing project' "$skill_dir/SKILL.md"
grep -q '## Project agent responsibilities' "$skill_dir/SKILL.md"
grep -q 'questions-only' "$skill_dir/SKILL.md"
grep -q '## Isolated Sanity Check Boundary' "$skill_dir/SKILL.md"
grep -q 'integration from a' "$skill_dir/SKILL.md"

grep -q '^Triggers:$' "$skill_dir/SKILL.md"
grep -q '^Composes:$' "$skill_dir/SKILL.md"
grep -q '^- handoff$' "$skill_dir/SKILL.md"
grep -q '## Handoff, Goal, And Creation Brief' "$skill_dir/SKILL.md"
grep -q '### HANDOFF.md Requirement' "$skill_dir/SKILL.md"
grep -q '### GOAL.md Requirement' "$skill_dir/SKILL.md"
grep -q '### Rendered Goal Page Requirement' "$skill_dir/SKILL.md"
grep -q 'GOAL.md' "$skill_dir/SKILL.md"
grep -q 'rendered HTML/CSS goal page' "$skill_dir/SKILL.md"
grep -q 'primary creation target' "$skill_dir/SKILL.md"
grep -q 'what WebGPT is expected to fix or create' "$skill_dir/SKILL.md"
grep -q 'similar in' "$skill_dir/SKILL.md"
grep -q 'A single' "$skill_dir/SKILL.md"
grep -q 'clear workflow/state-machine charts' "$skill_dir/SKILL.md"
grep -q 'source-derived numbered step model' "$skill_dir/SKILL.md"
grep -q 'end-to-end master flow' "$skill_dir/SKILL.md"
grep -q 'decision gates with explicit pass/fail exits' "$skill_dir/SKILL.md"
grep -q 'endpoint/tool roles' "$skill_dir/SKILL.md"
grep -q 'concrete worked examples' "$skill_dir/SKILL.md"
grep -q 'technical appendix with schemas' "$skill_dir/SKILL.md"
grep -q 'use `GOAL.md` and the rendered page' "$skill_dir/SKILL.md"
grep -q 'missing files, state machines, schemas, tests, and integration points' "$skill_dir/SKILL.md"
grep -q 'too thin to answer' "$skill_dir/SKILL.md"
grep -q '## Creation transport vs review transport' "$skill_dir/SKILL.md"
grep -q 'Do NOT use.*webgpt-review' "$skill_dir/SKILL.md"
grep -q '## Clarification loop until WebGPT is ready' "$skill_dir/SKILL.md"
grep -q 'WebGPT decides it has enough information' "$skill_dir/SKILL.md"
grep -q 'Run `/handoff`' "$skill_dir/SKILL.md"
grep -q 'prompt_improvements' "$skill_dir/SKILL.md"
grep -q '## Prompt Improvements For Next Turn' "$skill_dir/SKILL.md"
grep -q 'The project agent must read this section before continuing' "$skill_dir/SKILL.md"
grep -q '## HANDOFF.md' "$skill_dir/SKILL.md"
grep -q '## GOAL.md' "$skill_dir/SKILL.md"
grep -q 'Not Excalidraw / UX Lab' "$skill_dir/SKILL.md"
grep -q '## Runnable entrypoint' "$skill_dir/SKILL.md"
grep -q '## Round terminology' "$skill_dir/SKILL.md"
grep -q '## Creation bundle packaging' "$skill_dir/SKILL.md"
grep -q '## Solution zip layout' "$skill_dir/SKILL.md"
grep -q 'Multi-file delivery rule' "$skill_dir/SKILL.md"
grep -q 'Multi-file zip required' "$skill_dir/SKILL.md"
grep -q 'Solution zip filename (required' "$skill_dir/SKILL.md"
grep -q 'bundle_filename' "$skill_dir/SKILL.md"
grep -q 'Do not rename the download to .source.zip' "$skill_dir/SKILL.md"
grep -q '## Port and apply into the real repo' "$skill_dir/SKILL.md"
grep -q 'missing_webgpt_zip_download_capability' "$skill_dir/SKILL.md"

grep -q '## Rendered Goal Page Or Visual Reference' "$skill_dir/SKILL.md"

grep -q '## Document map' "$skill_dir/SKILL.md"
grep -q '## Artifact directories' "$skill_dir/SKILL.md"
grep -q 'Not Excalidraw / UX Lab' "$skill_dir/SKILL.md"
test -f "$skill_dir/REPORT_ENFORCEMENT.md"
grep -q "Report before closure" "$skill_dir/SKILL.md"
grep -q "Hard stop:" "$skill_dir/SKILL.md"
grep -q "engagement log" "$skill_dir/SKILL.md"
grep -q "Human verification surface" "$skill_dir/SKILL.md"
echo "create-architecture sanity passed"
