# Generated by test-lab — blind adversarial evaluation
"""test_scheduler - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

from pathlib import Path


def test_scheduler_command_is_full_run_transaction() -> None:
    source = (Path(__file__).parents[1] / "src" / "monitor_opportunities" / "cli.py").read_text(
        encoding="utf-8"
    )
    assert "monitor-opportunities-nightly" in source
    assert 'nightly_args = ["nightly"]' in source
    assert "--diagnostic" in source
    assert "--expected-revision" in source
    registered_args = source.split("nightly_args.extend(", 1)[1].split("command_parts", 1)[0]
    assert "--skip-relationship-memory" not in registered_args
    assert "MONITOR_RELATIONSHIP_SIGNALS_ENABLED=1" in source
    assert "scheduler" in source
    assert "_canonical_repo_root" in source
    assert '".worktrees"' in source
