# Generated by test-lab — blind adversarial evaluation
"""test_pipeline - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

import monitor_opportunities.pipeline as pipeline
from monitor_opportunities.cli import app
from monitor_opportunities.contracts import IMMUTABLE_GOAL, ContractError
from monitor_opportunities.discovery import _linkedin_evidence_candidates
from monitor_opportunities.pipeline import _is_report_opportunity, _source_intel, run_stage0
from monitor_opportunities.util import sha256_json

runner = CliRunner()
SKILL_DIR = Path(__file__).resolve().parents[1]


def test_diagnostic_run_degrades_required_source_gate_without_changing_strict_mode(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    skill_dir = SKILL_DIR

    def fake_sweep(*, out_dir: Path, **_: object) -> dict[str, object]:
        out_dir.mkdir(parents=True)
        (out_dir / "source-receipts.jsonl").write_text(
            json.dumps(
                {
                    "receipt_id": "locator-only",
                    "lane": "A",
                    "provider": "indeed",
                    "target": "indeed",
                    "required_source_id": "indeed",
                    "channel": "source_locator",
                    "source_class": "source_locator",
                    "result_status": "NO_MATCHES",
                    "observed_at": "2026-08-13T00:00:00Z",
                    "request_summary": "locator only",
                    "response_status": 200,
                    "content_type": None,
                    "response_bytes": 1,
                    "content_sha256": "a" * 64,
                    "evidence_refs": ["fixture://locator"],
                    "limitations": [],
                },
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        (out_dir / "run-manifest.json").write_text("{}", encoding="utf-8")
        return {"schema": "fake.discovery"}

    def fake_rank(discovery_dir: Path, limit: int, ranking_dir: Path) -> dict[str, object]:
        del discovery_dir, limit
        ranking_dir.mkdir(parents=True)
        (ranking_dir / "shortlist.json").write_text("[]\n", encoding="utf-8")
        (ranking_dir / "rejections.json").write_text("[]\n", encoding="utf-8")
        (ranking_dir / "ranking-receipt.json").write_text("{}", encoding="utf-8")
        return {"schema": "fake.ranking"}

    def fake_report_from_run(*_: object, **__: object) -> dict[str, object]:
        return {"schema": "fake.report", "generated_at": "2026-08-13T00:00:00Z"}

    def fake_render_report(_manifest: object, report_dir: Path) -> dict[str, str]:
        report_dir.mkdir(parents=True)
        html = report_dir / "index.html"
        report_json = report_dir / "report.json"
        html.write_text("<html></html>\n", encoding="utf-8")
        report_json.write_text("{}\n", encoding="utf-8")
        return {"report_html": str(html), "report_json": str(report_json)}

    monkeypatch.setattr(pipeline, "sweep", fake_sweep)
    monkeypatch.setattr(pipeline, "rank", fake_rank)
    monkeypatch.setattr(pipeline, "_report_from_run", fake_report_from_run)
    monkeypatch.setattr(pipeline, "load_manifest", lambda path: json.loads(path.read_text(encoding="utf-8")))
    monkeypatch.setattr(pipeline, "render_report", fake_render_report)

    with pytest.raises(ContractError) as strict_error:
        run_stage0(skill_dir, tmp_path / "strict")
    assert strict_error.value.code == "REQUIRED_SOURCE_CONTRACT_VIOLATION"

    receipt = run_stage0(skill_dir, tmp_path / "diagnostic", degrade_required_source_failures=True)
    assert receipt["terminal_state"] == "AWAITING_HUMAN"
    assert receipt["live"] is True
    assert receipt["degraded_contracts"]
    assert receipt["degraded_contracts"][0]["code"] == "REQUIRED_SOURCE_CONTRACT_VIOLATION"
    phases = {row["phase"] for row in receipt["phase_artifacts"]}
    assert "REQUIRED_SOURCES_DEGRADED" in phases
    assert (tmp_path / "diagnostic" / "report" / "index.html").exists()


def test_run_creates_one_report_and_receipt(tmp_path: Path) -> None:
    fixture_dir = Path(__file__).parent / "fixtures" / "discovery"
    out = tmp_path / "nightly"
    result = runner.invoke(app, ["run", "--fixture-dir", str(fixture_dir), "--out", str(out)])
    assert result.exit_code == 0, result.output
    receipt = json.loads((out / "run-receipt.json").read_text(encoding="utf-8"))
    assert receipt["terminal_state"] == "AWAITING_HUMAN"
    assert receipt["external_effects"] is False
    assert (out / "report" / "index.html").exists()
    status = runner.invoke(app, ["resume", "--run", str(out)])
    assert status.exit_code == 0, status.output
    assert json.loads(status.stdout)["state"] == "AWAITING_HUMAN"
    manifest = json.loads((out / "report-manifest.json").read_text(encoding="utf-8"))
    run_status = runner.invoke(app, ["status", "--run", str(out), "--json"])
    assert run_status.exit_code == 0, run_status.output
    payload = json.loads(run_status.stdout)
    assert payload["state"] == "AWAITING_HUMAN"
    assert payload["operational_readiness"] == manifest["operational_readiness"]
    assert payload["external_effects"] is False
    assert payload["current_stale"] is False
    assert payload["dependency_readiness"] == {
        "discovery": "READY",
        "ranking": "READY",
        "tailoring": "READY",
        "report": "READY",
    }
    assert payload["artifact_accounting"]["hidden_total"] == 0
    assert payload["artifact_counts"]["opportunities"] == len(manifest["opportunities"])
    assert payload["artifact_counts"]["resume_variants"] == len(manifest["resume_variants"])
    assert payload["artifact_counts"]["application_packets"] == len(manifest["application_packets"])
    assert payload["artifact_counts"]["relationship_signals"] == len(
        manifest.get("relationship_signals", [])
    )
    degraded_receipts = [
        row
        for row in manifest["source_receipts"]
        if row["result_status"] not in {"MATCHES", "NO_MATCHES"}
    ]
    assert payload["source_health"]["total_receipts"] == len(manifest["source_receipts"])
    assert payload["source_health"]["degraded_count"] == len(degraded_receipts)
    assert len(payload["lane_health"]) == 3
    assert payload["budget"]["max"] == 10.0
    assert manifest["application_packets"]
    packet = manifest["application_packets"][0]
    assert packet["visible_in_report"] is True
    assert packet["action_worthy"] is True
    assert packet["approval_status"] == "NOT_AUTHORIZED"
    assert packet["resume_digest"]
    assert packet["claim_snapshot_digest"] == manifest["resume_variants"][0]["claim_snapshot_sha256"]
    assert packet["field_answer_digest"]
    assert packet["posting_digest"]
    assert packet["approval_payload_digest"]
    packet_json = json.loads(Path(packet["packet_ref"]).read_text(encoding="utf-8"))
    assert packet_json["packet_id"] == packet["packet_id"]
    application_id = packet["application_id"]
    authorize = runner.invoke(
        app,
        [
            "decision",
            "--run",
            str(out),
            "--item",
            application_id,
            "--action",
            "AUTHORIZE_APPLICATION_PAYLOAD",
            "--idempotency-key",
            "authorize-before-drift",
        ],
    )
    assert authorize.exit_code == 0, authorize.output
    Path(packet["resume_artifacts"][0]["path"]).write_text("tampered resume\n", encoding="utf-8")
    drifted = runner.invoke(
        app,
        [
            "decision",
            "--run",
            str(out),
            "--item",
            application_id,
            "--action",
            "AUTHORIZE_APPLICATION_PAYLOAD",
            "--idempotency-key",
            "authorize-after-drift",
        ],
    )
    assert drifted.exit_code == 2
    assert "APPLICATION_PACKET_DRIFT" in drifted.stderr


def test_run_clears_generated_children_before_writing_current_artifacts(tmp_path: Path) -> None:
    fixture_dir = Path(__file__).parent / "fixtures" / "discovery"
    out = tmp_path / "nightly"
    stale_files = [
        out / "tailoring" / "stale-apply-prep.json",
        out / "application-packets" / "stale-packet.json",
        out / "report" / "stale-report.json",
        out / "morning-digest.json",
    ]
    for path in stale_files:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text('{"stale": true}\n', encoding="utf-8")

    result = runner.invoke(app, ["run", "--fixture-dir", str(fixture_dir), "--out", str(out)])

    assert result.exit_code == 0, result.output
    assert all(not path.exists() for path in stale_files)
    assert (out / "run-receipt.json").exists()
    assert (out / "report" / "report.json").exists()


def test_run_with_linkedin_evidence_renders_no_automation_policy(tmp_path: Path) -> None:
    fixture = Path(__file__).parent / "fixtures" / "discovery" / "linkedin-top-candidate.json"
    out = tmp_path / "nightly-linkedin"
    sam_ev = SKILL_DIR / "tests" / "fixtures" / "federal" / "sam-website-capture.json"
    result = runner.invoke(app, ["run", "--linkedin-evidence", str(fixture), "--federal-evidence", str(sam_ev), "--out", str(out)])
    assert result.exit_code == 2
    assert "CLAIM_SNAPSHOT_REQUIRED" in result.stderr
    receipt, rows = _linkedin_evidence_candidates(fixture)
    assert receipt["required_source_id"] == "linkedin_top_applicant"
    assert receipt["automation_policy"] == "linkedin_no_automation"
    assert rows
    assert _is_report_opportunity(rows[0]) is False
    intel = _source_intel(rows[0])
    assert intel is not None
    assert intel["signal_type"] == "LINKEDIN_LOCATOR"
    assert intel["decision"] == "LOCATOR_ONLY"
    assert intel["action_worthy"] is False


def test_run_with_ops_linkedin_capture_ranks_relevant_jobs_and_rejects_irrelevant(tmp_path: Path) -> None:
    fixture = Path(__file__).parent / "fixtures" / "discovery" / "ops-linkedin-jobs-capture.json"
    out = tmp_path / "nightly-ops-linkedin"
    sam_ev = SKILL_DIR / "tests" / "fixtures" / "federal" / "sam-website-capture.json"
    result = runner.invoke(app, ["run", "--linkedin-evidence", str(fixture), "--federal-evidence", str(sam_ev), "--out", str(out)])
    assert result.exit_code == 2
    assert "CLAIM_SNAPSHOT_REQUIRED" in result.stderr
    receipt, rows = _linkedin_evidence_candidates(fixture)
    assert receipt["source_class"] == "ops_linkedin_authorized_read_only"
    assert receipt["automation_policy"] == "linkedin_authorized_read_only_no_actions"
    assert rows
    assert all(_is_report_opportunity(row) is False for row in rows)
    intel = [_source_intel(row) for row in rows]
    assert all(row and row["signal_type"] == "LINKEDIN_LOCATOR" for row in intel)


def test_run_with_meetup_evidence_renders_networking_signal_and_decisions(tmp_path: Path) -> None:
    fixture_dir = Path(__file__).parent / "fixtures" / "discovery"
    meetup = fixture_dir / "meetup-buffalo-capture.json"
    out = tmp_path / "nightly-meetup"
    result = runner.invoke(
        app,
        ["run", "--fixture-dir", str(fixture_dir), "--meetup-evidence", str(meetup), "--out", str(out)],
    )
    assert result.exit_code == 0, result.output
    manifest = json.loads((out / "report-manifest.json").read_text(encoding="utf-8"))
    networking = [row for row in manifest["source_intel"] if row["signal_type"] == "MEETUP_NETWORKING"]
    assert networking
    assert any(row["organization"] == "Infosec 716" for row in networking)
    infosec = next(row for row in networking if row["organization"] == "Infosec 716")
    assert infosec["decision"] == "ATTEND_MEETUP"
    assert any("Meetup source-intel only" in item for item in infosec["reasons"])
    intel_ids = {row["signal_id"] for row in networking}
    assert not any(row["opportunity_id"] in intel_ids for row in manifest["resume_variants"])
    assert not any(row["opportunity_id"] in intel_ids for row in manifest["outreach_packets"])
    assert not any(row["opportunity_id"] in intel_ids for row in manifest["applications"])
    assert not any(row["opportunity_id"] in intel_ids for row in manifest["application_packets"])
    relationship_signals = manifest["relationship_signals"]
    assert relationship_signals
    assert any(row["subject"] == "Bit Haven overlap" for row in relationship_signals)
    assert all(row["visible_in_report"] is True for row in relationship_signals)
    assert all(row["external_effects"] is False for row in relationship_signals)
    assert all(row["contact_channel_risk"] == "corporate_email_may_be_blocked_after_long_gap" for row in relationship_signals)
    assert all("AUTHORIZED_PERSONA_GMAIL" in row["preferred_human_channels"] for row in relationship_signals)
    actions = {row["action"]: row for row in manifest["decision_actions"]}
    assert actions["ATTEND_MEETUP"]["effects_external"] is False
    assert actions["ATTEND_MEETUP"]["target_type"] == "source_intel"
    assert actions["WATCH_MEETUP"]["effects_external"] is False
    assert actions["SKIP_MEETUP"]["effects_external"] is False
    assert actions["RECONNECT_CONTACT"]["target_type"] == "relationship_signal"
    lane_c = next(row for row in manifest["lane_coverage"] if row["lane"] == "C")
    assert lane_c["candidates_admitted"] == (
        lane_c["candidates_admitted_opportunities"] + lane_c["candidates_admitted_source_intel"]
    )
    assert lane_c["candidates_admitted_source_intel"] >= len(networking)


def test_run_renders_reviewed_gmail_draft_receipt(tmp_path: Path) -> None:
    fixture_dir = Path(__file__).parent / "fixtures" / "discovery"
    baseline = tmp_path / "baseline"
    baseline_result = runner.invoke(app, ["run", "--fixture-dir", str(fixture_dir), "--out", str(baseline)])
    assert baseline_result.exit_code == 0, baseline_result.output
    baseline_manifest = json.loads((baseline / "report-manifest.json").read_text(encoding="utf-8"))
    gmail_packet = next(
        packet for packet in baseline_manifest["outreach_packets"] if packet["channel"] == "GMAIL"
    )
    roundtable_receipt = {
        "schema": "monitor_opportunities.outreach_roundtable_receipt.v1",
        "receipt_key": f"{gmail_packet['opportunity_id']}:GMAIL",
        "immutable_goal": IMMUTABLE_GOAL,
        "topology": "concurrent",
        "rounds": 1,
        "attributed_synthesis": True,
        "packet_digest": gmail_packet["payload_digest"],
        "verdict": "SEND_AS_IS",
        "seats": [
            {"handler": "gpt-5.5-high", "status": "PASS"},
            {"handler": "gpt-5.5-xhigh", "status": "PASS"},
        ],
        "dissent": [],
    }
    effect_payload = {
        "schema": "monitor_opportunities.outreach_effect_receipt.v1",
        "effect_id": "effect:test",
        "packet_id": gmail_packet["packet_id"],
        "channel": "GMAIL",
        "state": "DRAFT_CREATED_NOT_SENT",
        "draft_id": "draft:test",
        "idempotency_key": "same",
        "idempotency_marker": "marker:test",
        "subject_digest": sha256_json(gmail_packet["subject"]),
        "body_digest": sha256_json(gmail_packet["body"]),
        "gmail_sent": False,
        "linkedin_automated": False,
        "external_effects": True,
        "created_at": "2026-08-04T00:00:00+00:00",
    }
    effect_payload["receipt_digest"] = sha256_json(effect_payload)
    receipts = tmp_path / "roundtable.json"
    effects = tmp_path / "effects.json"
    receipts.write_text(
        json.dumps({roundtable_receipt["receipt_key"]: roundtable_receipt}),
        encoding="utf-8",
    )
    effects.write_text(json.dumps([effect_payload]), encoding="utf-8")

    out = tmp_path / "reviewed"
    result = runner.invoke(
        app,
        [
            "run",
            "--fixture-dir",
            str(fixture_dir),
            "--roundtable-receipts",
            str(receipts),
            "--outreach-effects",
            str(effects),
            "--out",
            str(out),
        ],
    )
    assert result.exit_code == 0, result.output
    manifest = json.loads((out / "report-manifest.json").read_text(encoding="utf-8"))
    reviewed = next(packet for packet in manifest["outreach_packets"] if packet["packet_id"] == gmail_packet["packet_id"])
    assert reviewed["roundtable_status"] == "PASS"
    assert reviewed["readiness_state"] == "REVIEW_PERMITTED"
    assert reviewed["effect_status"] == "DRAFT_CREATED_NOT_SENT"
    assert reviewed["draft_id"] == "draft:test"
    assert reviewed["mailbox_draft_ref"] == "gmail:draft:draft:test"
    assert reviewed["sendable"] is False
    assert "gmail:draft:draft:test" in (out / "report" / "index.html").read_text(encoding="utf-8")
