# Generated by test-lab — blind adversarial evaluation
"""Morning digest: ranks by response, classifies, attaches decision-makers."""
from __future__ import annotations

from monitor_opportunities.morning_digest import build_digest


def test_digest_ranks_classifies_and_flags_signals() -> None:
    sl = [
        {"organization": "Drata", "title": "Staff AI Engineer", "lane": "A", "fit_score": 0.8,
         "workplace_type": "REMOTE", "apply_url": "https://jobs.ashbyhq.com/drata/x",
         "source_class": "ashby"},
        {"organization": "CUBRC", "title": "AI research", "lane": "A", "fit_score": 0.8,
         "workplace_type": "WNY_ONSITE", "source_provider": "discover-contacts"},
        {"organization": "DARPA", "title": "Sources Sought", "lane": "B",
         "signal_type": "federal", "fit_score": 0.7},
    ]
    d = build_digest(sl)
    assert d["counts"]["employment"] == 2 and d["counts"]["consulting"] == 1
    assert d["signals_wired"]["warm_path"] is False  # honest: not wired yet
    # local Buffalo role outranks the remote cold-apply at equal fit
    orgs = [e["organization"] for e in d["top"]]
    assert orgs.index("CUBRC") < orgs.index("Drata")
    # consulting entry carries no apply action
    darpa = next(e for e in d["top"] if e["organization"] == "DARPA")
    assert darpa["opportunity_type"] == "consulting" and darpa["action"]["apply_on_site"] is None
    # known decision-maker attached
    drata = next(e for e in d["top"] if e["organization"] == "Drata")
    assert drata["inmail_target"] and "Lior" in drata["inmail_target"]["name"]


def test_per_org_diversity_cap_prevents_one_company_flooding() -> None:
    # One org with five open roles must not fill the whole digest.
    sl = [
        {"organization": "Unstructured", "title": f"Role {i}", "lane": "A",
         "fit_score": 0.9, "source_class": "ashby", "candidate_id": f"u{i}"}
        for i in range(5)
    ] + [
        {"organization": "Vanta", "title": "Backend", "lane": "A", "fit_score": 0.9,
         "source_class": "ashby", "candidate_id": "v1"},
    ]
    d = build_digest(sl, top_n=4, max_per_org=2)
    orgs = [e["organization"] for e in d["top"]]
    assert orgs.count("Unstructured") == 2  # capped
    assert "Vanta" in orgs  # diversity preserved


def test_live_trigger_reorders_and_surfaces_evidence() -> None:
    sl = [
        {"organization": "Alpha", "title": "AI Architect", "fit_score": 0.8,
         "source_class": "ashby"},
        {"organization": "Beta", "title": "ML Eng", "fit_score": 0.8, "source_class": "ashby"},
    ]
    d = build_digest(sl, triggers={"Beta": {"trigger": 0.9, "evidence": "raised $40M Series B"}})
    assert d["signals_wired"]["trigger"] is True
    beta = next(e for e in d["top"] if e["organization"] == "Beta")
    assert beta["trigger_evidence"] == "raised $40M Series B"
    alpha = next(e for e in d["top"] if e["organization"] == "Alpha")
    assert beta["response_score"] > alpha["response_score"]


def test_competition_varies_by_source_not_flat_default() -> None:
    from monitor_opportunities.response_likelihood import score_opportunity
    cold = score_opportunity({"organization": "X", "fit": 0.9, "source_class": "ashbyhq.com"})
    li = score_opportunity({
        "organization": "Y",
        "fit": 0.9,
        "source_provider": "ops_linkedin_authorized_read_only",
    })
    # Cold ATS is higher-competition than mass-board LinkedIn -> lower low_competition.
    assert cold["drivers"]["low_competition"] < li["drivers"]["low_competition"]
    # And neither is the flat 0.4 default (1 - 0.6) that collapsed the last run.
    assert cold["drivers"]["low_competition"] != 0.4


def test_digest_balances_employment_and_consulting() -> None:
    # Graham 2026-08-13: "roughly equal number of employment and consulting".
    # Employment vastly outnumbers consulting in discovery, so a global top-N
    # returned 8 employment / 0 consulting even with consulting rows available.
    sl = [{"organization": f"Emp{i}", "title": "AI Architect", "lane": "A",
           "fit_score": 0.9, "source_class": "ashby", "candidate_id": f"e{i}"}
          for i in range(10)]
    sl += [{"organization": f"Fed{i}", "title": "Sources Sought", "lane": "B",
            "signal_type": "federal", "fit_score": 0.6, "candidate_id": f"c{i}"}
           for i in range(6)]
    d = build_digest(sl, top_n=8)
    kinds = [e["opportunity_type"] for e in d["top"]]
    assert kinds.count("consulting") == 4 and kinds.count("employment") == 4


def test_short_track_releases_its_slots_instead_of_padding() -> None:
    # Under-supply must be honest: unfilled consulting slots go to employment
    # rather than admitting weak consulting rows.
    sl = [{"organization": f"Emp{i}", "title": "AI Architect", "lane": "A",
           "fit_score": 0.9, "source_class": "ashby", "candidate_id": f"e{i}"}
          for i in range(10)]
    sl += [{"organization": "Fed0", "title": "Sources Sought", "lane": "B",
            "signal_type": "federal", "fit_score": 0.6, "candidate_id": "c0"}]
    d = build_digest(sl, top_n=8)
    kinds = [e["opportunity_type"] for e in d["top"]]
    assert len(d["top"]) == 8
    assert kinds.count("consulting") == 1 and kinds.count("employment") == 7


def test_researched_consulting_leads_compete_for_the_consulting_half() -> None:
    # Consulting leads are researched (buyer-in-motion signals), not scraped.
    # They must reach the digest's consulting half rather than sit in a side file.
    sl = [{"organization": f"Emp{i}", "title": "AI Architect", "lane": "A",
           "fit_score": 0.9, "source_class": "ashby", "candidate_id": f"e{i}"}
          for i in range(10)]
    sl += [{"organization": "Hadrius", "title": "Raises $27M to build agentic compliance",
            "lane": "C", "signal_type": "commercial", "fit_score": 0.6,
            "source_provider": "consulting-research", "candidate_id": "r1"}]
    d = build_digest(sl, top_n=8)
    orgs = [e["organization"] for e in d["top"]]
    assert "Hadrius" in orgs
    assert next(e for e in d["top"] if e["organization"] == "Hadrius")[
        "opportunity_type"] == "consulting"


def test_employment_candidates_have_selection_accounting() -> None:
    sl = [{"organization": f"Emp{i}", "title": "AI Architect", "lane": "A",
           "fit_score": 0.9 - (i * 0.01), "source_class": "ashby",
           "candidate_id": f"employment-{i}"}
          for i in range(10)]
    sl += [{"organization": f"Fed{i}", "title": "Sources Sought", "lane": "B",
            "signal_type": "federal", "fit_score": 0.6, "candidate_id": f"consulting-{i}"}
           for i in range(3)]

    digest = build_digest(sl, top_n=8)
    accounting = digest["selection_accounting"]
    employment = accounting["by_type"]["employment"]
    employment_rows = [
        row for row in accounting["candidates"]
        if row["opportunity_type"] == "employment"
    ]

    assert accounting["input"] == 13
    assert accounting["included"] + accounting["excluded"] == accounting["input"]
    assert accounting["unaccounted"] == 0
    assert employment == {"input": 10, "included": 5, "excluded": 5}
    assert {row["candidate_id"] for row in employment_rows} == {
        f"employment-{i}" for i in range(10)
    }
    assert all(
        row["reason_code"] in {
            "selected_for_digest_top",
            "employment_below_balanced_digest_cutoff",
            "org_diversity_cap",
        }
        for row in employment_rows
    )
