# Generated by test-lab — blind adversarial evaluation
"""test_cli - tests.

Purpose: Auto-generated module docstring. Review for accuracy.
Inputs/Outputs/Failures: See functions below.
"""

from __future__ import annotations

import json
from pathlib import Path

from typer.testing import CliRunner

from monitor_opportunities.cli import app
from monitor_opportunities.verification import built_in_fixture

runner = CliRunner()


def test_status_json_is_truthful() -> None:
    result = runner.invoke(app, ["status", "--json"])
    assert result.exit_code == 0, result.output
    payload = json.loads(result.stdout)
    assert payload["stage"] == "STAGE_0_RESEARCH_ONLY"
    assert payload["operational_readiness"] == "NOT_ESTABLISHED"
    assert payload["network_access"] is True
    assert payload["external_effects"] is False
    assert payload["capabilities"]["gmail_send"] == "PERMANENTLY_FORBIDDEN"
    assert "apply" in payload["implemented_commands"]
    assert "apply" not in payload["not_implemented_commands"]


def test_report_writes_self_contained_artifacts(tmp_path: Path) -> None:
    input_path = tmp_path / "input.json"
    input_path.write_text(json.dumps(built_in_fixture()), encoding="utf-8")
    out = tmp_path / "out"
    result = runner.invoke(app, ["report", "--input", str(input_path), "--out", str(out)])
    assert result.exit_code == 0, result.output
    rendered = (out / "index.html").read_text(encoding="utf-8")
    assert "FEED_DOWN" in rendered
    assert "BLOCKED_STAGE_0" in rendered
    assert "human_required" in rendered
    assert "<form" not in rendered.lower()
    assert "<script" not in rendered.lower()
    assert "http://" not in rendered.lower()
    assert "https://" not in rendered.lower()
    assert json.loads((out / "report.json").read_text(encoding="utf-8"))["run_id"]


def test_verify_writes_passing_receipt(tmp_path: Path) -> None:
    result = runner.invoke(app, ["verify", "--out", str(tmp_path)])
    assert result.exit_code == 0, result.output
    receipt = json.loads((tmp_path / "verification-receipt.json").read_text(encoding="utf-8"))
    assert receipt["overall"] == "PASS"
    assert receipt["network_used"] is False
    assert receipt["external_effects"] is False
    assert len(receipt["cases"]) >= 9


def test_apply_requires_exact_report_visible_packet(tmp_path: Path) -> None:
    fixture_dir = Path(__file__).parent / "fixtures" / "discovery"
    out = tmp_path / "run"
    run_result = runner.invoke(app, ["run", "--fixture-dir", str(fixture_dir), "--out", str(out)])
    assert run_result.exit_code == 0, run_result.output

    result = runner.invoke(app, ["apply", "--run", str(out), "--application", "application:missing"])
    assert result.exit_code == 2
    payload = json.loads(result.stderr)
    assert payload["status"] == "APPLICATION_PACKET_MISSING"
    assert payload["application_packet_count"] >= 1
    assert payload["external_effects"] is False
    assert payload["does_not_submit"] is True


def test_apply_blocks_unresolved_human_required_fields(tmp_path: Path) -> None:
    fixture_dir = Path(__file__).parent / "fixtures" / "discovery"
    out = tmp_path / "run"
    run_result = runner.invoke(app, ["run", "--fixture-dir", str(fixture_dir), "--out", str(out)])
    assert run_result.exit_code == 0, run_result.output
    manifest = json.loads((out / "report-manifest.json").read_text(encoding="utf-8"))
    application_id = manifest["application_packets"][0]["application_id"]

    result = runner.invoke(app, ["apply", "--run", str(out), "--application", application_id])
    assert result.exit_code == 2
    payload = json.loads(result.stderr)
    assert payload["status"] == "HUMAN_FIELDS_REQUIRED"
    assert payload["command"] == "apply"
    assert payload["stage"] == "STAGE_0_RESEARCH_ONLY"
    assert payload["external_effects"] is False
    assert payload["does_not_submit"] is True
    assert payload["unresolved_required_fields"] == ["Why this role?"]
    assert payload["command"] == "apply"
