# Generated by test-lab — blind adversarial evaluation
"""Response-likelihood ranking: warm/trigger/low-competition beats cold high-fit."""
from __future__ import annotations
from monitor_opportunities.response_likelihood import score_opportunity, rank_by_response


def test_warm_beats_cold_at_equal_fit() -> None:
    cold = {"organization": "A", "title": "Staff AI Eng", "fit": 0.9, "source": "jobs.ashbyhq.com/a"}
    warm = {"organization": "B", "title": "Staff AI Eng", "fit": 0.9, "warm_path": 0.9, "source": "discover-contacts"}
    assert score_opportunity(warm)["response_score"] > score_opportunity(cold)["response_score"]


def test_trigger_and_lowcomp_lift_score() -> None:
    s = score_opportunity({"organization": "C", "fit": 0.8, "trigger": 0.9, "source": "skima.ai"})
    assert s["drivers"]["trigger"] == 0.9 and s["drivers"]["low_competition"] > 0.5
    assert any("trigger" in r for r in s["why_it_responds"])


def test_cold_application_flagged_low_odds() -> None:
    s = score_opportunity({"organization": "D", "fit": 0.7, "source": "ashbyhq.com"})
    assert any("cold application" in r for r in s["why_it_responds"])  # honest: low reply odds


def test_rank_orders_by_response() -> None:
    opps = [
        {"organization": "cold", "fit": 0.95, "source": "indeed.com"},
        {"organization": "warm-trigger", "fit": 0.7, "warm_path": 0.8, "trigger": 0.7, "source": "discover-contacts"},
    ]
    ranked = rank_by_response(opps)
    assert ranked[0]["organization"] == "warm-trigger"  # response probability, not fit or volume


def test_local_standout_boosts_only_with_fit() -> None:
    strong = score_opportunity({"organization": "CUBRC", "fit": 0.85, "workplace_type": "WNY_ONSITE", "source": "discover-contacts"})
    weak = score_opportunity({"organization": "Generic local shop", "fit": 0.2, "workplace_type": "WNY_ONSITE", "source": "indeed.com"})
    assert strong["drivers"]["local"] == 1.0
    assert any("Buffalo/WNY local" in r for r in strong["why_it_responds"])
    # mandate-first: weak-fit local must NOT be lifted, and must be flagged
    assert weak["response_score"] < strong["response_score"] * 0.4
    assert any("local alone is not a reason" in r for r in weak["why_it_responds"])


def test_local_fit_beats_remote_cold_at_equal_fit() -> None:
    local = score_opportunity({"organization": "Moog", "fit": 0.8, "workplace_type": "WNY_ONSITE", "source": "dogpile"})
    remote_cold = score_opportunity({"organization": "X", "fit": 0.8, "workplace_type": "REMOTE", "source": "ashbyhq.com"})
    assert local["response_score"] > remote_cold["response_score"]
